{
  "hash": "f9680835603a1162ad0f7118f3cd5876",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"1. Measuring climate change\"\nsubtitle: \"Charts and summary measures for the extent and causes of climate change\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nTwo questions: **how do we know the climate is changing**, and **how do we know human activity\nis responsible**?\n\n- **[Part 1.1](#part-1.1)** — the behaviour of average surface temperature over time\n- **[Part 1.2](#part-1.2)** — variation in temperature over time\n- **[Part 1.3](#part-1.3)** — carbon emissions and the environment\n\nNew concepts: variance, frequency tables, correlation, spurious correlation. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/01-01.html),\n[R walk-throughs](https://books.core-econ.org/doing-economics/book/text/01-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/01-04.html).\n\n## The data\n\n| | |\n|---|---|\n| **Temperature** | [NASA GISS](https://data.giss.nasa.gov/gistemp/) GISTEMP v4, Northern-Hemisphere mean anomalies by month, season and year, 1880 onward |\n| **CO₂** | [NOAA](https://gml.noaa.gov/ccgg/trends/) Mauna Loa Observatory monthly series, March 1958 onward, via CORE Econ's frozen 2018 snapshot |\n| **Vintage** | GISTEMP downloaded 2 September 2026; see `data/MANIFEST.toml` |\n\n::: {.callout-note}\n## On matching the book's published numbers\n\nGISTEMP is reissued every month, and each release revises the whole record slightly as\nstation data are corrected. Figures here are computed from a 2026 vintage against solutions\npublished years earlier, so some numbers differ in the last decimal place. Where that\nhappens it is flagged. The CO₂ side uses the book's own frozen snapshot, so nothing drifts\nthere.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing CSV, DataFrames, XLSX\nusing Statistics\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\nTemperature first. The file has a title line above the real header, and codes missing\nobservations as `***`:\n\n::: {#cell-read-temp .cell execution_count=1}\n``` {.julia .cell-code}\ntemp = CSV.read(rawpath(\"01\", \"NH.Ts+dSST.csv\"), DataFrame;\n                header = 2, missingstring = \"***\")\n\nfirst(temp, 4)\n```\n\n::: {#read-temp .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×19 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Year</th><th style = \"text-align: left;\">Jan</th><th style = \"text-align: left;\">Feb</th><th style = \"text-align: left;\">Mar</th><th style = \"text-align: left;\">Apr</th><th style = \"text-align: left;\">May</th><th style = \"text-align: left;\">Jun</th><th style = \"text-align: left;\">Jul</th><th style = \"text-align: left;\">Aug</th><th style = \"text-align: left;\">Sep</th><th style = \"text-align: left;\">Oct</th><th style = \"text-align: left;\">Nov</th><th style = \"text-align: left;\">Dec</th><th style = \"text-align: left;\">J-D</th><th style = \"text-align: left;\">D-N</th><th style = \"text-align: left;\">DJF</th><th style = \"text-align: left;\">MAM</th><th style = \"text-align: left;\">JJA</th><th style = \"text-align: left;\">SON</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1880</td><td style = \"text-align: right;\">-0.37</td><td style = \"text-align: right;\">-0.52</td><td style = \"text-align: right;\">-0.24</td><td style = \"text-align: right;\">-0.3</td><td style = \"text-align: right;\">-0.07</td><td style = \"text-align: right;\">-0.17</td><td style = \"text-align: right;\">-0.2</td><td style = \"text-align: right;\">-0.27</td><td style = \"text-align: right;\">-0.24</td><td style = \"text-align: right;\">-0.32</td><td style = \"text-align: right;\">-0.43</td><td style = \"text-align: right;\">-0.41</td><td style = \"text-align: right;\">-0.3</td><td style = \"font-style: italic; text-align: right;\">missing</td><td style = \"font-style: italic; text-align: right;\">missing</td><td style = \"text-align: right;\">-0.2</td><td style = \"text-align: right;\">-0.21</td><td style = \"text-align: right;\">-0.33</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1881</td><td style = \"text-align: right;\">-0.31</td><td style = \"text-align: right;\">-0.23</td><td style = \"text-align: right;\">-0.04</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.03</td><td style = \"text-align: right;\">-0.34</td><td style = \"text-align: right;\">0.07</td><td style = \"text-align: right;\">-0.05</td><td style = \"text-align: right;\">-0.27</td><td style = \"text-align: right;\">-0.44</td><td style = \"text-align: right;\">-0.37</td><td style = \"text-align: right;\">-0.24</td><td style = \"text-align: right;\">-0.18</td><td style = \"text-align: right;\">-0.2</td><td style = \"text-align: right;\">-0.32</td><td style = \"text-align: right;\">-0.01</td><td style = \"text-align: right;\">-0.11</td><td style = \"text-align: right;\">-0.36</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">1882</td><td style = \"text-align: right;\">0.25</td><td style = \"text-align: right;\">0.21</td><td style = \"text-align: right;\">0.02</td><td style = \"text-align: right;\">-0.3</td><td style = \"text-align: right;\">-0.23</td><td style = \"text-align: right;\">-0.29</td><td style = \"text-align: right;\">-0.28</td><td style = \"text-align: right;\">-0.17</td><td style = \"text-align: right;\">-0.26</td><td style = \"text-align: right;\">-0.52</td><td style = \"text-align: right;\">-0.34</td><td style = \"text-align: right;\">-0.69</td><td style = \"text-align: right;\">-0.22</td><td style = \"text-align: right;\">-0.18</td><td style = \"text-align: right;\">0.07</td><td style = \"text-align: right;\">-0.17</td><td style = \"text-align: right;\">-0.24</td><td style = \"text-align: right;\">-0.37</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">1883</td><td style = \"text-align: right;\">-0.58</td><td style = \"text-align: right;\">-0.65</td><td style = \"text-align: right;\">-0.15</td><td style = \"text-align: right;\">-0.29</td><td style = \"text-align: right;\">-0.24</td><td style = \"text-align: right;\">-0.11</td><td style = \"text-align: right;\">-0.06</td><td style = \"text-align: right;\">-0.23</td><td style = \"text-align: right;\">-0.34</td><td style = \"text-align: right;\">-0.15</td><td style = \"text-align: right;\">-0.44</td><td style = \"text-align: right;\">-0.15</td><td style = \"text-align: right;\">-0.28</td><td style = \"text-align: right;\">-0.33</td><td style = \"text-align: right;\">-0.64</td><td style = \"text-align: right;\">-0.23</td><td style = \"text-align: right;\">-0.13</td><td style = \"text-align: right;\">-0.31</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nNineteen columns: the year, the twelve months, two annual averages (`J-D` calendar-year and\n`D-N` December-to-November), and four seasonal averages.\n\n::: {#cell-temp-shape .cell execution_count=1}\n``` {.julia .cell-code}\n(rows = nrow(temp), years = extrema(temp.Year), columns = names(temp))\n```\n\n::: {#temp-shape .cell-output .cell-output-display execution_count=1}\n```\n(rows = 147, years = (1880, 2026), columns = [\"Year\", \"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\", \"J-D\", \"D-N\", \"DJF\", \"MAM\", \"JJA\", \"SON\"])\n```\n:::\n:::\n\n\n\n# Part 1.1 — The behaviour of average surface temperature over time {#part-1.1}\n\n## Q1. What \"anomalies\" means {#p1-q1}\n\nThe dataset holds **anomalies**, not temperatures: how far a month departed from the average\nfor that same month and place over 1951–1980. A June anomaly of `+0.5` means half a degree\nwarmer than the average 1951–1980 June.\n\nAnomalies rather than absolute readings because absolute temperature varies by location and\nseason, and the set of reporting stations changes over the decades — averaging raw readings\nacross a hemisphere would largely measure which stations were reporting. A departure from a\nlocal baseline is comparable between Norway and Egypt, so departures can be averaged.\n\nConsequence used later: since the baseline *is* the 1951–1980 mean, anomalies over that window\naverage to zero by construction.\n\n## Q2. A line chart for one month {#p1-q2}\n\nTake June, and plot the whole record.\n\n::: {#cell-fig-june .cell execution_count=1}\n``` {.julia .cell-code}\nrecent_june = mean(skipmissing(temp.Jun[temp.Year .>= 2015]))\n\nfig = Figure(size = (760, 420))\nax = Axis(fig[1, 1];\n          # Derived from the data rather than typed in, so the claim cannot go stale\n          # when a later GISTEMP vintage is downloaded.\n          title = \"June now runs about $(round(recent_june, digits = 1)) °C above \" *\n                  \"the 1951–1980 average\",\n          xlabel = \"Year\", ylabel = \"Anomaly (°C)\")\n\n# The baseline is a reference value, not data, so it stays in chrome grey.\nhlines!(ax, 0; color = BASELINE, linewidth = 1)\nlines!(ax, temp.Year, temp.Jun; color = series_color(1))\n\n# One direct label at the end of the line rather than a value on every point.\nlast_year, last_val = temp.Year[end], temp.Jun[end]\nscatter!(ax, [last_year], [last_val]; color = series_color(1))\ntext!(ax, last_year - 3, last_val + 0.12;\n      text = \"$(last_year): $(last_val) °C\", align = (:right, :bottom))\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![June temperature anomaly for the Northern Hemisphere, 1880–2026. The zero line is the 1951–1980 June average, so the chart reads as departures from mid-century conditions.](index_files/figure-html/fig-june-output-1.svg){#fig-june}\n:::\n:::\n\n\n\nSlightly below baseline until about 1930, up to 1940, flat or falling into the 1970s, then\nrising without pause for fifty years. Recent values sit outside the entire range of the first\ncentury of the record.\n\n## Q3. A chart for each season {#p1-q3}\n\nThe `DJF`, `MAM`, `JJA` and `SON` columns hold winter, spring, summer and autumn averages.\nFour small multiples on shared axes make them comparable — the point of interest is whether\nthe seasons behave differently, which needs the same scale on each.\n\n::: {#cell-fig-seasons .cell execution_count=1}\n``` {.julia .cell-code}\nseasons = [(:DJF, \"Winter (Dec–Feb)\"), (:MAM, \"Spring (Mar–May)\"),\n           (:JJA, \"Summer (Jun–Aug)\"), (:SON, \"Autumn (Sep–Nov)\")]\n\nfig = Figure(size = (860, 520))\n# `tellwidth = false` matters: a Label reports its own width to the layout by\n# default, which in a narrow figure squeezes the axes to fit the title instead of\n# the other way round.\nLabel(fig[0, 1:2], \"All four seasons warm, and they turn upward together\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\n# Shared limits across the four panels; without this the eye compares slopes that\n# are drawn at different scales.\nallvals = collect(skipmissing(vcat((temp[!, s] for (s, _) in seasons)...)))\nylims = (floor(minimum(allvals) * 2) / 2, ceil(maximum(allvals) * 2) / 2)\n\nfor (i, (col, label)) in enumerate(seasons)\n    r, c = fldmod1(i, 2)\n    ax = Axis(fig[r, c]; title = label, limits = (nothing, ylims),\n              xlabel = r == 2 ? \"Year\" : \"\", ylabel = c == 1 ? \"Anomaly (°C)\" : \"\")\n    hlines!(ax, 0; color = BASELINE, linewidth = 1)\n    lines!(ax, temp.Year, temp[!, col]; color = series_color(1))\n    c == 2 && hideydecorations!(ax; grid = false)\n    r == 1 && hidexdecorations!(ax; grid = false)\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Seasonal temperature anomalies on shared axes. Every season warms, and all four turn upward at about the same time.](index_files/figure-html/fig-seasons-output-1.svg){#fig-seasons}\n:::\n:::\n\n\n\nAll four rise, and turn upward at the same time. Winter swings widest — Q2.5 puts its\n1981–2010 variance at 0.079 °C² against summer's 0.068 — which matters for Part 1.2.\n\n## Q4. The annual series {#p1-q4}\n\n`J-D` is the calendar-year average. Averaging twelve months removes most of the month-to-month\nnoise, so the trend that had to be read *through* the scatter in @fig-june is simply the shape\nof the line.\n\n::: {#cell-fig-annual .cell execution_count=1}\n``` {.julia .cell-code}\nannual = dropmissing(temp[:, [:Year, Symbol(\"J-D\")]])\nrename!(annual, Symbol(\"J-D\") => :anomaly)\n\nfig = Figure(size = (760, 420))\nax = Axis(fig[1, 1];\n          title = \"Annual average anomaly, Northern Hemisphere\",\n          subtitle = \"Twelve-month averaging removes the monthly noise; the trend is the line\",\n          xlabel = \"Year\", ylabel = \"Anomaly (°C)\")\nhlines!(ax, 0; color = BASELINE, linewidth = 1)\nlines!(ax, annual.Year, annual.anomaly; color = series_color(1))\n\npeak = argmax(annual.anomaly)\nscatter!(ax, [annual.Year[peak]], [annual.anomaly[peak]]; color = series_color(1))\ntext!(ax, annual.Year[peak] - 3, annual.anomaly[peak];\n      text = \"$(annual.Year[peak]): $(annual.anomaly[peak]) °C\", align = (:right, :center))\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Annual average temperature anomaly, 1880–2025. The last incomplete year is excluded.](index_files/figure-html/fig-annual-output-1.svg){#fig-annual}\n:::\n:::\n\n\n\n## Q5. What each time interval shows {#p1-q5}\n\nAggregation trades variance for detail.\n\n**Monthly** (@fig-june) — most variation, least trend clarity. Consecutive years differ by\nmore than half a degree for reasons unrelated to climate, so any two adjacent years can be\npicked to show cooling.\n\n**Seasonal** (@fig-seasons) — averaging three months cuts the noise by roughly √3 and keeps\nwhat the annual series loses: whether warming is uniform across the year. It isn't; winter is\nnoisier, quantified in Q2.5.\n\n**Annual** (@fig-annual) — clearest trend, no within-year detail. Right chart for \"is it\nwarming\", wrong one for \"is summer warming faster than winter\".\n\n## Q6. Comparison with the book's Figure 1.4 {#p1-q6}\n\nThe book's Figure 1.4 plots the same GISTEMP annual series, so @fig-annual reproduces its\nshape: the flat late-19th-century stretch, the rise to 1940, the mid-century pause, and the\nsteady climb from the mid-1970s.\n\nTwo differences, both from the passage of time rather than method:\n\n1. **The record is longer.** The book's figure ends in the 2010s; this one runs to 2025 and\n   the additional years are all near the top of the range, extending the trend rather than\n   changing it.\n2. **The earlier values have moved slightly.** GISTEMP is revised with each monthly release.\n   The revisions are small — hundredths of a degree — but they are why exact numbers here\n   differ from the book's in the last decimal place.\n\n# Part 1.2 — Variation in temperature over time {#part-1.2}\n\nPart 1.1 showed the mean rose. This part asks whether temperature became **more variable** — a\nseparate claim, and the one that governs how often extremes occur.\n\nJune, July and August pooled, for two thirty-year windows.\n\n::: {#cell-pool-summer .cell execution_count=1}\n``` {.julia .cell-code}\nsummer = [:Jun, :Jul, :Aug]\n\n\"\"\"Pool the June/July/August anomalies for the years `lo` through `hi`.\"\"\"\nfunction pool_summer(df, lo, hi)\n    window = df[(df.Year .>= lo) .& (df.Year .<= hi), summer]\n    return collect(skipmissing(vec(Matrix(window))))\nend\n\nbase   = pool_summer(temp, 1951, 1980)   # the anomaly baseline period\nrecent = pool_summer(temp, 1981, 2010)\n\n(base = length(base), recent = length(recent))\n```\n\n::: {#pool-summer .cell-output .cell-output-display execution_count=1}\n```\n(base = 90, recent = 90)\n```\n:::\n:::\n\n\n\nNinety observations each — thirty years times three months.\n\n## Q1. Two frequency tables {#p2-q1}\n\nFor the two distributions to be comparable they must use **identical bins**, so the breaks are\nderived from both periods together rather than each separately.\n\n::: {#cell-freq-tables .cell execution_count=1}\n``` {.julia .cell-code}\nstep = 0.25\nlo = floor(minimum(vcat(base, recent)) / step) * step\nhi = ceil(maximum(vcat(base, recent)) / step) * step\nbreaks = lo:step:hi\n\nfreq_base   = freqtable_binned(base;   breaks = breaks)\nfreq_recent = freqtable_binned(recent; breaks = breaks)\n\nDataFrame(bin = freq_base.bin,\n          n_1951_1980 = freq_base.count,\n          n_1981_2010 = freq_recent.count)\n```\n\n::: {#freq-tables .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">bin</th><th style = \"text-align: left;\">n_1951_1980</th><th style = \"text-align: left;\">n_1981_2010</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">(-0.50, -0.25]</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">(-0.25, 0]</td><td style = \"text-align: right;\">40</td><td style = \"text-align: right;\">7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">(0, 0.25]</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">23</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">(0.25, 0.50]</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">28</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">(0.50, 0.75]</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">26</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">(0.75, 1]</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">6</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe two columns barely overlap. In 1951–1980 the mass sits around zero; in 1981–2010 it has\nmoved bodily to the right, and the coldest bins are empty.\n\n## Q2. Histograms of the two distributions {#p2-q2}\n\n::: {#cell-fig-hist .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (860, 400))\nLabel(fig[0, 1:2], \"The whole distribution moved, it did not just stretch\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nymax = maximum(vcat(freq_base.count, freq_recent.count)) * 1.15\ncentres(t) = (t.lower .+ t.upper) ./ 2\n\nfor (i, (t, label)) in enumerate(((freq_base, \"1951–1980\"), (freq_recent, \"1981–2010\")))\n    ax = Axis(fig[1, i]; title = label, xlabel = \"Anomaly (°C)\",\n              ylabel = i == 1 ? \"Number of months\" : \"\",\n              limits = ((lo - step / 2, hi + step / 2), (0, ymax)))\n    # One series, one colour - bar height already encodes the count, so shading\n    # the bars by size would spend the colour channel on nothing.\n    barplot!(ax, centres(t), t.count;\n             width = step * 0.85, color = series_color(1))\n    i == 2 && hideydecorations!(ax; grid = false)\nend\n\n# Without this the two panels' edge tick labels collide into each other.\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Distribution of summer (Jun–Aug) anomalies in two thirty-year windows, on identical bins and axes. The counts behind these bars are in the table above.](index_files/figure-html/fig-hist-output-1.svg){#fig-hist}\n:::\n:::\n\n\n\nBoth distributions have a similar *width*; the later one sits further right. That is a shift in\nthe mean, not obviously an increase in spread — which is exactly the distinction Q5 tests\nnumerically.\n\n## Q3. The 3rd and 7th deciles {#p2-q3}\n\nThe article's definition: \"cold\" months are the coldest third of the 1951–1980 baseline, \"hot\"\nmonths the warmest third. So the thresholds are the 3rd and 7th deciles of `base`.\n\n::: {#cell-deciles .cell execution_count=1}\n``` {.julia .cell-code}\nd3, d7 = quantile(base, [0.3, 0.7])\n(third_decile = d3, seventh_decile = d7)\n```\n\n::: {#deciles .cell-output .cell-output-display execution_count=1}\n```\n(third_decile = -0.08, seventh_decile = 0.08)\n```\n:::\n:::\n\n\n\n::: {.callout-note}\n## Divergence from the published solution\n\nThe book reports **−0.1** and **0.11**; this vintage gives **−0.08** and **0.08**.\n\nThe cause is GISTEMP revision, amplified by the data's granularity. Anomalies are published to\ntwo decimal places, so with 90 observations there are many ties, and a handful of values\nshifting by 0.01 moves a decile by a whole step. The mean over the same window is essentially\nunchanged (Q5 below), which is what you'd expect if the revisions are small and roughly\nsymmetric — deciles are simply more sensitive to them than means are.\n:::\n\n## Q4. How many recent months count as hot {#p2-q4}\n\n::: {#cell-hot-cold .cell execution_count=1}\n``` {.julia .cell-code}\nshares(v) = (cold = 100 * mean(v .< d3), hot = 100 * mean(v .> d7))\n\nDataFrame(period = [\"1951–1980\", \"1981–2010\"],\n          n = [length(base), length(recent)],\n          cold_pct = [shares(base).cold, shares(recent).cold],\n          hot_pct  = [shares(base).hot,  shares(recent).hot])\n```\n\n::: {#hot-cold .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">cold_pct</th><th style = \"text-align: left;\">hot_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">1951–1980</td><td style = \"text-align: right;\">90</td><td style = \"text-align: right;\">27.7778</td><td style = \"text-align: right;\">28.8889</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">1981–2010</td><td style = \"text-align: right;\">90</td><td style = \"text-align: right;\">1.11111</td><td style = \"text-align: right;\">84.4444</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**84.4% of summer months in 1981–2010 were \"hot\"** by the mid-century standard, matching the\nbook exactly. Cold months fell to near zero.\n\nThe 1951–1980 row should show 30% in each tail by definition and shows 27.8% and 28.9%. This\nis a tie effect, not an error: deciles are *values*, and since anomalies are rounded to 0.01\nseveral observations sit exactly on the threshold, where a strict `<` or `>` excludes them.\nUsing `≤` and `≥` overshoots to 33.3% and 31.1%. No single comparison recovers exactly 30% —\nthe book's \"30%\" is the definition, not a computed share.\n\nThe strict comparison is what reproduces 84.4%, which identifies the convention the book used.\n\nThe 1981–2010 cold share is 1.1% against the book's 2.2% — one month in ninety, from the\nrevised deciles above.\n\n## Q5. Mean and variance across three periods {#p2-q5}\n\nNow the actual question: mean and variance by season, for 1921–1950, 1951–1980 and 1981–2010.\n\n::: {#cell-mean-var .cell execution_count=1}\n``` {.julia .cell-code}\nperiods = [(1921, 1950), (1951, 1980), (1981, 2010)]\n\nsummary = DataFrame(season = Symbol[], period = String[],\n                    mean = Float64[], variance = Float64[])\n\nfor (col, _) in seasons, (plo, phi) in periods\n    v = collect(skipmissing(temp[(temp.Year .>= plo) .& (temp.Year .<= phi), col]))\n    # `$(plo)` rather than `$plo`: an en dash is a valid identifier character in\n    # Julia, so `\"$plo–$phi\"` parses as a variable named `plo–`.\n    push!(summary, (col, \"$(plo)–$(phi)\", mean(v), var(v)))\nend\n\nsummary\n```\n\n::: {#mean-var .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>12×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">season</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">variance</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Symbol\" style = \"text-align: left;\">Symbol</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">DJF</td><td style = \"text-align: left;\">1921–1950</td><td style = \"text-align: right;\">-0.037</td><td style = \"text-align: right;\">0.0557941</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">DJF</td><td style = \"text-align: left;\">1951–1980</td><td style = \"text-align: right;\">-0.00233333</td><td style = \"text-align: right;\">0.050384</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">DJF</td><td style = \"text-align: left;\">1981–2010</td><td style = \"text-align: right;\">0.519</td><td style = \"text-align: right;\">0.0792438</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">MAM</td><td style = \"text-align: left;\">1921–1950</td><td style = \"text-align: right;\">-0.05</td><td style = \"text-align: right;\">0.0305034</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">MAM</td><td style = \"text-align: left;\">1951–1980</td><td style = \"text-align: right;\">-2.77556e-18</td><td style = \"text-align: right;\">0.0251034</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">MAM</td><td style = \"text-align: left;\">1981–2010</td><td style = \"text-align: right;\">0.506667</td><td style = \"text-align: right;\">0.0763402</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">JJA</td><td style = \"text-align: left;\">1921–1950</td><td style = \"text-align: right;\">-0.0616667</td><td style = \"text-align: right;\">0.0205937</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">JJA</td><td style = \"text-align: left;\">1951–1980</td><td style = \"text-align: right;\">0.000666667</td><td style = \"text-align: right;\">0.0145375</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">JJA</td><td style = \"text-align: left;\">1981–2010</td><td style = \"text-align: right;\">0.397</td><td style = \"text-align: right;\">0.0681803</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">SON</td><td style = \"text-align: left;\">1921–1950</td><td style = \"text-align: right;\">0.0733333</td><td style = \"text-align: right;\">0.0273816</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">SON</td><td style = \"text-align: left;\">1951–1980</td><td style = \"text-align: right;\">-0.00133333</td><td style = \"text-align: right;\">0.0263844</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">SON</td><td style = \"text-align: left;\">1981–2010</td><td style = \"text-align: right;\">0.426</td><td style = \"text-align: right;\">0.11139</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n`var` here is the sample variance, dividing by *n* − 1 — the same definition R's `var` uses,\nso these are directly comparable with the book's.\n\n::: {#cell-fig-variance .cell execution_count=1}\n``` {.julia .cell-code}\nperiod_labels = [\"$(lo)–$(hi)\" for (lo, hi) in periods]\n\nfig = Figure(size = (800, 430))\nax = Axis(fig[1, 1];\n          title = \"Variance rises in the most recent period, in every season\",\n          ylabel = \"Variance (°C²)\",\n          xticks = (1:length(seasons), [first(l, 6) for (_, l) in seasons]))\n\n# Period carries the colour, season goes on the x-axis: the comparison the question\n# asks for is across periods, so that is what the colour channel should encode.\n# Three series also keeps every pair of colours on screen safely distinguishable -\n# four would put yellow next to orange, which is too close a pair for bars sitting\n# side by side.\nnper = length(periods)\nfor (i, plabel) in enumerate(period_labels)\n    vals = [only(summary[(summary.season .== col) .& (summary.period .== plabel),\n                         :variance]) for (col, _) in seasons]\n    # `collect` because barplot! takes vectors, not ranges.\n    xs = collect((1:length(seasons)) .+ (i - (nper + 1) / 2) * 0.24)\n    barplot!(ax, xs, vals; width = 0.22, color = series_color(i), label = plabel)\nend\n\nLegend(fig[1, 2], ax, \"Period\"; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Sample variance of seasonal anomalies, grouped by season with one bar per period. Reading left to right within each season, the most recent period is the tallest bar in all four. Values are in the table above.](index_files/figure-html/fig-variance-output-1.svg){#fig-variance}\n:::\n:::\n\n\n\nTwo separate findings:\n\n- **The mean rose.** Every season is near zero in both earlier windows and +0.40 to +0.52 °C\n  in 1981–2010. The near-zero for 1951–1980 is guaranteed by the baseline definition; the\n  near-zero for 1921–1950 is not, and puts that decade close to the 1951–1980 norm.\n- **The variance also rose, in every season.** Autumn roughly four-fold (0.026 → 0.111),\n  summer next. The distribution widened as well as sliding right.\n\n## Q6. Has temperature become more variable? {#p2-q6}\n\nYes, in all four seasons — but the mean shift is the larger effect.\n\nThe histograms in @fig-hist show the mean shift plainly and the variance change barely at all;\nonly computing the variance surfaces it. A chart of two distributions shows a change in\nlocation and hides a change in spread.\n\nThe two effects have different consequences. A pure mean shift makes previously-rare warm\nmonths common — the 84.4% result. Higher variance additionally widens both tails relative to\nthe new mean, so record heat becomes more frequent while severe cold events remain possible.\n\nStrength of the claim: three windows give three variance estimates per season, each from 30\nobservations, so each is itself uncertain. The direction is consistent across all four\nseasons, but this is description, not a test.\n\n# Part 1.3 — Carbon emissions and the environment {#part-1.3}\n\n::: {#cell-read-co2 .cell execution_count=1}\n``` {.julia .cell-code}\nco2 = DataFrame(XLSX.readtable(rawpath(\"01\", \"1_CO2-data.xlsx\"), \"Sheet1\"))\nrename!(co2, \"Monthly average\" => \"average\")\n\nfor c in [\"Year\", \"Month\"]\n    co2[!, c] = Int.(co2[!, c])\nend\nfor c in [\"average\", \"Interpolated\", \"Trend\"]\n    # NOAA codes an unavailable monthly reading as -99.99. Left as a number it would\n    # quietly drag any mean it touched down by a hundred parts per million.\n    co2[!, c] = replace(Float64.(co2[!, c]), -99.99 => missing)\nend\n\nfirst(co2, 4)\n```\n\n::: {#read-co2 .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Year</th><th style = \"text-align: left;\">Month</th><th style = \"text-align: left;\">average</th><th style = \"text-align: left;\">Interpolated</th><th style = \"text-align: left;\">Trend</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1958</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">315.71</td><td style = \"text-align: right;\">315.71</td><td style = \"text-align: right;\">314.62</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1958</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">317.45</td><td style = \"text-align: right;\">317.45</td><td style = \"text-align: right;\">315.29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">1958</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">317.5</td><td style = \"text-align: right;\">317.5</td><td style = \"text-align: right;\">314.71</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">1958</td><td style = \"text-align: right;\">6</td><td style = \"font-style: italic; text-align: right;\">missing</td><td style = \"text-align: right;\">317.1</td><td style = \"text-align: right;\">314.85</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-co2-shape .cell execution_count=1}\n``` {.julia .cell-code}\n(rows = nrow(co2), years = extrema(co2.Year),\n missing_average = count(ismissing, co2.average),\n missing_trend = count(ismissing, co2.Trend))\n```\n\n::: {#co2-shape .cell-output .cell-output-display execution_count=1}\n```\n(rows = 713, years = (1958, 2017), missing_average = 7, missing_trend = 0)\n```\n:::\n:::\n\n\n\nSeven months have no direct reading — early gaps in the Mauna Loa record.\n\n## Q1. Is one observatory a reliable proxy for the globe? {#p3-q1}\n\nFor the long-run trend, yes, for two specific reasons.\n\nCO₂ persists in the atmosphere for centuries, far longer than the one to two years the\natmosphere takes to mix, so it is well mixed globally — a molecule emitted anywhere ends up\nalmost everywhere. This does not hold for short-lived pollutants, where one station would\ndescribe only its own region.\n\nMauna Loa sits 3,400 m up a mid-Pacific volcano, thousands of kilometres from major sources,\nso it samples free-troposphere air; sampling protocols discard air arriving from the volcano's\nown vents.\n\nThree real limitations:\n\n- **The seasonal cycle is regional.** The sawtooth in @fig-co2 is Northern-Hemisphere\n  vegetation taking up carbon in spring and summer and releasing it in autumn and winter. A\n  Southern-Hemisphere station shows a smaller cycle in the opposite phase. The trend is global;\n  the cycle is not.\n- **The level runs slightly high.** Emissions concentrate in the Northern Hemisphere, so\n  northern stations read above the global mean.\n- **No redundancy.** Confidence comes from the global network agreeing with the site, not from\n  the site alone.\n\n## Q2. `interpolated` versus `trend` {#p3-q2}\n\nThree columns, three different jobs:\n\n- **`average`** — the actual monthly mean of the measurements, with `missing` where\n  instruments failed.\n- **`Interpolated`** — the same series with those gaps filled in, so it is complete. Still\n  contains the full seasonal cycle.\n- **`Trend`** — the interpolated series with the **seasonal cycle removed**, leaving the\n  underlying long-run movement.\n\nWhich one you need depends on the question. `Interpolated` answers \"what was the concentration\nin June 1985\", a level that includes the summer drawdown. `Trend` answers \"was CO₂ higher in\n1985 than 1984\", which the seasonal cycle would otherwise swamp: the sawtooth is about 6 ppm\npeak-to-trough against an annual increase of 1–2 ppm. Ask the second question of the seasonal\nseries and the answer depends mostly on which months you compared.\n\n## Q3. Plotting both series {#p3-q3}\n\nFrom January 1960. The full record shows the trend; a decade-long window is needed to see what\n`Trend` actually removes, because at full extent the two lines are visually one.\n\n::: {#cell-fig-co2 .cell execution_count=1}\n``` {.julia .cell-code}\nco2s = sort(co2[co2.Year .>= 1960, :], [:Year, :Month])\nco2s.time = co2s.Year .+ (co2s.Month .- 0.5) ./ 12\n\nfig = Figure(size = (900, 420))\nLabel(fig[0, 1:2], \"CO₂ rises relentlessly, with an annual cycle riding on top\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nax1 = Axis(fig[1, 1]; title = \"1960–2017\", xlabel = \"Year\",\n           ylabel = \"CO₂ (ppm)\")\nlines!(ax1, co2s.time, co2s.Interpolated; color = series_color(1),\n       label = \"Interpolated\")\nlines!(ax1, co2s.time, co2s.Trend; color = series_color(2), label = \"Trend\")\n\nzoom = co2s[co2s.Year .<= 1970, :]\nax2 = Axis(fig[1, 2]; title = \"1960–1970 (detail)\", xlabel = \"Year\")\nlines!(ax2, zoom.time, zoom.Interpolated; color = series_color(1),\n       label = \"Interpolated\")\nlines!(ax2, zoom.time, zoom.Trend; color = series_color(2), label = \"Trend\")\n\n# Two series, so a legend is present; it is shared rather than repeated per panel.\nLegend(fig[2, 1:2], ax1; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mauna Loa CO₂ from 1960: the seasonally-varying interpolated series and the deseasonalised trend. The right panel zooms to 1960–1970, where the seasonal cycle the trend removes is legible.](index_files/figure-html/fig-co2-output-1.svg){#fig-co2}\n:::\n:::\n\n\n\nOver the full record the two lines are indistinguishable at this scale — the trend dominates\neverything. In the detail panel the interpolated series oscillates by roughly 6 ppm each year\nwhile the trend passes smoothly through the middle of it.\n\n## Q4. CO₂ against temperature {#p3-q4}\n\nTake June, join CO₂ trend onto the temperature anomalies by year, and look at the relationship.\n\n::: {#cell-june-merge .cell execution_count=1}\n``` {.julia .cell-code}\nmonth_number = Dict(:Jan => 1, :Jun => 6, :Dec => 12)\n\n\"\"\"Join the CO2 trend for a given month onto that month's temperature anomaly.\"\"\"\nfunction month_panel(month::Symbol)\n    co2_month = co2[co2.Month .== month_number[month], [:Year, :Trend]]\n    joined = innerjoin(temp[:, [:Year, month]], co2_month; on = :Year)\n    rename!(joined, month => :anomaly)\n    return dropmissing(joined)\nend\n\njune = month_panel(:Jun)\n(n = nrow(june), years = extrema(june.Year))\n```\n\n::: {#june-merge .cell-output .cell-output-display execution_count=1}\n```\n(n = 60, years = (1958, 2017))\n```\n:::\n:::\n\n\n\n::: {#cell-june-cor .cell execution_count=1}\n``` {.julia .cell-code}\nr_june = cor(june.anomaly, june.Trend)\n```\n\n::: {#june-cor .cell-output .cell-output-display execution_count=1}\n```\n0.9140963559587252\n```\n:::\n:::\n\n\n\n::: {#cell-fig-scatter .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (700, 460))\nax = Axis(fig[1, 1];\n          title = \"June: r = $(round(r_june, digits = 3))\",\n          subtitle = \"Higher CO₂ years are warmer years — but see Q6 on what this does not show\",\n          xlabel = \"CO₂ trend (ppm)\", ylabel = \"June anomaly (°C)\")\nscatter!(ax, june.Trend, june.anomaly; color = series_color(1))\n\n# Label the two endpoints of the record rather than all sixty points.\nfor i in (argmin(june.Year), argmax(june.Year))\n    text!(ax, june.Trend[i], june.anomaly[i];\n          text = string(june.Year[i]), align = (:left, :top), offset = (6, -4),\n          fontsize = 11, color = MUTED)\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![June temperature anomaly against June CO₂ trend concentration, 1958–2017. Each point is one year.](index_files/figure-html/fig-scatter-output-1.svg){#fig-scatter}\n:::\n:::\n\n\n\nThe correlation is **0.914** against the book's 0.92 — the same answer, differing by the\nGISTEMP revision. The relationship is strong, positive, and close to linear over this range.\n\n::: {.callout-note}\n## Why this isn't the book's chart\n\nThe book's R walk-through 1.8 puts temperature and CO₂ on one set of axes with two y-scales,\nusing `par(new = TRUE)` and a second axis on the right.\n\nWhere the two scales line up is an arbitrary choice by whoever drew the chart. Slide one scale\nand the series appear to track each other more or less tightly with no number changing, so the\nchart implies a strength of relationship it never measured.\n\nTwo panels sharing an x-axis carry the same information without that. The correlation\ncoefficient, 0.914, is the actual answer to how closely the two move together.\n:::\n\n::: {#cell-fig-two-panel .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 520))\nLabel(fig[0, 1], \"Both series rise over the same six decades\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nax_t = Axis(fig[1, 1]; ylabel = \"June anomaly (°C)\")\nlines!(ax_t, june.Year, june.anomaly; color = series_color(1))\nhidexdecorations!(ax_t; grid = false)\n\nax_c = Axis(fig[2, 1]; xlabel = \"Year\", ylabel = \"CO₂ trend (ppm)\")\nlines!(ax_c, june.Year, june.Trend; color = series_color(2))\n\nlinkxaxes!(ax_t, ax_c)\nrowgap!(fig.layout, 8)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![June temperature anomaly and June CO₂ concentration over the same years, as two panels sharing an x-axis. Each series keeps its own units and no arbitrary alignment of scales is involved.](index_files/figure-html/fig-two-panel-output-1.svg){#fig-two-panel}\n:::\n:::\n\n\n\n### Why not index both series instead?\n\nIndexing both series to 100 at a common base year is the other standard fix for two measures on\ndifferent scales, and `index_to` does it. It is the wrong tool here.\n\nIndexing is a ratio to the base value, so the base has to mean something. CO₂ has a true zero\nand a 1958 value near 315 ppm. A temperature *anomaly* does not — zero is the 1951–1980 mean,\nan arbitrary reference — and June 1958's anomaly happens to be **0.05 °C**:\n\n::: {#cell-index-demo .cell execution_count=1}\n``` {.julia .cell-code}\nbase_anomaly = june.anomaly[1]\nfinal_anomaly = june.anomaly[end]\n\n(base = base_anomaly,\n final = final_anomaly,\n index = 100 * final_anomaly / base_anomaly,\n co2_index = 100 * june.Trend[end] / june.Trend[1])\n```\n\n::: {#index-demo .cell-output .cell-output-display execution_count=1}\n```\n(base = 0.05, final = 0.93, index = 1860.0, co2_index = 129.1186279180562)\n```\n:::\n:::\n\n\n\nTemperature reaches an index near 1,400 against CO₂'s 130 — less comparable than what we\nstarted with. The figure is also unstable: had 1958's anomaly been 0.01 °C, the index would\nread 7,000, with nothing about the climate different.\n\nIndex numbers work when both series have a meaningful zero and a base value away from it.\nAnomalies fail that, so the two-panel chart above is the right presentation.\n\n## Q5. A second and third month {#p3-q5}\n\n::: {#cell-fig-months .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 420))\nLabel(fig[0, 1:2], \"The relationship holds in every month\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\ncorrelations = DataFrame(month = String[], n = Int[], r = Float64[])\n\nfor (i, m) in enumerate((:Jan, :Dec))\n    panel = month_panel(m)\n    r = cor(panel.anomaly, panel.Trend)\n    push!(correlations, (string(m), nrow(panel), r))\n\n    ax = Axis(fig[1, i]; title = \"$m: r = $(round(r, digits = 3))\",\n              xlabel = \"CO₂ trend (ppm)\",\n              ylabel = i == 1 ? \"Anomaly (°C)\" : \"\")\n    scatter!(ax, panel.Trend, panel.anomaly; color = series_color(1))\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![January and December, the same relationship as June. Correlation is strong in every month but weaker than June's.](index_files/figure-html/fig-months-output-1.svg){#fig-months}\n:::\n:::\n\n\n\n::: {#cell-cor-table .cell execution_count=1}\n``` {.julia .cell-code}\npush!(correlations, (\"Jun\", nrow(june), r_june))\nsort!(correlations, :r, rev = true)\ncorrelations\n```\n\n::: {#cor-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">month</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">r</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Jun</td><td style = \"text-align: right;\">60</td><td style = \"text-align: right;\">0.914096</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Jan</td><td style = \"text-align: right;\">59</td><td style = \"text-align: right;\">0.828106</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Dec</td><td style = \"text-align: right;\">59</td><td style = \"text-align: right;\">0.814826</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nJune 0.914, January 0.828, December 0.815, against the book's 0.92, 0.82 and 0.81.\n\nSummer correlates more strongly than winter because winter anomalies are more variable\n(Q2.5). The extra variance is unrelated to CO₂ and dilutes the shared movement, so the\nmeasured correlation falls without the underlying relationship being weaker.\n\n## Q6. Correlation, causation, and spurious correlation {#p3-q6}\n\n**Correlation** says two variables move together. **Causation** says changing one changes the\nother. A **spurious correlation** is a strong correlation with no causal link either way.\n\nTwo mechanisms produce them:\n\n1. **A common cause.** Ice cream sales and drowning deaths correlate; summer causes both.\n2. **A shared trend.** Any two series rising over the same period correlate regardless of\n   subject. US cheese consumption and deaths from bedsheet entanglement correlate at about\n   0.95 — both grew with population.\n\nThe second applies here directly: **the 0.914 in @fig-scatter is on its own weak evidence.**\nBoth series trend upward over six decades, which guarantees a high correlation whatever the\ncausal story. Any smoothly rising 1958–2017 series would score similarly.\n\nWhat distinguishes this from cheese and bedsheets is not the coefficient:\n\n- **The mechanism was established first.** CO₂'s infrared absorption was measured in the\n  laboratory in the 1850s, decades before either series began. The correlation was predicted\n  before it was observed.\n- **Direction comes from the mechanism, not the data.** A correlation is symmetric and cannot\n  separate CO₂ warming the planet from a warming planet releasing CO₂. Both occur; the second\n  is a feedback. Isotopic evidence on the carbon's origin settles which dominates.\n- **Alternatives were checked.** Solar output and volcanic activity are measured separately\n  and do not account for the post-1970 rise.\n\nWhat this project establishes: temperature rose and became more variable (Parts 1.1–1.2); CO₂\nrose over the same period and the two correlate strongly (Part 1.3). Attribution to human\nactivity rests on the physics and the wider evidence base, not on the coefficient computed\nhere.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Line charts over time | Q1.2, Q1.3, Q1.4 | `lines`, `hlines!` |\n| Small multiples on shared axes | Q1.3 | `fig[r, c]`, shared `limits` |\n| Frequency tables | Q2.1 | `freqtable_binned` |\n| Histograms | Q2.2 | `barplot!` on binned counts |\n| Deciles and quantiles | Q2.3 | `quantile(x, [0.3, 0.7])` |\n| Proportions from a condition | Q2.4 | `mean(v .> threshold)` |\n| Mean and variance by group | Q2.5 | `groupby` + loop, `var` |\n| Joining two datasets | Q3.4 | `innerjoin(a, b; on = :Year)` |\n| Scatterplots and correlation | Q3.4, Q3.5 | `scatter`, `cor` |\n| Index numbers | Q3.4 | `index_to` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table, including\nthe walk-through idioms not needed here.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}