{
  "hash": "57d7cc290d638bc27f20a7dd03529fb9",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"12. Government policies and popularity: the Hong Kong cash handout\"\nsubtitle: \"A one-off HK$6,000 to every adult, and what it did to inequality and to approval\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nIn 2011 the Hong Kong government, sitting on a large budget surplus, gave **HK$6,000 to every\npermanent resident aged 18 or over**. Scheme $6,000 was defended as sharing the gains from\ngrowth, and suspected of buying popularity.\n\nBoth claims are testable. The first against household income data, the second against a public\nopinion series that runs from 1997.\n\n- **[Part 12.1](#part-12.1)** — inequality\n- **[Part 12.2](#part-12.2)** — government popularity\n\nConcepts: **Lorenz curves** and **Gini coefficients** applied to a policy, and converting\nnominal values to real ones. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/12-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/12-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/12-04.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, CSV, DataFrames\nusing Statistics, Dates\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-income .cell execution_count=1}\n``` {.julia .cell-code}\n# One sheet holding three blocks separated by blank rows, so it is read as a cell\n# matrix by row index rather than with `readtable`.\ncells = XLSX.readxlsx(rawpath(\"12\", \"hk-cash-handout.xlsx\"))[\"Sheet1\"][:]\n\nconst YEARS = [Int(cells[13, j]) for j in 2:9]\nconst PERCENTILES = [String(cells[i, 1]) for i in 14:18]\n\nnominal = [Float64(cells[i, j]) for i in 4:8, j in 2:9]\nreal_income = [Float64(cells[i, j]) for i in 14:18, j in 2:9]\ninflation = [Float64(cells[10, j]) for j in 2:9]\n\n(years = YEARS, percentile_rows = PERCENTILES, blocks = (\"nominal\", \"CPI change\", \"real\"))\n```\n\n::: {#read-income .cell-output .cell-output-display execution_count=1}\n```\n(years = [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016], percentile_rows = [\"85th\", \"75th\", \"50th\", \"25th\", \"15th\"], blocks = (\"nominal\", \"CPI change\", \"real\"))\n```\n:::\n:::\n\n\n\n::: {.callout-important}\n## The percentile rows are listed highest-first\n\n`PERCENTILES` comes back as `[\"85th\", \"75th\", \"50th\", \"25th\", \"15th\"]` — **descending**. Every\nconstruction below assigns household counts to income groups in ascending order, so the rows\nhave to be sorted first.\n\nGetting it wrong does not produce an error or an absurd figure. It produces a Gini of 0.434\ninstead of 0.469 — entirely plausible, and wrong. That is why [Q3](#p1-q3) checks the\neconomy-wide total against the published value before trusting the Gini.\n:::\n\n# Part 12.1 — Inequality {#part-12.1}\n\n## Q1. Real incomes by percentile over time {#p1-q1}\n\nThe figures here are **pre-intervention**: they exclude handouts and other government\ntransfers, which is what makes them a usable baseline for asking what the handout did.\n\n::: {#tbl-real-income .cell tbl-cap='Monthly real household income by percentile, 2009 prices.' execution_count=1}\n``` {.julia .cell-code}\nreal_table = DataFrame(percentile = PERCENTILES)\nfor (j, y) in enumerate(YEARS)\n    real_table[!, string(y)] = round.(real_income[:, j], digits = 0)\nend\nreal_table.change_pct = round.(100 .* (real_income[:, end] .- real_income[:, 1]) ./\n                               real_income[:, 1], digits = 1)\nreal_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×10 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">percentile</th><th style = \"text-align: left;\">2009</th><th style = \"text-align: left;\">2010</th><th style = \"text-align: left;\">2011</th><th style = \"text-align: left;\">2012</th><th style = \"text-align: left;\">2013</th><th style = \"text-align: left;\">2014</th><th style = \"text-align: left;\">2015</th><th style = \"text-align: left;\">2016</th><th style = \"text-align: left;\">change_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">85th</td><td style = \"text-align: right;\">43300.0</td><td style = \"text-align: right;\">43945.0</td><td style = \"text-align: right;\">44516.0</td><td style = \"text-align: right;\">44544.0</td><td style = \"text-align: right;\">45270.0</td><td style = \"text-align: right;\">45162.0</td><td style = \"text-align: right;\">47660.0</td><td style = \"text-align: right;\">47086.0</td><td style = \"text-align: right;\">8.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">75th</td><td style = \"text-align: right;\">31000.0</td><td style = \"text-align: right;\">31250.0</td><td style = \"text-align: right;\">32274.0</td><td style = \"text-align: right;\">32517.0</td><td style = \"text-align: right;\">34166.0</td><td style = \"text-align: right;\">33299.0</td><td style = \"text-align: right;\">34791.0</td><td style = \"text-align: right;\">34907.0</td><td style = \"text-align: right;\">12.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">50th</td><td style = \"text-align: right;\">17400.0</td><td style = \"text-align: right;\">17578.0</td><td style = \"text-align: right;\">17806.0</td><td style = \"text-align: right;\">17818.0</td><td style = \"text-align: right;\">18621.0</td><td style = \"text-align: right;\">18490.0</td><td style = \"text-align: right;\">19064.0</td><td style = \"text-align: right;\">19393.0</td><td style = \"text-align: right;\">11.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">25th</td><td style = \"text-align: right;\">8000.0</td><td style = \"text-align: right;\">8203.0</td><td style = \"text-align: right;\">8347.0</td><td style = \"text-align: right;\">8820.0</td><td style = \"text-align: right;\">8542.0</td><td style = \"text-align: right;\">8591.0</td><td style = \"text-align: right;\">8738.0</td><td style = \"text-align: right;\">8533.0</td><td style = \"text-align: right;\">6.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">15th</td><td style = \"text-align: right;\">4500.0</td><td style = \"text-align: right;\">4395.0</td><td style = \"text-align: right;\">4637.0</td><td style = \"text-align: right;\">4454.0</td><td style = \"text-align: right;\">4356.0</td><td style = \"text-align: right;\">4091.0</td><td style = \"text-align: right;\">3972.0</td><td style = \"text-align: right;\">3879.0</td><td style = \"text-align: right;\">-13.8</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-percentiles .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (960, 460))\norder = sortperm(real_income[:, 1])          # ascending, so panels read 15th to 85th\nfor (k, idx) in enumerate(order)\n    ax = Axis(fig[fldmod1(k, 5)...];\n              title = PERCENTILES[idx] * \" percentile\", titlesize = 11,\n              xlabel = \"Year\", ylabel = k == 1 ? \"HK\\$ per month (2009 prices)\" : \"\",\n              xticks = (2010:3:2016, string.(2010:3:2016)))\n    hlines!(ax, [real_income[idx, 1]]; color = BASELINE, linewidth = 1)\n    lines!(ax, YEARS, real_income[idx, :]; color = series_color(1), linewidth = 2.5)\n    scatter!(ax, YEARS, real_income[idx, :]; color = series_color(1), markersize = 6)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Monthly real household income by percentile, 2009 prices, each on its own panel so that series two orders of magnitude apart stay readable. The grey line in each panel is that percentile's 2009 level, so the shape shows change against the starting point rather than against zero.](index_files/figure-html/fig-percentiles-output-1.svg){#fig-percentiles}\n:::\n:::\n\n\n\n**Real income rose at every percentile except the bottom one.** The 85th, 75th, 50th and 25th\npercentiles all end 2016 above their 2009 level, while the **15th percentile falls** — from about\nHK$4,500 to HK$3,879 a month, a decline of roughly 14%.\n\nThat divergence is the substantive finding of the Part, and it is not a story about the handout.\nOver eight years the bottom of the Hong Kong distribution lost real income while everyone above\nit gained, which is inequality widening through the *level* of incomes rather than through\nanything a one-off transfer touches.\n\nNote the shape at the top: the 85th percentile rises to 2015 and then dips, while the 50th keeps\nclimbing. Growth was not uniform even among the gainers.\n\n## Q2. Lorenz curves before and after {#p1-q2}\n\n**(a) Cumulative income shares.** The data gives income *at* five percentiles. Turning that into\na Lorenz curve means building an economy of 100 households: each income group is repeated for as\nmany households as the group covers, with the bottom 15 households assigned zero income.\n\n::: {#cell-economy .cell execution_count=1}\n``` {.julia .cell-code}\nconst GROUP_SIZES = [15, 10, 25, 25, 10, 15]   # sums to 100 households\n\n\"\"\"The 100-household economy for `year`, in annual real HK\\$.\n\nA zero-income group is prepended, monthly figures are annualised, and in 2012 the\none-off HK\\$6,000 handout is added to every household.\n\"\"\"\nfunction economy(year)\n    col = findfirst(==(year), YEARS)\n    incomes = sort(vcat(0.0, real_income[:, col]))     # ascending: 0, 15th … 85th\n    annual = incomes .* 12\n    year == 2012 && (annual = annual .+ 6000)\n    return reduce(vcat, [fill(annual[g], GROUP_SIZES[g]) for g in eachindex(GROUP_SIZES)])\nend\n\n\"\"\"Thousands-separated string, e.g. `20,288,016`.\n\nDataFrames renders large floats in scientific notation (`2.0288e7`), which hides exactly\nthe digits these tables exist to let you check against the published figures.\n\"\"\"\nfunction commas(x; digits = 0)\n    text = digits > 0 ? rstrip(rstrip(string(round(x; digits)), '0'), '.') : string(round(Int, x))\n    sign, text = startswith(text, '-') ? (\"-\", text[2:end]) : (\"\", text)\n    whole, dot, frac = partition_decimal(text)\n    groups = String[]\n    while length(whole) > 3\n        pushfirst!(groups, whole[end-2:end])\n        whole = whole[1:end-3]\n    end\n    pushfirst!(groups, whole)\n    return sign * join(groups, \",\") * dot * frac\nend\n\n\"\"\"Split `\"543242.51\"` into `(\"543242\", \".\", \"51\")`, or `\"6000\"` into `(\"6000\", \"\", \"\")`.\"\"\"\nfunction partition_decimal(text)\n    i = findfirst('.', text)\n    return i === nothing ? (text, \"\", \"\") : (text[1:i-1], \".\", text[i+1:end])\nend\n\nDataFrame(year = [2011, 2012, 2013],\n          households = [length(economy(y)) for y in [2011, 2012, 2013]],\n          economy_total = [commas(sum(economy(y))) for y in [2011, 2012, 2013]])\n```\n\n::: {#economy .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">households</th><th style = \"text-align: left;\">economy_total</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">100</td><td style = \"text-align: left;\">20,288,016</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">100</td><td style = \"text-align: left;\">21,045,778</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">100</td><td style = \"text-align: left;\">20,919,962</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe 2011 total of **HK$20,288,016** and the 2012 total of **HK$21,045,778** both match the\npublished figures, which is the check that the group sizes line up with the right incomes.\n\n::: {#tbl-cumulative .cell tbl-cap='Cumulative share of income held by the bottom x% of households. Reproduces the book\\'s Solution figure 12.6.' execution_count=1}\n``` {.julia .cell-code}\ncumulative = DataFrame(population_pct = [0, 15, 25, 50, 75, 85, 100],\n                       perfect_equality = [0, 15, 25, 50, 75, 85, 100])\nfor y in [2011, 2012]\n    v = sort(economy(y))\n    total = sum(v)\n    cumulative[!, \"share_$y\"] = [round(p == 0 ? 0.0 : 100 * sum(v[1:p]) / total, digits = 2)\n                                 for p in cumulative.population_pct]\nend\ncumulative\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>7×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">population_pct</th><th style = \"text-align: left;\">perfect_equality</th><th style = \"text-align: left;\">share_2011</th><th style = \"text-align: left;\">share_2012</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.43</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">2.74</td><td style = \"text-align: right;\">3.25</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">50</td><td style = \"text-align: right;\">50</td><td style = \"text-align: right;\">15.09</td><td style = \"text-align: right;\">16.54</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">75</td><td style = \"text-align: right;\">75</td><td style = \"text-align: right;\">41.42</td><td style = \"text-align: right;\">42.65</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">85</td><td style = \"text-align: right;\">85</td><td style = \"text-align: right;\">60.5</td><td style = \"text-align: right;\">61.47</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">100</td><td style = \"text-align: right;\">100</td><td style = \"text-align: right;\">100.0</td><td style = \"text-align: right;\">100.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll ten values match the published table.\n\n**(b) The Lorenz curves.**\n\n::: {#cell-fig-lorenz .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (620, 600))\nax = Axis(fig[1, 1];\n          title = \"The handout lifted the whole curve, most at the bottom\",\n          xlabel = \"Cumulative share of population (%)\",\n          ylabel = \"Cumulative share of income (%)\",\n          limits = ((0, 100), (0, 100)), aspect = 1)\nlines!(ax, [0, 100], [0, 100]; color = BASELINE, linewidth = 1, linestyle = :dash)\ntext!(ax, 52, 55; text = \"perfect equality\", rotation = pi / 4, fontsize = 10,\n      align = (:center, :bottom), color = MUTED)\n\nfor (j, y) in enumerate([2011, 2012])\n    lines!(ax, cumulative.population_pct, cumulative[!, \"share_$y\"];\n           color = series_color(j), linewidth = 2.5, label = string(y))\n    scatter!(ax, cumulative.population_pct, cumulative[!, \"share_$y\"];\n             color = series_color(j))\nend\naxislegend(ax; position = :lt, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Lorenz curves for 2011 and 2012, with the perfect-equality diagonal. Two series, so the year carries the colour; the diagonal is a reference, not data, so it stays in chrome grey and dashed. The 2012 curve is the handout year and sits everywhere at or above 2011.](index_files/figure-html/fig-lorenz-output-1.svg){#fig-lorenz}\n:::\n:::\n\n\n\n**The 2012 curve sits above the 2011 curve everywhere**, which is what an equal lump sum to\neveryone must do: adding the same amount to every household raises the share held by the poor\nand lowers the share held by the rich.\n\n**The largest gap is at the bottom, and it comes off a floor of literally zero.** In 2011 the\nbottom 15% of households hold **0.00%** of income; in 2012 they hold **0.43%**. That is the\nhandout in its entirety — HK$6,000 against nothing — and it is why the curve lifts off the\nhorizontal axis at all.\n\nHigher up, the gap narrows: 15.09% to 16.54% at the median, and 60.50% to 61.47% at the 85th\npercentile. The proportional effect of a fixed sum shrinks as income rises, which is the\nmechanical reason a flat handout is progressive.\n\n## Q3. Gini coefficients {#p1-q3}\n\n**(a) Incomes for all 100 households.**\n\n::: {#tbl-percentile-incomes .cell tbl-cap='Annual real income for each of the 100 households, showing the ends of the distribution. Reproduces the book\\'s Solution figure 12.8.' execution_count=1}\n``` {.julia .cell-code}\nincomes_by_year = DataFrame(percentile = 1:100)\nfor y in [2011, 2012, 2013]\n    incomes_by_year[!, string(y)] = [commas(v; digits = 2) for v in sort(economy(y))]\nend\nvcat(first(incomes_by_year, 3), last(incomes_by_year, 3))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">percentile</th><th style = \"text-align: left;\">2011</th><th style = \"text-align: left;\">2012</th><th style = \"text-align: left;\">2013</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">0</td><td style = \"text-align: left;\">6,000</td><td style = \"text-align: left;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">0</td><td style = \"text-align: left;\">6,000</td><td style = \"text-align: left;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">0</td><td style = \"text-align: left;\">6,000</td><td style = \"text-align: left;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">98</td><td style = \"text-align: left;\">534,188.03</td><td style = \"text-align: left;\">540,530.13</td><td style = \"text-align: left;\">543,242.51</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">99</td><td style = \"text-align: left;\">534,188.03</td><td style = \"text-align: left;\">540,530.13</td><td style = \"text-align: left;\">543,242.51</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">100</td><td style = \"text-align: left;\">534,188.03</td><td style = \"text-align: left;\">540,530.13</td><td style = \"text-align: left;\">543,242.51</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nBoth ends match the published values: zero for the bottom households in 2011 and 2013 against\nHK$6,000 in 2012, and 534,188 / 540,530 / 543,242.51 at the top.\n\n**(b) The Gini coefficient for each year.**\n\n::: {#tbl-gini .cell tbl-cap='Gini coefficient of annual real household income, computed with `gini` from the shared helpers.' execution_count=1}\n``` {.julia .cell-code}\ngini_table = DataFrame(year = [2011, 2012, 2013],\n                       gini = [round(gini(economy(y)), digits = 4) for y in [2011, 2012, 2013]],\n                       handout = [\"no\", \"yes\", \"no\"])\ngini_table.change = [missing; round.(diff(gini_table.gini), digits = 4)]\ngini_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">gini</th><th style = \"text-align: left;\">handout</th><th style = \"text-align: left;\">change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">0.4688</td><td style = \"text-align: left;\">no</td><td style = \"font-style: italic; text-align: right;\">missing</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">0.4519</td><td style = \"text-align: left;\">yes</td><td style = \"text-align: right;\">-0.0169</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">0.4698</td><td style = \"text-align: left;\">no</td><td style = \"text-align: right;\">0.0179</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-gini .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (620, 440))\nax = Axis(fig[1, 1];\n          title = \"Inequality fell in the handout year and returned the year after\",\n          ylabel = \"Gini coefficient\",\n          xticks = (1:3, [\"2011\\nno handout\", \"2012\\nhandout\", \"2013\\nno handout\"]),\n          limits = (nothing, (0.44, 0.48)))\nbarplot!(ax, 1:3, gini_table.gini; width = 0.5, color = series_color(1))\nfor (x, v) in zip(1:3, gini_table.gini)\n    text!(ax, x, v; text = string(v), fontsize = 11,\n          align = (:center, :bottom), offset = (0, 4), color = INK)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Gini coefficient by year. One series, so one colour. The axis starts at 0.44 rather than 0 — the differences here are hundredths and a zero baseline would hide them — which is legitimate only because every bar is labelled with its value.](index_files/figure-html/fig-gini-output-1.svg){#fig-gini}\n:::\n:::\n\n\n\n**0.4688 in 2011, 0.4519 in 2012, 0.4698 in 2013** — all three matching the published values.\n\n## Q4. What the handout did, and for how long {#p1-q4}\n\n**In the short run it worked, by about 0.017 Gini points.** The fall from 0.4688 to 0.4519 is\nreal and it is exactly what the arithmetic requires: give everyone the same amount and the\ndistribution compresses.\n\n**In the long run it did nothing.** 2013 comes in at 0.4698 — marginally *above* 2011. The effect\nlasted precisely as long as the payment.\n\nFour reasons that is the expected outcome rather than a disappointment:\n\n1. **A one-off transfer cannot change a distribution's structure.** The Gini is a property of how\n   income is generated — education, occupation, capital ownership, mobility. A payment that\n   arrives once and is not repeated leaves every one of those untouched. By 2013 the only trace\n   is whatever the money bought.\n2. **The amount was too small to be an investment.** HK$6,000 is roughly a month and a half of\n   income at the 15th percentile. It cannot fund a qualification or start a business, and\n   low-income households are typically credit-constrained, so it was most likely spent on\n   consumption. Useful, and not transformative.\n3. **The 2013 figure is slightly worse than 2011**, which the handout cannot explain. Something\n   else was widening the distribution over these years — and [Q1](#p1-q1) already showed what:\n   the 15th percentile's real income was falling throughout.\n4. **The 2012 change is not all handout.** Other things moved incomes that year, including\n   bonuses and rebates that fall disproportionately to higher earners. If those widened the\n   distribution, the handout's own effect was larger than 0.017 and was partly offset.\n\n**Two thought experiments the questions raise**, both of which the Lorenz curve makes easy to\nreason about:\n\n- **Transfers targeted only at zero-income households** would raise the very bottom of the curve\n  further, moving it toward the diagonal and lowering the Gini more per dollar spent than a\n  universal payment. Scheme $6,000 spent most of its money on households that were not poor.\n- **Income tax on the richest households** would cut the top of the curve, also moving it toward\n  the diagonal and also lowering the Gini. The two instruments work from opposite ends and the\n  Lorenz curve shows why both reduce measured inequality.\n\n::: {.callout-note}\n## What this measure can and cannot see\n\nEvery Gini here comes from **six income values** expanded into 100 households, so within each\ngroup inequality is assumed away. [Project 5](../05-measuring-inequality/index.qmd) showed that\ncomputing a Gini from grouped data understates it, and this is a far coarser grouping than\ndeciles — the Lorenz curve is six straight segments.\n\nThe direction and rough size of the 2012 change are trustworthy, because the handout is a known\nconstant added to every household. The *level* of 0.4688 is not a good estimate of Hong Kong's\nactual Gini.\n:::\n\n## Extension: nominal and real values {#p1-extension}\n\nThe workbook supplies real income already deflated, but the conversion is worth doing since it\nexplains why the two blocks differ.\n\n::: {#tbl-inflation .cell tbl-cap='Building a price index from year-on-year inflation rates. Reproduces the book\\'s Solution figure 12.9.' execution_count=1}\n``` {.julia .cell-code}\nindex_table = DataFrame(year = YEARS, inflation_pct = inflation)\nindex_table.price_index = let running = 1.0\n    [k == 1 ? 1.0 : (running *= 1 + inflation[k] / 100) for k in eachindex(YEARS)]\nend\nindex_table.price_index = round.(index_table.price_index, digits = 3)\nindex_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">inflation_pct</th><th style = \"text-align: left;\">price_index</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2009</td><td style = \"text-align: right;\">0.5</td><td style = \"text-align: right;\">1.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">1.024</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">5.3</td><td style = \"text-align: right;\">1.078</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">4.1</td><td style = \"text-align: right;\">1.122</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">4.3</td><td style = \"text-align: right;\">1.171</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">4.4</td><td style = \"text-align: right;\">1.222</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">1.259</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2016</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">1.289</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll eight index values match the published table. **Prices rose 28.9% between 2009 and 2016**, so\na nominal income that grew by less than that lost purchasing power.\n\n::: {#cell-nominal-vs-real .cell execution_count=1}\n``` {.julia .cell-code}\ncheck = DataFrame(percentile = PERCENTILES,\n                  nominal_2009 = nominal[:, 1], nominal_2016 = nominal[:, end],\n                  nominal_growth_pct = round.(100 .* (nominal[:, end] .- nominal[:, 1]) ./\n                                              nominal[:, 1], digits = 1),\n                  real_growth_pct = round.(100 .* (real_income[:, end] .- real_income[:, 1]) ./\n                                           real_income[:, 1], digits = 1))\ncheck\n```\n\n::: {#nominal-vs-real .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">percentile</th><th style = \"text-align: left;\">nominal_2009</th><th style = \"text-align: left;\">nominal_2016</th><th style = \"text-align: left;\">nominal_growth_pct</th><th style = \"text-align: left;\">real_growth_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">85th</td><td style = \"text-align: right;\">43300.0</td><td style = \"text-align: right;\">60700.0</td><td style = \"text-align: right;\">40.2</td><td style = \"text-align: right;\">8.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">75th</td><td style = \"text-align: right;\">31000.0</td><td style = \"text-align: right;\">45000.0</td><td style = \"text-align: right;\">45.2</td><td style = \"text-align: right;\">12.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">50th</td><td style = \"text-align: right;\">17400.0</td><td style = \"text-align: right;\">25000.0</td><td style = \"text-align: right;\">43.7</td><td style = \"text-align: right;\">11.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">25th</td><td style = \"text-align: right;\">8000.0</td><td style = \"text-align: right;\">11000.0</td><td style = \"text-align: right;\">37.5</td><td style = \"text-align: right;\">6.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">15th</td><td style = \"text-align: right;\">4500.0</td><td style = \"text-align: right;\">5000.0</td><td style = \"text-align: right;\">11.1</td><td style = \"text-align: right;\">-13.8</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**This is why the distinction matters.** In nominal terms the 15th percentile's income was\n**flat** between 2009 and 2016 — HK$4,500 to HK$5,000, up 11.1%. In real terms it **fell 13.8%**,\nbecause prices rose 28.9% over the same period.\n\nA nominal series would have shown the bottom of the distribution standing still. The real series\nshows it going backwards. Same data, opposite conclusion, and the only difference is the\ndeflator.\n\nNote also the ordering: real growth rises monotonically with the percentile — the higher the\nincome, the better it did. That is the inequality story the Gini cannot see, because the Gini\nhere is dominated by a handout the income data excludes.\n\n# Part 12.2 — Government popularity {#part-12.2}\n\n## Q1. Who would support the scheme, and who would object {#p2-q1}\n\n**Support** is easiest to explain for two groups with quite different reasons:\n\n- **Lower-income recipients**, for whom HK$6,000 is a meaningful share of annual income — around\n  a tenth at the 15th percentile, on the annualised figures in [Q3](#p1-q3).\n- **The government and politicians**, for whom the scheme is visible, immediate and\n  attributable. A universal payment is noticed by everyone; a targeted programme of the same cost\n  is noticed by few. If popularity is the objective, universality is a feature.\n\n**Objection** comes from three directions, and the interesting ones are not the obvious ones:\n\n- **Wealthier residents and business interests** may object to an equal split on the grounds that\n  contributions to growth were unequal.\n- **Some lower-income residents** may object *because* it is universal — a payment unrelated to\n  need spends most of its money on people who do not need it, which is precisely what\n  [Q4](#p1-q4) found.\n- **Policymakers** who would prefer the surplus spent on pensions, housing or training, on the\n  grounds that a one-off payment buys a one-off effect. The Gini series is evidence for their\n  position.\n\n## Q2. Is the poll sample representative? {#p2-q2}\n\nThe survey is a telephone poll of Cantonese-speaking Hong Kong residents aged 18 and over. Some\nof the design is sound:\n\n- **Numbers are randomly generated** rather than drawn from a directory, which avoids excluding\n  unlisted households.\n- **The sample is weighted to the population's age and sex distribution**, so those margins match\n  by construction.\n\nThree limitations matter for reading the series:\n\n1. **Telephone coverage is not neutral.** Whether landlines or mobiles are called changes who is\n   reachable, and that correlates with age and income. Weighting to age and sex does not fix a\n   bias in who answers within those cells.\n2. **Willingness to spend time on a survey is not random**, and it plausibly correlates with\n   political engagement — the thing being measured.\n3. **Cantonese-only excludes part of the population**, notably non-Cantonese-speaking migrants,\n   whose views on a residents-only handout might differ systematically.\n\nNone of this undermines the *comparison over time*, which is what Part 12.2 needs. A stable bias\nshifts the whole series and leaves changes intact. It would matter if the bias changed around\n2011, and there is no reason to think it did.\n\n## Q3. Satisfaction over time {#p2-q3}\n\n::: {#cell-read-polls .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Read one HKPORI half-yearly table.\n\nColumns are bilingual with no separator, e.g. \"淨值Netvalue\". Percentages carry a\n\"%\" and counts carry thousands separators, so both need stripping before parsing.\n\"\"\"\nfunction read_poll(file)\n    raw = CSV.read(rawpath(\"12\", file), DataFrame)\n    col(fragment) = names(raw)[findfirst(c -> occursin(fragment, c), names(raw))]\n    clean(x) = tryparse(Float64, replace(string(x), \"%\" => \"\", \",\" => \"\"))\n    out = DataFrame(start_date = Date.(string.(raw[!, col(\"Survey Start Date\")])),\n                    end_date = Date.(string.(raw[!, col(\"Survey End Date\")])),\n                    netvalue = clean.(raw[!, col(\"Netvalue\")]),\n                    mean_value = clean.(raw[!, col(\"Mean value\")]))\n    sort!(out, :start_date)\n    return dropmissing(out, :netvalue)\nend\n\noverall = read_poll(\"datatables.csv\")\nlivelihood = read_poll(\"satisfaction_datatables.csv\")\n\nDataFrame(series = [\"Overall satisfaction\", \"Improving people's livelihood\"],\n          polls = [nrow(overall), nrow(livelihood)],\n          first = [minimum(overall.start_date), minimum(livelihood.start_date)],\n          last = [maximum(overall.start_date), maximum(livelihood.start_date)],\n          net_min = [minimum(overall.netvalue), minimum(livelihood.netvalue)],\n          net_max = [maximum(overall.netvalue), maximum(livelihood.netvalue)])\n```\n\n::: {#read-polls .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">series</th><th style = \"text-align: left;\">polls</th><th style = \"text-align: left;\">first</th><th style = \"text-align: left;\">last</th><th style = \"text-align: left;\">net_min</th><th style = \"text-align: left;\">net_max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Dates.Date\" style = \"text-align: left;\">Date</th><th title = \"Dates.Date\" style = \"text-align: left;\">Date</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Overall satisfaction</td><td style = \"text-align: right;\">51</td><td style = \"text-align: left;\">1997-07-29</td><td style = \"text-align: left;\">2022-07-04</td><td style = \"text-align: right;\">-62.4</td><td style = \"text-align: right;\">40.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Improving people&apos;s livelihood</td><td style = \"text-align: right;\">50</td><td style = \"text-align: left;\">1997-07-29</td><td style = \"text-align: left;\">2022-10-10</td><td style = \"text-align: right;\">-57.0</td><td style = \"text-align: right;\">14.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {.callout-important}\n## The source the book names no longer serves this data\n\nThe book says to open the HKU POP overall performance page and click \"Download Excel\". HKU POP\nbecame the Hong Kong Public Opinion Research Institute in 2019; the page is now on `pori.hk`,\nwhere the table is rendered client-side behind bot protection. The page HTML contains **no table\nat all**, so there is nothing to fetch.\n\nThe Internet Archive does hold the old HKU POP series as plain text, and it loads cleanly — but\nit publishes only the **positive** percentages for six performance questions. The book's\nquestion needs the **net** value, positive minus negative, and the dissatisfaction companion\nseries is not archived as data.\n\nThe copy used here comes from **CORE Econ's own Python implementation** of the book, whose data\ndirectory carries the file under the same name the walk-through uses, with the full response\nbreakdown including the net value. Provenance for all three of this project's files is in\n`data/MANIFEST.toml`.\n:::\n\n**(a) Net satisfaction with the government since 2006.**\n\n::: {#cell-fig-satisfaction .cell execution_count=1}\n``` {.julia .cell-code}\nfrom_2006(df) = df[df.start_date .>= Date(2006, 1, 1), :]\no, l = from_2006(overall), from_2006(livelihood)\n\n# Dates are converted to fractional years rather than handed to Makie as `Date`.\n# Mixing a Date axis with `vspan!` and `text!` needs Makie's dimension-conversion\n# machinery to be primed by the first plot call, which is fragile; a numeric axis with\n# explicit year ticks behaves the same and always works.\nas_year(d) = year(d) + (dayofyear(d) - 1) / 365.25\n\nfig = Figure(size = (960, 520))\nax = Axis(fig[1, 1];\n          title = \"Approval was already falling when the handout arrived, and kept falling\",\n          xlabel = \"Survey start date\", ylabel = \"Net satisfaction (% points)\",\n          xticks = (2006:2:2022, string.(2006:2:2022)))\nvspan!(ax, as_year(Date(2011, 3, 1)), as_year(Date(2012, 8, 31)); color = (GRIDLINE, 0.9))\nhlines!(ax, [0]; color = BASELINE, linewidth = 1)\ntext!(ax, as_year(Date(2011, 4, 1)), 34; text = \"Scheme \\$6,000\\nannounced and paid\",\n      fontsize = 10, align = (:left, :top), color = MUTED)\n\nfor (j, (df, lab)) in enumerate([(o, \"Government overall\"),\n                                 (l, \"Improving people's livelihood\")])\n    x = as_year.(df.start_date)\n    lines!(ax, x, df.netvalue; color = series_color(j), linewidth = 2.5)\n    scatter!(ax, x, df.netvalue; color = series_color(j), markersize = 6)\n    text!(ax, x[end], df.netvalue[end]; text = lab, fontsize = 10,\n          align = (:right, :top), offset = (-4, -8), color = INK_SECONDARY)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Net satisfaction — the percentage satisfied minus the percentage dissatisfied — with the government overall and with its performance on improving livelihoods. Two series, so the question carries the colour, and both are direct-labelled. The rule at zero is where satisfied and dissatisfied balance; the shaded band marks the 2011–12 handout.](index_files/figure-html/fig-satisfaction-output-1.svg){#fig-satisfaction}\n:::\n:::\n\n\n\n::: {#tbl-around-handout .cell tbl-cap='Net satisfaction in the polls either side of the handout.' execution_count=1}\n``` {.julia .cell-code}\nwindow = overall[(overall.start_date .>= Date(2009, 1, 1)) .&\n                 (overall.start_date .<= Date(2014, 12, 31)), :]\nselect(window, :start_date, :end_date, :netvalue, :mean_value)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>12×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">start_date</th><th style = \"text-align: left;\">end_date</th><th style = \"text-align: left;\">netvalue</th><th style = \"text-align: left;\">mean_value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Dates.Date\" style = \"text-align: left;\">Date</th><th title = \"Dates.Date\" style = \"text-align: left;\">Date</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">2009-01-19</td><td style = \"text-align: left;\">2009-06-21</td><td style = \"text-align: right;\">-3.2</td><td style = \"text-align: right;\">2.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">2009-07-20</td><td style = \"text-align: left;\">2009-12-17</td><td style = \"text-align: right;\">-0.3</td><td style = \"text-align: right;\">2.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">2010-01-18</td><td style = \"text-align: left;\">2010-06-22</td><td style = \"text-align: right;\">-9.7</td><td style = \"text-align: right;\">2.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">2010-07-19</td><td style = \"text-align: left;\">2010-12-22</td><td style = \"text-align: right;\">-3.5</td><td style = \"text-align: right;\">2.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">2011-01-18</td><td style = \"text-align: left;\">2011-06-29</td><td style = \"text-align: right;\">-17.8</td><td style = \"text-align: right;\">2.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">2011-07-21</td><td style = \"text-align: left;\">2011-12-28</td><td style = \"text-align: right;\">-25.8</td><td style = \"text-align: right;\">2.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">2012-01-12</td><td style = \"text-align: left;\">2012-06-25</td><td style = \"text-align: right;\">-25.6</td><td style = \"text-align: right;\">2.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">2012-07-09</td><td style = \"text-align: left;\">2012-12-28</td><td style = \"text-align: right;\">-16.4</td><td style = \"text-align: right;\">2.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">2013-01-02</td><td style = \"text-align: left;\">2013-06-19</td><td style = \"text-align: right;\">-14.8</td><td style = \"text-align: right;\">2.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">2013-07-02</td><td style = \"text-align: left;\">2013-12-19</td><td style = \"text-align: right;\">-24.9</td><td style = \"text-align: right;\">2.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">2014-01-02</td><td style = \"text-align: left;\">2014-06-19</td><td style = \"text-align: right;\">-16.1</td><td style = \"text-align: right;\">2.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">2014-07-07</td><td style = \"text-align: left;\">2014-12-22</td><td style = \"text-align: right;\">-20.0</td><td style = \"text-align: right;\">2.6</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Overall satisfaction was high through 2006 and the first half of 2008, then fell.** It dropped\nin the second half of 2008 — the financial crisis — stayed low through 2009, and then declined\nfurther from 2010 through 2012. It crossed into **negative** territory and stayed there for\nyears.\n\n**The handout is not visible in the series.** Approval was falling before it, during it, and\nafter it. If the scheme was intended to buy popularity, the series gives no sign that it worked.\n\n**(b) and (c) The livelihood indicator.** Satisfaction with the government's performance on\nimproving people's livelihood tracks the overall series closely — the two rise and fall together\nacross the whole period, and neither shows a break at the handout.\n\nThe livelihood series sits **below** the overall series for most of the period, which is the\nmore interesting detail: people rated the government worse on improving livelihoods than they\nrated it in general. A cash handout is about as direct an attempt at improving livelihoods as a\ngovernment can make, and it did not move the indicator most specific to it.\n\n## Q4. Did the scheme achieve its aims? {#p2-q4}\n\n**On inequality: briefly and mechanically, yes.** The Gini fell 0.017 points in 2012 and returned\nto its prior level in 2013.\n\n**On popularity: no evidence at all.** Net satisfaction was in decline before the payment and\ncontinued declining after it, on both the overall measure and the one closest to the policy.\n\n**Why this cannot be read as \"the handout was unpopular\".** The design here is a single series\nwith a single intervention and no comparison group, so anything else happening in Hong Kong over\n2010–2012 is inside the estimate. That is the weakness [Project 3](../03-sugar-tax/index.qmd)\nidentified in before-and-after comparisons, and it applies with full force:\n\n- **The trend was already downward.** The decline runs from 2008. Extrapolating it, 2012's value\n  is roughly where the trend was heading — so the handout may have arrived, done nothing, or\n  slowed a steeper fall, and this data cannot distinguish those.\n- **Other things dominated the period.** Political controversies, housing costs and the\n  2012 Chief Executive transition all bear on government approval, and any of them could swamp a\n  one-off payment.\n- **A one-off payment plausibly buys a one-off response.** Even a real effect on approval would\n  be expected to decay, and the polls are half-yearly, so a short-lived bump could fall between\n  observations entirely.\n\n**What would be needed to answer the question properly** is the difference-in-differences design\nthis project does not have: a comparable population that did not receive the payment, so that the\ncommon trend could be removed. Scheme $6,000 went to every adult resident simultaneously, which\nis excellent policy delivery and leaves no control group. The universality that made it\npolitically attractive is exactly what makes its effect unmeasurable.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading blocks from one sheet | Setup | `readxlsx(path)[sheet][:]`, index by row |\n| Rows in an unexpected order | Setup | `sort` before assigning group sizes |\n| Expanding grouped data to units | Q12.1 Q2 | `reduce(vcat, [fill(v, n) for ...])` |\n| Cumulative income shares | Q12.1 Q2 | `sum(sorted[1:p]) / sum(sorted)` |\n| Lorenz curve with an equality line | Q12.1 Q2 | `lines!` plus a dashed reference diagonal |\n| Gini from unit records | Q12.1 Q3 | `gini(v)` from the shared helpers |\n| A chain index from growth rates | Q12.1 ext | running product inside a `let` |\n| Bilingual column names | Q12.2 Q3 | match on a fragment with `occursin` |\n| Percentages stored as text | Q12.2 Q3 | strip `%` and `,` before `tryparse` |\n| Dates from ISO strings | Q12.2 Q3 | `Date.(string.(col))` |\n| Shading a period on a time axis | Q12.2 Q3 | `vspan!(ax, from, to)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}