{
  "hash": "feba5565825936b2a2081778340831be",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"6. Measuring management practices\"\nsubtitle: \"Scoring how firms are run, and how confident we can be about it\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nFirms in the same industry and country differ enormously in productivity. One candidate\nexplanation is that some are simply better managed — which requires management to be measurable.\nBloom, Genakos, Sadun and Van Reenen built a survey that scores it, and this project works with\ntheir data.\n\n- **[Part 6.1](#part-6.1)** — how management practices vary\n- **[Part 6.2](#part-6.2)** — how confident we can be in the differences\n- **[Part 6.3](#part-6.3)** — what management varies *with*\n\nNew concept: the **confidence interval**, and the discipline of not reading a difference between\ntwo means without one. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/06-01.html),\n[R walk-throughs](https://books.core-econ.org/doing-economics/book/text/06-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/06-04.html).\n\n## The data\n\nTwo extracts from the World Management Survey, inside one zip:\n\n| | |\n|---|---|\n| `AMP_graph_manufacturing.csv` | 9,207 manufacturing firms, 20 countries |\n| `AMP_graph_public.csv` | 1,963 hospitals and schools, 7 countries |\n\nEvery published figure in this project reproduces — all 19 country means, all twelve\nhospital and school means, and both confidence interval widths.\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing ZipFile, CSV, DataFrames\nusing Statistics\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-wms .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    read_wms(filename)\n\nRead one CSV out of the project zip. Both files carry trailing junk from the original\nStata export - an empty `Column20`, and a fragment of the codebook that ended up as a\ncolumn header - so anything unnamed or all-missing is dropped.\n\"\"\"\nfunction read_wms(filename)\n    archive = ZipFile.Reader(rawpath(\"06\", \"project-6-datafile.zip\"))\n    try\n        idx = findfirst(f -> f.name == filename, archive.files)\n        idx === nothing && error(\"$filename not found in the archive\")\n        df = CSV.read(read(archive.files[idx]), DataFrame; missingstring = \"\")\n        keep = [c for c in names(df)\n                if !startswith(c, \"Column\") && !occursin(\"storage\", c) &&\n                   !occursin(\"str44\", c) && !all(ismissing, df[!, c])]\n        return select(df, keep)\n    finally\n        close(archive)\n    end\nend\n\nmanufacturing = read_wms(\"AMP_graph_manufacturing.csv\")\npublic_sector = read_wms(\"AMP_graph_public.csv\")\n\n(manufacturing = size(manufacturing), public = size(public_sector),\n countries = length(unique(manufacturing.country)))\n```\n\n::: {#read-wms .cell-output .cell-output-display execution_count=1}\n```\n(manufacturing = (9207, 19), public = (1963, 11), countries = 20)\n```\n:::\n:::\n\n\n\n# Part 6.1 — How management practices vary {#part-6.1}\n\n## Q1. How the survey works {#p1-q1}\n\nThe survey scores firms on eighteen practices grouped into three families, each scored 1 to 5,\nwith the overall `management` score their average.\n\n- **Monitoring** — whether performance is tracked, how often, and whether anyone acts on it.\n- **Targets** — whether goals exist, are stretching, and connect to the firm's strategy.\n- **Incentives** (`people` in the data) — whether promotion, pay and dismissal follow performance.\n\n**How the interviews were run.** Interviewers spoke to plant managers by telephone using\nopen-ended questions and scored the answers against a rubric — asking \"how do you track\nperformance?\" rather than \"do you track performance on a scale of 1 to 5\". The point is to score\nwhat the firm actually does rather than what a manager will claim.\n\n**What makes the scores trustworthy**, and each is a specific design choice:\n\n- **Double scoring.** A subset of interviews was scored by a second interviewer who did not hear\n  the first's assessment, so scorer disagreement can be measured rather than assumed away.\n- **Blind to performance.** Interviewers were not told the firm's financials, so they could not\n  score a profitable firm as well managed by inference.\n- **Blind to purpose.** Managers were told it was a research exercise, not a benchmarking\n  service, which removes the incentive to talk the score up.\n- **Interviewer fixed effects.** Who conducted the interview is recorded, so systematic\n  interviewer leniency can be controlled for.\n\n**Are monitoring, targets and incentives the right criteria?** They are defensible and\nincomplete. All three come from a particular view of the firm — that the central problem is\ngetting information about performance and making it worth someone's while to act on it. That\nmisses things a different theory would emphasise: strategy, product design, whether the firm is\nin the right business at all. So the score measures a *specific and coherent* notion of\nmanagement quality, not management in general. A firm could score 5 on all eighteen practices\nwhile executing a doomed strategy efficiently.\n\n## Q2. Mean management score by country {#p1-q2}\n\n::: {#cell-country-means .cell execution_count=1}\n``` {.julia .cell-code}\ncountry_stats = combine(groupby(manufacturing, :country),\n    :management => (x -> mean(skipmissing(x))) => :mean,\n    :management => (x -> std(skipmissing(x))) => :sd,\n    nrow => :firms)\nsort!(country_stats, :mean, rev = true)\ncountry_stats.rank = 1:nrow(country_stats)\n\nselect(transform(country_stats, [:mean, :sd] .=> ByRow(x -> round(x, digits = 3));\n                 renamecols = false),\n       :rank, :country, :firms, :mean, :sd)\n```\n\n::: {#country-means .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>20×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">rank</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">firms</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"InlineStrings.String31\" style = \"text-align: left;\">String31</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1225</td><td style = \"text-align: right;\">3.348</td><td style = \"text-align: right;\">0.643</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">646</td><td style = \"text-align: right;\">3.23</td><td style = \"text-align: right;\">0.569</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">Japan</td><td style = \"text-align: right;\">176</td><td style = \"text-align: right;\">3.23</td><td style = \"text-align: right;\">0.615</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">388</td><td style = \"text-align: right;\">3.206</td><td style = \"text-align: right;\">0.545</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: right;\">385</td><td style = \"text-align: right;\">3.17</td><td style = \"text-align: right;\">0.615</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">6</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: right;\">1242</td><td style = \"text-align: right;\">3.034</td><td style = \"text-align: right;\">0.679</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">7</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">613</td><td style = \"text-align: right;\">3.03</td><td style = \"text-align: right;\">0.651</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">8</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">289</td><td style = \"text-align: right;\">3.027</td><td style = \"text-align: right;\">0.614</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">9</td><td style = \"text-align: left;\">Australia</td><td style = \"text-align: right;\">392</td><td style = \"text-align: right;\">3.019</td><td style = \"text-align: right;\">0.577</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">New Zealand</td><td style = \"text-align: right;\">106</td><td style = \"text-align: right;\">2.928</td><td style = \"text-align: right;\">0.542</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">11</td><td style = \"text-align: left;\">Mexico</td><td style = \"text-align: right;\">189</td><td style = \"text-align: right;\">2.919</td><td style = \"text-align: right;\">0.699</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">12</td><td style = \"text-align: left;\">Poland</td><td style = \"text-align: right;\">351</td><td style = \"text-align: right;\">2.896</td><td style = \"text-align: right;\">0.641</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">13</td><td style = \"text-align: left;\">Republic of Ireland</td><td style = \"text-align: right;\">106</td><td style = \"text-align: right;\">2.887</td><td style = \"text-align: right;\">0.801</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">14</td><td style = \"text-align: left;\">Portugal</td><td style = \"text-align: right;\">247</td><td style = \"text-align: right;\">2.869</td><td style = \"text-align: right;\">0.626</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">15</td><td style = \"text-align: left;\">Chile</td><td style = \"text-align: right;\">317</td><td style = \"text-align: right;\">2.828</td><td style = \"text-align: right;\">0.599</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: right;\">16</td><td style = \"text-align: left;\">Argentina</td><td style = \"text-align: right;\">249</td><td style = \"text-align: right;\">2.761</td><td style = \"text-align: right;\">0.714</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: right;\">17</td><td style = \"text-align: left;\">Greece</td><td style = \"text-align: right;\">251</td><td style = \"text-align: right;\">2.735</td><td style = \"text-align: right;\">0.808</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: right;\">18</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">746</td><td style = \"text-align: right;\">2.71</td><td style = \"text-align: right;\">0.471</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: right;\">19</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">569</td><td style = \"text-align: right;\">2.708</td><td style = \"text-align: right;\">0.685</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: right;\">20</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">720</td><td style = \"text-align: right;\">2.67</td><td style = \"text-align: right;\">0.68</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-country-means .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (860, 520))\nax = Axis(fig[1, 1];\n          title = \"The United States leads; the gap top to bottom is about 0.7 points\",\n          ylabel = \"Mean management score\",\n          xticks = (1:nrow(country_stats), country_stats.country),\n          xticklabelrotation = pi / 3,\n          limits = (nothing, (0, 3.8)))\nbarplot!(ax, 1:nrow(country_stats), country_stats.mean;\n         width = 0.6, color = series_color(1))\nfor (x, v) in zip(1:nrow(country_stats), country_stats.mean)\n    text!(ax, x, v; text = string(round(v, digits = 2)), fontsize = 9,\n          align = (:center, :bottom), offset = (0, 3))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean management score by country, manufacturing firms, ordered highest to lowest. One series, so one colour — shading the bars by height would spend the colour channel on information the bar length already carries.](index_files/figure-html/fig-country-means-output-1.svg){#fig-country-means}\n:::\n:::\n\n\n\nEvery one of these reproduces the book's published figures. The United States leads at **3.35**,\nfollowed by Germany and Japan at 3.23; India is lowest at 2.67. The book's list names Great\nBritain where the data says UK — same value, 3.03.\n\n**Comparison with Figure 1 of Bloom et al.** The ordering matches: the US clearly ahead, a\ncluster of European and East Asian economies behind it, then the middle-income countries. The\nspread is the striking feature — the entire range from best to worst country is about 0.7\npoints on a 5-point scale, which is *smaller than the standard deviation within most individual\ncountries* (0.47 to 0.81). Variation between firms inside a country dwarfs variation between\ncountry averages. That is the paper's central finding and Q3 makes it visible.\n\n## Q3. Distributions, not just means {#p1-q3}\n\nThree countries plus the United States, in 0.2-wide bins across the 1–5 range.\n\n::: {#cell-frequency-tables .cell execution_count=1}\n``` {.julia .cell-code}\nconst FOCUS = [\"United States\", \"Germany\", \"Brazil\", \"India\"]\nconst BREAKS = 1.0:0.2:5.0\n\nfreq = DataFrame(bin = freqtable_binned(\n    collect(skipmissing(manufacturing[manufacturing.country .== \"United States\", :management]));\n    breaks = BREAKS).bin)\n\nfor country in FOCUS\n    scores = collect(skipmissing(manufacturing[manufacturing.country .== country, :management]))\n    t = freqtable_binned(scores; breaks = BREAKS)\n    freq[!, country] = round.(100 .* t.proportion, digits = 1)\nend\n\nfreq[6:16, :]\n```\n\n::: {#frequency-tables .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>11×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">bin</th><th style = \"text-align: left;\">United States</th><th style = \"text-align: left;\">Germany</th><th style = \"text-align: left;\">Brazil</th><th style = \"text-align: left;\">India</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">(2, 2.20]</td><td style = \"text-align: right;\">2.3</td><td style = \"text-align: right;\">2.2</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">8.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">(2.20, 2.40]</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">4.2</td><td style = \"text-align: right;\">9.1</td><td style = \"text-align: right;\">11.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">(2.40, 2.60]</td><td style = \"text-align: right;\">4.7</td><td style = \"text-align: right;\">3.7</td><td style = \"text-align: right;\">10.2</td><td style = \"text-align: right;\">9.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">(2.60, 2.80]</td><td style = \"text-align: right;\">7.8</td><td style = \"text-align: right;\">9.1</td><td style = \"text-align: right;\">12.0</td><td style = \"text-align: right;\">12.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">(2.80, 3]</td><td style = \"text-align: right;\">11.3</td><td style = \"text-align: right;\">11.1</td><td style = \"text-align: right;\">12.5</td><td style = \"text-align: right;\">10.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">(3, 3.20]</td><td style = \"text-align: right;\">9.6</td><td style = \"text-align: right;\">11.8</td><td style = \"text-align: right;\">7.6</td><td style = \"text-align: right;\">6.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">(3.20, 3.40]</td><td style = \"text-align: right;\">13.4</td><td style = \"text-align: right;\">16.4</td><td style = \"text-align: right;\">8.6</td><td style = \"text-align: right;\">8.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">(3.40, 3.60]</td><td style = \"text-align: right;\">9.1</td><td style = \"text-align: right;\">11.6</td><td style = \"text-align: right;\">5.1</td><td style = \"text-align: right;\">4.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">(3.60, 3.80]</td><td style = \"text-align: right;\">11.8</td><td style = \"text-align: right;\">12.1</td><td style = \"text-align: right;\">4.2</td><td style = \"text-align: right;\">4.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">(3.80, 4]</td><td style = \"text-align: right;\">9.3</td><td style = \"text-align: right;\">8.5</td><td style = \"text-align: right;\">2.3</td><td style = \"text-align: right;\">2.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">(4, 4.20]</td><td style = \"text-align: right;\">4.9</td><td style = \"text-align: right;\">3.1</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">1.5</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nPercentages rather than counts, because the samples differ by a factor of ten and raw counts\nwould only show that the US sample is large.\n\n::: {#cell-fig-distributions .cell execution_count=1}\n``` {.julia .cell-code}\nus_scores = collect(skipmissing(manufacturing[manufacturing.country .== \"United States\", :management]))\nus_table = freqtable_binned(us_scores; breaks = BREAKS)\ncentres(t) = (t.lower .+ t.upper) ./ 2\n\nfig = Figure(size = (900, 560))\nLabel(fig[0, 1:2], \"Countries differ less in where the distribution sits than in how wide it is\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nfor (i, country) in enumerate(FOCUS)\n    r, c = fldmod1(i, 2)\n    ax = Axis(fig[r, c]; title = country,\n              xlabel = r == 2 ? \"Management score\" : \"\",\n              ylabel = c == 1 ? \"% of firms\" : \"\",\n              limits = ((1, 5), (0, 20)))\n    # The US distribution behind every panel as the reference.\n    barplot!(ax, centres(us_table), 100 .* us_table.proportion;\n             width = 0.18, color = (BASELINE, 0.55))\n    scores = collect(skipmissing(manufacturing[manufacturing.country .== country, :management]))\n    t = freqtable_binned(scores; breaks = BREAKS)\n    barplot!(ax, centres(t), 100 .* t.proportion;\n             width = 0.11, color = series_color(1))\n    c == 2 && hideydecorations!(ax; grid = false)\n    r == 1 && hidexdecorations!(ax; grid = false)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Distribution of management scores, each country against the United States in grey. Overlaying four filled histograms on one axis would need four hues and four transparencies fighting each other; small multiples against a common reference answer the question the book asks — how does each country compare with the US — more directly.](index_files/figure-html/fig-distributions-output-1.svg){#fig-distributions}\n:::\n:::\n\n\n\nAll four distributions are broadly bell-shaped and heavily overlapping. The US panel is the\nreference against itself. Germany sits close to the US with a slightly tighter spread. Brazil and\nIndia are shifted left, but the overlap is the point: **a large fraction of Brazilian and Indian\nfirms score above the US average, and a large fraction of US firms score below the Brazilian\naverage.** The country means differ; the distributions mostly do not separate.\n\nIndia's left tail is the clearest difference — a group of very badly managed firms with no real\nUS counterpart. That tail, rather than a wholesale shift, is much of what moves the mean.\n\n## Q4. Box and whisker plots {#p1-q4}\n\n::: {#cell-fig-boxplots .cell execution_count=1}\n``` {.julia .cell-code}\nbox_data = manufacturing[in(FOCUS).(manufacturing.country) .&\n                         .!ismissing.(manufacturing.management), :]\npositions = [findfirst(==(c), FOCUS) for c in box_data.country]\n\nfig = Figure(size = (760, 480))\nax = Axis(fig[1, 1];\n          title = \"Medians differ by less than the spread within any one country\",\n          ylabel = \"Management score\",\n          xticks = (1:length(FOCUS), FOCUS))\nboxplot!(ax, positions, Float64.(box_data.management);\n         width = 0.5, color = series_color(1),\n         mediancolor = SURFACE, whiskercolor = BASELINE, strokecolor = BASELINE)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Management score distributions as box plots. The box spans the interquartile range with the median inside it; whiskers reach 1.5 times the IQR and points beyond are drawn individually.](index_files/figure-html/fig-boxplots-output-1.svg){#fig-boxplots}\n:::\n:::\n\n\n\n::: {#cell-quartiles .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(country = FOCUS,\n          q25 = [round(quantile(collect(skipmissing(\n                    manufacturing[manufacturing.country .== c, :management])), 0.25), digits = 2)\n                 for c in FOCUS],\n          median = [round(median(collect(skipmissing(\n                    manufacturing[manufacturing.country .== c, :management]))), digits = 2)\n                 for c in FOCUS],\n          q75 = [round(quantile(collect(skipmissing(\n                    manufacturing[manufacturing.country .== c, :management])), 0.75), digits = 2)\n                 for c in FOCUS])\n```\n\n::: {#quartiles .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">q25</th><th style = \"text-align: left;\">median</th><th style = \"text-align: left;\">q75</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">2.89</td><td style = \"text-align: right;\">3.33</td><td style = \"text-align: right;\">3.78</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">2.89</td><td style = \"text-align: right;\">3.28</td><td style = \"text-align: right;\">3.61</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">2.22</td><td style = \"text-align: right;\">2.67</td><td style = \"text-align: right;\">3.17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">2.17</td><td style = \"text-align: right;\">2.66</td><td style = \"text-align: right;\">3.11</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe box plots say the same thing as Q3 more compactly, and lose something. They make the\n*overlap* of the interquartile ranges immediately obvious — every box overlaps every other box —\nwhich is the central point. What they discard is shape: a box plot cannot show that India's\ndistribution has a long thin left tail rather than being uniformly shifted, because five summary\nnumbers do not encode skew. The histograms and the box plots are worth having together for that\nreason.\n\n## Q5. Hospitals and schools {#p1-q5}\n\n::: {#cell-public-means .cell execution_count=1}\n``` {.julia .cell-code}\npublic_stats = combine(groupby(dropmissing(public_sector, :management), [:ind, :country]),\n    :management => mean => :mean,\n    :monitoring => (x -> mean(skipmissing(x))) => :monitoring,\n    :targets => (x -> mean(skipmissing(x))) => :targets,\n    :people => (x -> mean(skipmissing(x))) => :people,\n    nrow => :organisations)\nsort!(public_stats, [:ind, :mean], rev = [false, true])\n\nselect(transform(public_stats, names(public_stats, Float64) .=>\n                 ByRow(x -> round(x, digits = 3)); renamecols = false),\n       :ind, :country, :organisations, :mean, :monitoring, :targets, :people)\n```\n\n::: {#public-means .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>12×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">ind</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">organisations</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">monitoring</th><th style = \"text-align: left;\">targets</th><th style = \"text-align: left;\">people</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"InlineStrings.String15\" style = \"text-align: left;\">String15</th><th title = \"InlineStrings.String7\" style = \"text-align: left;\">String7</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">US</td><td style = \"text-align: right;\">327</td><td style = \"text-align: right;\">3.005</td><td style = \"text-align: right;\">3.212</td><td style = \"text-align: right;\">2.872</td><td style = \"text-align: right;\">2.923</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: right;\">184</td><td style = \"text-align: right;\">2.824</td><td style = \"text-align: right;\">3.07</td><td style = \"text-align: right;\">2.711</td><td style = \"text-align: right;\">2.621</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">130</td><td style = \"text-align: right;\">2.64</td><td style = \"text-align: right;\">2.848</td><td style = \"text-align: right;\">2.549</td><td style = \"text-align: right;\">2.454</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">43</td><td style = \"text-align: right;\">2.566</td><td style = \"text-align: right;\">2.898</td><td style = \"text-align: right;\">2.679</td><td style = \"text-align: right;\">2.364</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: right;\">175</td><td style = \"text-align: right;\">2.524</td><td style = \"text-align: right;\">2.823</td><td style = \"text-align: right;\">2.44</td><td style = \"text-align: right;\">2.173</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">166</td><td style = \"text-align: right;\">2.48</td><td style = \"text-align: right;\">2.672</td><td style = \"text-align: right;\">2.33</td><td style = \"text-align: right;\">2.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">158</td><td style = \"text-align: right;\">2.404</td><td style = \"text-align: right;\">2.592</td><td style = \"text-align: right;\">2.29</td><td style = \"text-align: right;\">2.033</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: right;\">110</td><td style = \"text-align: right;\">2.958</td><td style = \"text-align: right;\">3.075</td><td style = \"text-align: right;\">2.967</td><td style = \"text-align: right;\">2.745</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">89</td><td style = \"text-align: right;\">2.801</td><td style = \"text-align: right;\">3.09</td><td style = \"text-align: right;\">2.724</td><td style = \"text-align: right;\">2.506</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: right;\">151</td><td style = \"text-align: right;\">2.78</td><td style = \"text-align: right;\">2.915</td><td style = \"text-align: right;\">2.862</td><td style = \"text-align: right;\">2.328</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">US</td><td style = \"text-align: right;\">285</td><td style = \"text-align: right;\">2.725</td><td style = \"text-align: right;\">2.881</td><td style = \"text-align: right;\">2.625</td><td style = \"text-align: right;\">2.474</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">143</td><td style = \"text-align: right;\">2.538</td><td style = \"text-align: right;\">2.695</td><td style = \"text-align: right;\">2.494</td><td style = \"text-align: right;\">2.262</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-public .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 440))\nLabel(fig[0, 1:2], \"The US leads in hospitals and the UK in schools - and both trail manufacturing\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nfor (i, industry) in enumerate((\"Hospitals\", \"Schools\"))\n    sub = sort(public_stats[public_stats.ind .== industry, :], :mean, rev = true)\n    ax = Axis(fig[1, i]; title = industry,\n              ylabel = i == 1 ? \"Mean management score\" : \"\",\n              xticks = (1:nrow(sub), sub.country), xticklabelrotation = pi / 4,\n              limits = (nothing, (0, 3.4)))\n    barplot!(ax, 1:nrow(sub), sub.mean; width = 0.6, color = series_color(1))\n    for (x, v) in zip(1:nrow(sub), sub.mean)\n        text!(ax, x, v; text = string(round(v, digits = 2)), fontsize = 10,\n              align = (:center, :bottom), offset = (0, 3))\n    end\n    i == 2 && hideydecorations!(ax; grid = false)\nend\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean management score in hospitals and schools, sorted within each panel. Note the vertical scale: public-sector scores sit below the manufacturing range throughout.](index_files/figure-html/fig-public-output-1.svg){#fig-public}\n:::\n:::\n\n\n\nBoth reproduce the book exactly. Hospitals: the US leads at 3.00, France lowest at 2.40. Schools:\nthe UK leads at 2.96, Germany lowest at 2.54.\n\n**Two things worth noticing.** Public-sector scores are *lower across the board* than\nmanufacturing — every hospital and school average falls below almost every manufacturing country\naverage. And the country ordering changes between sectors: the US leads hospitals but sits fourth\nof five in schools, while the UK is the reverse.\n\n**Plausible explanations.** The incentives family is where public organisations score worst, and\nthat is close to mechanical: promotion and dismissal in a public hospital or state school are\nconstrained by tenure rules and collective agreements in ways a manufacturer's are not, so\npractices the rubric rewards are often not legally available. Competitive pressure is also weaker\n— a badly managed factory loses customers, a badly managed school may not.\n\nThat the ordering differs by sector is the more interesting fact, because it argues against a\nsingle national management culture. Whatever makes the US good at running factories and hospitals\ndoes not carry to its schools.\n\n# Part 6.2 — How confident can we be? {#part-6.2}\n\nEvery mean in Part 6.1 is an estimate from a sample. A confidence interval says how precise.\n\n## Q1. Confidence intervals for four countries {#p2-q1}\n\n::: {#cell-confidence-intervals .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    mean_ci(values; z = 1.96)\n\nSample mean with the half-width of its 95% confidence interval, `z * s / sqrt(n)`.\n\nThe book writes the half-width as `1.96 * sqrt(s^2 / (n - 1))`, which puts `n - 1`\nunder the root rather than using it in the variance. At these sample sizes the two\nagree to three decimal places; the conventional form is used here.\n\"\"\"\nfunction mean_ci(values; z = 1.96)\n    v = collect(skipmissing(values))\n    n = length(v)\n    m, s = mean(v), std(v)\n    return (n = n, mean = m, sd = s, half_width = z * s / sqrt(n))\nend\n\nci_table = DataFrame(country = String[], firms = Int[], mean = Float64[],\n                     sd = Float64[], half_width = Float64[],\n                     lower = Float64[], upper = Float64[])\nfor country in FOCUS\n    r = mean_ci(manufacturing[manufacturing.country .== country, :management])\n    push!(ci_table, (country, r.n, round(r.mean, digits = 3), round(r.sd, digits = 3),\n                     round(r.half_width, digits = 3),\n                     round(r.mean - r.half_width, digits = 3),\n                     round(r.mean + r.half_width, digits = 3)))\nend\nci_table\n```\n\n::: {#confidence-intervals .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">firms</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">half_width</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1225</td><td style = \"text-align: right;\">3.348</td><td style = \"text-align: right;\">0.643</td><td style = \"text-align: right;\">0.036</td><td style = \"text-align: right;\">3.312</td><td style = \"text-align: right;\">3.384</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">646</td><td style = \"text-align: right;\">3.23</td><td style = \"text-align: right;\">0.569</td><td style = \"text-align: right;\">0.044</td><td style = \"text-align: right;\">3.186</td><td style = \"text-align: right;\">3.274</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">569</td><td style = \"text-align: right;\">2.708</td><td style = \"text-align: right;\">0.685</td><td style = \"text-align: right;\">0.056</td><td style = \"text-align: right;\">2.651</td><td style = \"text-align: right;\">2.764</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">720</td><td style = \"text-align: right;\">2.67</td><td style = \"text-align: right;\">0.68</td><td style = \"text-align: right;\">0.05</td><td style = \"text-align: right;\">2.621</td><td style = \"text-align: right;\">2.72</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAdding Chile, which the book uses as its contrast with the US:\n\n::: {#cell-chile-us .cell execution_count=1}\n``` {.julia .cell-code}\ncomparison = DataFrame(country = String[], firms = Int[], mean = Float64[],\n                       sd = Float64[], half_width = Float64[])\nfor country in (\"United States\", \"Chile\")\n    r = mean_ci(manufacturing[manufacturing.country .== country, :management])\n    push!(comparison, (country, r.n, round(r.mean, digits = 2), round(r.sd, digits = 2),\n                       round(r.half_width, digits = 3)))\nend\ncomparison\n```\n\n::: {#chile-us .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">firms</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">half_width</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1225</td><td style = \"text-align: right;\">3.35</td><td style = \"text-align: right;\">0.64</td><td style = \"text-align: right;\">0.036</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Chile</td><td style = \"text-align: right;\">317</td><td style = \"text-align: right;\">2.83</td><td style = \"text-align: right;\">0.6</td><td style = \"text-align: right;\">0.066</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe book reports a half-width of **0.04** for the US and **0.07** for Chile; the computed values\nare 0.036 and 0.066. The one difference anywhere in this project: the US firm count is 1,225 here\nagainst the book's 1,224.\n\n::: {#cell-fig-ci .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 480))\nax = Axis(fig[1, 1];\n          title = \"Intervals narrow enough that these four countries are distinguishable\",\n          ylabel = \"Mean management score\",\n          xticks = (1:nrow(ci_table), ci_table.country),\n          limits = (nothing, (2.0, 3.7)))\nbarplot!(ax, 1:nrow(ci_table), ci_table.mean; width = 0.5, color = series_color(1))\nerrorbars!(ax, 1:nrow(ci_table), ci_table.mean, ci_table.half_width;\n           color = INK, whiskerwidth = 12, linewidth = 2)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean management score with 95% confidence intervals. The interval is the estimate's precision, not the spread of firms — which is far wider, and shown in Q1.4.](index_files/figure-html/fig-ci-output-1.svg){#fig-ci}\n:::\n:::\n\n\n\n**What the interval means.** If the sampling were repeated many times, 95% of the intervals\nconstructed this way would contain the true population mean. It is a statement about the\nprocedure, not a 95% probability that this particular interval contains the truth.\n\n**Reading the differences.** The rule of thumb is that non-overlapping intervals indicate a\ndifference unlikely to be chance. Here none of the four overlap, so the ranking of these four\ncountries is not an artefact of sampling. Note how much narrower the intervals are than the\ndistributions in Q1.3 — with 646 to 1,225 firms per country, the *mean* is pinned down precisely\neven though individual firms vary hugely. Those are different quantities and the chart types keep\nthem separate.\n\n**A different confidence level** changes the multiplier: 1.645 for 90%, 2.576 for 99%. A 99%\ninterval is about 31% wider than a 95% one on the same data. Nothing about the data changes —\nonly how much of the sampling distribution you insist on covering. Demanding more confidence buys\nit with precision.\n\n## Q2. Which public-sector countries differ from the US {#p2-q2}\n\n::: {#cell-public-ci .cell execution_count=1}\n``` {.julia .cell-code}\npublic_ci = DataFrame(ind = String[], country = String[], n = Int[],\n                      mean = Float64[], half_width = Float64[],\n                      lower = Float64[], upper = Float64[])\nfor industry in (\"Hospitals\", \"Schools\")\n    sub = public_sector[(public_sector.ind .== industry) .& .!ismissing.(public_sector.management), :]\n    for country in sort(unique(sub.country))\n        r = mean_ci(sub[sub.country .== country, :management])\n        push!(public_ci, (industry, country, r.n, round(r.mean, digits = 3),\n                          round(r.half_width, digits = 3),\n                          round(r.mean - r.half_width, digits = 3),\n                          round(r.mean + r.half_width, digits = 3)))\n    end\nend\nsort!(public_ci, [:ind, :mean], rev = [false, true])\npublic_ci\n```\n\n::: {#public-ci .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>12×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">ind</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">half_width</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">US</td><td style = \"text-align: right;\">327</td><td style = \"text-align: right;\">3.005</td><td style = \"text-align: right;\">0.059</td><td style = \"text-align: right;\">2.946</td><td style = \"text-align: right;\">3.063</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: right;\">184</td><td style = \"text-align: right;\">2.824</td><td style = \"text-align: right;\">0.062</td><td style = \"text-align: right;\">2.762</td><td style = \"text-align: right;\">2.886</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">130</td><td style = \"text-align: right;\">2.64</td><td style = \"text-align: right;\">0.066</td><td style = \"text-align: right;\">2.574</td><td style = \"text-align: right;\">2.707</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">43</td><td style = \"text-align: right;\">2.566</td><td style = \"text-align: right;\">0.131</td><td style = \"text-align: right;\">2.435</td><td style = \"text-align: right;\">2.698</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: right;\">175</td><td style = \"text-align: right;\">2.524</td><td style = \"text-align: right;\">0.067</td><td style = \"text-align: right;\">2.457</td><td style = \"text-align: right;\">2.591</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">166</td><td style = \"text-align: right;\">2.48</td><td style = \"text-align: right;\">0.079</td><td style = \"text-align: right;\">2.401</td><td style = \"text-align: right;\">2.559</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">158</td><td style = \"text-align: right;\">2.404</td><td style = \"text-align: right;\">0.067</td><td style = \"text-align: right;\">2.337</td><td style = \"text-align: right;\">2.471</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: right;\">110</td><td style = \"text-align: right;\">2.958</td><td style = \"text-align: right;\">0.074</td><td style = \"text-align: right;\">2.884</td><td style = \"text-align: right;\">3.032</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">89</td><td style = \"text-align: right;\">2.801</td><td style = \"text-align: right;\">0.092</td><td style = \"text-align: right;\">2.708</td><td style = \"text-align: right;\">2.893</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: right;\">151</td><td style = \"text-align: right;\">2.78</td><td style = \"text-align: right;\">0.063</td><td style = \"text-align: right;\">2.717</td><td style = \"text-align: right;\">2.842</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">US</td><td style = \"text-align: right;\">285</td><td style = \"text-align: right;\">2.725</td><td style = \"text-align: right;\">0.052</td><td style = \"text-align: right;\">2.672</td><td style = \"text-align: right;\">2.777</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">143</td><td style = \"text-align: right;\">2.538</td><td style = \"text-align: right;\">0.07</td><td style = \"text-align: right;\">2.468</td><td style = \"text-align: right;\">2.607</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-public-ci .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (940, 460))\nLabel(fig[0, 1:2], \"Confidently worse than the US in hospitals; in schools, mostly indistinguishable\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nfor (i, industry) in enumerate((\"Hospitals\", \"Schools\"))\n    sub = sort(public_ci[public_ci.ind .== industry, :], :mean, rev = true)\n    us = only(sub[sub.country .== \"US\", :])\n    ax = Axis(fig[1, i]; title = industry,\n              ylabel = i == 1 ? \"Mean management score\" : \"\",\n              xticks = (1:nrow(sub), sub.country), xticklabelrotation = pi / 4,\n              limits = (nothing, (2.0, 3.3)))\n    # The US interval as a band, so \"clears the US\" is readable directly.\n    hspan!(ax, us.lower, us.upper; color = (BASELINE, 0.4))\n    scatter!(ax, 1:nrow(sub), sub.mean; color = series_color(1))\n    errorbars!(ax, 1:nrow(sub), sub.mean, sub.half_width;\n               color = series_color(1), whiskerwidth = 12, linewidth = 2)\n    i == 2 && hideydecorations!(ax; grid = false)\nend\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Public-sector management with 95% confidence intervals. The horizontal band is the US interval, so a country whose interval clears the band differs from the US with confidence.](index_files/figure-html/fig-public-ci-output-1.svg){#fig-public-ci}\n:::\n:::\n\n\n\n::: {#cell-vs-us .cell execution_count=1}\n``` {.julia .cell-code}\nverdicts = DataFrame(ind = String[], country = String[], verdict = String[])\nfor industry in (\"Hospitals\", \"Schools\")\n    sub = public_ci[public_ci.ind .== industry, :]\n    us = only(sub[sub.country .== \"US\", :])\n    for r in eachrow(sub[sub.country .!= \"US\", :])\n        v = r.upper < us.lower ? \"confidently worse\" :\n            r.lower > us.upper ? \"confidently better\" : \"not distinguishable\"\n        push!(verdicts, (industry, r.country, v))\n    end\nend\nverdicts\n```\n\n::: {#vs-us .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">ind</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">verdict</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: left;\">confidently worse</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: left;\">confidently worse</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: left;\">confidently worse</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: left;\">confidently worse</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: left;\">confidently worse</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">France</td><td style = \"text-align: left;\">confidently worse</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: left;\">confidently better</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: left;\">not distinguishable</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: left;\">not distinguishable</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: left;\">confidently worse</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Hospitals**: every other country's interval sits entirely below the US band, so all six are\nconfidently worse managed on this measure.\n\n**Schools**: the picture reverses. Of the four comparisons, only Germany is confidently worse;\nCanada and Sweden cannot be distinguished from the US despite both having *higher* point\nestimates, and the UK is confidently **better** at 2.96 against 2.73.\n\nCanada and Sweden are the instructive pair. Both look better than the US on the means — 2.78 and\n2.80 against 2.73 — and neither difference survives its confidence interval. Reading the ranking\noff the point estimates alone would assert something the data does not support.\n\nSample sizes are much smaller in the public files — 43 Swedish hospitals, 89 Swedish schools\nagainst 1,225 US manufacturers — so intervals are wide and fewer comparisons resolve. Same\nmeasure, same method: how much confidence a country ranking can carry depends on how many\norganisations were surveyed.\n\n## Q3. What determines the interval's width {#p2-q3}\n\n::: {#cell-width-drivers .cell execution_count=1}\n``` {.julia .cell-code}\ndrivers = combine(groupby(manufacturing, :country),\n    :management => (x -> length(collect(skipmissing(x)))) => :n,\n    :management => (x -> std(skipmissing(x))) => :sd)\ndrivers.half_width = 1.96 .* drivers.sd ./ sqrt.(drivers.n)\nsort!(drivers, :half_width, rev = true)\n\nselect(transform(drivers, [:sd, :half_width] .=> ByRow(x -> round(x, digits = 4));\n                 renamecols = false), :country, :n, :sd, :half_width)\n```\n\n::: {#width-drivers .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>20×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">half_width</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"InlineStrings.String31\" style = \"text-align: left;\">String31</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Republic of Ireland</td><td style = \"text-align: right;\">106</td><td style = \"text-align: right;\">0.8011</td><td style = \"text-align: right;\">0.1525</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">New Zealand</td><td style = \"text-align: right;\">106</td><td style = \"text-align: right;\">0.5418</td><td style = \"text-align: right;\">0.1032</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Greece</td><td style = \"text-align: right;\">251</td><td style = \"text-align: right;\">0.8084</td><td style = \"text-align: right;\">0.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Mexico</td><td style = \"text-align: right;\">189</td><td style = \"text-align: right;\">0.6994</td><td style = \"text-align: right;\">0.0997</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Japan</td><td style = \"text-align: right;\">176</td><td style = \"text-align: right;\">0.6149</td><td style = \"text-align: right;\">0.0909</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Argentina</td><td style = \"text-align: right;\">249</td><td style = \"text-align: right;\">0.7141</td><td style = \"text-align: right;\">0.0887</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Portugal</td><td style = \"text-align: right;\">247</td><td style = \"text-align: right;\">0.6262</td><td style = \"text-align: right;\">0.0781</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">289</td><td style = \"text-align: right;\">0.6139</td><td style = \"text-align: right;\">0.0708</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Poland</td><td style = \"text-align: right;\">351</td><td style = \"text-align: right;\">0.6414</td><td style = \"text-align: right;\">0.0671</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Chile</td><td style = \"text-align: right;\">317</td><td style = \"text-align: right;\">0.5988</td><td style = \"text-align: right;\">0.0659</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Canada</td><td style = \"text-align: right;\">385</td><td style = \"text-align: right;\">0.6153</td><td style = \"text-align: right;\">0.0615</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Australia</td><td style = \"text-align: right;\">392</td><td style = \"text-align: right;\">0.5773</td><td style = \"text-align: right;\">0.0571</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">569</td><td style = \"text-align: right;\">0.6848</td><td style = \"text-align: right;\">0.0563</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">388</td><td style = \"text-align: right;\">0.5453</td><td style = \"text-align: right;\">0.0543</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">613</td><td style = \"text-align: right;\">0.6505</td><td style = \"text-align: right;\">0.0515</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">720</td><td style = \"text-align: right;\">0.6797</td><td style = \"text-align: right;\">0.0496</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">646</td><td style = \"text-align: right;\">0.5694</td><td style = \"text-align: right;\">0.0439</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">UK</td><td style = \"text-align: right;\">1242</td><td style = \"text-align: right;\">0.6788</td><td style = \"text-align: right;\">0.0378</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1225</td><td style = \"text-align: right;\">0.6428</td><td style = \"text-align: right;\">0.036</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">746</td><td style = \"text-align: right;\">0.4715</td><td style = \"text-align: right;\">0.0338</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-width .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 520))\nax = Axis(fig[1, 1];\n          title = \"Width falls with the square root of sample size\",\n          xlabel = \"Firms surveyed (log scale)\",\n          ylabel = \"95% CI half-width (log scale)\",\n          xscale = log10, yscale = log10)\nscatter!(ax, drivers.n, drivers.half_width; color = series_color(1))\nfor name in (\"New Zealand\", \"United States\", \"UK\", \"Greece\")\n    idx = findfirst(==(name), drivers.country)\n    idx === nothing && continue\n    text!(ax, drivers.n[idx], drivers.half_width[idx]; text = name, fontsize = 11,\n          color = MUTED, align = (:left, :center), offset = (7, 0))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Confidence interval half-width against sample size, log scale on both axes. The relationship is the square-root law: quadrupling the sample halves the interval.](index_files/figure-html/fig-width-output-1.svg){#fig-width}\n:::\n:::\n\n\n\nThe half-width is $1.96 \\, s / \\sqrt{n}$, so it rises with the standard deviation and falls with\nthe square root of the sample size. Both show up in the table:\n\n- **Greece** has the widest interval despite a mid-sized sample, because its standard deviation\n  is the largest at 0.81 — its firms genuinely differ more from each other.\n- **New Zealand** has a wide interval for the opposite reason: 106 firms, though its spread is the\n  second *smallest*.\n- **The UK and US** have the narrowest intervals, on more than 1,200 firms each.\n\nThe square-root relationship is why precision gets expensive. Halving an interval requires\n**four times** the sample. Going from New Zealand's 106 firms to the UK's 1,242 — nearly twelve\ntimes as many — narrows the interval by only a factor of about three.\n\n# Part 6.3 — What management varies with {#part-6.3}\n\n## Q1. Ownership and industry in the public sector {#p3-q1}\n\n::: {#cell-public-ownership .cell execution_count=1}\n``` {.julia .cell-code}\npub_own = DataFrame(ind = String[], ownership = String[], n = Int[],\n                    mean = Float64[], half_width = Float64[])\nfor industry in (\"Hospitals\", \"Schools\"), own in sort(unique(public_sector.ownership))\n    sub = public_sector[(public_sector.ind .== industry) .&\n                        (public_sector.ownership .== own) .&\n                        .!ismissing.(public_sector.management), :]\n    nrow(sub) < 10 && continue\n    r = mean_ci(sub.management)\n    push!(pub_own, (industry, own, r.n, round(r.mean, digits = 3),\n                    round(r.half_width, digits = 3)))\nend\npub_own\n```\n\n::: {#public-ownership .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">ind</th><th style = \"text-align: left;\">ownership</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">half_width</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Private</td><td style = \"text-align: right;\">355</td><td style = \"text-align: right;\">2.94</td><td style = \"text-align: right;\">0.055</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Hospitals</td><td style = \"text-align: left;\">Public</td><td style = \"text-align: right;\">828</td><td style = \"text-align: right;\">2.591</td><td style = \"text-align: right;\">0.033</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Private</td><td style = \"text-align: right;\">145</td><td style = \"text-align: right;\">2.763</td><td style = \"text-align: right;\">0.084</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Schools</td><td style = \"text-align: left;\">Public</td><td style = \"text-align: right;\">632</td><td style = \"text-align: right;\">2.737</td><td style = \"text-align: right;\">0.033</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-public-ownership .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (860, 460))\nfor (i, industry) in enumerate((\"Hospitals\", \"Schools\"))\n    sub = pub_own[pub_own.ind .== industry, :]\n    ax = Axis(fig[1, i]; title = industry,\n              ylabel = i == 1 ? \"Mean management score\" : \"\",\n              xticks = (1:nrow(sub), sub.ownership),\n              limits = (nothing, (2.0, 3.4)))\n    barplot!(ax, 1:nrow(sub), sub.mean; width = 0.45, color = series_color(1))\n    errorbars!(ax, 1:nrow(sub), sub.mean, sub.half_width;\n               color = INK, whiskerwidth = 12, linewidth = 2)\n    i == 2 && hideydecorations!(ax; grid = false)\nend\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Public-sector management by ownership type, with 95% intervals. Groups with fewer than 10 organisations are omitted rather than plotted as a point with an interval wider than the axis.](index_files/figure-html/fig-public-ownership-output-1.svg){#fig-public-ownership}\n:::\n:::\n\n\n\nPrivate organisations score higher than public ones in both sectors, and the intervals separate in\nhospitals. The gap is not evidence that private ownership causes better management — Q3 is about\nexactly that problem — but it is a real difference in the practices the rubric measures.\n\n## Q2. Firm size and ownership in manufacturing {#p3-q2}\n\n::: {#cell-size-split .cell execution_count=1}\n``` {.julia .cell-code}\n# `lemp_firm` is log employment, so the median in levels is exp of the median.\nmedian_log_employment = median(skipmissing(manufacturing.lemp_firm))\nmedian_employees = round(exp(median_log_employment), digits = 0)\n\nwork = dropmissing(manufacturing[:, [:management, :lemp_firm, :ownership, :country]])\nwork.size_group = ifelse.(work.lemp_firm .<= median_log_employment,\n                          \"Smaller (<= $(Int(median_employees)))\",\n                          \"Larger (> $(Int(median_employees)))\")\n\n(median_log_employment = round(median_log_employment, digits = 3),\n median_employees = median_employees,\n smaller = sum(work.size_group .!= \"Larger (> $(Int(median_employees)))\"),\n larger = sum(work.size_group .== \"Larger (> $(Int(median_employees)))\"))\n```\n\n::: {#size-split .cell-output .cell-output-display execution_count=1}\n```\n(median_log_employment = 5.799, median_employees = 330.0, smaller = 4309, larger = 4231)\n```\n:::\n:::\n\n\n\nThe median firm has **330 employees**, matching the threshold the book uses.\n\n::: {#cell-ownership-size .cell execution_count=1}\n``` {.julia .cell-code}\nconst OWNERSHIP_4 = [\"Dispersed Shareholders\", \"Private Individuals\",\n                     \"Founder\", \"Family owned, family CEO\"]\n\nown_size = DataFrame(ownership = String[], size_group = String[], n = Int[],\n                     mean = Float64[], half_width = Float64[])\nfor own in OWNERSHIP_4, grp in unique(work.size_group)\n    sub = work[(work.ownership .== own) .& (work.size_group .== grp), :]\n    nrow(sub) < 10 && continue\n    r = mean_ci(sub.management)\n    push!(own_size, (own, grp, r.n, round(r.mean, digits = 3), round(r.half_width, digits = 3)))\nend\nown_size\n```\n\n::: {#ownership-size .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">ownership</th><th style = \"text-align: left;\">size_group</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">half_width</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Dispersed Shareholders</td><td style = \"text-align: left;\">Larger (&gt; 330)</td><td style = \"text-align: right;\">1511</td><td style = \"text-align: right;\">3.306</td><td style = \"text-align: right;\">0.031</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Dispersed Shareholders</td><td style = \"text-align: left;\">Smaller (&lt;= 330)</td><td style = \"text-align: right;\">1049</td><td style = \"text-align: right;\">3.143</td><td style = \"text-align: right;\">0.038</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Private Individuals</td><td style = \"text-align: left;\">Larger (&gt; 330)</td><td style = \"text-align: right;\">662</td><td style = \"text-align: right;\">3.071</td><td style = \"text-align: right;\">0.047</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Private Individuals</td><td style = \"text-align: left;\">Smaller (&lt;= 330)</td><td style = \"text-align: right;\">807</td><td style = \"text-align: right;\">2.844</td><td style = \"text-align: right;\">0.043</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Founder</td><td style = \"text-align: left;\">Larger (&gt; 330)</td><td style = \"text-align: right;\">558</td><td style = \"text-align: right;\">2.755</td><td style = \"text-align: right;\">0.051</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Founder</td><td style = \"text-align: left;\">Smaller (&lt;= 330)</td><td style = \"text-align: right;\">821</td><td style = \"text-align: right;\">2.568</td><td style = \"text-align: right;\">0.042</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Family owned, family CEO</td><td style = \"text-align: left;\">Larger (&gt; 330)</td><td style = \"text-align: right;\">506</td><td style = \"text-align: right;\">2.911</td><td style = \"text-align: right;\">0.056</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Family owned, family CEO</td><td style = \"text-align: left;\">Smaller (&lt;= 330)</td><td style = \"text-align: right;\">834</td><td style = \"text-align: right;\">2.678</td><td style = \"text-align: right;\">0.043</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-ownership-size .cell execution_count=1}\n``` {.julia .cell-code}\nlarger_label = \"Larger (> $(Int(median_employees)))\"\ngroups = [larger_label, \"Smaller (<= $(Int(median_employees)))\"]\n\nfig = Figure(size = (960, 460))\nLabel(fig[0, 1:4], \"Larger firms score higher under every ownership type\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nfor (i, own) in enumerate(OWNERSHIP_4)\n    sub = own_size[own_size.ownership .== own, :]\n    ax = Axis(fig[1, i]; title = replace(own, \", \" => \",\\n\"),\n              ylabel = i == 1 ? \"Mean management score\" : \"\",\n              xticks = (1:2, [\"Larger\", \"Smaller\"]),\n              limits = (nothing, (2.0, 3.8)))\n    for (j, grp) in enumerate(groups)\n        row = sub[sub.size_group .== grp, :]\n        isempty(row) && continue\n        barplot!(ax, [j], row.mean; width = 0.45, color = series_color(j),\n                 label = j == 1 ? \"Larger\" : \"Smaller\")\n        errorbars!(ax, [j], row.mean, row.half_width;\n                   color = INK, whiskerwidth = 10, linewidth = 2)\n    end\n    i > 1 && hideydecorations!(ax; grid = false)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Management score by ownership type and firm size, with 95% intervals. Faceting by ownership keeps size on two colours; the four ownership categories would need four hues on one axis.](index_files/figure-html/fig-ownership-size-output-1.svg){#fig-ownership-size}\n:::\n:::\n\n\n\nTwo patterns, both consistent across ownership types:\n\n- **Larger firms score higher**, in every category, and the intervals separate in most.\n- **Ownership matters and the ordering is stable.** Firms with dispersed shareholders score\n  highest; founder-run and family-owned-with-a-family-CEO firms score lowest. The book's numbers\n  for Brazil and the US show the same ranking within each country.\n\nThe family-CEO result is the one the paper emphasises: firms that pass management to a family\nmember score materially worse than those recruiting externally, and the gap persists after\ncontrolling for size and country.\n\n## Q3. Which way does the causation run? {#p3-q3}\n\nEvery relationship in Q1 and Q2 is a correlation. For each, the reverse story is also plausible.\n\n**Manager education.** The obvious reading is that better-educated managers run firms better.\nReversed: well-managed firms are more profitable, can pay more, and so attract managers with\nbetter credentials — the education follows the management quality. There is also a common cause:\nfirms in richer regions face both a better-educated labour pool and stronger product-market\ncompetition. Plausible mechanisms in both directions, and the data cannot separate them.\n\n**Number of competitors.** Forward: competition kills badly managed firms and forces survivors to\nimprove. Reversed: well-managed firms are more productive, cut prices, and *drive competitors out*\n— so good management reduces the competitor count, giving a negative relationship from the\nopposite direction. Worse, the measure is self-reported: managers who monitor their market\ncarefully may simply be more aware of competitors, so the variable partly measures the management\npractice it is meant to explain.\n\n**Firm size.** Forward: large firms need formal monitoring and targets because informal oversight\ndoes not scale, and can spread the fixed cost of good management systems over more output.\nReversed: well-managed firms grow. This is the cleanest case for reverse causation of the three —\ngrowth is exactly what good management should produce, so a size–management correlation is close\nto what the hypothesis predicts either way.\n\n## Q4. The field experiment {#p3-q4}\n\nThe correlational evidence cannot settle this, which is why Bloom et al. ran a randomised\nexperiment on Indian textile firms.\n\n**The design.** Large multi-plant textile firms near Mumbai were randomly split. Treatment plants\nreceived five months of free management consulting implementing the practices the survey scores —\ninventory control, quality monitoring, preventive maintenance, production scheduling. Control\nplants received only a one-month diagnostic, so both groups were measured equally and only the\n*implementation* differed.\n\n**Why randomisation is the point.** It breaks every reverse-causal channel in Q3 at once. Treated\nplants were not chosen for being ambitious, well-run or fast-growing — a coin decided. Any\nsubsequent difference is caused by the consulting, because nothing else systematically\ndistinguished the groups beforehand. This is the same logic as Project 2's period 1 comparison and\nProject 3's parallel pre-trends, achieved by design rather than argued for after the fact.\n\n**The results.** Treated plants adopted a substantial share of the recommended practices, and\nproductivity rose roughly 17% within a year — from better quality, less downtime and lower\ninventory rather than from working harder. Firms also expanded, opening new plants faster than\ncontrols.\n\n**Reading Figure 12.** The productivity series for the two groups track each other before the\nintervention and separate after it, with the gap persisting rather than fading. The persistence\nmatters: a temporary Hawthorne-style response to being studied would decay, and this does not.\n\n**What it does not settle.** One industry, one region, large firms, and consulting that was free —\nthe firms did not choose to pay for it. If good management raises productivity 17%, the obvious\nquestion is why firms had not adopted it already. The paper's answer is that managers did not know\nthese practices existed or believed they were already following them, which is an argument about\ninformation rather than about incentives — and that answer is specific to this setting rather\nthan general.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading one file from a zip | Setup | `ZipFile.Reader`, `CSV.read(read(f), ...)` |\n| Dropping junk columns | Setup | `select` on a filtered name list |\n| Grouped means and counts | Q6.1 Q2 | `combine(groupby(df, :country), ...)` |\n| Frequency tables on fixed bins | Q6.1 Q3 | `freqtable_binned(x; breaks)` |\n| Reference distribution behind a facet | Q6.1 Q3 | two `barplot!` calls, grey then colour |\n| Box plots | Q6.1 Q4 | `boxplot!(ax, positions, values)` |\n| Confidence interval | Q6.2 Q1 | `1.96 * std(v) / sqrt(length(v))` |\n| Error bars | Q6.2 Q1 | `errorbars!(ax, x, y, half_width)` |\n| A reference interval as a band | Q6.2 Q2 | `hspan!(ax, lower, upper)` |\n| Median split on a log variable | Q6.3 Q2 | compare in logs, report `exp` of the median |\n| Log-log scatter | Q6.2 Q3 | `Axis(...; xscale = log10, yscale = log10)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}