{
  "hash": "c2e6035b91873fbc7199787f3f310db1",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"9. Credit-excluded households in a developing country\"\nsubtitle: \"Who cannot borrow, who does not bother asking, and why the second group is larger\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nThe Ethiopian Socioeconomic Survey, 2013–14: 5,262 households, of which 1,480 borrowed. The\nquestion is who is shut out of credit — and the survey is unusually good at separating the\nhousehold that *asked and was refused* from the household that *never asked because it expected\nrefusal*.\n\n- **[Part 9.1](#part-9.1)** — households that did not get a loan\n- **[Part 9.2](#part-9.2)** — households that got a loan\n\nNew concepts: **credit-excluded** and **credit-constrained** households, **discouraged\nborrowers**, indicator variables built from survey answers, and **selection bias**. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/09-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/09-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/09-04.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames\nusing Statistics\nusing CairoMakie\nusing Dates\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-ess .cell execution_count=1}\n``` {.julia .cell-code}\npath = rawpath(\"09\", \"ethiopia-credit-ess.xlsx\")\ndictionary = DataFrame(XLSX.readtable(path, \"Data dictionary\"))\nallHH = DataFrame(XLSX.readtable(path, \"All households\"; infer_eltypes = true))\ngotL = DataFrame(XLSX.readtable(path, \"Got loan\"; infer_eltypes = true))\n\n(all_households = size(allHH), got_loan = size(gotL))\n```\n\n::: {#read-ess .cell-output .cell-output-display execution_count=1}\n```\n(all_households = (5262, 19), got_loan = (1480, 21))\n```\n:::\n:::\n\n\n\nAfter Project 8 this file is a relief: missing values are empty cells, which XLSX.jl reads as\n`missing` directly, and nothing needs recoding from words to numbers. The dictionary covers the\nhousehold characteristics:\n\n::: {#cell-dictionary .cell execution_count=1}\n``` {.julia .cell-code}\ndictionary\n```\n\n::: {#dictionary .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>11×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Variable name</th><th style = \"text-align: left;\">Description</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">household_id2</td><td style = \"text-align: left;\">Unique household ID</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">got_loan</td><td style = \"text-align: left;\">Over the past 12 months, did anyone in this household borrow on credit from someone outside the household or from an institution for business or farming purposes, receiving either cash or inputs?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">rural</td><td style = \"text-align: left;\">Whether household lives in rural area, small town (urban), or large town (urban)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">hhsize</td><td style = \"text-align: left;\">Household size</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">region</td><td style = \"text-align: left;\">Region</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">gender</td><td style = \"text-align: left;\">Gender of household head</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">age</td><td style = \"text-align: left;\">Age of household head (years)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">young_children</td><td style = \"text-align: left;\">Number of young children in household (13 years of age or below)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">working_age_adults</td><td style = \"text-align: left;\">Number of working-age adults in household (aged between 14 to 54)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">max_education</td><td style = \"text-align: left;\">Highest education level attained by anyone in the household (number of years of schooling)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">number_assets</td><td style = \"text-align: left;\">Number of assets owned by household (the sum of all items in Section 10 of the questionnaire) </td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEleven variables described, but `allHH` has nineteen columns. **The credit variables are the ones\nnot documented** — `loan_rejected`, `rejection_source1` and `2`, `did_not_apply`,\n`reason_not_apply1` and `2`, `loan_purpose` and `loan_purpose_other`. Section 14 of the ESS\nhousehold questionnaire has the question wording, and Part 9.1 is largely about turning those\nanswers into indicators.\n\n::: {.callout-note}\n## `did_not_apply` is named for one answer and coded for the other\n\n::: {#cell-coding-check .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(variable = [\"did_not_apply\", \"loan_rejected\", \"rural\"],\n          values = [join(sort(unique(skipmissing(allHH[!, c]))), \" | \")\n                    for c in [\"did_not_apply\", \"loan_rejected\", \"rural\"]])\n```\n\n::: {#coding-check .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">values</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">did_not_apply</td><td style = \"text-align: left;\">Applied | Did not apply</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">loan_rejected</td><td style = \"text-align: left;\">No | Yes</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">rural</td><td style = \"text-align: left;\">Large town (urban) | Rural | Small town (urban)</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n`did_not_apply` takes the values `\"Applied\"` and `\"Did not apply\"`, so the *name* reads as a\nnegation while the *values* read as a statement. Writing `did_not_apply == \"Applied\"` looks like\na mistake and is correct; writing `did_not_apply == true` would be a mistake and looks fine.\nEvery filter below spells out the string.\n:::\n\n# Part 9.1 — Households that did not get a loan {#part-9.1}\n\n## Q1. Where these households are, and who they are {#p1-q1}\n\n**(a) Region by area type.** Each row is a region and the first three columns are that region's\nsplit between large towns, small towns and rural areas, so they sum across to 1. The last column\nis the region's share of the whole sample.\n\n::: {#tbl-region .cell tbl-cap='Area type within each region, and each region\\'s share of the sample. Reproduces the book\\'s Solution figure 9.1.' execution_count=1}\n``` {.julia .cell-code}\nconst AREAS = [\"Rural\", \"Small town (urban)\", \"Large town (urban)\"]\n\nregion_table = DataFrame(region = String[], rural = Float64[], small_town = Float64[],\n                         large_town = Float64[], share_of_sample = Float64[])\nfor r in sort(unique(skipmissing(allHH.region)))\n    rows = allHH[coalesce.(allHH.region .== r, false), :]\n    push!(region_table, (r, [round(count(==(a), skipmissing(rows.rural)) / nrow(rows),\n                                   digits = 2) for a in AREAS]...,\n                         round(nrow(rows) / nrow(allHH), digits = 2)))\nend\nshow_all(region_table)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>11×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">region</th><th style = \"text-align: left;\">rural</th><th style = \"text-align: left;\">small_town</th><th style = \"text-align: left;\">large_town</th><th style = \"text-align: left;\">share_of_sample</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Addis Ababa</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">0.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Afar</td><td style = \"text-align: right;\">0.76</td><td style = \"text-align: right;\">0.15</td><td style = \"text-align: right;\">0.1</td><td style = \"text-align: right;\">0.03</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Amhara</td><td style = \"text-align: right;\">0.67</td><td style = \"text-align: right;\">0.11</td><td style = \"text-align: right;\">0.22</td><td style = \"text-align: right;\">0.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Benshagul Gumuz</td><td style = \"text-align: right;\">0.9</td><td style = \"text-align: right;\">0.1</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Diredwa</td><td style = \"text-align: right;\">0.53</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.47</td><td style = \"text-align: right;\">0.04</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Gambelia</td><td style = \"text-align: right;\">0.8</td><td style = \"text-align: right;\">0.08</td><td style = \"text-align: right;\">0.12</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Harari</td><td style = \"text-align: right;\">0.73</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.27</td><td style = \"text-align: right;\">0.03</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Oromia</td><td style = \"text-align: right;\">0.61</td><td style = \"text-align: right;\">0.11</td><td style = \"text-align: right;\">0.28</td><td style = \"text-align: right;\">0.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">SNNP</td><td style = \"text-align: right;\">0.73</td><td style = \"text-align: right;\">0.09</td><td style = \"text-align: right;\">0.18</td><td style = \"text-align: right;\">0.23</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Somalie</td><td style = \"text-align: right;\">0.76</td><td style = \"text-align: right;\">0.09</td><td style = \"text-align: right;\">0.16</td><td style = \"text-align: right;\">0.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Tigray</td><td style = \"text-align: right;\">0.56</td><td style = \"text-align: right;\">0.07</td><td style = \"text-align: right;\">0.37</td><td style = \"text-align: right;\">0.12</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll eleven regions reproduce the published table. **63% of the sample is rural**, and the\nregional variation is the thing to notice: Addis Ababa is 100% large-town by construction, while\nBenshagul Gumuz is 90% rural. Three regions — Amhara, Oromia and SNNP — hold **63% of all\nhouseholds** between them.\n\n**(b) Female household heads.**\n\n::: {#cell-female-heads .cell execution_count=1}\n``` {.julia .cell-code}\nfemale = count(==(\"Female\"), skipmissing(allHH.gender))\n(female_heads = female,\n gender_recorded = count(!ismissing, allHH.gender),\n pct_of_all = round(100 * female / nrow(allHH), digits = 2),\n pct_of_recorded = round(100 * female / count(!ismissing, allHH.gender), digits = 2))\n```\n\n::: {#female-heads .cell-output .cell-output-display execution_count=1}\n```\n(female_heads = 1599, gender_recorded = 5261, pct_of_all = 30.39, pct_of_recorded = 30.39)\n```\n:::\n:::\n\n\n\n**30.39%**, against the book's 30.40%. One household has no gender recorded, and neither\ndenominator gives 30.40 — the last digit is a rounding difference in the published figure, not a\ndifferent sample.\n\n**(c) The household characteristics.**\n\n::: {#tbl-summary .cell tbl-cap='Household demographics, all 5,262 households. Reproduces the book\\'s Solution figure 9.2.' execution_count=1}\n``` {.julia .cell-code}\nallHH.female = [g === missing ? missing : Float64(g == \"Female\") for g in allHH.gender]\n\nconst CHARS = [\"hhsize\" => \"Household size\", \"female\" => \"Gender (1 = female head)\",\n               \"age\" => \"Age of household head\", \"young_children\" => \"Young children\",\n               \"working_age_adults\" => \"Working-age adults\",\n               \"max_education\" => \"Max education (years)\",\n               \"number_assets\" => \"Number of assets\"]\n\nsummary_table = DataFrame(variable = String[], mean = Float64[], sd = Float64[],\n                          min = Float64[], max = Float64[], n = Int[])\nfor (col, label) in CHARS\n    x = Float64.(collect(skipmissing(allHH[!, col])))\n    push!(summary_table, (label, round(mean(x), digits = 2), round(std(x), digits = 2),\n                          minimum(x), maximum(x), length(x)))\nend\nsummary_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>7×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">n</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Household size</td><td style = \"text-align: right;\">4.58</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">16.0</td><td style = \"text-align: right;\">5260</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Gender (1 = female head)</td><td style = \"text-align: right;\">0.3</td><td style = \"text-align: right;\">0.46</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5261</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Age of household head</td><td style = \"text-align: right;\">44.18</td><td style = \"text-align: right;\">15.61</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">99.0</td><td style = \"text-align: right;\">5253</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Young children</td><td style = \"text-align: right;\">1.89</td><td style = \"text-align: right;\">1.71</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: right;\">5262</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Working-age adults</td><td style = \"text-align: right;\">2.58</td><td style = \"text-align: right;\">1.52</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: right;\">5262</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Max education (years)</td><td style = \"text-align: right;\">7.53</td><td style = \"text-align: right;\">7.28</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">30.0</td><td style = \"text-align: right;\">5262</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Number of assets</td><td style = \"text-align: right;\">14.9</td><td style = \"text-align: right;\">17.23</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">203.0</td><td style = \"text-align: right;\">5262</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery mean and standard deviation matches the published table.\n\n**(d) What the tables say.** The typical household is **4.58 people** — call it five — with one\nor two young children and two or three working-age adults. Its head is **44** and its most\neducated member has **7.5 years** of schooling, which is primary plus a little. It owns about\n**15 assets**.\n\nThe spreads matter more than the averages, because they are what the credit analysis will be\nabout:\n\n- **Assets: mean 14.9, SD 17.2, max 203.** The standard deviation exceeds the mean, so the\n  distribution is strongly right-skewed and the mean is not the typical household. This is the\n  variable most likely to serve as collateral, and it is the least evenly held.\n- **Education: mean 7.5, SD 7.3, min 0.** Again SD ≈ mean. A substantial share of households have\n  *nobody* with any schooling, while the maximum is 30 years.\n- **Age min 3.** A three-year-old household head is not a household head. It is either a coding\n  error or a household recorded by a child's age after some other loss; either way it is a\n  reminder that survey extremes deserve a look before they enter a regression.\n\n## Q2. Applications and rejections {#p1-q2}\n\n**(a) The cross-tabulation**, with missing values kept as their own row and column, because the\npoint of the table is to find the responses that should not exist.\n\n::: {#tbl-crosstab .cell tbl-cap='Loan applications against rejections, all responses including blanks. Reproduces the book\\'s Solution figure 9.3.' execution_count=1}\n``` {.julia .cell-code}\nlabel(v) = v === missing ? \"Blank\" : string(v)\nconst APPLY = [\"Applied\", \"Did not apply\", \"Blank\"]\nconst REJECT = [\"No\", \"Yes\", \"Blank\"]\n\ncrosstab = DataFrame(application = String[], not_rejected = Int[], rejected = Int[],\n                     blank = Int[], total = Int[])\nfor a in APPLY\n    counts = [count(i -> label(allHH.did_not_apply[i]) == a &&\n                         label(allHH.loan_rejected[i]) == b, 1:nrow(allHH)) for b in REJECT]\n    push!(crosstab, (a, counts..., sum(counts)))\nend\npush!(crosstab, (\"Total\", [sum(crosstab[!, c]) for c in\n                           [:not_rejected, :rejected, :blank]]..., nrow(allHH)))\ncrosstab\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">application</th><th style = \"text-align: left;\">not_rejected</th><th style = \"text-align: left;\">rejected</th><th style = \"text-align: left;\">blank</th><th style = \"text-align: left;\">total</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Applied</td><td style = \"text-align: right;\">1363</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">1565</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Did not apply</td><td style = \"text-align: right;\">3632</td><td style = \"text-align: right;\">24</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">3658</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Blank</td><td style = \"text-align: right;\">37</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">39</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Total</td><td style = \"text-align: right;\">5032</td><td style = \"text-align: right;\">227</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">5262</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**(b) Which responses cannot be true.** Two cells are contradictory, because both questions cover\nthe same twelve months:\n\n- **24 households say they did not apply and were also rejected.** A loan cannot be refused if it\n  was never requested.\n- **2 households give no answer on applying but report a rejection.**\n\nDropping those, plus the 39 blank-application and 3 blank-rejection rows, leaves the three cells\nthe book keeps:\n\n::: {#cell-usable .cell execution_count=1}\n``` {.julia .cell-code}\nsane = allHH[.!ismissing.(allHH.did_not_apply) .& .!ismissing.(allHH.loan_rejected) .&\n             .!((allHH.did_not_apply .== \"Did not apply\") .&\n                (allHH.loan_rejected .== \"Yes\")), :]\n\nsane.HH_status = [r.did_not_apply == \"Applied\" ?\n                  (r.loan_rejected == \"No\" ? \"successful\" : \"denied\") : \"did not apply\"\n                  for r in eachrow(sane)]\n\napplicants = sane[sane.did_not_apply .== \"Applied\", :]\n(usable = nrow(sane),\n dropped = nrow(allHH) - nrow(sane),\n applied = nrow(applicants),\n pct_applied = round(100 * nrow(applicants) / nrow(sane), digits = 2),\n pct_successful_of_applicants =\n     round(100 * count(==(\"successful\"), applicants.HH_status) / nrow(applicants), digits = 2))\n```\n\n::: {#usable .cell-output .cell-output-display execution_count=1}\n```\n(usable = 5196, dropped = 66, applied = 1564, pct_applied = 30.1, pct_successful_of_applicants = 87.15)\n```\n:::\n:::\n\n\n\n**5,196 households remain and 30.10% of them applied** — both match the book.\n\n::: {.callout-warning}\n## The published success rate uses the wrong denominator\n\nThe question asks: of the households that applied, what percentage were successful? The\nSolutions page answers **96.13%**. The data says **87.15%**.\n\nWhere 96.13 comes from:\n\n::: {#cell-denominator .cell execution_count=1}\n``` {.julia .cell-code}\nrejected = count(==(\"denied\"), sane.HH_status)\nsuccessful = count(==(\"successful\"), sane.HH_status)\n\nDataFrame(quantity = [\"successful ÷ applicants  (the question asked)\",\n                      \"100 − rejected ÷ all usable  (the published 96.13)\",\n                      \"rejected ÷ applicants\",\n                      \"rejected ÷ all usable\"],\n          value = round.([100 * successful / nrow(applicants),\n                          100 - 100 * rejected / nrow(sane),\n                          100 * rejected / nrow(applicants),\n                          100 * rejected / nrow(sane)], digits = 2))\n```\n\n::: {#denominator .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">quantity</th><th style = \"text-align: left;\">value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">successful ÷ applicants  (the question asked)</td><td style = \"text-align: right;\">87.15</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">100 − rejected ÷ all usable  (the published 96.13)</td><td style = \"text-align: right;\">96.13</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">rejected ÷ applicants</td><td style = \"text-align: right;\">12.85</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">rejected ÷ all usable</td><td style = \"text-align: right;\">3.87</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n96.13% is the rejected households as a share of **all 5,196**, subtracted from 100. It divides by\nthe whole sample where the question divides by applicants.\n\nThis is not a rounding difference. **12.85% of applicants were turned down, not 3.87%** — a\nrejection rate more than three times what the published figure implies, and the difference\nbetween \"credit is almost freely available to those who ask\" and \"one applicant in eight is\nrefused.\"\n\nThe book's very next sentence uses 3.87% correctly, as a share of all households. The two\ndenominators are crossed inside a single paragraph, which is what makes it easy to miss: both\nnumbers are individually right about something, and neither answers the question above it.\n:::\n\n**(c) Which category is which.** The three surviving cells map onto the concepts unevenly, and\nthe mapping is the substance of this Part.\n\n::: {#tbl-categories .cell tbl-cap='The three usable response patterns as shares of the 5,196 households.' execution_count=1}\n``` {.julia .cell-code}\nDataFrame(category = [\"Applied, got a loan\", \"Applied, refused\", \"Did not apply\"],\n          n = [successful, rejected, count(==(\"did not apply\"), sane.HH_status)],\n          pct = round.(100 .* [successful, rejected,\n                               count(==(\"did not apply\"), sane.HH_status)] ./ nrow(sane),\n                       digits = 2))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">category</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Applied, got a loan</td><td style = \"text-align: right;\">1363</td><td style = \"text-align: right;\">26.23</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Applied, refused</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">3.87</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Did not apply</td><td style = \"text-align: right;\">3632</td><td style = \"text-align: right;\">69.9</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n- **Applied and refused (3.87%) is credit excluded.** These households wanted to borrow at the\n  going terms and could not, which is the definition.\n- **Applied and got a loan (26.23%) is not credit excluded, but may still be credit\n  constrained.** Receiving a loan says nothing about the terms. A household that borrowed at\n  200% interest from a moneylender got credit and was still constrained by it — and\n  [Part 9.2](#part-9.2) shows such loans exist in this data.\n- **Did not apply (69.90%) is unclassifiable from this table alone**, and it is by far the\n  largest group. It contains households with no need to borrow, households that expected refusal,\n  and households deterred by the terms. Separating them needs the *reasons*, which is Q3.\n\nThat ordering is the point of the Part. The group the two questions can classify cleanly is the\nsmallest one, and the group that matters most for measuring exclusion is the one the questions\ncannot classify at all.\n\n## Q3. Discouraged borrowers and credit-constrained households {#p1-q3}\n\nTwo indicators built from the two free-response reason fields.\n\n::: {#cell-indicators .cell execution_count=1}\n``` {.julia .cell-code}\nreasons(r) = [x for x in (r.reason_not_apply1, r.reason_not_apply2) if x !== missing]\n\n# Discouraged: expected refusal, so never asked.\nsane.discouraged = [Int(\"Believe Would Be Refused\" in reasons(r)) for r in eachrow(sane)]\n\n# Constrained: gave any reason other than no-need or unclassifiable.\nconst NOT_CONSTRAINED = [\"Other (Specify)\", \"Have Adequate Farm\"]\nsane.credit_constrained = [Int(any(!in(x, NOT_CONSTRAINED) for x in reasons(r)))\n                           for r in eachrow(sane)]\n\nDataFrame(indicator = [\"Discouraged borrowers\", \"Credit constrained\"],\n          n = [sum(sane.discouraged), sum(sane.credit_constrained)],\n          pct = round.(100 .* [mean(sane.discouraged), mean(sane.credit_constrained)],\n                       digits = 2))\n```\n\n::: {#indicators .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Discouraged borrowers</td><td style = \"text-align: right;\">588</td><td style = \"text-align: right;\">11.32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Credit constrained</td><td style = \"text-align: right;\">3012</td><td style = \"text-align: right;\">57.97</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**588 discouraged (11.32%)** and **3,012 credit constrained (57.97%)**, both matching the book.\n\nPut those beside Q2: **the credit-excluded group the survey can identify directly is 3.87% of\nhouseholds, while the credit-constrained group is 57.97%** — fifteen times larger. Measuring\nexclusion by rejections alone would miss almost all of it.\n\nBoth definitions are choices, and the book says so about the first. Two things worth being\nexplicit about:\n\n- **\"Discouraged\" here means only `\"Believe Would Be Refused\"`.** A household answering\n  `\"Inadequate Collateral\"` or `\"Too Expensive\"` is arguably also discouraged — it has assessed\n  the terms and concluded there is no point. The narrow definition makes 11.32% a **lower bound**.\n- **\"Constrained\" is broad by comparison**, excluding only `\"Have Adequate Farm\"` (no need) and\n  `\"Other (Specify)\"` (unclassifiable). It therefore counts `\"Do Not Like To Be In Debt\"` as a\n  constraint, which is a preference rather than a constraint. That makes 57.97% an **upper\n  bound**, and the largest single reason falls in exactly this contested category.\n\nThe two indicators bracket the truth rather than measuring it, and Q4's reason tables show why\nthe bracket is wide.\n\n## Q4. Why households did not apply {#p1-q4}\n\n::: {#tbl-reasons .cell tbl-cap='Reasons for not applying for a loan, as proportions of the households giving each answer. Reproduces the book\\'s Solution figures 9.4 and 9.5.' execution_count=1}\n``` {.julia .cell-code}\nfunction reason_shares(col)\n    vals = collect(skipmissing(sane[!, col]))\n    Dict(r => count(==(r), vals) / length(vals) for r in unique(vals)), length(vals)\nend\n\nfirst_shares, n_first = reason_shares(\"reason_not_apply1\")\nsecond_shares, n_second = reason_shares(\"reason_not_apply2\")\n\nreason_table = DataFrame(reason = collect(keys(first_shares)),\n                         most_important = round.(collect(values(first_shares)), digits = 2))\nreason_table.second_most = [round(get(second_shares, r, 0.0), digits = 2)\n                            for r in reason_table.reason]\nsort!(reason_table, :most_important, rev = true)\n(n_giving_a_first_reason = n_first, n_giving_a_second_reason = n_second)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(n_giving_a_first_reason = 3566, n_giving_a_second_reason = 1995)\n```\n:::\n:::\n\n\n\n::: {#cell-reason-table-show .cell execution_count=1}\n``` {.julia .cell-code}\nreason_table\n```\n\n::: {#reason-table-show .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">reason</th><th style = \"text-align: left;\">most_important</th><th style = \"text-align: left;\">second_most</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Do Not Like To Be In Debt</td><td style = \"text-align: right;\">0.19</td><td style = \"text-align: right;\">0.24</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Have Adequate Farm</td><td style = \"text-align: right;\">0.19</td><td style = \"text-align: right;\">0.05</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Fear Not Be Able To Pay</td><td style = \"text-align: right;\">0.17</td><td style = \"text-align: right;\">0.28</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Believe Would Be Refused</td><td style = \"text-align: right;\">0.12</td><td style = \"text-align: right;\">0.09</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">No Farm or Business</td><td style = \"text-align: right;\">0.1</td><td style = \"text-align: right;\">0.04</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Do Not Know Any Lender</td><td style = \"text-align: right;\">0.07</td><td style = \"text-align: right;\">0.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Inadequate Collateral</td><td style = \"text-align: right;\">0.05</td><td style = \"text-align: right;\">0.09</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Too Expensive</td><td style = \"text-align: right;\">0.05</td><td style = \"text-align: right;\">0.07</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Other (Specify)</td><td style = \"text-align: right;\">0.04</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Too Much Trouble</td><td style = \"text-align: right;\">0.03</td><td style = \"text-align: right;\">0.06</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nBoth columns reproduce the published tables. Note the denominators: **3,566 households gave a\nfirst reason but only 1,995 gave a second**, so the two columns are shares of different groups\nand are not directly comparable as a pair.\n\n::: {#cell-fig-reasons .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 520))\nax = Axis(fig[1, 1];\n          title = \"Debt aversion and fear of non-payment dominate both rankings\",\n          xlabel = \"Share of households giving a reason at that rank\",\n          yticks = (1:nrow(reason_table), reverse(reason_table.reason)),\n          limits = ((0, 0.32), nothing))\n\npositions = collect(nrow(reason_table):-1:1)\nfor (j, (col, lab)) in enumerate([(:most_important, \"Most important reason\"),\n                                  (:second_most, \"Second most important\")])\n    barplot!(ax, positions .+ (j == 1 ? 0.19 : -0.19), reason_table[!, col];\n             direction = :x, width = 0.34, color = series_color(j), label = lab)\nend\nLegend(fig[0, 1], ax; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Reasons for not applying for a loan. Two series, so the reason's rank carries the colour; shares are of the households giving a reason at that rank, which is why the columns do not sum across. Bars are dodged with a surface gap rather than stacked, because these are shares of two different denominators and a stack would imply a total.](index_files/figure-html/fig-reasons-output-1.svg){#fig-reasons}\n:::\n:::\n\n\n\n**The most common answers are not about supply.** `\"Do Not Like To Be In Debt\"` is the joint\nlargest first reason at 0.19 and the second largest second reason at 0.24. `\"Have Adequate Farm\"`\nties it at 0.19 among first reasons — a household saying it does not need a loan.\n\nBetween them, those two answers account for roughly **38% of first reasons**, and they mean\nopposite things for this project: one is a preference, the other is an absence of demand. Neither\nis a credit market failing to serve a household that wants credit.\n\nThe reasons that *do* indicate a constraint are, taken together, comparable in size.\n`\"Fear Not Be Able To Pay\"` (0.17 first, 0.28 second — the largest second reason),\n`\"Believe Would Be Refused\"` (0.12), `\"Too Expensive\"` (0.05), `\"Inadequate Collateral\"` (0.05)\nand `\"Do Not Know Any Lender\"` (0.07) describe households that assessed their prospects and\nstopped.\n\n`\"Do Not Know Any Lender\"` at 0.07 is worth singling out. It is not a price or a collateral\nproblem; it is an **information** problem, and it implies a different remedy from the others.\n\nThis is the evidence that Q3's 57.97% is an upper bound. Most of the gap between 11.32% and\n57.97% is `\"Do Not Like To Be In Debt\"` and `\"Fear Not Be Able To Pay\"` — the first a preference,\nthe second ambiguous between a constraint and a realistic assessment of one's own income risk.\n\n## Q5. Successful against denied borrowers {#p1-q5}\n\n**Loan purpose first.** The book flags a data problem here: in `allHH` the purpose recorded for\nevery *successful* household is `\"Other\"`, so the successful column has to come from the\n`gotL` sheet instead.\n\n::: {#tbl-purpose .cell tbl-cap='Loan purpose for successful and denied applicants, as proportions. Successful purposes come from the \"Got loan\" sheet; denied from \"All households\". Reproduces the book\\'s Solution figure 9.6.' execution_count=1}\n``` {.julia .cell-code}\ndenied_rows = sane[sane.HH_status .== \"denied\", :]\n\nfunction purpose_shares(vals)\n    v = collect(skipmissing(vals))\n    Dict(string(p) => count(==(p), v) / length(v) for p in unique(v)), length(v)\nend\nsucc_shares, n_succ = purpose_shares(gotL.loan_purpose)\nden_shares, n_den = purpose_shares(denied_rows.loan_purpose)\n\n# `union` of two key sets is a Set, which has no ordering — collect before sorting.\npurpose_table = DataFrame(purpose = sort(collect(union(keys(succ_shares),\n                                                       keys(den_shares)))))\npurpose_table.successful = [round(get(succ_shares, p, 0.0), digits = 3)\n                            for p in purpose_table.purpose]\npurpose_table.denied = [round(get(den_shares, p, 0.0), digits = 3)\n                        for p in purpose_table.purpose]\nsort!(purpose_table, :successful, rev = true)\n(successful_n = n_succ, denied_n = n_den, columns_sum =\n     round.([sum(purpose_table.successful), sum(purpose_table.denied)], digits = 3))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(successful_n = 1444, denied_n = 195, columns_sum = [1.001, 1.0])\n```\n:::\n:::\n\n\n\n::: {#cell-purpose-show .cell execution_count=1}\n``` {.julia .cell-code}\npurpose_table\n```\n\n::: {#purpose-show .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>9×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">purpose</th><th style = \"text-align: left;\">successful</th><th style = \"text-align: left;\">denied</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Purchase Agricultural Inputs for Food Crop</td><td style = \"text-align: right;\">0.3</td><td style = \"text-align: right;\">0.21</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">For consumption and personal expenses</td><td style = \"text-align: right;\">0.202</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Business Start-up Capital</td><td style = \"text-align: right;\">0.155</td><td style = \"text-align: right;\">0.262</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Purchase Non-farm Inputs</td><td style = \"text-align: right;\">0.114</td><td style = \"text-align: right;\">0.026</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Purchase Inputs for other Crops</td><td style = \"text-align: right;\">0.098</td><td style = \"text-align: right;\">0.062</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Expanding Business</td><td style = \"text-align: right;\">0.082</td><td style = \"text-align: right;\">0.138</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Other (Specify)</td><td style = \"text-align: right;\">0.027</td><td style = \"text-align: right;\">0.256</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Purchase House/Lease Land</td><td style = \"text-align: right;\">0.023</td><td style = \"text-align: right;\">0.031</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">10</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.015</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {.callout-note}\n## Solution figure 9.6's successful column sums to 0.91\n\nThe published table lists **0.01** for `\"Purchase Inputs for other Crops\"` among successful\nborrowers. The data gives **0.098**. Their own column is the check: with 0.01 it sums to 0.91,\nand with 0.10 it sums to 1.00. It is a dropped decimal place, not a different sample — every\nother cell in both columns reproduces.\n:::\n\n**The comparison is not clean, and the book says why.** `\"For consumption and personal expenses\"`\nis its own category for successful borrowers (0.202) but is folded into `\"Other (Specify)\"` for\ndenied ones — which is most of why denied borrowers show 0.256 on `\"Other\"` against 0.027 for\nsuccessful. The free-text field confirms the size:\n\n::: {#cell-purpose-other .cell execution_count=1}\n``` {.julia .cell-code}\n(households_with_other_text = count(!ismissing, allHH.loan_purpose_other),)\n```\n\n::: {#purpose-other .cell-output .cell-output-display execution_count=1}\n```\n(households_with_other_text = 52,)\n```\n:::\n:::\n\n\n\n52 households wrote in a reason, so the consumption share among denied applicants cannot be\nreconstructed at anything like 20%. **The two columns should not be differenced on `\"Other\"` or\non consumption.**\n\nWhat survives the incomparability:\n\n- **Business start-up is the largest denied purpose (0.262) and less than half that among\n  successful (0.155).** Together with `\"Expanding Business\"` (0.138 against 0.082), business\n  lending is where refusal concentrates. Start-up capital has no track record and often no\n  collateral, which is what a lender prices.\n- **Agricultural inputs for food crops is the largest successful purpose (0.300) against 0.210\n  denied.** Short, seasonal, and against a harvest a lender can anticipate.\n- **`\"10\"` appears as a purpose for 0.015 of denied households.** It is not a category in the\n  survey — a code that escaped its labels.\n\n**Household characteristics.**\n\n::: {#tbl-chars-status .cell tbl-cap='Mean household characteristics for successful and denied applicants. Reproduces the book\\'s Solution figure 9.7.' execution_count=1}\n``` {.julia .cell-code}\nconst COMPARE = [\"age\" => \"Age of household head\",\n                 \"max_education\" => \"Highest education in household\",\n                 \"number_assets\" => \"Number of assets\", \"hhsize\" => \"Household size\",\n                 \"young_children\" => \"Number of young children\",\n                 \"working_age_adults\" => \"Number of working-age adults\"]\n\nchars_table = DataFrame(characteristic = String[], successful = Float64[], denied = Float64[])\nfor (col, lab) in COMPARE\n    push!(chars_table, (lab,\n        [round(mean(skipmissing(sane[sane.HH_status .== st, col])), digits = 2)\n         for st in [\"successful\", \"denied\"]]...))\nend\npushfirst!(chars_table, (\"Number of observations\", Float64(successful), Float64(rejected)))\nchars_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>7×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">characteristic</th><th style = \"text-align: left;\">successful</th><th style = \"text-align: left;\">denied</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Number of observations</td><td style = \"text-align: right;\">1363.0</td><td style = \"text-align: right;\">201.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Age of household head</td><td style = \"text-align: right;\">43.37</td><td style = \"text-align: right;\">41.21</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Highest education in household</td><td style = \"text-align: right;\">7.26</td><td style = \"text-align: right;\">8.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Number of assets</td><td style = \"text-align: right;\">15.88</td><td style = \"text-align: right;\">14.46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Household size</td><td style = \"text-align: right;\">4.87</td><td style = \"text-align: right;\">4.82</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Number of young children</td><td style = \"text-align: right;\">2.09</td><td style = \"text-align: right;\">2.22</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Number of working-age adults</td><td style = \"text-align: right;\">2.75</td><td style = \"text-align: right;\">2.76</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**How each characteristic should matter, before looking.** A lender is pricing the probability of\nrepayment:\n\n1. **Age** — an older head has had longer to accumulate assets and a repayment record. Expect\n   successful borrowers to be older.\n2. **Education** — more schooling means higher and steadier income. Expect successful to be more\n   educated.\n3. **Assets** — the collateral channel, and the most direct of the six. Expect successful to own\n   more.\n4. **Household size** — more members to service the debt, but also more claims on income. Sign\n   ambiguous.\n5. **Young children** — dependants who consume now and earn later. Ambiguous, and negative in the\n   short run.\n6. **Working-age adults** — earning capacity. Expect successful to have more.\n\n**Three of the six go the expected way, and the largest surprise is education.** Successful\nborrowers are 2.2 years older (43.37 against 41.21) and own 1.4 more assets (15.88 against\n14.46). But their households are **less** educated — 7.26 years against 8.00.\n\nThat is backwards on the repayment story, and the likely reason is that education drives\n*application* rather than approval. A more educated household knows lenders exist, knows how to\napply, and is confident enough to try — so it appears in the applicant pool more often, including\nin its rejected tail. The comparison here conditions on having applied, so it cannot separate\n\"education makes approval more likely\" from \"education makes applying more likely.\" Q6 shows this\ndifference is not measured precisely enough to lean on either way.\n\nHousehold size, children and working-age adults are all essentially identical between the two\ngroups.\n\n## Q6. Are those differences real? {#p1-q6}\n\nSix differences in means with 95% confidence intervals, using the standard error for a\ndifference between independent groups from\n[Project 8](../08-unemployment-cost/index.qmd#part-8.3).\n\n::: {#tbl-differences .cell tbl-cap='Differences in mean characteristics, successful minus denied, with 95% confidence intervals. Reproduces the book\\'s Solution figure 9.9.' execution_count=1}\n``` {.julia .cell-code}\nconst Z = 1.96\n\ndifferences = DataFrame(characteristic = String[], successful = Float64[], sd_s = Float64[],\n                        n_s = Int[], denied = Float64[], sd_d = Float64[], n_d = Int[],\n                        difference = Float64[], lower = Float64[], upper = Float64[],\n                        excludes_zero = Bool[])\nfor (col, lab) in COMPARE\n    x = Float64.(collect(skipmissing(sane[sane.HH_status .== \"successful\", col])))\n    y = Float64.(collect(skipmissing(sane[sane.HH_status .== \"denied\", col])))\n    d = mean(x) - mean(y)\n    se = sqrt(var(x) / length(x) + var(y) / length(y))\n    push!(differences, (lab, round(mean(x), digits = 2), round(std(x), digits = 2), length(x),\n                        round(mean(y), digits = 2), round(std(y), digits = 2), length(y),\n                        round(d, digits = 3), round(d - Z * se, digits = 2),\n                        round(d + Z * se, digits = 2), abs(d) > Z * se))\nend\ndifferences\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×11 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">characteristic</th><th style = \"text-align: left;\">successful</th><th style = \"text-align: left;\">sd_s</th><th style = \"text-align: left;\">n_s</th><th style = \"text-align: left;\">denied</th><th style = \"text-align: left;\">sd_d</th><th style = \"text-align: left;\">n_d</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">excludes_zero</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Bool\" style = \"text-align: left;\">Bool</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Age of household head</td><td style = \"text-align: right;\">43.37</td><td style = \"text-align: right;\">14.27</td><td style = \"text-align: right;\">1361</td><td style = \"text-align: right;\">41.21</td><td style = \"text-align: right;\">12.85</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">2.154</td><td style = \"text-align: right;\">0.22</td><td style = \"text-align: right;\">4.09</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Highest education in household</td><td style = \"text-align: right;\">7.26</td><td style = \"text-align: right;\">6.74</td><td style = \"text-align: right;\">1363</td><td style = \"text-align: right;\">8.0</td><td style = \"text-align: right;\">7.9</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">-0.735</td><td style = \"text-align: right;\">-1.88</td><td style = \"text-align: right;\">0.41</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Number of assets</td><td style = \"text-align: right;\">15.88</td><td style = \"text-align: right;\">19.0</td><td style = \"text-align: right;\">1363</td><td style = \"text-align: right;\">14.46</td><td style = \"text-align: right;\">16.84</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">1.421</td><td style = \"text-align: right;\">-1.12</td><td style = \"text-align: right;\">3.96</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Household size</td><td style = \"text-align: right;\">4.87</td><td style = \"text-align: right;\">2.35</td><td style = \"text-align: right;\">1362</td><td style = \"text-align: right;\">4.82</td><td style = \"text-align: right;\">2.35</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">0.047</td><td style = \"text-align: right;\">-0.3</td><td style = \"text-align: right;\">0.39</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Number of young children</td><td style = \"text-align: right;\">2.09</td><td style = \"text-align: right;\">1.68</td><td style = \"text-align: right;\">1363</td><td style = \"text-align: right;\">2.22</td><td style = \"text-align: right;\">1.8</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">-0.135</td><td style = \"text-align: right;\">-0.4</td><td style = \"text-align: right;\">0.13</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Number of working-age adults</td><td style = \"text-align: right;\">2.75</td><td style = \"text-align: right;\">1.49</td><td style = \"text-align: right;\">1363</td><td style = \"text-align: right;\">2.76</td><td style = \"text-align: right;\">1.42</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">-0.003</td><td style = \"text-align: right;\">-0.21</td><td style = \"text-align: right;\">0.21</td><td style = \"text-align: right;\">false</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll six reproduce the published intervals.\n\n::: {.callout-note}\n## Here the book's interval arithmetic is correct\n\n[Project 8's Solutions page](../08-unemployment-cost/index.qmd#part-8.3) computed confidence\nintervals with a combined standard deviation over the pooled sample size, which understated\nevery width. Solution figure 9.9 uses the right formula and this page matches it to the second\ndecimal. The error there was local to that page, not a convention running through the book.\n:::\n\n::: {#cell-fig-differences .cell execution_count=1}\n``` {.julia .cell-code}\nsorted_diff = sort(differences, :difference)\n\nfig = Figure(size = (880, 500))\nax = Axis(fig[1, 1];\n          title = \"Only age differs measurably between successful and denied applicants\",\n          ylabel = \"Difference in means (successful − denied)\",\n          xticks = (1:nrow(sorted_diff), sorted_diff.characteristic),\n          xticklabelrotation = pi / 7,\n          limits = (nothing, (-2.5, 5.0)))\nhlines!(ax, [0]; color = BASELINE, linewidth = 1)\nbarplot!(ax, 1:nrow(sorted_diff), sorted_diff.difference;\n         width = 0.5, color = series_color(1))\nerrorbars!(ax, 1:nrow(sorted_diff), sorted_diff.difference,\n           sorted_diff.difference .- sorted_diff.lower,\n           sorted_diff.upper .- sorted_diff.difference;\n           color = INK_SECONDARY, whiskerwidth = 12, linewidth = 2)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Difference in mean characteristics, successful minus denied applicants, sorted. One series, so one colour; error bars are the 95% half-widths from the table above and the rule at zero is what each is read against. Age and assets are plotted on the same axis as counts of people because all six are differences in whatever unit the characteristic uses — the axis is a difference, not a level.](index_files/figure-html/fig-differences-output-1.svg){#fig-differences}\n:::\n:::\n\n\n\n**One of the six differences excludes zero.** Age: **2.15 years [0.22, 4.09]**, and only just —\nthe lower bound is a fifth of a year from zero. Assets, the difference with the clearest\nmechanism, is **1.42 [−1.12, 3.96]**: the interval is nearly three times the estimate.\n\nThe reason is visible in the table. **There are 201 denied households against 1,361 successful\nones**, and the standard error of a difference is dominated by the smaller group. On assets, the\ndenied group's SD of 16.8 over 201 observations contributes about six times the variance that\n1,361 successful households contribute.\n\nSo the honest reading is that **this comparison cannot distinguish successful from denied\napplicants on five of six characteristics**, and the education result that looked like a puzzle\nin Q5 has an interval of [−1.88, 0.41] — comfortably including zero. It is not a finding that\nneeds explaining; it is noise, and the explanation offered in Q5 is a hypothesis rather than a\nresult.\n\n**What would help.** More denied households, which the survey cannot supply — refusal is rare, so\na nationally representative sample of 5,262 yields only 201. That is a structural feature of\nstudying exclusion from a general household survey, and it is why the next question widens the\ncomparison to groups the survey has more of.\n\n## Q7. Four groups, not two {#p1-q7}\n\nSuccessful and denied applicants, plus the discouraged and the credit constrained. The last two\noverlap with each other and with \"did not apply\", which is why they are shown as separate\ncolumns rather than a partition.\n\n::: {#tbl-four-groups .cell tbl-cap='Mean characteristics across four borrower types. Discouraged and credit-constrained overlap, so the columns are not mutually exclusive. Reproduces the book\\'s Solution figure 9.11.' execution_count=1}\n``` {.julia .cell-code}\nconst GROUPS = [\"successful\" => sane.HH_status .== \"successful\",\n                \"denied\" => sane.HH_status .== \"denied\",\n                \"discouraged\" => sane.discouraged .== 1,\n                \"constrained\" => sane.credit_constrained .== 1]\n\nfour_groups = DataFrame(characteristic = [\"Number of observations\";\n                                          [lab for (_, lab) in COMPARE]])\nfor (label, mask) in GROUPS\n    rows = sane[mask, :]\n    four_groups[!, label] = [Float64(nrow(rows));\n                             [round(mean(skipmissing(rows[!, col])), digits = 2)\n                              for (col, _) in COMPARE]]\nend\nfour_groups\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>7×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">characteristic</th><th style = \"text-align: left;\">successful</th><th style = \"text-align: left;\">denied</th><th style = \"text-align: left;\">discouraged</th><th style = \"text-align: left;\">constrained</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Number of observations</td><td style = \"text-align: right;\">1363.0</td><td style = \"text-align: right;\">201.0</td><td style = \"text-align: right;\">588.0</td><td style = \"text-align: right;\">3012.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Age of household head</td><td style = \"text-align: right;\">43.37</td><td style = \"text-align: right;\">41.21</td><td style = \"text-align: right;\">43.28</td><td style = \"text-align: right;\">44.84</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Highest education in household</td><td style = \"text-align: right;\">7.26</td><td style = \"text-align: right;\">8.0</td><td style = \"text-align: right;\">6.5</td><td style = \"text-align: right;\">7.14</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Number of assets</td><td style = \"text-align: right;\">15.88</td><td style = \"text-align: right;\">14.46</td><td style = \"text-align: right;\">10.16</td><td style = \"text-align: right;\">13.54</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Household size</td><td style = \"text-align: right;\">4.87</td><td style = \"text-align: right;\">4.82</td><td style = \"text-align: right;\">4.65</td><td style = \"text-align: right;\">4.44</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Number of young children</td><td style = \"text-align: right;\">2.09</td><td style = \"text-align: right;\">2.22</td><td style = \"text-align: right;\">2.03</td><td style = \"text-align: right;\">1.81</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Number of working-age adults</td><td style = \"text-align: right;\">2.75</td><td style = \"text-align: right;\">2.76</td><td style = \"text-align: right;\">2.49</td><td style = \"text-align: right;\">2.49</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery value matches the published table.\n\n::: {#cell-fig-four-groups .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (960, 560))\nlabels = [lab for (_, lab) in COMPARE]\nnames_ = [label for (label, _) in GROUPS]\n\nfor (k, lab) in enumerate(labels)\n    row, col = fldmod1(k, 3)\n    values = Float64[four_groups[four_groups.characteristic .== lab, g][1] for g in names_]\n    ax = Axis(fig[row, col];\n              title = lab, titlesize = 12,\n              xticks = (1:4, names_), xticklabelrotation = pi / 6,\n              limits = (nothing, (0, maximum(values) * 1.25)))\n    barplot!(ax, 1:4, values; width = 0.55, color = series_color(1))\n    for (x, v) in zip(1:4, values)\n        text!(ax, x, v; text = string(v), fontsize = 9,\n              align = (:center, :bottom), offset = (0, 3))\n    end\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Each characteristic across the four borrower types, one panel per characteristic so that variables on different scales keep their own axis. One series throughout — the group is a category on the horizontal axis, not a colour, which keeps the four bars comparable within each panel.](index_files/figure-html/fig-four-groups-output-1.svg){#fig-four-groups}\n:::\n:::\n\n\n\n**Discouraged households are the asset-poor ones.** They own **10.16 assets** against 15.88 for\nsuccessful borrowers and 14.46 for denied ones — a gap of about a third, and far larger than any\ndifference Q6 could measure. They also have the least education of the four groups, at 6.50 years.\n\nThis is the useful result of the Part, and it comes from the group the survey classifies *least*\ndirectly. The households that never applied because they expected refusal look materially poorer\nthan the households that applied and were refused. If exclusion were measured by rejections\nalone, the most disadvantaged group would be invisible.\n\n**Credit-constrained households are the smallest ones**: household size 4.44 against 4.87,\nyoung children 1.81 against 2.09, working-age adults 2.49. Their head is also the oldest at\n44.84. But this group is 3,012 households — 58% of the sample — so its means are close to the\nsample averages almost by construction, and the comparison is less informative than the\ndiscouraged column.\n\n**Selection bias, and why it matters here.** Every comparison in Part 9.1 conditions on an\noutcome the household influenced. Q5 and Q6 compare applicants only, so they measure the effect\nof characteristics on approval *among households that chose to apply* — and the choice to apply\ndepends on the same characteristics. If more educated households are more likely to apply\nincluding when their prospects are marginal, then the applicant pool's education gap tells you\nabout applying, not about approval, which is exactly the ambiguity Q5 hit.\n\nThe general form: **estimating a relationship on a sample selected by the outcome recovers the\nselection as much as the relationship.** A study of what makes countries prosper that uses only\ncountries publishing good statistics is drawing from a sample whose membership depends on state\ncapacity — itself a determinant of prosperity. The estimate absorbs the selection.\n\nWhat would fix it here is data on the *terms* households expected, so that the decision not to\napply could be modelled rather than conditioned away. The survey records reasons but not expected\nprices, so the four groups can be described and compared, and that is as far as this design goes.\n\n# Part 9.2 — Households that got a loan {#part-9.2}\n\n1,480 loans, with start and end dates, amount, interest, and source. The dates need cleaning\nfirst, and one of the problems is not a problem.\n\n## Q1. Loan duration {#p2-q1}\n\n**(a) What is wrong with the date fields.**\n\n::: {#tbl-date-values .cell tbl-cap='Every distinct value in the four date fields, with counts. The year fields are where the errors are.' execution_count=1}\n``` {.julia .cell-code}\ndate_values = DataFrame(field = String[], value = String[], n = Int[])\nfor c in [\"loan_startyear\", \"loan_endyear\"]\n    vals = collect(skipmissing(gotL[!, c]))\n    for v in sort(unique(vals); by = string)\n        push!(date_values, (c, string(v), count(==(v), vals)))\n    end\nend\nshow_all(date_values)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>18×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">field</th><th style = \"text-align: left;\">value</th><th style = \"text-align: left;\">n</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">1996</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">1999</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">200</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">2002</td><td style = \"text-align: right;\">2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">2003</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">2004</td><td style = \"text-align: right;\">12</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">2005</td><td style = \"text-align: right;\">758</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">2006</td><td style = \"text-align: right;\">700</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">loan_startyear</td><td style = \"text-align: left;\">3</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">1</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2003</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2005</td><td style = \"text-align: right;\">8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2006</td><td style = \"text-align: right;\">696</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2007</td><td style = \"text-align: right;\">186</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2008</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2009</td><td style = \"text-align: right;\">16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2010</td><td style = \"text-align: right;\">5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">loan_endyear</td><td style = \"text-align: left;\">2012</td><td style = \"text-align: right;\">1</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-month-values .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(field = [\"loan_startmonth\", \"loan_endmonth\"],\n          distinct = [join(sort(unique(string.(skipmissing(gotL[!, c])))), \", \")\n                      for c in [\"loan_startmonth\", \"loan_endmonth\"]])\n```\n\n::: {#month-values .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">field</th><th style = \"text-align: left;\">distinct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">loan_startmonth</td><td style = \"text-align: left;\">April, August, December, February, January, July, June, March, May, November, October, September</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">loan_endmonth</td><td style = \"text-align: left;\">April, August, December, February, January, July, June, March, May, November, October, Pagume, September</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThree impossible years — `\"3\"` and `\"200\"` as start years, `\"1\"` as an end year — each appearing\nonce. `\"200\"` is plainly a truncated `\"2005\"` or `\"2006\"`, but there is no way to tell which, so\nguessing would invent data; all three become missing.\n\n::: {.callout-note}\n## \"Pagume\" is a real month\n\n`loan_endmonth` contains **Pagume**, which looks like a data error and is not. The Ethiopian\ncalendar has thirteen months: twelve of 30 days, then Pagume, a five- or six-day intercalary\nmonth falling in early September on the Gregorian calendar.\n\nSo it maps to September rather than to missing. This is the kind of thing that is only visible if\nyou look at the distinct values before cleaning — an automated \"drop what isn't a month name\"\nrule would silently discard valid observations, and a survey of Ethiopian households is exactly\nwhere a thirteenth month should be expected.\n:::\n\n**(b) and (c) Dates, and how much is missing.**\n\n::: {#cell-clean-dates .cell execution_count=1}\n``` {.julia .cell-code}\nconst MONTHS = Dict(\"January\" => 1, \"February\" => 2, \"March\" => 3, \"April\" => 4,\n                    \"May\" => 5, \"June\" => 6, \"July\" => 7, \"August\" => 8,\n                    \"September\" => 9, \"October\" => 10, \"November\" => 11,\n                    \"December\" => 12,\n                    # Pagume is the 13th Ethiopian month, in early September.\n                    \"Pagume\" => 9)\n\nparse_year(y) = y === missing ? missing :\n                (n = tryparse(Int, string(y));\n                 n === nothing || n < 1990 || n > 2015 ? missing : n)\nparse_month(m) = m === missing ? missing : get(MONTHS, string(m), missing)\n\ngotL.start_year = parse_year.(gotL.loan_startyear)\ngotL.start_month = parse_month.(gotL.loan_startmonth)\ngotL.end_year = parse_year.(gotL.loan_endyear)\ngotL.end_month = parse_month.(gotL.loan_endmonth)\n\nas_date(y, m) = (y === missing || m === missing) ? missing : Date(y, m)\ngotL.start_date = as_date.(gotL.start_year, gotL.start_month)\ngotL.end_date = as_date.(gotL.end_year, gotL.end_month)\n\nDataFrame(date = [\"Start date\", \"End date\"],\n          missing_n = [count(ismissing, gotL.start_date), count(ismissing, gotL.end_date)],\n          missing_pct = [round(100 * count(ismissing, gotL.start_date) / nrow(gotL), digits = 2),\n                         round(100 * count(ismissing, gotL.end_date) / nrow(gotL), digits = 2)])\n```\n\n::: {#clean-dates .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">date</th><th style = \"text-align: left;\">missing_n</th><th style = \"text-align: left;\">missing_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Start date</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">End date</td><td style = \"text-align: right;\">535</td><td style = \"text-align: right;\">36.15</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**6 start dates missing (0.41%) and 535 end dates (36.15%)**, both matching the book.\n\n**The asymmetry is the finding, not the total.** Start dates are essentially complete; **more\nthan a third of end dates are absent**. That is not random non-response — a loan with no end date\nis most naturally a loan that had not ended when the survey was taken. If so, the missing third\nis disproportionately *long* loans, and every duration statistic below is computed on a sample\nbiased toward loans short enough to have finished. It is the same selection problem as\n[Q7](#p1-q7), arriving through missingness instead of through a filter.\n\n**(d) and (e) Duration, and the negative ones.**\n\n::: {#cell-duration .cell execution_count=1}\n``` {.julia .cell-code}\ngotL.duration = [(s === missing || e === missing) ? missing : Dates.value(e - s)\n                 for (s, e) in zip(gotL.start_date, gotL.end_date)]\n\n# Two treatments of a negative duration: drop it, or assume the dates were swapped.\ngotL.duration_dropped = [x === missing ? missing : (x < 0 ? missing : x)\n                         for x in gotL.duration]\ngotL.loan_length = [x === missing ? missing : abs(x) for x in gotL.duration]\n\ncomputable = collect(skipmissing(gotL.duration))\n(computable = length(computable),\n negative = count(<(0), computable),\n negative_pct = round(100 * count(<(0), computable) / length(computable), digits = 1),\n range_days = extrema(computable))\n```\n\n::: {#duration .cell-output .cell-output-display execution_count=1}\n```\n(computable = 943, negative = 172, negative_pct = 18.2, range_days = (-1066, 4748))\n```\n:::\n:::\n\n\n\n**943 loans have both dates, and 172 of them — 18.2% — end before they begin.** That is far too\nmany to be a handful of typos, and it makes the choice of treatment consequential rather than\ncosmetic:\n\n- **Dropping them** leaves 771 loans and assumes the affected records are uninformative.\n- **Taking the absolute value** keeps all 943 and assumes the two dates were transposed, so the\n  magnitude is right and only the order is wrong.\n\nThe book uses the absolute value for what follows, so this page does too — but with 18% of\ncomputable durations affected, the two treatments are different samples, not the same sample\ncleaned two ways. Note also that the most extreme negative is **−1,066 days**, nearly three\nyears, which is hard to read as a transcription slip and easier to read as a genuinely confused\npair of dates.\n\n**(f) Long-term loans.**\n\n::: {#cell-long-term .cell execution_count=1}\n``` {.julia .cell-code}\ngotL.long_term = [x === missing ? missing : Int(x > 365) for x in gotL.loan_length]\nclassified = collect(skipmissing(gotL.long_term))\n\n(with_a_duration = length(classified),\n long_term = sum(classified),\n short_term = count(iszero, classified),\n unclassified = count(ismissing, gotL.long_term),\n pct_long_term = round(100 * mean(classified), digits = 2))\n```\n\n::: {#long-term .cell-output .cell-output-display execution_count=1}\n```\n(with_a_duration = 943, long_term = 215, short_term = 728, unclassified = 537, pct_long_term = 22.8)\n```\n:::\n:::\n\n\n\n**22.80% of classifiable loans ran longer than a year** — 215 of 943, matching the book, with 537\nloans unclassifiable.\n\nThe denominator deserves the emphasis the headline number usually gets. **537 of 1,480 loans —\n36% — have no duration at all**, and by the argument above they are the ones most likely to be\nlong. So 22.80% is a lower bound on the long-term share, and possibly a substantial\nunderestimate.\n\n## Q2. Amounts and interest rates {#p2-q2}\n\n**(a) The distribution of loan size.**\n\n::: {#tbl-amounts .cell tbl-cap='Loan principal and total repayable, in Ethiopian birr. Reproduces the book\\'s Solution figure 9.12.' execution_count=1}\n``` {.julia .cell-code}\namount = Float64.(collect(skipmissing(gotL.loan_amount)))\npaired = [(Float64(r.loan_amount), Float64(r.loan_interest)) for r in eachrow(gotL)\n          if r.loan_amount !== missing && r.loan_interest !== missing]\ntotal = [a + i for (a, i) in paired]\n\nDataFrame(measure = [\"Loan amount (principal)\", \"Total amount to repay\"],\n          n = [length(amount), length(total)],\n          mean = round.([mean(amount), mean(total)]),\n          sd = round.([std(amount), std(total)]),\n          min = [minimum(amount), minimum(total)],\n          max = [maximum(amount), maximum(total)])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">measure</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Loan amount (principal)</td><td style = \"text-align: right;\">1479</td><td style = \"text-align: right;\">26896.0</td><td style = \"text-align: right;\">783587.0</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">3.0e7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Total amount to repay</td><td style = \"text-align: right;\">1445</td><td style = \"text-align: right;\">29223.0</td><td style = \"text-align: right;\">827144.0</td><td style = \"text-align: right;\">20.0</td><td style = \"text-align: right;\">3.126e7</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nBoth rows match the published table. **The mean is meaningless here and the reason is in the same\nrow.** A mean of 26,896 birr with a standard deviation of 783,587 — twenty-nine times the mean —\nand a range from **1 birr to 30 million**. One loan is 1,100 times the mean.\n\nA single observation is doing most of the work, which is why the quartiles in (d) are the honest\nsummary and the mean is not.\n\n**(b) and (c) Interest rates, and the extreme observation.**\n\n::: {#cell-interest-rate .cell execution_count=1}\n``` {.julia .cell-code}\ngotL.rate = [(r.loan_amount === missing || r.loan_interest === missing ||\n              r.loan_amount == 0) ? missing :\n             100 * r.loan_interest / r.loan_amount for r in eachrow(gotL)]\nrates = collect(skipmissing(gotL.rate))\n\n(with_a_rate = length(rates),\n zero_interest_pct = round(100 * count(iszero, rates) / length(rates), digits = 2),\n median = round(median(rates), digits = 2),\n max = round(maximum(rates), digits = 0))\n```\n\n::: {#interest-rate .cell-output .cell-output-display execution_count=1}\n```\n(with_a_rate = 1445, zero_interest_pct = 50.52, median = 0.0, max = 20000.0)\n```\n:::\n:::\n\n\n\n**50.52% of loans carry no interest at all**, matching the book, and the maximum rate is\n**20,000%**.\n\n::: {.callout-note}\n## The book calls this loan \"200%\"\n\nThe Solutions page describes the extreme observation as having an interest rate of 200%. The\ninterest is 200 *times* the principal, so as a percentage that is 20,000% — their rate is the\nratio, not multiplied by 100.\n\nThe observation identified is the same one either way, and it is excluded from what follows on\nboth readings. Only the units differ, and this page states rates as percentages throughout.\n:::\n\n::: {#cell-fig-interest .cell execution_count=1}\n``` {.julia .cell-code}\nplotted = [(a, r) for (a, r) in zip(gotL.loan_amount, gotL.rate)\n           if a !== missing && r !== missing && a > 0 && r > 0]\nextreme = argmax(last.(plotted))\n\nfig = Figure(size = (880, 500))\nax = Axis(fig[1, 1];\n          title = \"One loan sits two orders of magnitude above every other rate\",\n          xlabel = \"Loan principal (birr, log scale)\",\n          ylabel = \"Interest rate (%, log scale)\",\n          xscale = log10, yscale = log10)\nscatter!(ax, first.(plotted), last.(plotted); color = series_color(1), markersize = 7)\ntext!(ax, first(plotted[extreme]), last(plotted[extreme]);\n      text = \"excluded: $(round(Int, last(plotted[extreme])))%\", fontsize = 11,\n      align = (:left, :center), offset = (10, 0), color = INK)\ntext!(ax, 1.5, 1.2;\n      text = \"$(count(iszero, rates)) zero-interest loans are not shown\\n\" *\n             \"(a log axis has no zero)\",\n      fontsize = 10, align = (:left, :bottom), color = MUTED)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Interest rate against loan principal, both on log scales because each spans four to five orders of magnitude. One series, so one colour; the single excluded observation is labelled rather than given a colour of its own. Zero-interest loans cannot be drawn on a log axis and are counted in the annotation instead.](index_files/figure-html/fig-interest-output-1.svg){#fig-interest}\n:::\n:::\n\n\n\n**(d) By term.** Excluding the one extreme observation.\n\n::: {#tbl-by-term .cell tbl-cap='Loan amount and interest rate by term, excluding the single extreme-rate observation. Reproduces the book\\'s Solution figure 9.14.' execution_count=1}\n``` {.julia .cell-code}\nkeep = [r !== missing && r < 10_000 for r in gotL.rate]\n\nby_term = DataFrame(measure = String[], term = String[], n = Int[], mean = Float64[],\n                    sd = Float64[], min = Float64[], q1 = Float64[], median = Float64[],\n                    q3 = Float64[], max = Float64[])\nfor (measure, col, digits) in [(\"Loan amount\", :loan_amount, 0), (\"Interest rate (%)\", :rate, 2)]\n    for (term, flag) in [\"Long term\" => 1, \"Short term\" => 0]\n        mask = keep .& coalesce.(gotL.long_term .== flag, false)\n        v = Float64.(collect(skipmissing(gotL[mask, col])))\n        push!(by_term, (measure, term, length(v), round(mean(v); digits),\n                        round(std(v); digits), round(minimum(v); digits),\n                        round(quantile(v, 0.25); digits), round(median(v); digits),\n                        round(quantile(v, 0.75); digits), round(maximum(v); digits)))\n    end\nend\nby_term\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×10 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">measure</th><th style = \"text-align: left;\">term</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">q1</th><th style = \"text-align: left;\">median</th><th style = \"text-align: left;\">q3</th><th style = \"text-align: left;\">max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Loan amount</td><td style = \"text-align: left;\">Long term</td><td style = \"text-align: right;\">211</td><td style = \"text-align: right;\">172718.0</td><td style = \"text-align: right;\">2.07274e6</td><td style = \"text-align: right;\">20.0</td><td style = \"text-align: right;\">1000.0</td><td style = \"text-align: right;\">3700.0</td><td style = \"text-align: right;\">8000.0</td><td style = \"text-align: right;\">3.0e7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Loan amount</td><td style = \"text-align: left;\">Short term</td><td style = \"text-align: right;\">717</td><td style = \"text-align: right;\">3017.0</td><td style = \"text-align: right;\">8398.0</td><td style = \"text-align: right;\">40.0</td><td style = \"text-align: right;\">480.0</td><td style = \"text-align: right;\">1500.0</td><td style = \"text-align: right;\">3500.0</td><td style = \"text-align: right;\">150000.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Interest rate (%)</td><td style = \"text-align: left;\">Long term</td><td style = \"text-align: right;\">211</td><td style = \"text-align: right;\">18.9</td><td style = \"text-align: right;\">26.79</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">14.08</td><td style = \"text-align: right;\">24.52</td><td style = \"text-align: right;\">223.53</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Interest rate (%)</td><td style = \"text-align: left;\">Short term</td><td style = \"text-align: right;\">717</td><td style = \"text-align: right;\">11.01</td><td style = \"text-align: right;\">17.25</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">17.14</td><td style = \"text-align: right;\">111.76</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery cell matches the published table.\n\n**Long-term loans are larger, and far more unequally sized.** Median 3,700 birr against 1,500 for\nshort-term — a factor of 2.5 at the median. But the *means* are 172,718 against 3,017, a factor\nof 57, because the 30-million-birr loan is long term. Comparing medians and comparing means gives\nanswers an order of magnitude apart, and the median is the one to trust.\n\n**Long-term loans also charge more.** Median rate 14.08% against 5.00%, and mean 18.90% against\n11.01%. Both terms have a first quartile of **0.00%**, so at least a quarter of loans in each\ngroup are interest-free.\n\nThat last fact is the interesting one, and it does not fit a market story. A quarter of loans at\nzero interest in both terms suggests two different lending arrangements coexisting rather than a\nsingle market pricing risk — which is what Q3 tests by looking at who the lender was.\n\n**(e) Interest rates against household characteristics.**\n\n::: {#tbl-rate-correlations .cell tbl-cap='Correlation between the interest rate charged and household characteristics, excluding the extreme observation.' execution_count=1}\n``` {.julia .cell-code}\nrate_corr = DataFrame(characteristic = String[], correlation = Float64[], n = Int[])\nfor (col, lab) in COMPARE\n    ok = keep .& .!ismissing.(gotL[!, col])\n    push!(rate_corr, (lab, round(cor(Float64.(gotL[ok, col]), Float64.(gotL[ok, :rate])),\n                                 digits = 3), count(ok)))\nend\nsort!(rate_corr, :correlation)\nrate_corr\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">characteristic</th><th style = \"text-align: left;\">correlation</th><th style = \"text-align: left;\">n</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Highest education in household</td><td style = \"text-align: right;\">-0.084</td><td style = \"text-align: right;\">1444</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Number of assets</td><td style = \"text-align: right;\">-0.047</td><td style = \"text-align: right;\">1444</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Age of household head</td><td style = \"text-align: right;\">0.026</td><td style = \"text-align: right;\">1443</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Number of working-age adults</td><td style = \"text-align: right;\">0.047</td><td style = \"text-align: right;\">1444</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Number of young children</td><td style = \"text-align: right;\">0.102</td><td style = \"text-align: right;\">1444</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Household size</td><td style = \"text-align: right;\">0.105</td><td style = \"text-align: right;\">1442</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nReading the interest rate as a price for default risk, the expectation is that households with\nmore assets and more earners pay less, and households with more dependants pay more.\n\n::: {#cell-fig-rate-correlations .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (860, 460))\nax = Axis(fig[1, 1];\n          title = \"No household characteristic explains much of the rate charged\",\n          ylabel = \"Correlation with interest rate\",\n          xticks = (1:nrow(rate_corr), rate_corr.characteristic),\n          xticklabelrotation = pi / 7,\n          limits = (nothing, (-0.5, 0.5)))\nhlines!(ax, [0]; color = BASELINE, linewidth = 1)\nbarplot!(ax, 1:nrow(rate_corr), rate_corr.correlation;\n         width = 0.5, color = series_color(1))\nfor (x, v) in zip(1:nrow(rate_corr), rate_corr.correlation)\n    text!(ax, x, v; text = string(v), fontsize = 10,\n          align = (:center, v < 0 ? :top : :bottom), offset = (0, v < 0 ? -4 : 4))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Correlation between interest rate charged and each household characteristic. One series; the zero rule is the reference. All six correlations are small — the axis is deliberately not stretched to fill the panel, because doing so would make weak associations look strong.](index_files/figure-html/fig-rate-correlations-output-1.svg){#fig-rate-correlations}\n:::\n:::\n\n\n\n**Every correlation is small.** Nothing about the household explains much of what it was charged,\nwhich is itself the answer: if these rates were priced on household default risk, the\ncharacteristics a lender can observe should show up here, and they barely do.\n\nThe alternative explanation is that the rate is set by *which lender* the household reached\nrather than by the household's own risk — a moneylender and a relative charge differently for the\nsame borrower. That is Q3.\n\n## Q3. Who lends {#p2-q3}\n\n::: {#tbl-sources .cell tbl-cap='Source of finance by area type, counts. Reproduces the structure of the book\\'s Solution figure for R walk-through 9.11.' execution_count=1}\n``` {.julia .cell-code}\nsources = sort(unique(skipmissing(gotL.borrowed_from)))\nsource_table = DataFrame(source = String[])\nfor a in AREAS\n    source_table[!, a] = Int[]\nend\nsource_table.total = Int[]\nfor s in sources\n    rows = gotL[coalesce.(gotL.borrowed_from .== s, false), :]\n    counts = [count(==(a), skipmissing(rows.rural)) for a in AREAS]\n    push!(source_table, (s, counts..., nrow(rows)))\nend\nsort!(source_table, :total, rev = true)\nshow_all(source_table)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">source</th><th style = \"text-align: left;\">Rural</th><th style = \"text-align: left;\">Small town (urban)</th><th style = \"text-align: left;\">Large town (urban)</th><th style = \"text-align: left;\">total</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Relative</td><td style = \"text-align: right;\">329</td><td style = \"text-align: right;\">42</td><td style = \"text-align: right;\">168</td><td style = \"text-align: right;\">539</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Microfinance Institution</td><td style = \"text-align: right;\">286</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">63</td><td style = \"text-align: right;\">375</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Neighbour</td><td style = \"text-align: right;\">118</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">38</td><td style = \"text-align: right;\">163</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Other (specify)</td><td style = \"text-align: right;\">123</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">19</td><td style = \"text-align: right;\">146</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Grocery/Local Merchant</td><td style = \"text-align: right;\">50</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">86</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">NGO</td><td style = \"text-align: right;\">49</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">58</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Money Lender (Katapila)</td><td style = \"text-align: right;\">49</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">52</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Religious Institution</td><td style = \"text-align: right;\">21</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">22</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Employer</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">16</td><td style = \"text-align: right;\">19</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Bank (commercial)</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">10</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Relatives are the single largest source of credit — 539 loans, more than a third of the\ntotal** — followed by microfinance institutions at 375. Commercial banks made **10 loans out of\n1,480**.\n\nGrouping by what kind of institution each is:\n\n::: {#tbl-source-groups .cell tbl-cap='Sources grouped by type of lender. Formal excludes microfinance, which is treated separately because it is neither an informal relationship nor a commercial bank.' execution_count=1}\n``` {.julia .cell-code}\nconst LENDER_TYPE = Dict(\n    \"Bank (commercial)\" => \"Formal\", \"Employer\" => \"Formal\",\n    \"Microfinance Institution\" => \"Microfinance\", \"NGO\" => \"Microfinance\",\n    \"Relative\" => \"Informal\", \"Neighbour\" => \"Informal\",\n    \"Money Lender (Katapila)\" => \"Informal\", \"Grocery/Local Merchant\" => \"Informal\",\n    \"Religious Institution\" => \"Informal\", \"Other (specify)\" => \"Other\")\n\ngotL.lender_type = [s === missing ? missing : LENDER_TYPE[string(s)] for s in gotL.borrowed_from]\ntypes = collect(skipmissing(gotL.lender_type))\n\ntype_table = DataFrame(lender_type = unique(types))\ntype_table.loans = [count(==(t), types) for t in type_table.lender_type]\ntype_table.pct = round.(100 .* type_table.loans ./ length(types), digits = 1)\ntype_table.median_rate = [round(median(skipmissing(gotL[coalesce.(gotL.lender_type .== t,\n                                                                 false) .& keep, :rate])),\n                                digits = 2) for t in type_table.lender_type]\ntype_table.zero_interest_pct =\n    [round(100 * mean(iszero,\n                      collect(skipmissing(gotL[coalesce.(gotL.lender_type .== t, false) .&\n                                               keep, :rate]))), digits = 1)\n     for t in type_table.lender_type]\nsort!(type_table, :loans, rev = true)\ntype_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">lender_type</th><th style = \"text-align: left;\">loans</th><th style = \"text-align: left;\">pct</th><th style = \"text-align: left;\">median_rate</th><th style = \"text-align: left;\">zero_interest_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Informal</td><td style = \"text-align: right;\">862</td><td style = \"text-align: right;\">58.6</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">79.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Microfinance</td><td style = \"text-align: right;\">433</td><td style = \"text-align: right;\">29.5</td><td style = \"text-align: right;\">15.0</td><td style = \"text-align: right;\">5.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Other</td><td style = \"text-align: right;\">146</td><td style = \"text-align: right;\">9.9</td><td style = \"text-align: right;\">10.7</td><td style = \"text-align: right;\">17.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Formal</td><td style = \"text-align: right;\">29</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">42.3</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**This is where the zero-interest loans come from.** Informal lenders — relatives, neighbours,\nlocal merchants, religious institutions and moneylenders — make **58.6% of all loans**, and\n**79.8% of them charge nothing**. Their median rate is 0.00%. Microfinance institutions and NGOs\nmake 29.5% of loans at a median of 15.00%, with only 5.4% interest-free.\n\nThat resolves the puzzle from [Q2](#p2-q2). Half of all loans carry no interest not because\nEthiopian credit is cheap, but because **half of it is not priced credit at all**: informal\nzero-interest lending alone accounts for about 47% of every loan in the file, which is most of\nthe 50.52% zero-interest share. A loan from a relative at 0% and a microfinance loan at 15% are\ndifferent instruments, and averaging them produces a \"market interest rate\" that describes\nneither.\n\nThe formal category — commercial banks and employers — is **29 loans out of 1,480**, so its\nmedian of 6.00% rests on too little data to compare. That scarcity is itself the finding: formal\nfinance is close to absent for these households.\n\nIt also explains why household characteristics barely correlate with the rate. The rate is\nmostly determined by which of these two systems the household borrowed in, and that is a\nquestion about the household's *network and location* rather than its balance sheet — which is\nwhy the rural/urban split in the source table is the more informative cut.\n\n::: {#tbl-source-by-area .cell tbl-cap='Each source\\'s loans as a share of that area type\\'s loans, so columns sum to 1 and areas of very different size can be compared.' execution_count=1}\n``` {.julia .cell-code}\narea_shares = DataFrame(source = source_table.source)\nfor a in AREAS\n    n_area = count(==(a), skipmissing(gotL.rural))\n    area_shares[!, a] = round.(source_table[!, a] ./ n_area, digits = 3)\nend\nshow_all(area_shares)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">source</th><th style = \"text-align: left;\">Rural</th><th style = \"text-align: left;\">Small town (urban)</th><th style = \"text-align: left;\">Large town (urban)</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Relative</td><td style = \"text-align: right;\">0.317</td><td style = \"text-align: right;\">0.429</td><td style = \"text-align: right;\">0.49</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Microfinance Institution</td><td style = \"text-align: right;\">0.275</td><td style = \"text-align: right;\">0.265</td><td style = \"text-align: right;\">0.184</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Neighbour</td><td style = \"text-align: right;\">0.114</td><td style = \"text-align: right;\">0.071</td><td style = \"text-align: right;\">0.111</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Other (specify)</td><td style = \"text-align: right;\">0.118</td><td style = \"text-align: right;\">0.041</td><td style = \"text-align: right;\">0.055</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Grocery/Local Merchant</td><td style = \"text-align: right;\">0.048</td><td style = \"text-align: right;\">0.102</td><td style = \"text-align: right;\">0.076</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">NGO</td><td style = \"text-align: right;\">0.047</td><td style = \"text-align: right;\">0.051</td><td style = \"text-align: right;\">0.012</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Money Lender (Katapila)</td><td style = \"text-align: right;\">0.047</td><td style = \"text-align: right;\">0.02</td><td style = \"text-align: right;\">0.003</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Religious Institution</td><td style = \"text-align: right;\">0.02</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.003</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Employer</td><td style = \"text-align: right;\">0.002</td><td style = \"text-align: right;\">0.01</td><td style = \"text-align: right;\">0.047</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Bank (commercial)</td><td style = \"text-align: right;\">0.004</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.017</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Microfinance is a rural institution in this data** and moneylenders are almost entirely rural,\nwhile employer loans and commercial banks are concentrated in large towns. Relatives lend\neverywhere.\n\n**(d) What is missing from the data.** Three things that the questions above kept running into:\n\n1. **The terms that were offered but refused.** Every rate here is a rate somebody accepted. The\n   households in Part 9.1 that did not apply because credit was `\"Too Expensive\"` faced a price\n   that this dataset does not record, so the distribution of *offered* rates cannot be recovered\n   from the distribution of *accepted* ones — the same selection problem as\n   [Q7](#p1-q7), now on the price rather than the quantity.\n2. **Loan duration for the third of loans still outstanding.** No end date means no duration, and\n   those are the loans most likely to be long.\n3. **Whether the loan was repaid**, which `loan_repaid` records but which cannot be interpreted\n   without knowing whether the term had ended. Default is the outcome the interest rate is\n   supposed to be pricing, and it is the one thing this data cannot check the pricing against.\n\nCollateral offered, the household's prior borrowing history, and distance to the nearest lender\nwould each address a specific gap above. The last is the one that would speak most directly to\n`\"Do Not Know Any Lender\"` — 7% of first reasons in [Q4](#p1-q4).\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading several sheets separately | Setup | `XLSX.readtable(path, \"Got loan\")` |\n| Cross-tabulation keeping blanks | Q9.1 Q2 | `count` over a labelling function |\n| Indicators from free-response fields | Q9.1 Q3 | `Int(any(...))` over the reason columns |\n| Row-proportion tables | Q9.1 Q1 | divide each row by its own total |\n| Difference in means with a CI | Q9.1 Q6 | `sqrt(var(x)/nx + var(y)/ny)`, `± 1.96se` |\n| Asymmetric error bars | Q9.1 Q6 | `errorbars!(ax, x, y, low, high)` |\n| Small multiples over a variable list | Q9.1 Q7 | `fldmod1(k, 3)` for the grid position |\n| Guarded string-to-number parsing | Q9.2 Q1 | `tryparse` plus a plausible-range check |\n| Dates from separate month and year | Q9.2 Q1 | `Date(year, month)`, `Dates.value(a - b)` |\n| A non-Gregorian month name | Q9.2 Q1 | map `\"Pagume\"` to September, not to `missing` |\n| Log scales on both axes | Q9.2 Q2 | `xscale = log10, yscale = log10` |\n| Quartiles beside a skewed mean | Q9.2 Q2 | `quantile(v, [0.25, 0.5, 0.75])` |\n| Every row of a long table | Q9.1 Q1 | `show_all(df)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}