{
  "hash": "ac5a8c749a5c3ddb83434b01a35de619",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"10. Characteristics of banking systems around the world\"\nsubtitle: \"Depth, access and stability across 200 countries, and what a weighted average changes\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nThe World Bank's Global Financial Development Database: 11,330 country-years from 1960 to 2014,\n110 indicators. This project takes eight of them, covering how **deep** a banking system is, how\nmuch **access** people have to it, and how **stable** it is — then asks whether stability\nimproved after 2008.\n\n- **[Part 10.1](#part-10.1)** — summarizing the data\n- **[Part 10.2](#part-10.2)** — financial stability before and after the 2008 crisis\n\nNew concepts: **box and whisker plots**, **weighted averages**, and **Winsorization** as a way\nto keep extreme observations without letting them dominate. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/10-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/10-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/10-04.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames\nusing Statistics\nusing HypothesisTests\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {.callout-important}\n## The file the book specifies is no longer downloadable\n\nThe book sends you to the World Bank's Global Financial Development Database page and says to\nclick **\"June 2017 Version\"**. That link is still on the page and still points at\n`GlobalFinancialDevelopmentDatabaseJune2017.xlsx` — but the file has been removed. The request\nreturns the World Bank's 404 page as a 100 KB HTML body, so a naive download produces an HTML\nfile with an `.xlsx` extension and the failure only surfaces when something tries to read it.\nThe November 2013 link is dead the same way; November 2021 and September 2022 still work.\n\nThe copy here is the **1 April 2022 Internet Archive capture**, requested in `id_` form so the\nbytes are the original file rather than a rewritten page. An April 2023 revisit carries the same\nWARC digest, so the capture is stable.\n\nUsing a current version was the alternative, and the book warns results differ between versions.\nSince every figure below is checked against the published solutions, the specified vintage is\nwhat makes those checks mean anything. This is the second dataset in this repository whose\nofficial source has gone — [Project 5](../05-measuring-inequality/index.qmd)'s was the first.\n:::\n\n::: {#cell-read-gfdd .cell execution_count=1}\n``` {.julia .cell-code}\npath = rawpath(\"10\", \"gfdd-june-2017.xlsx\")\n\n# The \"June 2017\" release contains tabs named \"Data - May 2017\" and \"Data - June 2016\".\n# The book uses the June 2016 tab, which is the one covering 1960-2014.\ngfdd = DataFrame(XLSX.readtable(path, \"Data - June 2016\"; infer_eltypes = true))\nrename!(gfdd, \"Income Group\" => :income)\n\nconst INDICATORS = [\n    (\"GFDD.DI.01\", \"Depth\", \"Private credit by deposit money banks to GDP (%)\"),\n    (\"GFDD.DI.02\", \"Depth\", \"Deposit money banks' assets to GDP (%)\"),\n    (\"GFDD.AI.01\", \"Access\", \"Bank accounts per 1,000 adults\"),\n    (\"GFDD.AI.02\", \"Access\", \"Bank branches per 100,000 adults\"),\n    (\"GFDD.AI.03\", \"Access\", \"Firms with a bank loan or line of credit (%)\"),\n    (\"GFDD.AI.04\", \"Access\", \"Small firms with a bank loan or line of credit (%)\"),\n    (\"GFDD.SI.01\", \"Stability\", \"Bank Z-score\"),\n    (\"GFDD.SI.05\", \"Stability\", \"Bank regulatory capital to risk-weighted assets (%)\"),\n]\nconst CODES = first.(INDICATORS)\n\n# Numeric columns arrive as `Any` because blanks are interleaved with numbers.\nnum(x) = x === missing ? missing : x isa Number ? Float64(x) : tryparse(Float64, string(x))\nfor col in vcat(CODES, \"SP.POP.TOTL\", \"Year\")\n    gfdd[!, col] = num.(gfdd[!, col])\nend\n\n(rows = nrow(gfdd), columns = ncol(gfdd),\n years = extrema(skipmissing(gfdd.Year)),\n countries = length(unique(gfdd.Country)))\n```\n\n::: {#read-gfdd .cell-output .cell-output-display execution_count=1}\n```\n(rows = 11330, columns = 122, years = (1960.0, 2014.0), countries = 206)\n```\n:::\n:::\n\n\n\n::: {#cell-coverage .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(code = CODES,\n          category = [c for (_, c, _) in INDICATORS],\n          indicator = [d for (_, _, d) in INDICATORS],\n          observations = [count(!ismissing, gfdd[!, c]) for c in CODES],\n          coverage_pct = [round(100 * count(!ismissing, gfdd[!, c]) / nrow(gfdd), digits = 1)\n                          for c in CODES])\n```\n\n::: {#coverage .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">code</th><th style = \"text-align: left;\">category</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">observations</th><th style = \"text-align: left;\">coverage_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">GFDD.DI.01</td><td style = \"text-align: left;\">Depth</td><td style = \"text-align: left;\">Private credit by deposit money banks to GDP (%)</td><td style = \"text-align: right;\">7575</td><td style = \"text-align: right;\">66.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">GFDD.DI.02</td><td style = \"text-align: left;\">Depth</td><td style = \"text-align: left;\">Deposit money banks&apos; assets to GDP (%)</td><td style = \"text-align: right;\">7600</td><td style = \"text-align: right;\">67.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">GFDD.AI.01</td><td style = \"text-align: left;\">Access</td><td style = \"text-align: left;\">Bank accounts per 1,000 adults</td><td style = \"text-align: right;\">918</td><td style = \"text-align: right;\">8.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">GFDD.AI.02</td><td style = \"text-align: left;\">Access</td><td style = \"text-align: left;\">Bank branches per 100,000 adults</td><td style = \"text-align: right;\">1955</td><td style = \"text-align: right;\">17.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">GFDD.AI.03</td><td style = \"text-align: left;\">Access</td><td style = \"text-align: left;\">Firms with a bank loan or line of credit (%)</td><td style = \"text-align: right;\">220</td><td style = \"text-align: right;\">1.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">GFDD.AI.04</td><td style = \"text-align: left;\">Access</td><td style = \"text-align: left;\">Small firms with a bank loan or line of credit (%)</td><td style = \"text-align: right;\">220</td><td style = \"text-align: right;\">1.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">GFDD.SI.01</td><td style = \"text-align: left;\">Stability</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: right;\">3244</td><td style = \"text-align: right;\">28.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">GFDD.SI.05</td><td style = \"text-align: left;\">Stability</td><td style = \"text-align: left;\">Bank regulatory capital to risk-weighted assets (%)</td><td style = \"text-align: right;\">1728</td><td style = \"text-align: right;\">15.3</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Coverage is the first thing to notice and it constrains everything after.** The two depth\nindicators are recorded for a large share of country-years; the two firm-level access indicators\nare recorded for very few, because they come from enterprise surveys run occasionally rather\nthan from banking returns collected annually. Any comparison using `GFDD.AI.03` or `GFDD.AI.04`\nis working with a fraction of the sample, and not a random fraction.\n\n## Part 10.1 — Summarizing the data {#part-10.1}\n\n### Q1. What each indicator measures, and where it misleads {#p1-q1}\n\nThe workbook's own definitions:\n\n::: {#cell-definitions .cell execution_count=1}\n``` {.julia .cell-code}\ndefinitions = DataFrame(XLSX.readtable(path, \"Definitions and Sources\"))\nwanted = definitions[in(CODES).(coalesce.(definitions[!, 1], \"\")), :]\nselect(wanted, 1 => :code, 3 => :short_description)\n```\n\n::: {#definitions .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>0×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">code</th><th style = \"text-align: left;\">short_description</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead></table></div>\n```\n:::\n:::\n\n\n\n**Depth.**\n\n- **Private credit by deposit money banks to GDP** is the standard measure of financial depth:\n  outstanding credit from resident deposit-taking banks to the non-financial private sector,\n  scaled by GDP. It is a good measure because it captures the function that matters — moving\n  savings to private borrowers — rather than the mere existence of institutions. Its weakness is\n  **institutional coverage**: where the state provides credit directly or owns the enterprises\n  doing the borrowing, real intermediation is happening that this indicator does not count, so it\n  understates depth in state-dominated economies.\n- **Deposit money banks' assets to GDP** is broader, and the breadth cuts both ways. It includes\n  lending to state-owned enterprises, which fixes part of the problem above. But it also counts\n  assets that are not lending to the economy at all — most importantly **government bonds**. A\n  banking system that funds the state by holding its debt looks as deep on this measure as one\n  funding firms, which are very different economic functions.\n\n**Access.**\n\n- **Bank accounts per 1,000 adults** is the most direct measure of whether people are inside the\n  financial system. Two problems: **one person can hold several accounts**, so the numerator is\n  accounts rather than people, and the denominator effect varies with how many accounts a typical\n  customer holds — which itself differs by country. Cross-country differences may reflect banking\n  conventions rather than access.\n- **Bank branches per 100,000 adults** measures physical reach. Its weakness is **distribution**:\n  the same branch count is very different if the branches are spread across a country or\n  clustered in the capital, and the indicator cannot tell them apart. It is also increasingly\n  **obsolete as a measure** — a country with widespread mobile and online banking needs fewer\n  branches, so falling branch density can mean improving access.\n- **Firms with a bank loan or line of credit** narrows to a group with a clear demand for\n  credit, which removes some of the taste variation that troubles household measures. It remains\n  a mix of supply and demand: a low value is consistent with firms being refused *or* not\n  needing to borrow.\n- **Small firms with a bank loan or line of credit** is the policy-relevant version of the\n  same, because small and new firms are where credit rationing bites hardest — they have the\n  least collateral and no track record. It is the closest indicator here to what\n  [Project 9](../09-credit-excluded/index.qmd) measured at the household level.\n\n**Stability.**\n\n- **Bank Z-score** combines capitalisation, return and the volatility of returns into an\n  estimated distance from default, asset-weighted across banks. Higher is more stable. It is a\n  genuine risk measure rather than a balance-sheet ratio, which is its strength. Its blind spot\n  is **interconnectedness**: it scores each bank in isolation, so a system of individually sound\n  but mutually exposed banks scores well, and that is precisely the configuration that failed in\n  2008.\n- **Bank regulatory capital to risk-weighted assets** is the regulatory solvency ratio, the\n  inverse of leverage. More capital against risk-weighted assets means more capacity to absorb\n  losses. Its weakness is that **the risk weights are chosen**, and both the weights and the\n  accounting behind them differ across countries and over time, so the ratio is not comparable\n  across borders in the way its units suggest. It is also gameable: the same portfolio can be\n  made to look better capitalised by reclassifying assets.\n\n### Q2. Distributions and outliers {#p1-q2}\n\n::: {#tbl-quartiles .cell tbl-cap='Distribution of each indicator across all country-years, with the count of observations beyond 1.5 times the interquartile range from the nearer quartile — the convention a box plot uses to draw an outlier.' execution_count=1}\n``` {.julia .cell-code}\nquartile_table = DataFrame(indicator = String[], n = Int[], min = Float64[], q1 = Float64[],\n                           median = Float64[], q3 = Float64[], max = Float64[],\n                           outliers = Int[], outlier_pct = Float64[])\nfor (code, _, desc) in INDICATORS\n    v = Float64.(collect(skipmissing(gfdd[!, code])))\n    q1, q3 = quantile(v, [0.25, 0.75])\n    fence = 1.5 * (q3 - q1)\n    n_out = count(x -> x < q1 - fence || x > q3 + fence, v)\n    push!(quartile_table, (desc, length(v), round(minimum(v), digits = 2),\n                           round(q1, digits = 2), round(median(v), digits = 2),\n                           round(q3, digits = 2), round(maximum(v), digits = 2),\n                           n_out, round(100 * n_out / length(v), digits = 1)))\nend\nquartile_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×9 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">q1</th><th style = \"text-align: left;\">median</th><th style = \"text-align: left;\">q3</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">outliers</th><th style = \"text-align: left;\">outlier_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Private credit by deposit money banks to GDP (%)</td><td style = \"text-align: right;\">7575</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">12.32</td><td style = \"text-align: right;\">23.62</td><td style = \"text-align: right;\">46.02</td><td style = \"text-align: right;\">262.46</td><td style = \"text-align: right;\">435</td><td style = \"text-align: right;\">5.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Deposit money banks&apos; assets to GDP (%)</td><td style = \"text-align: right;\">7600</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">16.28</td><td style = \"text-align: right;\">30.7</td><td style = \"text-align: right;\">56.93</td><td style = \"text-align: right;\">263.13</td><td style = \"text-align: right;\">383</td><td style = \"text-align: right;\">5.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Bank accounts per 1,000 adults</td><td style = \"text-align: right;\">918</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">92.16</td><td style = \"text-align: right;\">328.41</td><td style = \"text-align: right;\">730.19</td><td style = \"text-align: right;\">3368.39</td><td style = \"text-align: right;\">38</td><td style = \"text-align: right;\">4.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Bank branches per 100,000 adults</td><td style = \"text-align: right;\">1955</td><td style = \"text-align: right;\">0.13</td><td style = \"text-align: right;\">4.62</td><td style = \"text-align: right;\">12.78</td><td style = \"text-align: right;\">24.76</td><td style = \"text-align: right;\">285.0</td><td style = \"text-align: right;\">108</td><td style = \"text-align: right;\">5.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Firms with a bank loan or line of credit (%)</td><td style = \"text-align: right;\">220</td><td style = \"text-align: right;\">2.8</td><td style = \"text-align: right;\">19.05</td><td style = \"text-align: right;\">34.6</td><td style = \"text-align: right;\">48.92</td><td style = \"text-align: right;\">79.6</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Small firms with a bank loan or line of credit (%)</td><td style = \"text-align: right;\">220</td><td style = \"text-align: right;\">1.9</td><td style = \"text-align: right;\">14.92</td><td style = \"text-align: right;\">26.8</td><td style = \"text-align: right;\">41.28</td><td style = \"text-align: right;\">72.5</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: right;\">3244</td><td style = \"text-align: right;\">-21.22</td><td style = \"text-align: right;\">5.82</td><td style = \"text-align: right;\">9.68</td><td style = \"text-align: right;\">15.3</td><td style = \"text-align: right;\">89.93</td><td style = \"text-align: right;\">110</td><td style = \"text-align: right;\">3.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Bank regulatory capital to risk-weighted assets (%)</td><td style = \"text-align: right;\">1728</td><td style = \"text-align: right;\">1.8</td><td style = \"text-align: right;\">12.6</td><td style = \"text-align: right;\">15.15</td><td style = \"text-align: right;\">18.1</td><td style = \"text-align: right;\">48.6</td><td style = \"text-align: right;\">94</td><td style = \"text-align: right;\">5.4</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-boxplots .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (960, 620))\nfor (k, (code, category, desc)) in enumerate(INDICATORS)\n    row, col = fldmod1(k, 4)\n    v = Float64.(collect(skipmissing(gfdd[!, code])))\n    ax = Axis(fig[row, col];\n              title = \"$code\\n$category\", titlesize = 11,\n              xticksvisible = false, xticklabelsvisible = false,\n              xgridvisible = false)\n    boxplot!(ax, fill(1, length(v)), v;\n             width = 0.5, color = series_color(1), whiskerwidth = 0.4,\n             mediancolor = SURFACE, markersize = 4,\n             outliercolor = (series_color(1), 0.35), strokecolor = SURFACE, strokewidth = 0)\n    hidexdecorations!(ax; grid = true)\nend\nLabel(fig[0, 1:4], \"Every indicator is right-skewed with a long upper tail\";\n      fontsize = 14, color = INK, halign = :left, padding = (8, 0, 0, 0))\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Box and whisker plot for each indicator, outliers shown. One panel per indicator rather than one axis for all eight, because the indicators are measured in different units and on ranges differing by three orders of magnitude — a shared axis would flatten six of them into a line. One series throughout, so one colour.](index_files/figure-html/fig-boxplots-output-1.svg){#fig-boxplots}\n:::\n:::\n\n\n\n**Every one of the eight is right-skewed**, and for six of them the box is narrow relative to the\nwhiskers — most country-years cluster and a minority sit far above. The outlier counts in the\ntable put numbers on it.\n\n**The two exceptions are the firm-level access indicators**, which have far fewer flagged\noutliers. That is not because firm credit is more evenly distributed but because those\nindicators are **bounded percentages** — a share of firms cannot exceed 100 — whereas bank\naccounts per 1,000 adults and assets-to-GDP have no ceiling. A bounded measure cannot produce a\nlong tail.\n\n**Why so many outliers.** Three distinct causes, worth separating because they call for\ndifferent responses:\n\n1. **Genuine structural differences.** Financial centres — Luxembourg, Hong Kong, Switzerland —\n   host banking systems sized for the world rather than for their own economies, so\n   credit-to-GDP ratios of several hundred per cent are real, not errors. Scaling by domestic GDP\n   is the problem, not the data.\n2. **Different banking technology.** A country where most transactions are mobile or online\n   needs few branches; a cash economy needs many. Both extremes appear as outliers on branch\n   density while describing normal arrangements.\n3. **Measurement and definition.** The capital ratio depends on national accounting and on\n   chosen risk weights, so some spread is the measurement apparatus rather than the thing\n   measured.\n\nOnly the third is an argument for excluding observations. The first two are the variation the\nproject is about, which is why [Q5](#p1-q5) uses Winsorization — pulling the tails in while\nkeeping every country — rather than dropping anything.\n\n### Q3. One depth and one access indicator over time {#p1-q3}\n\nFollowing the book's examples: **deposit money banks' assets to GDP** for depth and **bank\naccounts per 1,000 adults** for access, 2000–2014.\n\n**(a) By income group and by region.**\n\n::: {#tbl-depth-income .cell tbl-cap='Deposit money banks\\' assets to GDP (%), mean by income group, with the number of countries reporting. Reproduces the book\\'s Solution figure 10.10.' execution_count=1}\n``` {.julia .cell-code}\nconst INCOME_ORDER = [\"Low income\", \"Lower middle income\", \"Upper middle income\",\n                      \"High income: nonOECD\", \"High income: OECD\"]\n\nfunction group_means(indicator, groupcol, groups, years)\n    out = DataFrame(year = collect(years))\n    for g in groups\n        means, counts = Float64[], Int[]\n        for y in years\n            v = Float64[x for x in gfdd[coalesce.(gfdd[!, groupcol] .== g, false) .&\n                                        coalesce.(gfdd.Year .== y, false), indicator]\n                        if x !== missing]\n            push!(means, isempty(v) ? NaN : round(mean(v), digits = 2))\n            push!(counts, length(v))\n        end\n        out[!, g] = means\n        out[!, \"n ($g)\"] = counts\n    end\n    return out\nend\n\ndepth_income = group_means(\"GFDD.DI.02\", :income, INCOME_ORDER, 2000:2014)\nshow_all(select(depth_income, :year, INCOME_ORDER...))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>15×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">Low income</th><th style = \"text-align: left;\">Lower middle income</th><th style = \"text-align: left;\">Upper middle income</th><th style = \"text-align: left;\">High income: nonOECD</th><th style = \"text-align: left;\">High income: OECD</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2000</td><td style = \"text-align: right;\">15.26</td><td style = \"text-align: right;\">28.1</td><td style = \"text-align: right;\">45.6</td><td style = \"text-align: right;\">63.8</td><td style = \"text-align: right;\">89.67</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2001</td><td style = \"text-align: right;\">14.96</td><td style = \"text-align: right;\">27.85</td><td style = \"text-align: right;\">46.79</td><td style = \"text-align: right;\">67.17</td><td style = \"text-align: right;\">90.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2002</td><td style = \"text-align: right;\">14.98</td><td style = \"text-align: right;\">27.61</td><td style = \"text-align: right;\">45.17</td><td style = \"text-align: right;\">68.69</td><td style = \"text-align: right;\">91.16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">2003</td><td style = \"text-align: right;\">15.71</td><td style = \"text-align: right;\">27.76</td><td style = \"text-align: right;\">44.8</td><td style = \"text-align: right;\">67.29</td><td style = \"text-align: right;\">92.75</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">2004</td><td style = \"text-align: right;\">15.2</td><td style = \"text-align: right;\">28.61</td><td style = \"text-align: right;\">44.92</td><td style = \"text-align: right;\">63.35</td><td style = \"text-align: right;\">94.17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2005</td><td style = \"text-align: right;\">15.25</td><td style = \"text-align: right;\">30.36</td><td style = \"text-align: right;\">46.68</td><td style = \"text-align: right;\">62.19</td><td style = \"text-align: right;\">98.79</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2006</td><td style = \"text-align: right;\">15.86</td><td style = \"text-align: right;\">30.35</td><td style = \"text-align: right;\">48.37</td><td style = \"text-align: right;\">62.77</td><td style = \"text-align: right;\">105.78</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2007</td><td style = \"text-align: right;\">16.57</td><td style = \"text-align: right;\">32.02</td><td style = \"text-align: right;\">50.24</td><td style = \"text-align: right;\">65.25</td><td style = \"text-align: right;\">110.92</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">2008</td><td style = \"text-align: right;\">18.28</td><td style = \"text-align: right;\">34.73</td><td style = \"text-align: right;\">54.25</td><td style = \"text-align: right;\">68.73</td><td style = \"text-align: right;\">117.73</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">2009</td><td style = \"text-align: right;\">19.11</td><td style = \"text-align: right;\">37.65</td><td style = \"text-align: right;\">58.59</td><td style = \"text-align: right;\">79.37</td><td style = \"text-align: right;\">123.16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">20.3</td><td style = \"text-align: right;\">37.23</td><td style = \"text-align: right;\">58.52</td><td style = \"text-align: right;\">78.77</td><td style = \"text-align: right;\">120.75</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">21.58</td><td style = \"text-align: right;\">37.88</td><td style = \"text-align: right;\">58.91</td><td style = \"text-align: right;\">78.0</td><td style = \"text-align: right;\">118.81</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">21.19</td><td style = \"text-align: right;\">38.63</td><td style = \"text-align: right;\">59.95</td><td style = \"text-align: right;\">78.85</td><td style = \"text-align: right;\">117.64</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">22.87</td><td style = \"text-align: right;\">40.28</td><td style = \"text-align: right;\">61.48</td><td style = \"text-align: right;\">80.12</td><td style = \"text-align: right;\">115.07</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">23.56</td><td style = \"text-align: right;\">42.46</td><td style = \"text-align: right;\">64.68</td><td style = \"text-align: right;\">83.81</td><td style = \"text-align: right;\">112.49</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#tbl-depth-income-n .cell tbl-cap='Countries reporting deposit money banks\\' assets to GDP, by income group.' execution_count=1}\n``` {.julia .cell-code}\nshow_all(select(depth_income, :year, [\"n ($g)\" for g in INCOME_ORDER]...))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>15×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">n (Low income)</th><th style = \"text-align: left;\">n (Lower middle income)</th><th style = \"text-align: left;\">n (Upper middle income)</th><th style = \"text-align: left;\">n (High income: nonOECD)</th><th style = \"text-align: left;\">n (High income: OECD)</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2000</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">44</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2001</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2002</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">2003</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">2004</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2005</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2006</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2007</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">2008</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">2009</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">30</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">30</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">23</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">23</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">44</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">29</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nFifteen years by five groups, and the published table reproduces throughout **except one cell**.\n\n::: {.callout-note}\n## One cell differs from the published table\n\nThe book's Solution figure 10.10 gives **63.89** for High income: nonOECD in 2000. This gives\n**63.80**, from the same 25 countries.\n\n::: {#cell-cell-check .cell execution_count=1}\n``` {.julia .cell-code}\nh = gfdd[coalesce.(gfdd.income .== \"High income: nonOECD\", false) .&\n         coalesce.(gfdd.Year .== 2000, false) .& .!ismissing.(gfdd[!, \"GFDD.DI.02\"]), :]\nvalues = Float64.(h[!, \"GFDD.DI.02\"])\n\n(countries = length(values),\n sum = round(sum(values), digits = 3),\n mean = round(mean(values), digits = 4),\n sum_needed_for_63_89 = round(63.89 * length(values), digits = 3))\n```\n\n::: {#cell-check .cell-output .cell-output-display execution_count=1}\n```\n(countries = 25, sum = 1595.04, mean = 63.8016, sum_needed_for_63_89 = 1597.25)\n```\n:::\n:::\n\n\n\nSame count of countries, and 2001 through 2014 all reproduce exactly, as do every other group's\n2000 value. An isolated 0.09 in one cell of a 75-cell table, with the neighbouring years correct,\nis most consistent with a transcription slip in the published figure — but the cause cannot be\nestablished from here, so it is reported rather than explained.\n:::\n\n::: {#tbl-access-region .cell tbl-cap='Bank accounts per 1,000 adults, simple mean by region. North America reports no values for this indicator in any year.' execution_count=1}\n``` {.julia .cell-code}\nconst REGIONS = sort(unique(skipmissing(gfdd.Region)))\naccess_region = group_means(\"GFDD.AI.01\", :Region, REGIONS, 2000:2014)\nshow_all(select(access_region, :year, REGIONS...))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>15×8 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">East Asia &amp; Pacific</th><th style = \"text-align: left;\">Europe &amp; Central Asia</th><th style = \"text-align: left;\">Latin America &amp; Caribbean</th><th style = \"text-align: left;\">Middle East &amp; North Africa</th><th style = \"text-align: left;\">North America</th><th style = \"text-align: left;\">South Asia</th><th style = \"text-align: left;\">Sub-Saharan Africa</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2000</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2001</td><td style = \"text-align: right;\">265.15</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">8.12</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2002</td><td style = \"text-align: right;\">285.32</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">29.19</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">2003</td><td style = \"text-align: right;\">366.82</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">29.65</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">2004</td><td style = \"text-align: right;\">580.53</td><td style = \"text-align: right;\">537.83</td><td style = \"text-align: right;\">521.01</td><td style = \"text-align: right;\">368.07</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">425.56</td><td style = \"text-align: right;\">126.12</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2005</td><td style = \"text-align: right;\">575.46</td><td style = \"text-align: right;\">843.54</td><td style = \"text-align: right;\">473.32</td><td style = \"text-align: right;\">380.89</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">452.45</td><td style = \"text-align: right;\">139.72</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2006</td><td style = \"text-align: right;\">516.7</td><td style = \"text-align: right;\">919.94</td><td style = \"text-align: right;\">528.12</td><td style = \"text-align: right;\">388.46</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">487.81</td><td style = \"text-align: right;\">145.62</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2007</td><td style = \"text-align: right;\">557.99</td><td style = \"text-align: right;\">982.22</td><td style = \"text-align: right;\">600.95</td><td style = \"text-align: right;\">420.53</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">525.75</td><td style = \"text-align: right;\">150.74</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">2008</td><td style = \"text-align: right;\">713.03</td><td style = \"text-align: right;\">1092.63</td><td style = \"text-align: right;\">651.44</td><td style = \"text-align: right;\">463.48</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">458.24</td><td style = \"text-align: right;\">167.85</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">2009</td><td style = \"text-align: right;\">738.29</td><td style = \"text-align: right;\">1053.4</td><td style = \"text-align: right;\">695.64</td><td style = \"text-align: right;\">523.62</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">428.6</td><td style = \"text-align: right;\">185.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">764.47</td><td style = \"text-align: right;\">1116.05</td><td style = \"text-align: right;\">750.63</td><td style = \"text-align: right;\">523.34</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">431.42</td><td style = \"text-align: right;\">216.89</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">973.88</td><td style = \"text-align: right;\">1159.48</td><td style = \"text-align: right;\">647.61</td><td style = \"text-align: right;\">531.78</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">545.29</td><td style = \"text-align: right;\">235.62</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">796.89</td><td style = \"text-align: right;\">1156.74</td><td style = \"text-align: right;\">695.38</td><td style = \"text-align: right;\">536.23</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">560.5</td><td style = \"text-align: right;\">277.71</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">744.74</td><td style = \"text-align: right;\">1097.12</td><td style = \"text-align: right;\">730.9</td><td style = \"text-align: right;\">529.63</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">580.13</td><td style = \"text-align: right;\">320.58</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">863.2</td><td style = \"text-align: right;\">1161.06</td><td style = \"text-align: right;\">797.02</td><td style = \"text-align: right;\">542.29</td><td style = \"text-align: right;\">NaN</td><td style = \"text-align: right;\">672.26</td><td style = \"text-align: right;\">413.4</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**(b) The trends.**\n\n::: {#cell-fig-depth-trend .cell execution_count=1}\n``` {.julia .cell-code}\nramp = sequential_steps(length(INCOME_ORDER))\nyears = depth_income.year\n\nfig = Figure(size = (920, 520))\nax = Axis(fig[1, 1];\n          title = \"The gap between rich and poor banking systems widened, then stalled\",\n          xlabel = \"Year\", ylabel = \"Deposit money banks' assets to GDP (%)\",\n          limits = ((1999.5, 2019.5), (0, 130)))\n\nfor (j, g) in enumerate(INCOME_ORDER)\n    v = depth_income[!, g]\n    lines!(ax, years, v; color = ramp[j], linewidth = 2.5, label = g)\n    text!(ax, 2014.4, v[end]; text = g, fontsize = 10,\n          align = (:left, :center), color = INK_SECONDARY)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Deposit money banks' assets to GDP by income group. Income group is an *ordered* variable, so this uses a single-hue sequential ramp from light (low income) to dark (high income) rather than five categorical hues — the ordering is information, and a categorical palette would discard it. Each line is also labelled at its right end, so identity never rests on colour alone.](index_files/figure-html/fig-depth-trend-output-1.svg){#fig-depth-trend}\n:::\n:::\n\n\n\n::: {#cell-fig-access-trend .cell execution_count=1}\n``` {.julia .cell-code}\nplotted = [r for r in REGIONS if !all(isnan, access_region[!, r])]\n\nfig = Figure(size = (960, 520))\nfor (k, r) in enumerate(plotted)\n    row, col = fldmod1(k, 3)\n    ax = Axis(fig[row, col];\n              title = r, titlesize = 11,\n              xlabel = row == 2 ? \"Year\" : \"\",\n              ylabel = col == 1 ? \"Accounts per 1,000 adults\" : \"\",\n              limits = ((1999.5, 2014.5), (0, 1300)))\n    for other in plotted\n        lines!(ax, years, access_region[!, other]; color = GRIDLINE, linewidth = 1.5)\n    end\n    lines!(ax, years, access_region[!, r]; color = series_color(1), linewidth = 2.5)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Bank accounts per 1,000 adults by region, one panel per region with every other region drawn in grey behind it. Small multiples rather than six coloured lines: six unordered categories sit at the edge of what a single axis can distinguish, and faceting keeps each series to one colour with the others as context.](index_files/figure-html/fig-access-trend-output-1.svg){#fig-access-trend}\n:::\n:::\n\n\n\n**Depth.** The ordering is exactly what the income ranking predicts, and it is remarkably stable:\nhigh-income OECD systems hold bank assets worth around 90–120% of GDP throughout, low-income\nsystems around 15–20%. **The ratio between top and bottom is roughly six to one and does not\nclose over fifteen years.**\n\nThe one visible dynamic is the crisis. High-income OECD depth rises through the 2000s, peaks\naround 2009, and then flattens or falls — consistent with balance sheets expanding into 2008 and\ndeleveraging after. The low-income series does not show that shape at all, which is the\nsubstantive point: **these systems were not deep enough to be part of the crisis**.\n\n**Access.** The regional picture is one of broad convergence from very different starting points.\nSub-Saharan Africa more than triples over the period. Europe and Central Asia rises fastest in\nabsolute terms. Every region rises, and none reverses.\n\nTwo cautions the tables make visible and the charts hide:\n\n- **North America has no observations at all** for bank accounts per 1,000 adults, in any year.\n  Its row is absent rather than zero, and a chart that omitted the table would suggest the region\n  had no bank accounts.\n- **The country counts move between years**, so part of any year-on-year change is composition\n  rather than change within countries. A region's mean can rise because a well-banked country\n  started reporting.\n\n### Q4. Weighted against simple averages {#p1-q4}\n\nA simple average across countries treats Luxembourg and China as equally informative about the\nregion. Weighting by population asks a different question: what is the average *person*'s access?\n\n**(a) and (b) Constructing the weights**, using population only over countries with a\nnon-missing indicator value, so the weights sum to one within each region-year.\n\n::: {#cell-weights .cell execution_count=1}\n``` {.julia .cell-code}\nfunction weighted_by_population(indicator, groupcol, group, year)\n    mask = coalesce.(gfdd[!, groupcol] .== group, false) .&\n           coalesce.(gfdd.Year .== year, false) .&\n           .!ismissing.(gfdd[!, indicator]) .& .!ismissing.(gfdd[!, \"SP.POP.TOTL\"])\n    sub = gfdd[mask, :]\n    nrow(sub) == 0 && return (value = NaN, n = 0, weight_sum = NaN)\n    w = Float64.(sub[!, \"SP.POP.TOTL\"])\n    w ./= sum(w)\n    return (value = sum(w .* Float64.(sub[!, indicator])), n = nrow(sub), weight_sum = sum(w))\nend\n\n# The check the question asks for: weights must sum to 1 within a region-year.\ncheck = weighted_by_population(\"GFDD.AI.01\", :Region, \"Europe & Central Asia\", 2010)\n(countries = check.n, weight_sum = check.weight_sum, weighted_average = round(check.value, digits = 2))\n```\n\n::: {#weights .cell-output .cell-output-display execution_count=1}\n```\n(countries = 15, weight_sum = 1.0, weighted_average = 1371.62)\n```\n:::\n:::\n\n\n\n**(c) The weighted averages.**\n\n::: {#tbl-weighted .cell tbl-cap='Population-weighted mean bank accounts per 1,000 adults, by region. Reproduces the book\\'s Solution figure 10.17. North America is absent because the indicator has no observations there.' execution_count=1}\n``` {.julia .cell-code}\nweighted_table = DataFrame(year = collect(2004:2014))\nfor r in plotted\n    weighted_table[!, r] = [round(weighted_by_population(\"GFDD.AI.01\", :Region, r, y).value,\n                                 digits = 2) for y in 2004:2014]\nend\nshow_all(weighted_table)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>11×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">East Asia &amp; Pacific</th><th style = \"text-align: left;\">Europe &amp; Central Asia</th><th style = \"text-align: left;\">Latin America &amp; Caribbean</th><th style = \"text-align: left;\">Middle East &amp; North Africa</th><th style = \"text-align: left;\">South Asia</th><th style = \"text-align: left;\">Sub-Saharan Africa</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2004</td><td style = \"text-align: right;\">253.86</td><td style = \"text-align: right;\">637.4</td><td style = \"text-align: right;\">504.48</td><td style = \"text-align: right;\">301.03</td><td style = \"text-align: right;\">529.82</td><td style = \"text-align: right;\">64.48</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2005</td><td style = \"text-align: right;\">336.63</td><td style = \"text-align: right;\">1262.14</td><td style = \"text-align: right;\">471.72</td><td style = \"text-align: right;\">324.82</td><td style = \"text-align: right;\">531.27</td><td style = \"text-align: right;\">76.57</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2006</td><td style = \"text-align: right;\">81.43</td><td style = \"text-align: right;\">1324.44</td><td style = \"text-align: right;\">484.82</td><td style = \"text-align: right;\">351.77</td><td style = \"text-align: right;\">549.06</td><td style = \"text-align: right;\">79.62</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">2007</td><td style = \"text-align: right;\">85.34</td><td style = \"text-align: right;\">1380.43</td><td style = \"text-align: right;\">520.49</td><td style = \"text-align: right;\">393.35</td><td style = \"text-align: right;\">573.51</td><td style = \"text-align: right;\">132.21</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">2008</td><td style = \"text-align: right;\">87.54</td><td style = \"text-align: right;\">1525.15</td><td style = \"text-align: right;\">561.82</td><td style = \"text-align: right;\">418.4</td><td style = \"text-align: right;\">614.92</td><td style = \"text-align: right;\">149.09</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2009</td><td style = \"text-align: right;\">90.62</td><td style = \"text-align: right;\">1501.88</td><td style = \"text-align: right;\">633.35</td><td style = \"text-align: right;\">436.77</td><td style = \"text-align: right;\">227.03</td><td style = \"text-align: right;\">195.23</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">94.6</td><td style = \"text-align: right;\">1371.62</td><td style = \"text-align: right;\">686.92</td><td style = \"text-align: right;\">431.48</td><td style = \"text-align: right;\">267.47</td><td style = \"text-align: right;\">220.34</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2011</td><td style = \"text-align: right;\">105.83</td><td style = \"text-align: right;\">1419.89</td><td style = \"text-align: right;\">688.62</td><td style = \"text-align: right;\">420.16</td><td style = \"text-align: right;\">334.88</td><td style = \"text-align: right;\">236.72</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">2012</td><td style = \"text-align: right;\">96.85</td><td style = \"text-align: right;\">1269.52</td><td style = \"text-align: right;\">736.57</td><td style = \"text-align: right;\">426.43</td><td style = \"text-align: right;\">373.07</td><td style = \"text-align: right;\">277.92</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">2013</td><td style = \"text-align: right;\">101.48</td><td style = \"text-align: right;\">1043.82</td><td style = \"text-align: right;\">755.75</td><td style = \"text-align: right;\">427.68</td><td style = \"text-align: right;\">399.85</td><td style = \"text-align: right;\">309.17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">106.33</td><td style = \"text-align: right;\">1059.82</td><td style = \"text-align: right;\">780.49</td><td style = \"text-align: right;\">524.85</td><td style = \"text-align: right;\">411.35</td><td style = \"text-align: right;\">350.8</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery value matches the published table.\n\n**(d) Comparison with the simple averages.**\n\n::: {#tbl-weighted-vs-simple .cell tbl-cap='Weighted minus simple mean bank accounts per 1,000 adults, 2014. A negative gap means the region\\'s populous countries have poorer access than its small ones.' execution_count=1}\n``` {.julia .cell-code}\ncomparison = DataFrame(region = plotted)\ncomparison.simple = [round(access_region[access_region.year .== 2014, r][1], digits = 2)\n                     for r in plotted]\ncomparison.weighted = [weighted_table[weighted_table.year .== 2014, r][1] for r in plotted]\ncomparison.gap = round.(comparison.weighted .- comparison.simple, digits = 2)\nsort!(comparison, :gap)\ncomparison\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">region</th><th style = \"text-align: left;\">simple</th><th style = \"text-align: left;\">weighted</th><th style = \"text-align: left;\">gap</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">East Asia &amp; Pacific</td><td style = \"text-align: right;\">863.2</td><td style = \"text-align: right;\">106.33</td><td style = \"text-align: right;\">-756.87</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">South Asia</td><td style = \"text-align: right;\">672.26</td><td style = \"text-align: right;\">411.35</td><td style = \"text-align: right;\">-260.91</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Europe &amp; Central Asia</td><td style = \"text-align: right;\">1161.06</td><td style = \"text-align: right;\">1059.82</td><td style = \"text-align: right;\">-101.24</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Sub-Saharan Africa</td><td style = \"text-align: right;\">413.4</td><td style = \"text-align: right;\">350.8</td><td style = \"text-align: right;\">-62.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Middle East &amp; North Africa</td><td style = \"text-align: right;\">542.29</td><td style = \"text-align: right;\">524.85</td><td style = \"text-align: right;\">-17.44</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Latin America &amp; Caribbean</td><td style = \"text-align: right;\">797.02</td><td style = \"text-align: right;\">780.49</td><td style = \"text-align: right;\">-16.53</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-weighted-vs-simple .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 500))\nax = Axis(fig[1, 1];\n          title = \"Weighting by population moves East Asia most, and downward\",\n          ylabel = \"Bank accounts per 1,000 adults, 2014\",\n          xticks = (1:nrow(comparison), comparison.region),\n          xticklabelrotation = pi / 7,\n          limits = (nothing, (0, 1300)))\nfor (j, (col, lab)) in enumerate([(:simple, \"Simple mean\"), (:weighted, \"Population-weighted\")])\n    barplot!(ax, (1:nrow(comparison)) .+ (j == 1 ? -0.19 : 0.19), comparison[!, col];\n             width = 0.34, color = series_color(j), label = lab)\nend\nLegend(fig[0, 1], ax; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Simple against population-weighted mean bank accounts per 1,000 adults, 2014. Two series, so the averaging method carries the colour; bars are dodged with a surface gap. Both are means of the same observations, so they share one axis legitimately.](index_files/figure-html/fig-weighted-vs-simple-output-1.svg){#fig-weighted-vs-simple}\n:::\n:::\n\n\n\n**East Asia and Pacific is the case that makes the point.** Its simple mean in 2014 is about 863\naccounts per 1,000 adults; its population-weighted mean is **106**. Weighting by population cuts\nit by a factor of eight, because the region's small, well-banked economies count the same as\nChina and Indonesia under a simple average and almost nothing under a weighted one.\n\n**The direction of the gap identifies where the population lives.** Where the weighted mean is\nlower, the populous countries have worse access than the small ones — East Asia, and South Asia.\nWhere it is higher, as in Latin America and the Caribbean, the large countries are the\nbetter-banked ones and the small Caribbean states pull the simple average down.\n\nNeither is the \"right\" average; they answer different questions. **The simple mean describes the\ntypical country; the weighted mean describes the typical person.** For \"how far has financial\ninclusion spread\", the weighted mean is the relevant one, and it is far less flattering: the\nunweighted series suggests East Asian access approaching European levels, and the weighted series\ndoes not.\n\nOne artefact worth flagging: the East Asian weighted series jumps from 253.86 in 2004 to 336.63\nin 2005 and then **falls to 81.43 in 2006**. A change that large in a population-weighted mean is\na change in *which* populous country reports, not a change in banking. The weights make the\nseries highly sensitive to the entry and exit of large countries.\n\n### Q5. Winsorization {#p1-q5}\n\nExtreme values are real here, so dropping them would discard the financial centres that make the\ndistribution interesting. Winsorization instead **replaces** anything beyond a percentile with\nthe percentile value, keeping every country in the calculation.\n\n::: {#cell-winsorize .cell execution_count=1}\n``` {.julia .cell-code}\nyear2010 = gfdd[coalesce.(gfdd.Year .== 2010, false) .&\n                .!ismissing.(gfdd[!, \"GFDD.AI.01\"]), :]\nvalues2010 = Float64.(year2010[!, \"GFDD.AI.01\"])\np5, p95 = quantile(values2010, [0.05, 0.95])\nyear2010.winsorized = clamp.(values2010, p5, p95)\n\n(countries = length(values2010),\n p5 = round(p5, digits = 2), p95 = round(p95, digits = 2),\n below_p5 = count(<(p5), values2010), above_p95 = count(>(p95), values2010))\n```\n\n::: {#winsorize .cell-output .cell-output-display execution_count=1}\n```\n(countries = 93, p5 = 27.59, p95 = 1604.69, below_p5 = 5, above_p95 = 5)\n```\n:::\n:::\n\n\n\n**(a)** The 5th percentile is **27.59** accounts per 1,000 adults and the 95th is **1,604.69**,\nboth matching the book.\n\n**(b) and (c)** Averages before and after, by income group.\n\n::: {#tbl-winsorized .cell tbl-cap='Bank accounts per 1,000 adults in 2010, simple mean before and after Winsorizing at the 5th and 95th percentiles. Reproduces the book\\'s Solution figure 10.18.' execution_count=1}\n``` {.julia .cell-code}\nwins_table = DataFrame(income_group = String[], n = Int[], raw = Float64[],\n                       winsorized = Float64[], change = Float64[])\nfor g in INCOME_ORDER\n    s = year2010[coalesce.(year2010.income .== g, false), :]\n    nrow(s) == 0 && continue\n    raw = mean(Float64.(s[!, \"GFDD.AI.01\"]))\n    push!(wins_table, (g, nrow(s), round(raw, digits = 2),\n                       round(mean(s.winsorized), digits = 2),\n                       round(mean(s.winsorized) - raw, digits = 2)))\nend\nwins_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">income_group</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">raw</th><th style = \"text-align: left;\">winsorized</th><th style = \"text-align: left;\">change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Low income</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">121.95</td><td style = \"text-align: right;\">123.06</td><td style = \"text-align: right;\">1.11</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Lower middle income</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">475.07</td><td style = \"text-align: right;\">422.65</td><td style = \"text-align: right;\">-52.42</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Upper middle income</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">634.92</td><td style = \"text-align: right;\">635.71</td><td style = \"text-align: right;\">0.79</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">High income: nonOECD</td><td style = \"text-align: right;\">14</td><td style = \"text-align: right;\">956.33</td><td style = \"text-align: right;\">916.9</td><td style = \"text-align: right;\">-39.44</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">High income: OECD</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">1590.47</td><td style = \"text-align: right;\">1356.47</td><td style = \"text-align: right;\">-234.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**All five Winsorized values match the published table exactly.** The raw column is where the two\ndiverge, and one of the book's figures cannot be right.\n\n::: {.callout-warning}\n## The published non-Winsorized average for Upper middle income is arithmetically impossible\n\nSolution figure 10.18 gives Upper middle income a 2010 average of **643.92** before Winsorizing\nand **635.71** after. This page gets **634.92** before and the same **635.71** after.\n\nThe Winsorized figures agreeing to the cent means both calculations use the same 22 countries.\nSo the raw means should agree too — and the direction of the change settles which is right:\n\n::: {#cell-winsor-direction .cell execution_count=1}\n``` {.julia .cell-code}\numi = year2010[coalesce.(year2010.income .== \"Upper middle income\", false), :]\numi_values = Float64.(umi[!, \"GFDD.AI.01\"])\n\n(countries = length(umi_values),\n below_p5 = round.(umi_values[umi_values .< p5], digits = 2),\n above_p95 = round.(umi_values[umi_values .> p95], digits = 2),\n raw_mean = round(mean(umi_values), digits = 4),\n winsorized_mean = round(mean(clamp.(umi_values, p5, p95)), digits = 4),\n shift = round(mean(clamp.(umi_values, p5, p95)) - mean(umi_values), digits = 4),\n shift_implied_by_643_92 = round(635.71 - 643.92, digits = 4))\n```\n\n::: {#winsor-direction .cell-output .cell-output-display execution_count=1}\n```\n(countries = 22, below_p5 = [10.28], above_p95 = Float64[], raw_mean = 634.9219, winsorized_mean = 635.7088, shift = 0.7869, shift_implied_by_643_92 = -8.21)\n```\n:::\n:::\n\n\n\nExactly one Upper middle income country falls below the 5th percentile, at 10.28 accounts per\n1,000 adults, and **none is above the 95th**. Winsorization can therefore only move this mean\n*upward* — it raises that single value to 27.59 and leaves the other 21 untouched, adding\n(27.59 − 10.28) ÷ 22 ≈ **+0.79**.\n\nSo the raw mean must be 635.71 − 0.79 = **634.92**. For 643.92 to be the raw mean, Winsorizing\nwould have to *lower* the average by 8.21, which requires values above the 95th percentile that\nthis group does not have. **643.92 is a digit transposition of 634.92.**\n:::\n\n**What Winsorization does, and the book's summary of it is too strong.** The published note says\n\"the simple averages of Winsorized values are lower.\" That holds for three groups and **fails for\ntwo**:\n\n- **High income: OECD** falls from 1,590.47 to 1,356.47, a drop of 234 — this group has the\n  values above the 95th percentile, so pulling the upper tail in moves it a long way.\n- **Low income** *rises*, from 121.95 to 123.06, and **Upper middle income** rises from 634.92 to\n  635.71.\n\nWinsorization pulls in **both** tails. It lowers a mean when the group's mass beyond the 95th\npercentile outweighs its mass below the 5th, and raises it otherwise. Poor countries sit in the\nlow tail, so for them the procedure is a correction upward. Describing it as a downward\nadjustment gets the mechanism backwards for exactly the groups where financial access is worst.\n\nNote also **n = 4** for High income: OECD. Only four OECD high-income countries report this\nindicator in 2010, so that 234-point change rests on a handful of observations.\n\n## Part 10.2 — Financial stability before and after 2008 {#part-10.2}\n\n### Q1. What post-crisis regulation should have done to each indicator {#p2-q1}\n\nThe regulatory response — Basel III above all, phased in from 2013, plus national measures like\nDodd-Frank — was aimed squarely at bank loss absorption.\n\n- **Bank regulatory capital to risk-weighted assets should rise**, and this is close to a\n  mechanical prediction rather than a behavioural one. Basel III raised minimum capital ratios,\n  added a conservation buffer and a countercyclical buffer, and tightened what counts as capital.\n  The indicator *is* the regulated quantity, so if the rules bound at all, it increases.\n- **Bank Z-score should also rise, but less reliably.** It combines capitalisation with return on\n  assets and the volatility of returns: $Z = (\\text{ROA} + \\text{equity/assets}) \\div\n  \\sigma(\\text{ROA})$. Higher capital raises it, so the same regulation pushes in the same\n  direction. But two of its three inputs work against that. Higher capital requirements\n  **reduce return on equity**, and the post-crisis period was one of compressed margins and\n  unusually low interest rates, which lowers ROA. Whether Z rises depends on which effect\n  dominates.\n\nSo the sharp prediction is on the capital ratio; the Z-score is ambiguous *ex ante*. That\ndistinction matters for reading the results, because a null on the Z-score is not evidence\nagainst the regulation working.\n\n### Q2. Differences between 2007 and 2014, with confidence intervals {#p2-q2}\n\nComparing each region's and income group's mean in 2014 against 2007. The groups are different\nsets of countries in the two years, so these are independent-sample comparisons, as the book's\n`t.test` treats them.\n\n::: {#tbl-stability .cell tbl-cap='Difference in mean stability indicator between 2014 and 2007, with 95% confidence intervals from Welch\\'s t-test. Reproduces the book\\'s R walk-through 10.6 output for GFDD.SI.05 by region.' execution_count=1}\n``` {.julia .cell-code}\nfunction difference_table(indicator, groupcol, groups)\n    out = DataFrame(group = String[], n_2007 = Int[], n_2014 = Int[], difference = Float64[],\n                    lower = Float64[], upper = Float64[], width = Float64[],\n                    excludes_zero = Bool[])\n    for g in groups\n        pick(y) = Float64[v for v in gfdd[coalesce.(gfdd[!, groupcol] .== g, false) .&\n                                          coalesce.(gfdd.Year .== y, false), indicator]\n                          if v !== missing]\n        before, after = pick(2007), pick(2014)\n        (length(before) < 2 || length(after) < 2) && continue\n        t = UnequalVarianceTTest(after, before)\n        lo, hi = confint(t)\n        push!(out, (g, length(before), length(after), round((lo + hi) / 2, digits = 3),\n                    round(lo, digits = 3), round(hi, digits = 3), round((hi - lo) / 2, digits = 3),\n                    lo > 0 || hi < 0))\n    end\n    return out\nend\n\ncapital_region = difference_table(\"GFDD.SI.05\", :Region, REGIONS)\ncapital_region\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>7×8 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">group</th><th style = \"text-align: left;\">n_2007</th><th style = \"text-align: left;\">n_2014</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">width</th><th style = \"text-align: left;\">excludes_zero</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Bool\" style = \"text-align: left;\">Bool</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">East Asia &amp; Pacific</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">1.863</td><td style = \"text-align: right;\">-2.021</td><td style = \"text-align: right;\">5.747</td><td style = \"text-align: right;\">3.884</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Europe &amp; Central Asia</td><td style = \"text-align: right;\">44</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">2.731</td><td style = \"text-align: right;\">0.714</td><td style = \"text-align: right;\">4.747</td><td style = \"text-align: right;\">2.016</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Latin America &amp; Caribbean</td><td style = \"text-align: right;\">17</td><td style = \"text-align: right;\">17</td><td style = \"text-align: right;\">0.353</td><td style = \"text-align: right;\">-1.144</td><td style = \"text-align: right;\">1.85</td><td style = \"text-align: right;\">1.497</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Middle East &amp; North Africa</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">0.057</td><td style = \"text-align: right;\">-2.948</td><td style = \"text-align: right;\">3.062</td><td style = \"text-align: right;\">3.005</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">North America</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0.5</td><td style = \"text-align: right;\">-11.693</td><td style = \"text-align: right;\">12.693</td><td style = \"text-align: right;\">12.193</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">South Asia</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">3.06</td><td style = \"text-align: right;\">-1.368</td><td style = \"text-align: right;\">7.488</td><td style = \"text-align: right;\">4.428</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Sub-Saharan Africa</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">19</td><td style = \"text-align: right;\">1.293</td><td style = \"text-align: right;\">-2.582</td><td style = \"text-align: right;\">5.167</td><td style = \"text-align: right;\">3.875</td><td style = \"text-align: right;\">false</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe seven rows match the walk-through's printed output to eight decimal places.\n\n::: {#tbl-stability-rest .cell tbl-cap='The same comparison for the capital ratio by income group, and for the Bank Z-score by region and by income group.' execution_count=1}\n``` {.julia .cell-code}\ncapital_income = difference_table(\"GFDD.SI.05\", :income, INCOME_ORDER)\nzscore_region = difference_table(\"GFDD.SI.01\", :Region, REGIONS)\nzscore_income = difference_table(\"GFDD.SI.01\", :income, INCOME_ORDER)\n\ncombined = vcat(\n    insertcols(capital_region, 1, :indicator => \"Capital ratio\", :cut => \"Region\"),\n    insertcols(capital_income, 1, :indicator => \"Capital ratio\", :cut => \"Income group\"),\n    insertcols(zscore_region, 1, :indicator => \"Bank Z-score\", :cut => \"Region\"),\n    insertcols(zscore_income, 1, :indicator => \"Bank Z-score\", :cut => \"Income group\"))\nshow_all(combined)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>24×10 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">cut</th><th style = \"text-align: left;\">group</th><th style = \"text-align: left;\">n_2007</th><th style = \"text-align: left;\">n_2014</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">width</th><th style = \"text-align: left;\">excludes_zero</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Bool\" style = \"text-align: left;\">Bool</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">East Asia &amp; Pacific</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">1.863</td><td style = \"text-align: right;\">-2.021</td><td style = \"text-align: right;\">5.747</td><td style = \"text-align: right;\">3.884</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Europe &amp; Central Asia</td><td style = \"text-align: right;\">44</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">2.731</td><td style = \"text-align: right;\">0.714</td><td style = \"text-align: right;\">4.747</td><td style = \"text-align: right;\">2.016</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Latin America &amp; Caribbean</td><td style = \"text-align: right;\">17</td><td style = \"text-align: right;\">17</td><td style = \"text-align: right;\">0.353</td><td style = \"text-align: right;\">-1.144</td><td style = \"text-align: right;\">1.85</td><td style = \"text-align: right;\">1.497</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Middle East &amp; North Africa</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">0.057</td><td style = \"text-align: right;\">-2.948</td><td style = \"text-align: right;\">3.062</td><td style = \"text-align: right;\">3.005</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">North America</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0.5</td><td style = \"text-align: right;\">-11.693</td><td style = \"text-align: right;\">12.693</td><td style = \"text-align: right;\">12.193</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">South Asia</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">3.06</td><td style = \"text-align: right;\">-1.368</td><td style = \"text-align: right;\">7.488</td><td style = \"text-align: right;\">4.428</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Sub-Saharan Africa</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">19</td><td style = \"text-align: right;\">1.293</td><td style = \"text-align: right;\">-2.582</td><td style = \"text-align: right;\">5.167</td><td style = \"text-align: right;\">3.875</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">Low income</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">-0.575</td><td style = \"text-align: right;\">-14.233</td><td style = \"text-align: right;\">13.083</td><td style = \"text-align: right;\">13.658</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">Lower middle income</td><td style = \"text-align: right;\">24</td><td style = \"text-align: right;\">30</td><td style = \"text-align: right;\">-1.336</td><td style = \"text-align: right;\">-4.488</td><td style = \"text-align: right;\">1.816</td><td style = \"text-align: right;\">3.152</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">Upper middle income</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">0.42</td><td style = \"text-align: right;\">-1.221</td><td style = \"text-align: right;\">2.061</td><td style = \"text-align: right;\">1.641</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">High income: nonOECD</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">19</td><td style = \"text-align: right;\">2.227</td><td style = \"text-align: right;\">0.24</td><td style = \"text-align: right;\">4.214</td><td style = \"text-align: right;\">1.987</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Capital ratio</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">High income: OECD</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">4.787</td><td style = \"text-align: right;\">3.123</td><td style = \"text-align: right;\">6.452</td><td style = \"text-align: right;\">1.664</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">East Asia &amp; Pacific</td><td style = \"text-align: right;\">24</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">-0.338</td><td style = \"text-align: right;\">-5.113</td><td style = \"text-align: right;\">4.436</td><td style = \"text-align: right;\">4.774</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Europe &amp; Central Asia</td><td style = \"text-align: right;\">51</td><td style = \"text-align: right;\">43</td><td style = \"text-align: right;\">-0.94</td><td style = \"text-align: right;\">-3.716</td><td style = \"text-align: right;\">1.837</td><td style = \"text-align: right;\">2.777</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Latin America &amp; Caribbean</td><td style = \"text-align: right;\">35</td><td style = \"text-align: right;\">28</td><td style = \"text-align: right;\">-0.491</td><td style = \"text-align: right;\">-3.965</td><td style = \"text-align: right;\">2.983</td><td style = \"text-align: right;\">3.474</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Middle East &amp; North Africa</td><td style = \"text-align: right;\">20</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">1.591</td><td style = \"text-align: right;\">-4.521</td><td style = \"text-align: right;\">7.702</td><td style = \"text-align: right;\">6.112</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">North America</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">-1.592</td><td style = \"text-align: right;\">-17.523</td><td style = \"text-align: right;\">14.339</td><td style = \"text-align: right;\">15.931</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">South Asia</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">-0.471</td><td style = \"text-align: right;\">-8.214</td><td style = \"text-align: right;\">7.272</td><td style = \"text-align: right;\">7.743</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Region</td><td style = \"text-align: left;\">Sub-Saharan Africa</td><td style = \"text-align: right;\">41</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">1.211</td><td style = \"text-align: right;\">-2.062</td><td style = \"text-align: right;\">4.483</td><td style = \"text-align: right;\">3.273</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">Low income</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">1.735</td><td style = \"text-align: right;\">-2.25</td><td style = \"text-align: right;\">5.72</td><td style = \"text-align: right;\">3.985</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">Lower middle income</td><td style = \"text-align: right;\">46</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">-0.052</td><td style = \"text-align: right;\">-4.113</td><td style = \"text-align: right;\">4.008</td><td style = \"text-align: right;\">4.06</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">22</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">Upper middle income</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">-0.486</td><td style = \"text-align: right;\">-4.645</td><td style = \"text-align: right;\">3.674</td><td style = \"text-align: right;\">4.159</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">23</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">High income: nonOECD</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">-0.569</td><td style = \"text-align: right;\">-4.186</td><td style = \"text-align: right;\">3.048</td><td style = \"text-align: right;\">3.617</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">24</td><td style = \"text-align: left;\">Bank Z-score</td><td style = \"text-align: left;\">Income group</td><td style = \"text-align: left;\">High income: OECD</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">0.173</td><td style = \"text-align: right;\">-3.7</td><td style = \"text-align: right;\">4.047</td><td style = \"text-align: right;\">3.873</td><td style = \"text-align: right;\">false</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n### Q3. Has stability improved? {#p2-q3}\n\n**(a) The four comparisons with their intervals.**\n\n::: {#cell-fig-stability .cell execution_count=1}\n``` {.julia .cell-code}\npanels = [(\"Capital ratio, by region\", capital_region, \"Percentage points\"),\n          (\"Capital ratio, by income group\", capital_income, \"Percentage points\"),\n          (\"Bank Z-score, by region\", zscore_region, \"Z-score points\"),\n          (\"Bank Z-score, by income group\", zscore_income, \"Z-score points\")]\n\nfig = Figure(size = (980, 760))\nfor (k, (title, tab, unit)) in enumerate(panels)\n    row, col = fldmod1(k, 2)\n    ax = Axis(fig[row, col];\n              title = title, titlesize = 12,\n              ylabel = unit,\n              xticks = (1:nrow(tab), tab.group), xticklabelrotation = pi / 5,\n              xticklabelsize = 9)\n    hlines!(ax, [0]; color = BASELINE, linewidth = 1)\n    barplot!(ax, 1:nrow(tab), tab.difference; width = 0.5, color = series_color(1))\n    errorbars!(ax, 1:nrow(tab), tab.difference, tab.difference .- tab.lower,\n               tab.upper .- tab.difference;\n               color = INK_SECONDARY, whiskerwidth = 10, linewidth = 2)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Change in each stability indicator from 2007 to 2014, with 95% confidence intervals. Four panels because the two indicators are in different units and the two groupings are different populations; one series each, so one colour. The rule at zero is what every interval is read against.](index_files/figure-html/fig-stability-output-1.svg){#fig-stability}\n:::\n:::\n\n\n\n**(b) What the results support.**\n\n**The capital ratio rose, and the clearest evidence is in the income-group cut rather than the\nregional one.** All seven regions have a positive point estimate but only **Europe and Central\nAsia** excludes zero, at **+2.73 points [0.71, 4.75]** — the region with the most observations,\nand the one containing most of the banks Basel III was written for.\n\nBy income group the result is stronger and more interpretable. **Both high-income groups show a\nmeasurable increase**: High income: OECD **+4.79 points [3.12, 6.45]** and High income: nonOECD\n**+2.23 [0.24, 4.21]**. Neither of the three lower-income groups does, and Lower middle income is\nactually negative at −1.34 [−4.49, 1.82].\n\nThat pattern is what the regulation predicts. Basel III bound on the banking systems of advanced\neconomies, and it is those systems whose capital ratios moved. The OECD estimate is both the\nlargest and the most precisely measured of the twelve comparisons here.\n\n**Where the intervals are useless, they are spectacularly so.** North America gives **+0.50\n[−11.69, 12.69]** on two observations per year, and Low income gives **−0.58 [−14.23, 13.08]** on\nfour and six. Both intervals are wider than the entire plausible range of the ratio, which\ntypically sits between 10 and 20. A point estimate reported without them would be meaningless.\n\n**The Z-score shows no improvement anywhere.** Five of seven regions have negative point\nestimates, none of the seven intervals excludes zero, and the same holds for all five income\ngroups. Given [Q1](#p2-q1) that is the expected result rather than a puzzle: capital rose, but\nreturns fell and the Z-score divides by the volatility of returns, so the three inputs pull\nagainst each other.\n\nSo the honest summary is narrow but not empty. **Regulatory capital measurably increased in the\nhigh-income banking systems the rules targeted, by nearly five percentage points in the OECD.\nThere is no evidence that estimated distance-to-default improved anywhere** — and those two\nstatements are consistent, because they measure different things.\n\nFour reasons not to read more into it than that:\n\n1. **Composition changes.** The countries reporting in 2014 are not the countries reporting in\n   2007 — Sub-Saharan Africa has 41 observations in 2007 and 15 in 2014 on the Z-score. A\n   difference of means across two different samples confounds change with who showed up.\n2. **Two years, not a trend.** 2007 and 2014 are single years, each with its own conditions.\n   2007 is the pre-crisis peak, which makes it a demanding baseline for capital and a flattering\n   one for returns.\n3. **Basel III was still phasing in.** The framework's timetable ran to 2019, so 2014 catches\n   part of the adjustment.\n4. **Rising capital is not the same as a safer system.** The Z-score's blind spot from\n   [Q1](#p1-q1) is interconnectedness, and neither indicator here measures it. A system can hold\n   more capital and remain vulnerable to the correlation of its exposures, which is what\n   propagated the 2008 crisis.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading one sheet of a large workbook | Setup | `XLSX.readtable(path, \"Data - June 2016\")` |\n| Coercing mixed number/blank columns | Setup | `num.(col)` with `tryparse` |\n| Box and whisker plots | Q10.1 Q2 | `boxplot!(ax, fill(1, n), v)` |\n| Outliers by the 1.5 IQR rule | Q10.1 Q2 | count beyond `q1 - 1.5iqr`, `q3 + 1.5iqr` |\n| Small multiples on a free scale | Q10.1 Q2 | one `Axis` per panel via `fldmod1` |\n| Sequential ramp for an ordered group | Q10.1 Q3 | `sequential_steps(5)`, not `series_color` |\n| Weighted mean | Q10.1 Q4 | normalise weights, then `sum(w .* x)` |\n| Winsorizing at percentiles | Q10.1 Q5 | `clamp.(v, p5, p95)` |\n| Difference in means with a CI | Q10.2 Q2 | `UnequalVarianceTTest`, `confint` |\n| Stacking labelled result tables | Q10.2 Q2 | `insertcols` then `vcat` |\n| Grey-context small multiples | Q10.1 Q3 | draw all series grey, then one in colour |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}