{
  "hash": "40665886c85cda2b16779dec77863905",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Extra 2. The politics of carbon taxation\"\nsubtitle: \"Why rural voters reject carbon taxes, and a survey experiment that moves the belief\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nA UK survey of 2,997 respondents on carbon taxation, from Hope, Limberg and Steinebach (2026).\nIt is a **survey experiment**: half the sample received an information treatment before being\nasked their views, so the difference between the halves is caused by the information rather than\nmerely correlated with it.\n\nThe argument being tested is that rural opposition to carbon taxes is not only about the higher\ncosts rural households face, but about **fairness** — a sense that the state already treats\nthese communities unequally, and that a carbon tax adds to the injury.\n\n- **[Part 1](#part-1)** — measuring and explaining support for carbon taxation\n- **[Part 2](#part-2)** — explaining rural backlashes\n\nConcepts: **Likert scales**, **dummy variables**, **conditional means**, and an\n**information-provision survey experiment** as a way to test a causal claim about beliefs. Book\npages: [project](https://books.core-econ.org/doing-economics/book/text/14-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/14-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/14-06.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames\nusing Statistics\nusing HypothesisTests\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-survey .cell execution_count=1}\n``` {.julia .cell-code}\npath = rawpath(\"14\", \"carbon-tax-hope.xlsx\")\n\nfunction sheet_frame(p, name)\n    cells = XLSX.readxlsx(p)[name][:]\n    return DataFrame([cells[2:end, j] for j in axes(cells, 2)],\n                     Symbol.(string.(cells[1, :])); makeunique = true)\nend\n\nsurvey = sheet_frame(path, \"Data\")\n\nfunction num(x)\n    (x === missing || x === nothing) && return missing\n    x isa Number && return Float64(x)\n    parsed = tryparse(Float64, string(x))\n    return parsed === nothing ? missing : parsed\nend\nfor col in [:age, :treatment, :carbon_tax_support, :unequal_treatment, :carbon_tax_unfairness]\n    survey[!, col] = num.(survey[!, col])\nend\ntext_col(v) = [x === missing || x === nothing ? missing : string(x) for x in v]\nfor col in [:neighbourhood, :commute, :partisanship]\n    survey[!, col] = text_col(survey[!, col])\nend\n\n(respondents = nrow(survey), variables = names(survey))\n```\n\n::: {#read-survey .cell-output .cell-output-display execution_count=1}\n```\n(respondents = 2997, variables = [\"respondent_id\", \"age\", \"neighbourhood\", \"commute\", \"partisanship\", \"treatment\", \"carbon_tax_support\", \"unequal_treatment\", \"carbon_tax_unfairness\"])\n```\n:::\n:::\n\n\n\n# Part 1 — Measuring and explaining support for carbon taxation {#part-1}\n\n## Q1. How the question was asked {#p1-q1}\n\nBoth groups are given a short explanation of a carbon tax immediately before being asked their\nview: how the tax works, that heavier fossil-fuel users pay more, and that it is aimed at\nclimate change.\n\n**That explanation is the step taken to improve accuracy.** Asking about an unfamiliar policy\notherwise measures whatever the respondent imagines the words mean, and \"carbon tax\" is a phrase\nmany people hold an opinion about without holding a definition. Briefing everyone identically\nmeans the answers refer to the same object — and because *both* arms get it, it is not the\nexperimental treatment.\n\n## Q2. Sample sizes {#p1-q2}\n\n::: {#cell-sample-sizes .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(group = [\"Treatment\", \"Control\", \"Total\"],\n          respondents = [count(==(1.0), survey.treatment),\n                         count(==(0.0), survey.treatment), nrow(survey)])\n```\n\n::: {#sample-sizes .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">group</th><th style = \"text-align: left;\">respondents</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Treatment</td><td style = \"text-align: right;\">1481</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Control</td><td style = \"text-align: right;\">1516</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Total</td><td style = \"text-align: right;\">2997</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**2,997 respondents, 1,481 treated and 1,516 control**, all three matching the published\nsolution. The split is near-even, as random assignment should produce.\n\n## Q3. How the authors recode support, and what it costs {#p1-q3}\n\n::: {.callout-important}\n## The book's own description of the scale is inverted\n\nThe project text says support is measured \"on a 5-point scale running from 1 for 'strongly\noppose' to 5 for 'strongly support'\". The **data dictionary in the spreadsheet says the\nopposite**: 1 is strongly support and 5 is strongly oppose.\n\nThe dictionary is right, and the book's own instructions confirm it — the dummy variable is\ndefined as 1 when `carbon_tax_support` is 1 or 2, described as \"strongly support or support\".\nThat only makes sense if low numbers mean support.\n\nTaking the question text at face value would invert every result on this page while leaving all\nthe arithmetic looking perfectly reasonable. The check is the published frequency table, which\nthis page reproduces below: if the coding were reversed, the counts would attach to the opposite\nlabels.\n:::\n\nThe authors collapse the five-point scale to a **dummy**: 1 for support or strong support, 0\notherwise.\n\n- **The advantage is interpretability.** The mean of a 0/1 variable *is* the share supporting, so\n  every conditional mean below reads directly as a percentage, and it behaves well in a\n  regression.\n- **The cost is intensity.** Someone who strongly supports and someone who merely supports become\n  identical, as do a neutral respondent and a strong opponent. The variable can no longer detect\n  a change that moves people from \"oppose\" to \"strongly oppose\" — a real hardening of opinion\n  that this measure records as nothing at all.\n\n## Q4 and Q5. The dummy variables {#p1-q4}\n\n::: {#cell-dummies .cell execution_count=1}\n``` {.julia .cell-code}\n# Missing stays missing throughout: a respondent who skipped the question is not a zero.\nsurvey.supports = [s === missing ? missing : Float64(s <= 2) for s in survey.carbon_tax_support]\nsurvey.aged_40_plus = [a === missing ? missing : Float64(a >= 40) for a in survey.age]\nsurvey.commutes_by_car = [c === missing ? missing : Float64(c == \"Car\") for c in survey.commute]\nsurvey.rural = [n === missing ? missing : Float64(n == \"Rural\") for n in survey.neighbourhood]\nsurvey.high_unequal = [u === missing ? missing : Float64(u >= 8)\n                       for u in survey.unequal_treatment]\n\nconst DUMMIES = [:supports, :aged_40_plus, :commutes_by_car, :rural, :high_unequal]\nDataFrame(dummy = DUMMIES,\n          ones = [count(==(1.0), skipmissing(survey[!, d])) for d in DUMMIES],\n          zeros = [count(==(0.0), skipmissing(survey[!, d])) for d in DUMMIES],\n          missing_n = [count(ismissing, survey[!, d]) for d in DUMMIES],\n          mean = [round(mean(skipmissing(survey[!, d])), digits = 4) for d in DUMMIES])\n```\n\n::: {#dummies .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">dummy</th><th style = \"text-align: left;\">ones</th><th style = \"text-align: left;\">zeros</th><th style = \"text-align: left;\">missing_n</th><th style = \"text-align: left;\">mean</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Symbol\" style = \"text-align: left;\">Symbol</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">supports</td><td style = \"text-align: right;\">1318</td><td style = \"text-align: right;\">1623</td><td style = \"text-align: right;\">56</td><td style = \"text-align: right;\">0.4481</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">aged_40_plus</td><td style = \"text-align: right;\">1735</td><td style = \"text-align: right;\">1064</td><td style = \"text-align: right;\">198</td><td style = \"text-align: right;\">0.6199</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">commutes_by_car</td><td style = \"text-align: right;\">1124</td><td style = \"text-align: right;\">917</td><td style = \"text-align: right;\">956</td><td style = \"text-align: right;\">0.5507</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">rural</td><td style = \"text-align: right;\">613</td><td style = \"text-align: right;\">2384</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.2045</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">high_unequal</td><td style = \"text-align: right;\">1727</td><td style = \"text-align: right;\">1270</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.5762</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nKeeping missing as missing matters more than it looks. Coding a non-response as 0 would silently\nrecruit every respondent who skipped the question into the \"does not support\" camp, which is a\ndifferent claim from \"did not say\".\n\n## Q6 to Q10. Baseline support, in the control group only {#p1-q7}\n\nEverything from here to the end of Part 1 uses the **control group**, so it measures support\nuncontaminated by the experimental treatment.\n\n::: {#tbl-distribution .cell tbl-cap='Distribution of carbon tax support in the control group. Reproduces the book\\'s Solution figure 1.' execution_count=1}\n``` {.julia .cell-code}\ncontrol = survey[survey.treatment .== 0.0, :]\nconst SCALE = [1 => \"Strongly support\", 2 => \"Support\", 3 => \"Neither support nor oppose\",\n               4 => \"Oppose\", 5 => \"Strongly oppose\"]\nanswered = count(!ismissing, control.carbon_tax_support)\n\ndistribution = DataFrame(\n    code = first.(SCALE),\n    response = last.(SCALE),\n    respondents = [count(==(Float64(k)), skipmissing(control.carbon_tax_support))\n                   for k in first.(SCALE)])\ndistribution.percentage = round.(100 .* distribution.respondents ./ answered, digits = 1)\ndistribution\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">code</th><th style = \"text-align: left;\">response</th><th style = \"text-align: left;\">respondents</th><th style = \"text-align: left;\">percentage</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Strongly support</td><td style = \"text-align: right;\">131</td><td style = \"text-align: right;\">8.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">Support</td><td style = \"text-align: right;\">557</td><td style = \"text-align: right;\">37.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">Neither support nor oppose</td><td style = \"text-align: right;\">282</td><td style = \"text-align: right;\">18.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: left;\">Oppose</td><td style = \"text-align: right;\">317</td><td style = \"text-align: right;\">21.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: left;\">Strongly oppose</td><td style = \"text-align: right;\">207</td><td style = \"text-align: right;\">13.9</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-coverage .cell execution_count=1}\n``` {.julia .cell-code}\n(control_group = nrow(control), answered = answered,\n did_not_answer = nrow(control) - answered)\n```\n\n::: {#coverage .cell-output .cell-output-display execution_count=1}\n```\n(control_group = 1516, answered = 1494, did_not_answer = 22)\n```\n:::\n:::\n\n\n\nAll five counts and all five percentages match the published table. Note that **22 of the 1,516\ncontrol respondents did not answer**, so the percentages are shares of 1,494.\n\n::: {#cell-fig-distribution .cell execution_count=1}\n``` {.julia .cell-code}\nordered = reverse(distribution)\n\nfig = Figure(size = (820, 480))\nax = Axis(fig[1, 1];\n          title = \"Support outweighs opposition, but a third of the public is opposed\",\n          ylabel = \"% of respondents\",\n          xticks = (1:5, ordered.response), xticklabelrotation = pi / 9,\n          limits = (nothing, (0, 44)))\nbarplot!(ax, 1:5, ordered.percentage; width = 0.6, color = series_color(1))\nfor (x, v) in zip(1:5, ordered.percentage)\n    text!(ax, x, v; text = string(v) * \"%\", fontsize = 11,\n          align = (:center, :bottom), offset = (0, 4), color = INK)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Percentage of control-group respondents at each level of carbon tax support, ordered from strongest opposition to strongest support so the axis reads left to right as increasing support. One series, so one colour; every bar is labelled, which is what the book's question asks for.](index_files/figure-html/fig-distribution-output-1.svg){#fig-distribution}\n:::\n:::\n\n\n\n**The modal answer is \"Support\", at 37.3%**, and only 8.8% strongly support. Adding the two\nsupport categories gives **46.1%**; the two opposition categories give **35.1%**; 18.9% sit in\nthe middle.\n\n::: {#cell-dummy-mean .cell execution_count=1}\n``` {.julia .cell-code}\n(support_share = round(mean(skipmissing(control.supports)), digits = 4),\n from_the_table = round((distribution.percentage[1] + distribution.percentage[2]) / 100,\n                        digits = 4))\n```\n\n::: {#dummy-mean .cell-output .cell-output-display execution_count=1}\n```\n(support_share = 0.4605, from_the_table = 0.461)\n```\n:::\n:::\n\n\n\n**The dummy's mean is 0.461**, which is exactly the combined \"support\" plus \"strongly support\"\nshare from the table — matching the published value. That identity is the whole reason the dummy\nis convenient: its average *is* the share.\n\n**So is carbon taxation popular in the UK?** More people support it than oppose it, by about 11\npercentage points. But two features of the distribution matter more than the sign:\n\n- **Support is broad and shallow, opposition is narrower and deeper.** Only 8.8% strongly\n  support, while 13.9% strongly oppose. The intense minority is on the opposing side, and\n  intensity is what turns opinion into protest — which is what Part 2 is about.\n- **A third of the public is against it**, and 18.9% more are uncommitted. A policy with 46%\n  support is not one a government can treat as settled.\n\n## Q11 and Q12. Who supports it {#p1-q11}\n\n::: {#tbl-conditional-means .cell tbl-cap='Share supporting a carbon tax within each subgroup of the control group. Reproduces the book\\'s Solution figures 3 to 6.' execution_count=1}\n``` {.julia .cell-code}\nfunction conditional(col, labels)\n    out = DataFrame(group = String[], respondents = Int[], support = Float64[])\n    for (v, label) in labels\n        sub = control[coalesce.(control[!, col] .== v, false), :]\n        s = collect(skipmissing(sub.supports))\n        push!(out, (label, length(s), round(mean(s), digits = 4)))\n    end\n    return out\nend\n\nvcat(conditional(:aged_40_plus, [0.0 => \"Under 40\", 1.0 => \"40 and over\"]),\n     conditional(:commutes_by_car, [0.0 => \"Does not commute by car\",\n                                    1.0 => \"Commutes by car\"]),\n     conditional(:rural, [0.0 => \"Non-rural\", 1.0 => \"Rural\"]),\n     conditional(:high_unequal, [0.0 => \"Perceives less unequal treatment (0–7)\",\n                                 1.0 => \"Perceives unequal treatment (8–10)\"]))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">group</th><th style = \"text-align: left;\">respondents</th><th style = \"text-align: left;\">support</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Under 40</td><td style = \"text-align: right;\">528</td><td style = \"text-align: right;\">0.5303</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">40 and over</td><td style = \"text-align: right;\">867</td><td style = \"text-align: right;\">0.4141</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Does not commute by car</td><td style = \"text-align: right;\">451</td><td style = \"text-align: right;\">0.5521</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Commutes by car</td><td style = \"text-align: right;\">562</td><td style = \"text-align: right;\">0.4075</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Non-rural</td><td style = \"text-align: right;\">1174</td><td style = \"text-align: right;\">0.4685</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Rural</td><td style = \"text-align: right;\">320</td><td style = \"text-align: right;\">0.4312</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Perceives less unequal treatment (0–7)</td><td style = \"text-align: right;\">683</td><td style = \"text-align: right;\">0.4949</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Perceives unequal treatment (8–10)</td><td style = \"text-align: right;\">811</td><td style = \"text-align: right;\">0.4316</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#tbl-by-party .cell tbl-cap='Share supporting a carbon tax by party, control group. Parties with fewer than 20 respondents are grouped as \"Smaller parties\" rather than reported separately, since a share computed on six people carries no information.' execution_count=1}\n``` {.julia .cell-code}\nparties = DataFrame(party = String[], respondents = Int[], support = Float64[])\nsmall = Float64[]\nfor p in sort(unique(skipmissing(control.partisanship)))\n    s = collect(skipmissing(control[coalesce.(control.partisanship .== p, false), :supports]))\n    if length(s) < 20\n        append!(small, s)\n    else\n        push!(parties, (p, length(s), round(mean(s), digits = 4)))\n    end\nend\nisempty(small) || push!(parties, (\"Smaller parties (combined)\", length(small),\n                                  round(mean(small), digits = 4)))\nsort!(parties, :support, rev = true)\nparties\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>9×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">party</th><th style = \"text-align: left;\">respondents</th><th style = \"text-align: left;\">support</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Green Party of England and Wales</td><td style = \"text-align: right;\">142</td><td style = \"text-align: right;\">0.6901</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Scottish National Party</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">0.617</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Labour Party</td><td style = \"text-align: right;\">500</td><td style = \"text-align: right;\">0.552</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Liberal Democrats</td><td style = \"text-align: right;\">140</td><td style = \"text-align: right;\">0.5286</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Other</td><td style = \"text-align: right;\">44</td><td style = \"text-align: right;\">0.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Smaller parties (combined)</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">0.4444</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Conservative Party</td><td style = \"text-align: right;\">265</td><td style = \"text-align: right;\">0.3434</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Prefer not to say</td><td style = \"text-align: right;\">42</td><td style = \"text-align: right;\">0.2619</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Reform UK</td><td style = \"text-align: right;\">108</td><td style = \"text-align: right;\">0.1667</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Party is by far the strongest divide.** Green voters support at **0.69** and Reform UK voters\nat **0.17** — a four-fold gap, and wider than anything else in the data. Labour (0.55), Liberal\nDemocrat (0.53) and SNP (0.62) sit above the average; Conservative (0.34) below.\n\nThe demographic splits are real but much smaller:\n\n- **Age**: under-40s 0.53 against 0.41 for those 40 and over — a 12-point gap.\n- **Car commuting**: 0.55 for non-car commuters against 0.41 for car commuters. This is the\n  cost channel in its most direct form: a carbon tax raises the price of fuel, and people who\n  drive to work pay it.\n- **Rural**: 0.43 against 0.47 non-rural — **only about 4 points**, which is the surprise.\n\n**That small rural gap is the puzzle Part 2 exists to explain.** Rural residents are the group\nwhose backlash the article is about, and on this measure they are barely less supportive than\neveryone else. Whatever drives rural opposition is not visible as a large average difference —\nit needs the mechanism, not the headline.\n\nThe last row points at it. **Respondents who feel the state treats people unequally support at\n0.43 against 0.49** for those who do not — a gap comparable to the rural gap, on a variable that\nis not about geography at all.\n\n**Two variables absent from this dataset that should matter:**\n\n1. **Income.** A carbon tax is regressive relative to income, so willingness to pay for it should\n   fall as income falls. Its absence is the biggest gap here, and it is likely correlated with\n   several variables that *are* present, including car commuting.\n2. **Home heating type.** A household on oil or LPG — common in rural areas off the gas grid —\n   faces a much larger bill from a carbon tax than one on mains gas or a heat pump, and unlike\n   commuting it cannot be changed cheaply.\n\nEither could account for part of what the party and commuting variables are currently absorbing.\n\n# Part 2 — Explaining rural backlashes {#part-2}\n\nThe argument is that rural opposition runs through **perceived unfairness**: rural communities\nbelieve the state already treats them unequally, and read a carbon tax as more of the same.\n\n`unequal_treatment` measures agreement that the government treats people equally regardless of\nwhere they live, **reverse-coded** so that high values mean perceiving *more* unequal treatment.\n`carbon_tax_unfairness` measures agreement that a carbon tax is unfair because it falls on\npeople the government has already disadvantaged.\n\n## Q1 to Q3. The correlation among rural respondents {#p2-q1}\n\n::: {#tbl-rural-control .cell tbl-cap='Rural control-group respondents split by whether they perceive unequal treatment. Reproduces the book\\'s Solution figures 7 and 8.' execution_count=1}\n``` {.julia .cell-code}\nrural_control = control[coalesce.(control.rural .== 1.0, false), :]\n\nrural_table = DataFrame(perception = [\"Low unequal treatment (0–7)\",\n                                      \"High unequal treatment (8–10)\"])\nfor (col, label) in [(:carbon_tax_unfairness, \"mean_unfairness\"),\n                     (:supports, \"mean_support\")]\n    rural_table[!, label] = [\n        round(mean(skipmissing(rural_control[coalesce.(rural_control.high_unequal .== v, false),\n                                             col])), digits = 4) for v in [0.0, 1.0]]\nend\nrural_table.respondents = [count(==(v), skipmissing(rural_control.high_unequal))\n                           for v in [0.0, 1.0]]\nrural_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">perception</th><th style = \"text-align: left;\">mean_unfairness</th><th style = \"text-align: left;\">mean_support</th><th style = \"text-align: left;\">respondents</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Low unequal treatment (0–7)</td><td style = \"text-align: right;\">5.127</td><td style = \"text-align: right;\">0.472</td><td style = \"text-align: right;\">126</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">High unequal treatment (8–10)</td><td style = \"text-align: right;\">6.203</td><td style = \"text-align: right;\">0.4051</td><td style = \"text-align: right;\">197</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nBoth published figures reproduce: unfairness **5.1 against 6.2**, support **0.47 against 0.41**.\n\n::: {#cell-rural-correlation .cell execution_count=1}\n``` {.julia .cell-code}\nok = .!ismissing.(rural_control.unequal_treatment) .&\n     .!ismissing.(rural_control.carbon_tax_unfairness)\n(rural_control_respondents = nrow(rural_control),\n correlation = round(cor(Float64.(rural_control[ok, :unequal_treatment]),\n                         Float64.(rural_control[ok, :carbon_tax_unfairness])), digits = 4),\n n = count(ok))\n```\n\n::: {#rural-correlation .cell-output .cell-output-display execution_count=1}\n```\n(rural_control_respondents = 323, correlation = 0.2029, n = 323)\n```\n:::\n:::\n\n\n\n**Among rural control respondents, perceiving unequal treatment goes with both finding the tax\nunfair and opposing it.** The unfairness gap is 1.08 points on an 11-point scale; the support gap\nis 6.7 percentage points.\n\nThe correlation between the two continuous measures is **0.20** — positive and clearly present,\nbut modest. That is worth stating plainly, because it is the honest version of the article's\nclaim: unequal-treatment perceptions are *one* input into fairness judgements about carbon taxes,\nnot the dominant one.\n\n**And none of this is causal.** Both variables are attitudes recorded in the same interview from\nthe same person. A respondent generally aggrieved with government would score high on both\nwithout either causing the other. That is precisely what the experiment is for.\n\n## Q4 to Q6. The information experiment {#p2-q4}\n\nThe treatment provides information about how the state treats different areas. If the article's\nmechanism is right, that information should raise perceived unequal treatment, raise perceived\nunfairness of the tax, and lower support — **among rural respondents**.\n\n::: {#tbl-treatment-effect .cell tbl-cap='Treatment against control among rural respondents, with 95% confidence intervals for the difference. Reproduces the p-values in the book\\'s solutions to Question 6.' execution_count=1}\n``` {.julia .cell-code}\nrural_all = survey[coalesce.(survey.rural .== 1.0, false), :]\n\neffects = DataFrame(outcome = String[], treated = Float64[], n_treated = Int[],\n                    control = Float64[], n_control = Int[], difference = Float64[],\n                    lower = Float64[], upper = Float64[], p_value = Float64[])\nfor (col, label) in [(:unequal_treatment, \"Unequal treatment perception (0–10)\"),\n                     (:carbon_tax_unfairness, \"Carbon tax unfairness (0–10)\"),\n                     (:supports, \"Supports a carbon tax (0/1)\")]\n    t = Float64.(collect(skipmissing(rural_all[rural_all.treatment .== 1.0, col])))\n    c = Float64.(collect(skipmissing(rural_all[rural_all.treatment .== 0.0, col])))\n    test = UnequalVarianceTTest(t, c)\n    lo, hi = confint(test)\n    push!(effects, (label, round(mean(t), digits = 4), length(t),\n                    round(mean(c), digits = 4), length(c),\n                    round(mean(t) - mean(c), digits = 4),\n                    round(lo, digits = 4), round(hi, digits = 4),\n                    round(pvalue(test), digits = 4)))\nend\neffects\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×9 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">outcome</th><th style = \"text-align: left;\">treated</th><th style = \"text-align: left;\">n_treated</th><th style = \"text-align: left;\">control</th><th style = \"text-align: left;\">n_control</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">p_value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Unequal treatment perception (0–10)</td><td style = \"text-align: right;\">8.0483</td><td style = \"text-align: right;\">290</td><td style = \"text-align: right;\">7.6904</td><td style = \"text-align: right;\">323</td><td style = \"text-align: right;\">0.3579</td><td style = \"text-align: right;\">0.0487</td><td style = \"text-align: right;\">0.667</td><td style = \"text-align: right;\">0.0234</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Carbon tax unfairness (0–10)</td><td style = \"text-align: right;\">6.1276</td><td style = \"text-align: right;\">290</td><td style = \"text-align: right;\">5.7833</td><td style = \"text-align: right;\">323</td><td style = \"text-align: right;\">0.3443</td><td style = \"text-align: right;\">-0.0438</td><td style = \"text-align: right;\">0.7324</td><td style = \"text-align: right;\">0.082</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Supports a carbon tax (0/1)</td><td style = \"text-align: right;\">0.3169</td><td style = \"text-align: right;\">284</td><td style = \"text-align: right;\">0.4312</td><td style = \"text-align: right;\">320</td><td style = \"text-align: right;\">-0.1143</td><td style = \"text-align: right;\">-0.1913</td><td style = \"text-align: right;\">-0.0374</td><td style = \"text-align: right;\">0.0036</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**All three p-values match the published solutions: 0.023, 0.082 and 0.004.**\n\n::: {#cell-fig-treatment .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (960, 420))\nfor (k, (col, label, limits)) in enumerate([\n        (:unequal_treatment, \"Unequal treatment\\nperception (0–10)\", (7.0, 8.6)),\n        (:carbon_tax_unfairness, \"Carbon tax\\nunfairness (0–10)\", (5.2, 6.7)),\n        (:supports, \"Supports a\\ncarbon tax\", (0.25, 0.50))])\n    ax = Axis(fig[1, k]; title = label, titlesize = 12,\n              xticks = (1:2, [\"Control\", \"Treatment\"]), limits = (nothing, limits))\n    for (j, arm) in enumerate([0.0, 1.0])\n        v = Float64.(collect(skipmissing(rural_all[rural_all.treatment .== arm, col])))\n        half = 1.96 * std(v) / sqrt(length(v))\n        barplot!(ax, [j], [mean(v)]; width = 0.45, color = series_color(j),\n                 label = j == 1 ? \"Control\" : \"Treatment\")\n        errorbars!(ax, [j], [mean(v)], [half];\n                   color = INK_SECONDARY, whiskerwidth = 12, linewidth = 2)\n    end\nend\nLegend(fig[0, 1:3], fig.content[1]; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Rural respondents' mean outcome by experimental arm, with 95% confidence intervals on each group mean. Two series, so the arm carries the colour. Three panels because the outcomes are on different scales — two 0–10 attitude scales and one 0/1 share — and a shared axis would be meaningless.](index_files/figure-html/fig-treatment-output-1.svg){#fig-treatment}\n:::\n:::\n\n\n\n**The experiment supports the mechanism, and the ordering of the three results is the\ninteresting part.**\n\n- **Unequal treatment perception rises by 0.36 points** [0.05, 0.67], p = 0.023. The information\n  did what it was meant to do: it changed the belief the article says is upstream of everything\n  else.\n- **Carbon tax unfairness rises by 0.34 points** [−0.04, 0.73], p = 0.082. Same direction, similar\n  size, but the interval includes zero. On a conventional 5% threshold this is *not* significant,\n  and it is the middle link in the causal chain.\n- **Support falls by 11.4 percentage points** [−0.19, −0.04], p = 0.004. The largest and most\n  precisely estimated of the three.\n\n**Why the middle link being weakest is awkward for the mechanism.** The proposed chain runs\ninformation → unequal-treatment perception → unfairness perception → lower support. The two ends\nmove clearly and the middle does not quite. If unfairness were the channel carrying the effect\nthrough to support, it should be at least as well identified as the outcome it explains.\n\nTwo readings, and this design cannot separate them:\n\n1. **The chain holds and the unfairness measure is noisy.** An 11-point agree/disagree scale is a\n   coarse instrument for a specific belief, and measurement error attenuates exactly this kind of\n   intermediate estimate. Its point estimate is the right sign and a comparable size.\n2. **Information affects support through some other route** — general grievance with government,\n   or simply priming a rural identity — and unfairness is a correlate rather than the conduit.\n\nDistinguishing them needs a design that manipulates unfairness perceptions directly, or a formal\nmediation analysis with its own assumptions. What the experiment does establish is the part that\nmatters most for the article's headline: **telling rural respondents about unequal treatment\ncauses them to withdraw support for a carbon tax.**\n\n## What this establishes, and what it does not {#p2-q7}\n\n**Established.** Rural support for carbon taxation is causally sensitive to beliefs about how the\nstate treats rural areas. An 11-point fall from a short information treatment is a large effect\nfor a survey experiment, and it is not explicable by rural respondents differing from urban ones\nin some fixed way, because the comparison is within rural respondents randomly assigned.\n\n**Not established.** Three limits worth being explicit about:\n\n- **Survey responses are not votes or protests.** The Gilets Jaunes did not fill in a Likert\n  scale. Whether a stated 11-point shift corresponds to political behaviour is outside this\n  design.\n- **The treatment is information a researcher chose to provide.** Its effect size depends on that\n  content, and it says how *malleable* the belief is, not how much of real-world rural opposition\n  the belief currently explains.\n- **Durability is unknown.** The outcome is measured minutes after the treatment. Attitude effects\n  from information provision are known to decay.\n\n**What it implies for policy**, taking [Part 1](#part-1) together with Part 2: the rural support\ngap is small on average (about 4 points) but highly *responsive* to fairness framing. A carbon\ntax introduced without visible attention to distribution across places has a latent\nconstituency against it that can be activated by a single piece of information. Revenue\nrecycling targeted at the places that pay most is the obvious lever, and it is aimed at exactly\nthe belief this experiment shows is doing the work.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| A scale coded opposite to its description | Q1 Q3 | check counts against the published table |\n| Dummy variables preserving missing | Q1 Q4 | `s === missing ? missing : Float64(s <= 2)` |\n| The mean of a dummy as a share | Q1 Q10 | `mean(skipmissing(col))` |\n| Conditional means by subgroup | Q1 Q11 | mask, `skipmissing`, `mean` |\n| Suppressing tiny subgroups | Q1 Q11 | pool categories under 20 respondents |\n| Treatment vs control difference | Q2 Q6 | `UnequalVarianceTTest`, `confint`, `pvalue` |\n| Error bars on group means | Q2 Q6 | `errorbars!` with `1.96 * sem` |\n| Panels for different scales | Q2 Q6 | one `Axis` per outcome, own `limits` |\n| Reversing a table for display | Q1 Q8 | `reverse(df)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}