{
  "hash": "a701f48ccf561d75dfad161aab9b3d09",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"11. Measuring willingness to pay for climate change mitigation\"\nsubtitle: \"What 1,512 Germans said they would pay, and how much the question format changed the answer\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nA German government-sponsored internet survey, 1,512 respondents, asking what people would pay\neach year for climate mitigation. Half were asked a **dichotomous choice** question — would you\npay €X, yes or no — and half a **two-way payment ladder**, naming the most they would certainly\npay and the least they would certainly refuse.\n\nThe point of the design is that both groups were asked about the same policy. Any difference in\nthe answers is a property of the *question*, not of what people want.\n\n- **[Part 11.1](#part-11.1)** — summarizing the data\n- **[Part 11.2](#part-11.2)** — comparing willingness to pay across methods\n\nNew concepts: **contingent valuation**, **Likert scales** and reverse-coding, index construction,\nand **Cronbach's alpha** for whether several questions measure one thing. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/11-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/11-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/11-04.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames\nusing Statistics\nusing HypothesisTests, Distributions\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {.callout-important}\n## This workbook needs a different reader\n\n`XLSX.readtable` fails on this file:\n\n```\nKeyError: key \"xl/worksheets/sheet2.xml\" not found\n```\n\nThe file is **strict OOXML** — the ISO variant of the xlsx format — and XLSX.jl's\nstrict-to-transitional conversion path cannot handle it, even though the sheet it names is\npresent in the archive. `XLSX.readxlsx` opens it fine, so reading the sheet as a matrix and\nbuilding the frame by hand works:\n\n::: {#cell-sheet-frame .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Read a worksheet as a DataFrame, taking row 1 as the header.\n\n`XLSX.readtable` cannot open this workbook (strict OOXML), but `readxlsx` can, and\nindexing a sheet with `[:]` gives the full cell matrix.\n\"\"\"\nfunction sheet_frame(path, name)\n    cells = XLSX.readxlsx(path)[name][:]\n    return DataFrame([cells[2:end, j] for j in axes(cells, 2)],\n                     Symbol.(string.(cells[1, :])); makeunique = true)\nend\n\npath = rawpath(\"11\", \"climate-wtp.xlsx\")\nsurvey = sheet_frame(path, \"Data\")\n(rows = nrow(survey), columns = ncol(survey))\n```\n\n::: {#sheet-frame .cell-output .cell-output-display execution_count=1}\n```\n(rows = 1512, columns = 79)\n```\n:::\n:::\n\n\n\nOne consequence to watch: empty cells come back as `nothing` rather than `missing` on this\npath, so the numeric coercion below has to handle both.\n:::\n\n::: {#cell-dictionary .cell execution_count=1}\n``` {.julia .cell-code}\ndictionary = sheet_frame(path, \"Data dictionary\")\nshow_all(dictionary)\n```\n\n::: {#dictionary .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>79×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Variable</th><th style = \"text-align: left;\">Description</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Any\" style = \"text-align: left;\">Any</th><th title = \"Any\" style = \"text-align: left;\">Any</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">id</td><td style = \"text-align: left;\">Participant ID number</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">sex</td><td style = \"text-align: left;\">Gender</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">age</td><td style = \"text-align: left;\">Age (given in bands)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">education</td><td style = \"text-align: left;\">Highest educational attainment (1 = in school, 2 = without school degree, 3 = secondary general school, 4 = intermediate general school, 5 = polytechnic school, 6 = university preparatory school)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">voc_training</td><td style = \"text-align: left;\">Highest vocational degree (1 = in training, 2 = no voc degree and not in training, 3 = apprenticeship/vocational school degree, 4 = technical college of the GDR, 5 = technical college, 6 = university of applied sciences, 7 = university)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">prob_a</td><td style = \"text-align: left;\">Most important problem: unemployment</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">prob_b</td><td style = \"text-align: left;\">Most important problem: rising prices</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">prob_c</td><td style = \"text-align: left;\">most important problem: gov. debt</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">prob_d</td><td style = \"text-align: left;\">most important problem: taxes</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">prob_e</td><td style = \"text-align: left;\">most important problem: educational system</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">prob_f</td><td style = \"text-align: left;\">most important problem: public health system</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">prob_g</td><td style = \"text-align: left;\">most important problem: public pension system</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">prob_h</td><td style = \"text-align: left;\">most important problem: immigration</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">prob_i</td><td style = \"text-align: left;\">Most important problem: environment</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">prob_j</td><td style = \"text-align: left;\">most important problem: energy system</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">worry</td><td style = \"text-align: left;\">are you worried about global warming (1 = very worried, 5 = not at all worried)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">know</td><td style = \"text-align: left;\">subjective knowledge about global warming</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">infoall</td><td style = \"text-align: left;\">How attentively did you read the info text?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: left;\">costs</td><td style = \"text-align: left;\">DC format: costs in Euro per year</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: left;\">abst_format</td><td style = \"text-align: left;\">Treatment question format (ref = DC format, ladder = payment ladder (TWPL/PL))</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: left;\">DC_ref_outcome</td><td style = \"text-align: left;\">DC format: response </td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">22</td><td style = \"text-align: left;\">dcothers_dk</td><td style = \"text-align: left;\">DC format: don&apos;t know how others vote</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">23</td><td style = \"text-align: left;\">dcothers_perc</td><td style = \"text-align: left;\">DC format: how many percent do you think will vote in favor?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">24</td><td style = \"text-align: left;\">PL_zerowtp</td><td style = \"text-align: left;\">PL format: Zero WTP</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">25</td><td style = \"text-align: left;\">PL_novote</td><td style = \"text-align: left;\">PL format: I would not vote</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">26</td><td style = \"text-align: left;\">WTP_plmin</td><td style = \"text-align: left;\">PL format: Price that individual would definitely vote in favour at</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">27</td><td style = \"text-align: left;\">WTP_plmax</td><td style = \"text-align: left;\">PL format: Price that individual would no longer vote in favour at</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">28</td><td style = \"text-align: left;\">PLothers_dk</td><td style = \"text-align: left;\">PL format: don&apos;t know how others vote</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">29</td><td style = \"text-align: left;\">PLothers_perc</td><td style = \"text-align: left;\">PL format: how much on average do people say they would pay?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">30</td><td style = \"text-align: left;\">protest_1</td><td style = \"text-align: left;\">I can not afford additional expenses.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">31</td><td style = \"text-align: left;\">protest_2</td><td style = \"text-align: left;\">It&apos;s not fair that the costs of climate protection are to be borne by the households</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">32</td><td style = \"text-align: left;\">protest_3</td><td style = \"text-align: left;\">I already pay enough for climate protection.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">33</td><td style = \"text-align: left;\">protest_4</td><td style = \"text-align: left;\">It does not help if Germany reduced its emissions, if not all, other countries do not</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">34</td><td style = \"text-align: left;\">protest_5</td><td style = \"text-align: left;\">The industry is doing far too little to protect the climate.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">35</td><td style = \"text-align: left;\">protest_6</td><td style = \"text-align: left;\">I am generally opposed to price and tax increases.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">36</td><td style = \"text-align: left;\">protest_7</td><td style = \"text-align: left;\">The government is not able to take the right measures to reduce emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">37</td><td style = \"text-align: left;\">protest_8</td><td style = \"text-align: left;\">There are many other areas in which the money can be put to better use.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">38</td><td style = \"text-align: left;\">protest_9</td><td style = \"text-align: left;\">The specified reduction target is not reachable anyway. </td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">39</td><td style = \"text-align: left;\">protest_10</td><td style = \"text-align: left;\">The money for climate protection should be taken from existing government revenue.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">40</td><td style = \"text-align: left;\">protest_11</td><td style = \"text-align: left;\">Wealthier households should pay more for climate protection pay than me.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">41</td><td style = \"text-align: left;\">protest_12</td><td style = \"text-align: left;\">I do not have enough information on future action on climate change.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">42</td><td style = \"text-align: left;\">protest_13</td><td style = \"text-align: left;\">First other countries need to do more for climate protection before Germany does.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">43</td><td style = \"text-align: left;\">scepticism_1</td><td style = \"text-align: left;\">It is too early to say whether climate change is a real problem.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">44</td><td style = \"text-align: left;\">scepticism_2</td><td style = \"text-align: left;\">The dangers of climate change are generally exaggerated.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">45</td><td style = \"text-align: left;\">scepticism_3</td><td style = \"text-align: left;\">The human impact on climate is generally greatly exaggerated.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">46</td><td style = \"text-align: left;\">scepticism_4</td><td style = \"text-align: left;\">The Earth&apos;s climate system is very sensitive and can easily get out of balance.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">47</td><td style = \"text-align: left;\">scepticism_5</td><td style = \"text-align: left;\">The climate system is too complex so scientists cannot make useful predictions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">48</td><td style = \"text-align: left;\">scepticism_6</td><td style = \"text-align: left;\">Climate change is mainly caused by human activity.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">49</td><td style = \"text-align: left;\">scepticism_7</td><td style = \"text-align: left;\">There is clear evidence that global warming is taking place.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">50</td><td style = \"text-align: left;\">scepticism_8</td><td style = \"text-align: left;\">Global warming occurs mainly due to natural fluctuations in the Earth&apos;s temperature.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">51</td><td style = \"text-align: left;\">AR_1</td><td style = \"text-align: left;\">The German energy policy constitutes a substantial contribution to climate protection.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">52</td><td style = \"text-align: left;\">AR_2</td><td style = \"text-align: left;\">Germany is responsible for high global CO2 emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">53</td><td style = \"text-align: left;\">AR_3</td><td style = \"text-align: left;\">Germany should reduce CO2 emissions, regardless of what other countries do.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">54</td><td style = \"text-align: left;\">AR_4</td><td style = \"text-align: left;\">As long as other countries do not reduce their greenhouse gas emissions, climate change will still be a problem.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">55</td><td style = \"text-align: left;\">AR_5</td><td style = \"text-align: left;\">The CO2 emissions of Germany have a significant effect on climate change.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">56</td><td style = \"text-align: left;\">AR_6</td><td style = \"text-align: left;\">Germany&apos;s pioneering role will bring other countries to reduce CO2 emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">57</td><td style = \"text-align: left;\">AR_7</td><td style = \"text-align: left;\">Spending more money for climate protection will mitigate climate change.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">58</td><td style = \"text-align: left;\">AR_8</td><td style = \"text-align: left;\">Germany&apos;s action against climate change are effective.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">59</td><td style = \"text-align: left;\">PN_1</td><td style = \"text-align: left;\">I do not buy fruit and vegetables from distant lands, to reduce emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">60</td><td style = \"text-align: left;\">PN_2</td><td style = \"text-align: left;\">I feel obliged to take the impact of my daily activities on climate into account.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">61</td><td style = \"text-align: left;\">PN_3</td><td style = \"text-align: left;\">I feel better when I&apos;m reducing emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">62</td><td style = \"text-align: left;\">PN_4</td><td style = \"text-align: left;\">I have a bad conscience when I drive a car rather than use public transport.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">63</td><td style = \"text-align: left;\">PN_5</td><td style = \"text-align: left;\">It is useless to reduce emissions unless everyone else is doing the same thing.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">64</td><td style = \"text-align: left;\">PN_6</td><td style = \"text-align: left;\">I feel uncomfortable when I consume energy, thus causing emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">65</td><td style = \"text-align: left;\">PN_7</td><td style = \"text-align: left;\">In my daily activities I try to reduce as many emissions as I can.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">66</td><td style = \"text-align: left;\">PN_8</td><td style = \"text-align: left;\">My social environment is of the opinion that I should do more for reducing CO2 emissions.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">67</td><td style = \"text-align: left;\">cog_1</td><td style = \"text-align: left;\">The government interferes too much with the daily lives of people.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">68</td><td style = \"text-align: left;\">cog_2</td><td style = \"text-align: left;\">Sometimes, the government must pass laws so that people act to their own advantage.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">69</td><td style = \"text-align: left;\">cog_3</td><td style = \"text-align: left;\">The state should intervene as little as possible in economic matters.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">70</td><td style = \"text-align: left;\">cog_4</td><td style = \"text-align: left;\">The government should stop dictating to people how they should live.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">71</td><td style = \"text-align: left;\">cog_5</td><td style = \"text-align: left;\">The government should do more to achieve social goals, even if it restricts the freedom of the individual.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">72</td><td style = \"text-align: left;\">cog_6</td><td style = \"text-align: left;\">The government is trying to do too much for too many people. We should let the individual have more personal responsibility.</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">73</td><td style = \"text-align: left;\">liv_sit</td><td style = \"text-align: left;\">What best describes your living situation?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">74</td><td style = \"text-align: left;\">region</td><td style = \"text-align: left;\">In which region are you living?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">75</td><td style = \"text-align: left;\">occ_sit</td><td style = \"text-align: left;\">Which of the occupational situations from the list applies best to you?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">76</td><td style = \"text-align: left;\">kids_nr</td><td style = \"text-align: left;\">Number in children in househod</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">77</td><td style = \"text-align: left;\">member</td><td style = \"text-align: left;\">Membership in environmental organisation</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">78</td><td style = \"text-align: left;\">party</td><td style = \"text-align: left;\">Which political party would you vote?</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">79</td><td style = \"text-align: left;\">hhnetinc</td><td style = \"text-align: left;\">Household net income (monthly, in Euros)</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-coerce .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Numeric value, or `missing` for blanks and anything non-numeric.\n\n`tryparse` returns `nothing` on failure, which would silently overwrite text columns\nwith `nothing` if returned directly.\n\"\"\"\nfunction num(x)\n    (x === missing || x === nothing) && return missing\n    x isa Number && return Float64(x)\n    parsed = tryparse(Float64, string(x))\n    return parsed === nothing ? missing : parsed\nend\n\nconst SCALE_ITEMS = [\"scepticism_2\", \"scepticism_6\", \"scepticism_7\",\n                     \"cog_1\", \"cog_2\", \"cog_3\", \"cog_4\", \"cog_5\", \"cog_6\",\n                     \"PN_1\", \"PN_2\", \"PN_3\", \"PN_4\", \"PN_6\", \"PN_7\"]\nfor col in vcat(SCALE_ITEMS, [\"WTP_plmin\", \"WTP_plmax\", \"costs\", \"education\"])\n    survey[!, col] = num.(survey[!, col])\nend\n\n(format_values = unique(string.(survey.abst_format)),\n sex_values = unique(string.(survey.sex)),\n dc_outcomes = unique(string.(survey.DC_ref_outcome)))\n```\n\n::: {#coerce .cell-output .cell-output-display execution_count=1}\n```\n(format_values = [\"ref\", \"ladder\"], sex_values = [\"female\", \"male\"], dc_outcomes = [\"support referendum and pay\", \"do not support referendum and no pay\", \"missing\", \"would not vote\"])\n```\n:::\n:::\n\n\n\n`abst_format` splits the sample: `\"ref\"` is the dichotomous-choice group and `\"ladder\"` the\npayment ladder.\n\n# Part 11.1 — Summarizing the data {#part-11.1}\n\n## Q1. What contingent valuation can and cannot measure {#p1-q1}\n\nContingent valuation asks people what they *would* pay for something not traded in a market.\nNothing here is revealed behaviour — every number is a statement about a hypothetical. Four\nlimitations bite particularly hard on this survey.\n\n**Hypothetical bias.** Nobody was charged anything, so there is no cost to overstating. This is\nthe central problem with stated preference and it is not symmetric: the incentive runs toward\ngenerosity on a socially approved cause. Revealed-preference methods avoid it by construction,\nwhich is why the comparison table in the valuation literature puts stated preference below\nrevealed preference on exactly this axis.\n\n**Social desirability.** Climate protection is a norm-laden topic in Germany, and a respondent\nwho thinks the \"right\" answer is a high number can give one at no cost. This is what makes the\nDC/TWPL comparison in [Part 11.2](#part-11.2) interesting rather than merely methodological:\nthe two formats offer different opportunities to express approval, and if the answers differ,\nsome of what is being measured is the expression rather than the valuation.\n\n**Scope and embedding insensitivity.** Stated WTP tends not to scale with the size of the thing\nbeing valued — people name similar amounts for saving 2,000 birds and 200,000. A single\nmitigation target, as here, gives no way to check whether the amounts track the quantity of\nabatement at all.\n\n**Payment vehicle and protest responses.** The survey asks about an annual payment, and the\n`protest_1` to `protest_13` items exist precisely because some respondents reject the *premise*\nrather than valuing the good at zero: \"the industry is doing far too little\", \"wealthier\nhouseholds should pay more\", \"the money should come from existing government revenue\". A zero\nfrom someone who objects to the mechanism is not a zero valuation, and treating the two alike\nbiases the mean downward.\n\nThe one limitation that matters *less* here is sample representativeness. It is a serious problem\nfor estimating a national WTP figure, but the DC-versus-TWPL comparison is internal to the\nsample, and both groups were drawn the same way.\n\n## Q2. Recoding {#p1-q2}\n\n**(a) Reverse-coding.** Attitudes came on a 1–5 Likert scale, but the statements do not all point\nthe same way. `scepticism_6` is \"climate change is mainly caused by human activity\" — agreeing\nmeans *less* scepticism, the opposite of `scepticism_2` (\"the dangers are generally\nexaggerated\"). Averaging them as they stand would cancel the signal rather than accumulate it.\n\n::: {#cell-reverse-code .cell execution_count=1}\n``` {.julia .cell-code}\n# Reversing on a 1-5 scale maps 1<->5 and 2<->4, which is 6 - x.\nconst REVERSED = [\"cog_2\", \"cog_5\", \"scepticism_6\", \"scepticism_7\"]\nfor col in REVERSED\n    survey[!, col] = [v === missing ? missing : 6.0 - v for v in survey[!, col]]\nend\n\nDataFrame(item = REVERSED,\n          statement = [only(dictionary[dictionary[!, 1] .== c, 2]) for c in REVERSED],\n          new_min = [minimum(skipmissing(survey[!, c])) for c in REVERSED],\n          new_max = [maximum(skipmissing(survey[!, c])) for c in REVERSED])\n```\n\n::: {#reverse-code .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">item</th><th style = \"text-align: left;\">statement</th><th style = \"text-align: left;\">new_min</th><th style = \"text-align: left;\">new_max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">cog_2</td><td style = \"text-align: left;\">Sometimes, the government must pass laws so that people act to their own advantage.</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">cog_5</td><td style = \"text-align: left;\">The government should do more to achieve social goals, even if it restricts the freedom of the individual.</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">scepticism_6</td><td style = \"text-align: left;\">Climate change is mainly caused by human activity.</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">scepticism_7</td><td style = \"text-align: left;\">There is clear evidence that global warming is taking place.</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**(b) Ladder categories into euros.** `WTP_plmin` and `WTP_plmax` hold category numbers 1–14, not\namounts. The survey's actual figures:\n\n::: {#cell-euro-amounts .cell execution_count=1}\n``` {.julia .cell-code}\nconst EURO_AMOUNT = Dict(1 => 48.0, 2 => 72.0, 3 => 84.0, 4 => 108.0, 5 => 156.0,\n                         6 => 192.0, 7 => 252.0, 8 => 324.0, 9 => 432.0, 10 => 540.0,\n                         11 => 720.0, 12 => 960.0, 13 => 1200.0, 14 => 1440.0)\n\nto_euro(v) = v === missing ? missing : get(EURO_AMOUNT, Int(v), missing)\nsurvey.min_euro = to_euro.(survey.WTP_plmin)\nsurvey.max_euro = to_euro.(survey.WTP_plmax)\n\nDataFrame(category = 1:14, euro_per_year = [EURO_AMOUNT[k] for k in 1:14],\n          step_ratio = [k == 1 ? missing : round(EURO_AMOUNT[k] / EURO_AMOUNT[k-1], digits = 3)\n                        for k in 1:14])\n```\n\n::: {#euro-amounts .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>14×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">category</th><th style = \"text-align: left;\">euro_per_year</th><th style = \"text-align: left;\">step_ratio</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">48.0</td><td style = \"font-style: italic; text-align: right;\">missing</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">72.0</td><td style = \"text-align: right;\">1.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">84.0</td><td style = \"text-align: right;\">1.167</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">108.0</td><td style = \"text-align: right;\">1.286</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">156.0</td><td style = \"text-align: right;\">1.444</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">192.0</td><td style = \"text-align: right;\">1.231</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">252.0</td><td style = \"text-align: right;\">1.312</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">324.0</td><td style = \"text-align: right;\">1.286</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">432.0</td><td style = \"text-align: right;\">1.333</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">540.0</td><td style = \"text-align: right;\">1.25</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">720.0</td><td style = \"text-align: right;\">1.333</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">960.0</td><td style = \"text-align: right;\">1.333</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">13</td><td style = \"text-align: right;\">1200.0</td><td style = \"text-align: right;\">1.25</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">14</td><td style = \"text-align: right;\">1440.0</td><td style = \"text-align: right;\">1.2</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**The categories are roughly geometric, not linear.** Each step is about 1.2 to 1.5 times the\none below, so the ladder spans €48 to €1,440 — a factor of 30 — in fourteen steps. That matters\nfor [Part 11.2](#part-11.2): a mean taken over these amounts is sensitive to the top categories\nin a way a mean over evenly spaced options would not be, because the top rungs are far apart.\n\n## Q3. Three indices {#p1-q3}\n\nEach index is the row mean of its items, using the reverse-coded versions where relevant.\n\n::: {#cell-indices .cell execution_count=1}\n``` {.julia .cell-code}\nconst INDEX_ITEMS = [\n    \"climate\" => [\"scepticism_2\", \"scepticism_6\", \"scepticism_7\"],\n    \"gov_intervention\" => [\"cog_1\", \"cog_2\", \"cog_3\", \"cog_4\", \"cog_5\", \"cog_6\"],\n    \"pro_environment\" => [\"PN_1\", \"PN_2\", \"PN_3\", \"PN_4\", \"PN_6\", \"PN_7\"],\n]\n\nfor (name, items) in INDEX_ITEMS\n    survey[!, name] = [all(!ismissing(row[c]) for c in items) ?\n                       mean(Float64[row[c] for c in items]) : missing\n                       for row in eachrow(survey)]\nend\n\nDataFrame(index = first.(INDEX_ITEMS),\n          items = [length(i) for (_, i) in INDEX_ITEMS],\n          scored = [count(!ismissing, survey[!, n]) for (n, _) in INDEX_ITEMS],\n          mean = [round(mean(skipmissing(survey[!, n])), digits = 3) for (n, _) in INDEX_ITEMS],\n          min = [minimum(skipmissing(survey[!, n])) for (n, _) in INDEX_ITEMS],\n          max = [maximum(skipmissing(survey[!, n])) for (n, _) in INDEX_ITEMS])\n```\n\n::: {#indices .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">index</th><th style = \"text-align: left;\">items</th><th style = \"text-align: left;\">scored</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">1512</td><td style = \"text-align: right;\">2.344</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">1512</td><td style = \"text-align: right;\">3.173</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">1512</td><td style = \"text-align: right;\">3.019</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**A naming caution that affects how every later result reads.** After reverse-coding, all three\n`scepticism` items point the same way — *higher means more sceptical*. The book calls this index\n\"belief that climate change is a real phenomenon\", but as computed a high value is scepticism and\na low value is belief. Its mean of about 2.3 on a 1–5 scale therefore says this sample is, on\naverage, **not** very sceptical. The sign of its correlation with WTP in\n[Part 11.2](#p2-q1) only makes sense read that way.\n\n## Q4. Do the items in each index measure one thing? {#p1-q4}\n\n**(a) Correlations within each index.**\n\n::: {#tbl-item-correlations .cell tbl-cap='Correlation between the items making up each index. Reproduces the book\\'s Solution figures 11.1, 11.2 and 11.3.' execution_count=1}\n``` {.julia .cell-code}\nconst ITEM_LABELS = Dict(\n    \"scepticism_2\" => \"exaggeration\", \"scepticism_6\" => \"not.human.activity\",\n    \"scepticism_7\" => \"no.evidence\",\n    \"cog_1\" => \"too.much\", \"cog_2\" => \"not.pass.laws\", \"cog_3\" => \"minimal.intervention\",\n    \"cog_4\" => \"not.dictate\", \"cog_5\" => \"indiv.freedom\",\n    \"cog_6\" => \"personal.responsibility\",\n    \"PN_1\" => \"buy.local\", \"PN_2\" => \"indiv.impact\", \"PN_3\" => \"feel.better\",\n    \"PN_4\" => \"public.transport\", \"PN_6\" => \"conserve.energy\",\n    \"PN_7\" => \"reduce.emissions\")\n\npairs_table = DataFrame(index = String[], item_a = String[], item_b = String[],\n                        correlation = Float64[])\nfor (name, items) in INDEX_ITEMS, i in eachindex(items), j in 1:i-1\n    a = Float64.(collect(skipmissing(survey[!, items[i]])))\n    b = Float64.(collect(skipmissing(survey[!, items[j]])))\n    push!(pairs_table, (name, ITEM_LABELS[items[i]], ITEM_LABELS[items[j]],\n                        round(cor(a, b), digits = 2)))\nend\nshow_all(pairs_table)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>33×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">index</th><th style = \"text-align: left;\">item_a</th><th style = \"text-align: left;\">item_b</th><th style = \"text-align: left;\">correlation</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: left;\">not.human.activity</td><td style = \"text-align: left;\">exaggeration</td><td style = \"text-align: right;\">0.39</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: left;\">no.evidence</td><td style = \"text-align: left;\">exaggeration</td><td style = \"text-align: right;\">0.42</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: left;\">no.evidence</td><td style = \"text-align: left;\">not.human.activity</td><td style = \"text-align: right;\">0.46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">not.pass.laws</td><td style = \"text-align: left;\">too.much</td><td style = \"text-align: right;\">0.25</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">minimal.intervention</td><td style = \"text-align: left;\">too.much</td><td style = \"text-align: right;\">0.32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">minimal.intervention</td><td style = \"text-align: left;\">not.pass.laws</td><td style = \"text-align: right;\">0.12</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">not.dictate</td><td style = \"text-align: left;\">too.much</td><td style = \"text-align: right;\">0.68</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">not.dictate</td><td style = \"text-align: left;\">not.pass.laws</td><td style = \"text-align: right;\">0.28</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">not.dictate</td><td style = \"text-align: left;\">minimal.intervention</td><td style = \"text-align: right;\">0.33</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">indiv.freedom</td><td style = \"text-align: left;\">too.much</td><td style = \"text-align: right;\">0.29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">indiv.freedom</td><td style = \"text-align: left;\">not.pass.laws</td><td style = \"text-align: right;\">0.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">indiv.freedom</td><td style = \"text-align: left;\">minimal.intervention</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">indiv.freedom</td><td style = \"text-align: left;\">not.dictate</td><td style = \"text-align: right;\">0.27</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">personal.responsibility</td><td style = \"text-align: left;\">too.much</td><td style = \"text-align: right;\">0.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">personal.responsibility</td><td style = \"text-align: left;\">not.pass.laws</td><td style = \"text-align: right;\">0.08</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">personal.responsibility</td><td style = \"text-align: left;\">minimal.intervention</td><td style = \"text-align: right;\">0.31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">personal.responsibility</td><td style = \"text-align: left;\">not.dictate</td><td style = \"text-align: right;\">0.46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">personal.responsibility</td><td style = \"text-align: left;\">indiv.freedom</td><td style = \"text-align: right;\">0.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">indiv.impact</td><td style = \"text-align: left;\">buy.local</td><td style = \"text-align: right;\">0.48</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">feel.better</td><td style = \"text-align: left;\">buy.local</td><td style = \"text-align: right;\">0.43</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">feel.better</td><td style = \"text-align: left;\">indiv.impact</td><td style = \"text-align: right;\">0.63</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">22</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">public.transport</td><td style = \"text-align: left;\">buy.local</td><td style = \"text-align: right;\">0.42</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">23</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">public.transport</td><td style = \"text-align: left;\">indiv.impact</td><td style = \"text-align: right;\">0.44</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">24</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">public.transport</td><td style = \"text-align: left;\">feel.better</td><td style = \"text-align: right;\">0.46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">25</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">conserve.energy</td><td style = \"text-align: left;\">buy.local</td><td style = \"text-align: right;\">0.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">26</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">conserve.energy</td><td style = \"text-align: left;\">indiv.impact</td><td style = \"text-align: right;\">0.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">27</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">conserve.energy</td><td style = \"text-align: left;\">feel.better</td><td style = \"text-align: right;\">0.52</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">28</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">conserve.energy</td><td style = \"text-align: left;\">public.transport</td><td style = \"text-align: right;\">0.57</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">29</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">reduce.emissions</td><td style = \"text-align: left;\">buy.local</td><td style = \"text-align: right;\">0.46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">30</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">reduce.emissions</td><td style = \"text-align: left;\">indiv.impact</td><td style = \"text-align: right;\">0.65</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">31</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">reduce.emissions</td><td style = \"text-align: left;\">feel.better</td><td style = \"text-align: right;\">0.59</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">32</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">reduce.emissions</td><td style = \"text-align: left;\">public.transport</td><td style = \"text-align: right;\">0.39</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">33</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">reduce.emissions</td><td style = \"text-align: left;\">conserve.energy</td><td style = \"text-align: right;\">0.46</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery pair matches the published tables. **All twenty-four correlations are positive**, which is\nthe first thing to check after reverse-coding — a negative entry would mean an item still points\nthe wrong way.\n\n**(b) Cronbach's alpha.**\n\n::: {#tbl-alpha .cell tbl-cap='Cronbach\\'s alpha for each index. Computed by `cronbach_alpha` from the shared helpers, which is tested in test/runtests.jl.' execution_count=1}\n``` {.julia .cell-code}\nDataFrame(index = first.(INDEX_ITEMS),\n          items = [length(i) for (_, i) in INDEX_ITEMS],\n          alpha = [round(cronbach_alpha(reduce(hcat, [Float64.(collect(skipmissing(survey[!, c])))\n                                                      for c in items])), digits = 4)\n                   for (_, items) in INDEX_ITEMS])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">index</th><th style = \"text-align: left;\">items</th><th style = \"text-align: left;\">alpha</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">0.6848</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.7133</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.8521</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAlpha asks whether items behave like repeated measurements of one quantity:\n\n$$\\alpha = \\frac{k}{k-1}\\left(1 - \\frac{\\sum_i s_i^2}{s_T^2}\\right)$$\n\nwhere $s_i^2$ is item $i$'s variance and $s_T^2$ the variance of the row totals. If the items\nwere independent, the total variance would just be the sum of the item variances and the bracket\nwould collapse to zero. The more the items covary, the larger $s_T^2$ grows relative to that sum.\n\n**Two of the three clear the conventional 0.7 threshold, and the climate index does not** —\n0.685, just short. The book describes all the values as \"high\"; on the usual reading one of them\nis borderline.\n\nThe ordering is the informative part, and it tracks item count exactly: the six-item\n`pro_environment` index scores 0.852, the six-item `gov_intervention` index 0.713, and the\nthree-item `climate` index 0.685. Three points follow:\n\n- **Alpha rises mechanically with the number of items**, because adding items inflates the total\n  variance faster than the sum of item variances. So the climate index is not necessarily built\n  from worse items — it is built from *fewer*. Its three items correlate 0.39 to 0.46 with each\n  other, which is comparable to several pairs inside the six-item government index.\n- **The 0.7 line is a convention, not a test.** Nothing changes at 0.699. Treating 0.685 as a\n  failure and 0.713 as a success reads far more into the number than it carries, which is why\n  the item correlations above are the more useful diagnostic.\n- **Alpha measures consistency, not validity.** Six questions that all mis-measure the same thing\n  score beautifully. It says the items hang together, not that they capture the concept the index\n  is named after — and [Q3](#p1-q3) already showed this index is named for the opposite of what\n  it counts.\n\n## Q5. Are the two groups comparable on demographics? {#p1-q5}\n\nThe whole design rests on this. If the DC and ladder groups differ in who they are, a difference\nin their answers cannot be attributed to the question format.\n\n::: {#tbl-demographics .cell tbl-cap='Composition of the two question-format groups. Reproduces the book\\'s Solution figures 11.4 to 11.9.' execution_count=1}\n``` {.julia .cell-code}\nconst FORMATS = [\"ref\" => \"DC\", \"ladder\" => \"TWPL\"]\ngroup_rows(code) = survey[coalesce.(survey.abst_format .== code, false), :]\n\nfunction share_table(column, label)\n    out = DataFrame()\n    out[!, label] = String[]\n    for (_, name) in FORMATS\n        out[!, \"$name (%)\"] = Float64[]\n    end\n    values = sort(unique(string(v) for v in survey[!, column]\n                         if v !== missing && v !== nothing))\n    for v in values\n        row = Any[v]\n        for (code, _) in FORMATS\n            g = group_rows(code)\n            present = [string(x) for x in g[!, column] if x !== missing && x !== nothing]\n            push!(row, round(100 * count(==(v), present) / length(present), digits = 2))\n        end\n        push!(out, row)\n    end\n    return out\nend\n\nvcat(share_table(:sex, \"category\"), share_table(:age, \"category\"))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">category</th><th style = \"text-align: left;\">DC (%)</th><th style = \"text-align: left;\">TWPL (%)</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">52.29</td><td style = \"text-align: right;\">51.78</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">male</td><td style = \"text-align: right;\">47.71</td><td style = \"text-align: right;\">48.22</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">18 - 24</td><td style = \"text-align: right;\">9.64</td><td style = \"text-align: right;\">9.49</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">25 - 29</td><td style = \"text-align: right;\">8.65</td><td style = \"text-align: right;\">8.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">30 - 39</td><td style = \"text-align: right;\">17.2</td><td style = \"text-align: right;\">17.79</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">40 - 49</td><td style = \"text-align: right;\">22.56</td><td style = \"text-align: right;\">22.33</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">50 - 59</td><td style = \"text-align: right;\">23.86</td><td style = \"text-align: right;\">24.11</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">60 - 69</td><td style = \"text-align: right;\">18.09</td><td style = \"text-align: right;\">17.98</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-group-sizes .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(format = last.(FORMATS), code = first.(FORMATS),\n          respondents = [nrow(group_rows(c)) for (c, _) in FORMATS])\n```\n\n::: {#group-sizes .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">format</th><th style = \"text-align: left;\">code</th><th style = \"text-align: left;\">respondents</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">DC</td><td style = \"text-align: left;\">ref</td><td style = \"text-align: right;\">1006</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">TWPL</td><td style = \"text-align: left;\">ladder</td><td style = \"text-align: right;\">506</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**The two groups are close to identical in composition.** Women are 52.29% of the DC group and\n51.78% of the ladder group — a gap of half a percentage point. Every age band matches within\nabout half a point too.\n\nNote the group sizes: **1,006 in DC against 506 in the ladder**, so this was a 2:1 split rather\nthan an even one. That does not threaten comparability, but it means the ladder estimates rest on\nhalf as many people and will carry wider intervals.\n\n## Q6. Are the two groups comparable on attitudes? {#p1-q6}\n\nDemographics being balanced does not guarantee attitudes are, and attitudes are the more direct\nthreat: a group that happens to care more about climate would pay more regardless of format.\n\n::: {#tbl-index-balance .cell tbl-cap='The three attitude indices by question format. Reproduces the book\\'s Solution figures 11.10, 11.11 and 11.12.' execution_count=1}\n``` {.julia .cell-code}\nbalance = DataFrame(index = String[], format = String[], mean = Float64[], sd = Float64[],\n                    min = Float64[], max = Float64[], n = Int[])\nfor (name, _) in INDEX_ITEMS, (code, label) in FORMATS\n    v = Float64.(collect(skipmissing(group_rows(code)[!, name])))\n    push!(balance, (name, label, round(mean(v), digits = 2), round(std(v), digits = 2),\n                    minimum(v), maximum(v), length(v)))\nend\nbalance\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">index</th><th style = \"text-align: left;\">format</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">n</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: left;\">DC</td><td style = \"text-align: right;\">2.37</td><td style = \"text-align: right;\">0.85</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">1006</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: left;\">TWPL</td><td style = \"text-align: right;\">2.29</td><td style = \"text-align: right;\">0.84</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">506</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">DC</td><td style = \"text-align: right;\">3.19</td><td style = \"text-align: right;\">0.66</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">1006</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: left;\">TWPL</td><td style = \"text-align: right;\">3.15</td><td style = \"text-align: right;\">0.7</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">506</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">DC</td><td style = \"text-align: right;\">3.01</td><td style = \"text-align: right;\">0.82</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">1006</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: left;\">TWPL</td><td style = \"text-align: right;\">3.03</td><td style = \"text-align: right;\">0.79</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">506</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery mean and standard deviation matches the published tables.\n\n**The largest gap between the two groups on any index is 0.08 points on a 1–5 scale**, against\nwithin-group standard deviations of 0.66 to 0.85. The groups are, for this purpose,\ninterchangeable: climate scepticism 2.37 against 2.29, government intervention 3.19 against 3.15,\npersonal responsibility 3.01 against 3.03.\n\nTaken with [Q5](#p1-q5), that licenses the whole of Part 11.2. **Any difference in stated WTP\nbetween these two groups is a property of the question, because the people are the same.** It is\nworth being clear that this is what randomisation buys — and that the check was worth running\nrather than assuming, since the split turned out to be 2:1 rather than even.\n\n# Part 11.2 — Comparing willingness to pay across methods {#part-11.2}\n\n## Q1. The ladder responses {#p2-q1}\n\n**(a) The distribution of the two ladder answers.**\n\n::: {#cell-fig-ladder .cell execution_count=1}\n``` {.julia .cell-code}\nladder = group_rows(\"ladder\")\ncounts(col) = [count(v -> v !== missing && Int(v) == k, ladder[!, col]) for k in 1:14]\nmin_counts, max_counts = counts(:WTP_plmin), counts(:WTP_plmax)\n\nfig = Figure(size = (920, 500))\nax = Axis(fig[1, 1];\n          title = \"Both answers pile up at the bottom of the ladder\",\n          xlabel = \"Ladder category (1 = €48 per year, 14 = €1,440)\",\n          ylabel = \"Respondents\",\n          xticks = 1:14)\nfor (j, (c, lab)) in enumerate([(min_counts, \"Would certainly pay (WTP_plmin)\"),\n                                (max_counts, \"Would certainly refuse (WTP_plmax)\")])\n    barplot!(ax, (1:14) .+ (j == 1 ? -0.19 : 0.19), c;\n             width = 0.34, color = series_color(j), label = lab)\nend\nLegend(fig[0, 1], ax; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Distribution of the lowest amount respondents would certainly pay and the lowest they would certainly refuse, over the fourteen ladder categories. Two series, so the question carries the colour; bars are dodged with a surface gap. The horizontal axis is the category number, which is what respondents actually chose — the euro amounts behind it are not evenly spaced.](index_files/figure-html/fig-ladder-output-1.svg){#fig-ladder}\n:::\n:::\n\n\n\n::: {#tbl-ladder .cell tbl-cap='Frequency of each ladder category for the two answers.' execution_count=1}\n``` {.julia .cell-code}\nDataFrame(category = 1:14, euros = [EURO_AMOUNT[k] for k in 1:14],\n          would_pay = min_counts, would_refuse = max_counts)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>14×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">category</th><th style = \"text-align: left;\">euros</th><th style = \"text-align: left;\">would_pay</th><th style = \"text-align: left;\">would_refuse</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">48.0</td><td style = \"text-align: right;\">154</td><td style = \"text-align: right;\">8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">72.0</td><td style = \"text-align: right;\">37</td><td style = \"text-align: right;\">42</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">84.0</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">26</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">108.0</td><td style = \"text-align: right;\">57</td><td style = \"text-align: right;\">52</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">156.0</td><td style = \"text-align: right;\">20</td><td style = \"text-align: right;\">39</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">192.0</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">24</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">252.0</td><td style = \"text-align: right;\">23</td><td style = \"text-align: right;\">33</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">324.0</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">432.0</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">19</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">540.0</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">12</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">720.0</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">960.0</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">13</td><td style = \"text-align: right;\">1200.0</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">14</td><td style = \"text-align: right;\">1440.0</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">31</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Both distributions are heavily skewed toward the low categories**, and the two are shaped\ndifferently in a revealing way. The \"would certainly pay\" answers concentrate hardest at the very\nbottom, while the \"would certainly refuse\" answers sit higher and are more spread out — which is\nmechanically necessary, since each respondent's refuse-point is above their pay-point, but the\n*size* of the gap is what the design is trying to elicit.\n\nThere is visible clustering on particular rungs rather than a smooth decline, which is the\nsignature of a categorical instrument: respondents anchor on round-looking options.\n\n**(b) and (c) Average WTP.**\n\n::: {#cell-twpl-average .cell execution_count=1}\n``` {.julia .cell-code}\nsurvey.WTP_average = [(a === missing || b === missing) ? missing : (a + b) / 2\n                      for (a, b) in zip(survey.min_euro, survey.max_euro)]\ntwpl_wtp = Float64.(collect(skipmissing(survey.WTP_average)))\n\n(respondents = length(twpl_wtp),\n mean = round(mean(twpl_wtp), digits = 2),\n median = round(median(twpl_wtp), digits = 2),\n sd = round(std(twpl_wtp), digits = 2),\n range = extrema(twpl_wtp))\n```\n\n::: {#twpl-average .cell-output .cell-output-display execution_count=1}\n```\n(respondents = 348, mean = 268.53, median = 132.0, sd = 287.71, range = (48.0, 1440.0))\n```\n:::\n:::\n\n\n\n**Mean €268.53 and median €132.00**, both matching the book. The mean is more than double the\nmedian, which is the whole story of this variable: a minority naming amounts near the top of the\nladder drags the average far above the typical respondent. With €48 to €1,440 available and a\nmedian of €132, most people sat on the bottom few rungs.\n\nOf the 506 ladder respondents, **348 produced a usable average** — the rest either named no\namount, said they would pay zero, or said they would not vote.\n\n**(d) What predicts willingness to pay.**\n\n::: {#tbl-wtp-correlations .cell tbl-cap='Correlation between average ladder WTP and respondent characteristics. Reproduces the book\\'s R walk-through 11.6 output.' execution_count=1}\n``` {.julia .cell-code}\nsurvey.female = [(s === missing || s === nothing) ? missing :\n                 Float64(lowercase(string(s)) == \"female\") for s in survey.sex]\n\nwtp_corr = DataFrame(variable = String[], correlation = Float64[], n = Int[])\nfor col in [:education, :female, :climate, :gov_intervention, :pro_environment]\n    ok = .!ismissing.(survey.WTP_average) .& .!ismissing.(survey[!, col])\n    push!(wtp_corr, (string(col),\n                     round(cor(Float64.(survey[ok, :WTP_average]),\n                               Float64.(survey[ok, col])), digits = 8), count(ok)))\nend\nwtp_corr\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">correlation</th><th style = \"text-align: left;\">n</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">education</td><td style = \"text-align: right;\">0.138174</td><td style = \"text-align: right;\">348</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">-0.0369497</td><td style = \"text-align: right;\">348</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">climate</td><td style = \"text-align: right;\">-0.144621</td><td style = \"text-align: right;\">348</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">gov_intervention</td><td style = \"text-align: right;\">-0.188452</td><td style = \"text-align: right;\">348</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">pro_environment</td><td style = \"text-align: right;\">0.187503</td><td style = \"text-align: right;\">348</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll five reproduce the published values to eight decimals, with one sign difference explained\nbelow.\n\n**Every correlation is small** — the largest is under 0.19 — so respondent characteristics explain\nvery little of what people said they would pay. Within that, the signs are all\ninterpretable and all point the same way:\n\n- **Climate scepticism −0.145.** More sceptical respondents would pay less. Recall from\n  [Q3](#p1-q3) that a *high* value on this index is scepticism, so the negative sign is the\n  expected direction, not a puzzle.\n- **Preference for government intervention −0.188**, the strongest of the five. The index is\n  coded so that high means *less* appetite for state action, so people who want government to\n  intervene more would pay more.\n- **Personal responsibility +0.188.** Respondents who feel obliged to act pro-environmentally\n  would pay more.\n- **Education +0.138.** More educated respondents would pay more, which is the usual finding and\n  confounded with income.\n- **Sex −0.037.** Effectively zero.\n\n::: {.callout-note}\n## The sex correlation's sign depends on an arbitrary coding choice\n\nThe book prints **+0.03694972**; this gives **−0.03694972** — the same magnitude, opposite sign.\nThe variable is text, `\"female\"` or `\"male\"`, so turning it into a number requires picking which\none is 1. Coding female as 1 gives the negative value; coding male as 1 gives the book's.\n\nNeither is wrong, but neither is self-explanatory either, which is the point: a dummy's sign is\nmeaningless without stating its coding. This page codes **female = 1**, so the negative\ncorrelation reads \"women stated slightly lower WTP\".\n:::\n\n## Q2. The dichotomous-choice demand curve {#p2-q2}\n\nThe DC group each saw one amount and voted. Aggregating across the amounts traces out something\nthat looks like a demand curve.\n\n**(a) Votes by amount.**\n\n::: {#tbl-dc-votes .cell tbl-cap='Dichotomous-choice votes by the amount offered, as counts and as row percentages. Reproduces the book\\'s Solution figure 11.17.' execution_count=1}\n``` {.julia .cell-code}\nconst YES = \"support referendum and pay\"\nconst NO = \"do not support referendum and no pay\"\nconst ABSTAIN = \"would not vote\"\n\ndc = group_rows(\"ref\")\namounts = sort(unique(skipmissing(dc.costs)))\nvotes = DataFrame(euros = Float64[], yes = Int[], no = Int[], abstain = Int[], total = Int[],\n                  pct_yes_abstain_as_no = Float64[], pct_yes_abstain_dropped = Float64[])\nfor a in amounts\n    rows = dc[coalesce.(dc.costs .== a, false), :]\n    outcome = [string(v) for v in rows.DC_ref_outcome]\n    y, n, ab = count(==(YES), outcome), count(==(NO), outcome), count(==(ABSTAIN), outcome)\n    push!(votes, (a, y, n, ab, y + n + ab,\n                  round(100 * y / (y + n + ab), digits = 2),\n                  round(100 * y / (y + n), digits = 2)))\nend\nvotes\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>14×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">euros</th><th style = \"text-align: left;\">yes</th><th style = \"text-align: left;\">no</th><th style = \"text-align: left;\">abstain</th><th style = \"text-align: left;\">total</th><th style = \"text-align: left;\">pct_yes_abstain_as_no</th><th style = \"text-align: left;\">pct_yes_abstain_dropped</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">48.0</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">21</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">65</td><td style = \"text-align: right;\">49.23</td><td style = \"text-align: right;\">60.38</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">72.0</td><td style = \"text-align: right;\">40</td><td style = \"text-align: right;\">30</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">81</td><td style = \"text-align: right;\">49.38</td><td style = \"text-align: right;\">57.14</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">84.0</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">24</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">81</td><td style = \"text-align: right;\">55.56</td><td style = \"text-align: right;\">65.22</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">108.0</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">35</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">73</td><td style = \"text-align: right;\">42.47</td><td style = \"text-align: right;\">46.97</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">156.0</td><td style = \"text-align: right;\">40</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">13</td><td style = \"text-align: right;\">84</td><td style = \"text-align: right;\">47.62</td><td style = \"text-align: right;\">56.34</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">192.0</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">61</td><td style = \"text-align: right;\">40.98</td><td style = \"text-align: right;\">50.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">252.0</td><td style = \"text-align: right;\">28</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">69</td><td style = \"text-align: right;\">40.58</td><td style = \"text-align: right;\">46.67</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">324.0</td><td style = \"text-align: right;\">27</td><td style = \"text-align: right;\">41</td><td style = \"text-align: right;\">16</td><td style = \"text-align: right;\">84</td><td style = \"text-align: right;\">32.14</td><td style = \"text-align: right;\">39.71</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">432.0</td><td style = \"text-align: right;\">29</td><td style = \"text-align: right;\">35</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">75</td><td style = \"text-align: right;\">38.67</td><td style = \"text-align: right;\">45.31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">540.0</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">62</td><td style = \"text-align: right;\">35.48</td><td style = \"text-align: right;\">41.51</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">720.0</td><td style = \"text-align: right;\">13</td><td style = \"text-align: right;\">39</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">64</td><td style = \"text-align: right;\">20.31</td><td style = \"text-align: right;\">25.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">960.0</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">28</td><td style = \"text-align: right;\">14</td><td style = \"text-align: right;\">57</td><td style = \"text-align: right;\">26.32</td><td style = \"text-align: right;\">34.88</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">1200.0</td><td style = \"text-align: right;\">21</td><td style = \"text-align: right;\">42</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">74</td><td style = \"text-align: right;\">28.38</td><td style = \"text-align: right;\">33.33</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">1440.0</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">42</td><td style = \"text-align: right;\">19</td><td style = \"text-align: right;\">76</td><td style = \"text-align: right;\">19.74</td><td style = \"text-align: right;\">26.32</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**(b), (c) and (d) The demand curve, both ways of handling abstentions.**\n\n::: {#cell-fig-demand .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 500))\nax = Axis(fig[1, 1];\n          title = \"Demand falls with price, and how you count abstentions shifts the level\",\n          xlabel = \"Annual amount offered (€, log scale)\",\n          ylabel = \"Voting yes (%)\",\n          xscale = log10, xticks = (amounts, string.(Int.(amounts))),\n          limits = (nothing, (0, 100)))\nfor (j, (col, lab)) in enumerate([(:pct_yes_abstain_as_no, \"Abstain counted as no\"),\n                                  (:pct_yes_abstain_dropped, \"Abstain excluded\")])\n    lines!(ax, votes.euros, votes[!, col]; color = series_color(j), linewidth = 2.5)\n    scatter!(ax, votes.euros, votes[!, col]; color = series_color(j))\n    text!(ax, votes.euros[end], votes[!, col][end]; text = lab, fontsize = 10,\n          align = (:right, :top), offset = (-6, -8), color = INK_SECONDARY)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Share voting yes against the annual amount offered, under the two treatments of abstentions. Two series, so the treatment carries the colour, and both are direct-labelled. The horizontal axis is on a log scale because the offered amounts are roughly geometric — on a linear axis the four lowest amounts would be indistinguishable.](index_files/figure-html/fig-demand-output-1.svg){#fig-demand}\n:::\n:::\n\n\n\n**The curve slopes down, which is the basic sanity check** — a higher price brings fewer yes\nvotes — and it is worth appreciating that this is *not* guaranteed in a contingent-valuation\nsurvey. Respondents seeing only one amount cannot anchor on the others, so the downward slope is\nevidence that people responded to the price rather than to the topic.\n\n**Two features stand out.** The curve is far from a straight line even on a log axis, and the\nshare saying yes does not approach zero at the top amount — a floor of respondents will approve\nany amount, which is what \"protest in the other direction\" looks like.\n\n**How abstentions are treated shifts the level but not the shape.** Counting them as no is the\nconservative reading: someone who declines to vote has not agreed to pay. Excluding them assumes\nabstainers would have split like those who voted. The two curves stay roughly parallel, so\n**the qualitative conclusion does not depend on the choice** — but the level difference is large\nenough that a WTP estimate read off this curve would.\n\nThe conservative treatment is the defensible default here, because the alternative assumes\nabstention is unrelated to price, and the table shows abstention is not evenly spread across\namounts.\n\n## Q3. Does the question format change the answer? {#p2-q3}\n\n**(a) The two formats side by side.** For DC respondents, willingness to pay is the amount they\nwere offered and accepted; for ladder respondents it is the average of their two figures.\n\n::: {#tbl-format-comparison .cell tbl-cap='Willingness to pay by question format. DC uses the offered amount for respondents who voted yes. Reproduces the book\\'s Solution figure 11.21.' execution_count=1}\n``` {.julia .cell-code}\ndc_wtp = Float64[row.costs for row in eachrow(dc)\n                 if row.costs !== missing && string(row.DC_ref_outcome) == YES]\n\ncomparison = DataFrame(\n    format = [\"DC\", \"TWPL\"],\n    n = [length(dc_wtp), length(twpl_wtp)],\n    mean = round.([mean(dc_wtp), mean(twpl_wtp)], digits = 2),\n    sd = round.([std(dc_wtp), std(twpl_wtp)], digits = 2),\n    median = [median(dc_wtp), median(twpl_wtp)])\ncomparison\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">format</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">median</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">DC</td><td style = \"text-align: right;\">383</td><td style = \"text-align: right;\">348.19</td><td style = \"text-align: right;\">378.65</td><td style = \"text-align: right;\">192.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">TWPL</td><td style = \"text-align: right;\">348</td><td style = \"text-align: right;\">268.53</td><td style = \"text-align: right;\">287.71</td><td style = \"text-align: right;\">132.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery value matches the published table: **DC mean €348.19 on 383 respondents, ladder mean\n€268.53 on 348**, with medians of €192 and €132.\n\n**(b) A confidence interval for the difference.**\n\n::: {#tbl-format-ci .cell tbl-cap='95% confidence interval for the difference in mean WTP between the two formats.' execution_count=1}\n``` {.julia .cell-code}\ntest = UnequalVarianceTTest(dc_wtp, twpl_wtp)\nlower, upper = confint(test)\n\nDataFrame(quantity = [\"Difference in means (DC − TWPL)\", \"Standard error of the difference\",\n                      \"95% CI lower\", \"95% CI upper\", \"95% CI half-width\", \"p-value\"],\n          value = round.([mean(dc_wtp) - mean(twpl_wtp),\n                          sqrt(var(dc_wtp) / length(dc_wtp) + var(twpl_wtp) / length(twpl_wtp)),\n                          lower, upper, (upper - lower) / 2, pvalue(test)], digits = 5))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">quantity</th><th style = \"text-align: left;\">value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Difference in means (DC − TWPL)</td><td style = \"text-align: right;\">79.6535</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Standard error of the difference</td><td style = \"text-align: right;\">24.7429</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">95% CI lower</td><td style = \"text-align: right;\">31.0752</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">95% CI upper</td><td style = \"text-align: right;\">128.232</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">95% CI half-width</td><td style = \"text-align: right;\">48.5783</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">p-value</td><td style = \"text-align: right;\">0.00134</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {.callout-warning}\n## The published interval is a 5% confidence interval, not a 95% one\n\nThe book reports the interval as **[78.10, 81.21]**, a half-width of 1.55 on a difference of\n79.66, and concludes the difference is \"precisely estimated\". Its walk-through shows the call\nthat produced it:\n\n```r\nt.test(DC_WTP, TWPL_WTP, conf.level = 0.05)$conf.int\n## [1] 78.10141 81.20560\n```\n\n`conf.level` is the **confidence level**, so `0.05` requests a **5%** interval — one designed to\ncontain the true difference 5% of the time. It looks precise because it is tiny by construction.\nThe intended argument was almost certainly `0.95`; `0.05` is the significance level $\\alpha$,\nwhich is a natural thing to reach for and the opposite of what this parameter wants.\n\nReproducing both levels from the same data settles it:\n\n::: {#cell-conf-level-demo .cell execution_count=1}\n``` {.julia .cell-code}\nse = sqrt(var(dc_wtp) / length(dc_wtp) + var(twpl_wtp) / length(twpl_wtp))\ndifference = mean(dc_wtp) - mean(twpl_wtp)\n# Welch-Satterthwaite degrees of freedom, as used by both R's t.test and\n# HypothesisTests.UnequalVarianceTTest.\ndf = se^4 / ((var(dc_wtp) / length(dc_wtp))^2 / (length(dc_wtp) - 1) +\n             (var(twpl_wtp) / length(twpl_wtp))^2 / (length(twpl_wtp) - 1))\n\nDataFrame(conf_level = [0.95, 0.05],\n          multiplier = round.([quantile(TDist(df), (1 + l) / 2) for l in [0.95, 0.05]],\n                              digits = 6),\n          half_width = round.([quantile(TDist(df), (1 + l) / 2) * se for l in [0.95, 0.05]],\n                              digits = 4),\n          lower = round.([difference - quantile(TDist(df), (1 + l) / 2) * se\n                          for l in [0.95, 0.05]], digits = 4),\n          upper = round.([difference + quantile(TDist(df), (1 + l) / 2) * se\n                          for l in [0.95, 0.05]], digits = 4))\n```\n\n::: {#conf-level-demo .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">conf_level</th><th style = \"text-align: left;\">multiplier</th><th style = \"text-align: left;\">half_width</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0.95</td><td style = \"text-align: right;\">1.96332</td><td style = \"text-align: right;\">48.5783</td><td style = \"text-align: right;\">31.0752</td><td style = \"text-align: right;\">128.232</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">0.05</td><td style = \"text-align: right;\">0.062729</td><td style = \"text-align: right;\">1.5521</td><td style = \"text-align: right;\">78.1014</td><td style = \"text-align: right;\">81.2056</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe 5% row reproduces the book's printed bounds. **The real 95% interval is about 31 times\nwider**: roughly [31, 128] against [78.1, 81.2].\n\nJulia will not make this mistake quietly. `confint(test; level = 0.05)` throws\n`coverage level 0.05 not in range (0.5, 1)` — the API rejects a coverage below one half as\nincoherent, where R's `t.test` accepts it and returns an interval. That is a case where the\nstricter interface is worth the inflexibility.\n\n**The direction of the conclusion survives.** The correct interval still excludes zero\ncomfortably, so DC really does produce higher stated WTP. What does not survive is the claim\nthat the difference is *precisely* estimated, or that \"the confidence interval lower bound is a\nlong way from 0\" in the sense the book means — the lower bound is €31, not €78, and the\ndifference could plausibly be anywhere from a third of the ladder mean to half again as much.\n:::\n\n**(c) Medians against means.**\n\n::: {#tbl-mean-median .cell tbl-cap='How much each summary measure moves between question formats.' execution_count=1}\n``` {.julia .cell-code}\nDataFrame(measure = [\"Mean\", \"Median\"],\n          DC = [comparison.mean[1], comparison.median[1]],\n          TWPL = [comparison.mean[2], comparison.median[2]],\n          difference = [comparison.mean[1] - comparison.mean[2],\n                        comparison.median[1] - comparison.median[2]],\n          ratio = round.([comparison.mean[1] / comparison.mean[2],\n                          comparison.median[1] / comparison.median[2]], digits = 3))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">measure</th><th style = \"text-align: left;\">DC</th><th style = \"text-align: left;\">TWPL</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">ratio</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Mean</td><td style = \"text-align: right;\">348.19</td><td style = \"text-align: right;\">268.53</td><td style = \"text-align: right;\">79.66</td><td style = \"text-align: right;\">1.297</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Median</td><td style = \"text-align: right;\">192.0</td><td style = \"text-align: right;\">132.0</td><td style = \"text-align: right;\">60.0</td><td style = \"text-align: right;\">1.455</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**The mean moves by €79.66 and the median by €60** — but as a proportion the median is the less\nstable of the two here: 1.45 times against 1.30 for the mean. That is worth stating plainly\nbecause the book concludes the opposite, that \"the median is therefore more robust to changes in\nthe question format\".\n\nOn these numbers the median is *not* more robust in relative terms. What is true is the related\npoint the book is reaching for: **the median is far less sensitive to the top of the\ndistribution**, which is why the DC mean sits at €348 against a median of €192.\n\n**(d) Which should a government use?** The honest answer depends on the question being asked, and\nthe two measures answer different ones.\n\n- **The mean is what a budget needs.** Total revenue from a charge is the mean times the number\n  of payers, so if the policy question is \"does this fund the abatement\", the mean is the\n  relevant statistic. Its weakness is that it is set by the upper tail — a handful of people\n  naming €1,440 move it a long way, and those are exactly the responses most exposed to the\n  hypothetical bias from [Q1](#p1-q1).\n- **The median is what a vote needs.** A referendum at price $p$ passes if more than half the\n  electorate would accept $p$, which is the median WTP by definition. It ignores intensity\n  entirely: someone willing to pay the top ladder amount counts exactly the same as someone a\n  single euro above the median.\n\nGiven that the format changes the mean by €80 and neither format's mean can be checked against\nbehaviour, **reporting both and the interval around the difference is the defensible course**,\nwhich is what this page does and what the mislabelled interval obscured.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading strict OOXML | Setup | `XLSX.readxlsx(path)[sheet][:]`, not `readtable` |\n| Blanks that arrive as `nothing` | Setup | handle `nothing` and `missing` in the coercion |\n| Reverse-coding a Likert item | Q11.1 Q2 | `6 .- x` on a 1–5 scale |\n| Mapping categories to amounts | Q11.1 Q2 | `Dict` lookup with `get(..., missing)` |\n| Row means across chosen columns | Q11.1 Q3 | comprehension over `eachrow` |\n| Cronbach's alpha | Q11.1 Q4 | `cronbach_alpha(items)` from the shared helpers |\n| Composition tables by group | Q11.1 Q5 | shares of each group's non-missing responses |\n| Dummy from a text column | Q11.2 Q1 | state the coding — the sign depends on it |\n| Log axis with named ticks | Q11.2 Q2 | `xscale = log10, xticks = (amounts, labels)` |\n| Difference in means with a CI | Q11.2 Q3 | `UnequalVarianceTTest`, `confint` |\n| Welch degrees of freedom | Q11.2 Q3 | Welch–Satterthwaite, then `quantile(TDist(df), p)` |\n| A coverage level below ½ | Q11.2 Q3 | Julia throws; R's `t.test` accepts it |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}