{
  "hash": "dc0947ae0b61f67844095112f61311ca",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"3. Measuring the effect of a sugar tax\"\nsubtitle: \"Did Berkeley's soda tax reach the shelf price?\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nIn November 2014 Berkeley, California became the first US jurisdiction to tax distributors of\nsugar-sweetened beverages, at one cent per fluid ounce, effective January 2015. The tax falls\non distributors, not shoppers — so whether it changes behaviour depends entirely on how much\nof it reaches the shelf.\n\n- **[Part 3.1](#part-3.1)** — before-and-after comparisons of retail prices\n- **[Part 3.2](#part-3.2)** — before-and-after comparisons against prices elsewhere\n\nNew concept: **difference-in-differences**, and the reason a before-and-after comparison on its\nown cannot carry the conclusion. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/03-01.html),\n[R walk-throughs](https://books.core-econ.org/doing-economics/book/text/03-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/03-04.html).\n\n## The data\n\nTwo files, both from Silver et al. (2017), *PLoS Medicine* 14(4): e1002283.\n\n| | |\n|---|---|\n| **Store Price Survey** | `sps_public.xlsx` — 2,175 shelf prices, 26 stores, 247 products, three waves |\n| **Point-of-sale prices** | `public_use_weighted_prices2.dta` — 2,728 weighted monthly average prices, Berkeley vs elsewhere |\n\n::: {.callout-note}\n## Two notes on this data vintage\n\nThe store survey's third wave is labelled `MAR2015` in the current file and `MAR2016` in the\nbook's code, and `supp` is numeric here where the book compares it to the string `\"Standard\"`.\nThe published price means still reproduce exactly, so these are labelling changes rather than\ndifferent observations.\n\nThe point-of-sale table is distributed as Stata `.dta`. CORE also offers it as `.xls`, but that\nis the legacy binary format XLSX.jl cannot read — it would need LibreOffice or Python to\nconvert. The Stata original is what the book's own walk-through 3.7 reads, and\nReadStatTables.jl handles it directly, so no conversion step is needed.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames, ReadStatTables\nusing Statistics, HypothesisTests\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-sps .cell execution_count=1}\n``` {.julia .cell-code}\ndat = DataFrame(XLSX.readtable(rawpath(\"03\", \"sps_public.xlsx\"), \"Data\"))\n\nconst STORE_TYPE = Dict(1 => \"Large supermarket\", 2 => \"Small supermarket\",\n                        3 => \"Pharmacy\",          4 => \"Gas station\")\nconst WAVES = [\"DEC2014\", \"JUN2015\", \"MAR2015\"]\n\n(rows = nrow(dat), columns = names(dat))\n```\n\n::: {#read-sps .cell-output .cell-output-display execution_count=1}\n```\n(rows = 2175, columns = [\"store_id\", \"type\", \"store_type\", \"type2\", \"size\", \"price\", \"price_per_oz\", \"price_per_oz_c\", \"taxed\", \"supp\", \"time\", \"product_id\"])\n```\n:::\n:::\n\n\n\nThe data dictionary ships as a second sheet:\n\n::: {#cell-dictionary .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(XLSX.readtable(rawpath(\"03\", \"sps_public.xlsx\"), \"Data Dictionary\"))\n```\n\n::: {#dictionary .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>12×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Variable Name</th><th style = \"text-align: left;\">Type</th><th style = \"text-align: left;\">Description</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">price</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Purchase Price</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">price_per_oz</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Price per ounce</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">price_per_oz_c</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Price per ounce cents</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">product_id</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Unique product identifier</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">size</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Total package size</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">store_id</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Unique store identifier</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">store_type</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Store Type: 1(Large Supermarket), 2(Small Supermarket), 3(Pharmacy), 4(Gas Station)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">supp</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Supplemental(1) or standard(0) item in beverage panel</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">taxed</td><td style = \"text-align: left;\">Num</td><td style = \"text-align: left;\">Tax status</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">time</td><td style = \"text-align: left;\">Text</td><td style = \"text-align: left;\">Data collection month and year</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">type</td><td style = \"text-align: left;\">Text</td><td style = \"text-align: left;\">Product Type</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">type2</td><td style = \"text-align: left;\">Text</td><td style = \"text-align: left;\">Specifies milk type or coconut water</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n# Part 3.1 — Before-and-after comparisons of retail prices {#part-3.1}\n\n## Q1. Stores and products {#p1-q1}\n\nThe paper's S1 Text describes the survey: fieldworkers visited a fixed panel of Berkeley\nstores and recorded the shelf price and package size of a defined list of beverages, in three\nwaves. Prices are converted to cents per fluid ounce so that packages of different sizes are\ncomparable — the tax is levied per ounce, so per-ounce price is the quantity the policy acts on.\n\n::: {#cell-counts .cell execution_count=1}\n``` {.julia .cell-code}\n(stores = length(unique(dat.store_id)),\n products = length(unique(dat.product_id)),\n waves = sort(unique(dat.time)))\n```\n\n::: {#counts .cell-output .cell-output-display execution_count=1}\n```\n(stores = 26, products = 247, waves = [\"DEC2014\", \"JUN2015\", \"MAR2015\"])\n```\n:::\n:::\n\n\n\n**26 stores** — matching the paper's S1 Text — and **247 products**.\n\n## Q2. Three frequency tables {#p1-q2}\n\n::: {#cell-freq-store-type .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Count rows by `rowvar` across the two compared waves, with a total column.\"\"\"\nfunction wave_table(df, rowvar; waves = [\"DEC2014\", \"JUN2015\"])\n    keys = sort(unique(df[!, rowvar]), by = string)\n    out = DataFrame(rowvar => keys)\n    for w in waves\n        out[!, w] = [sum((df[!, rowvar] .== k) .& (df.time .== w)) for k in keys]\n    end\n    return out\nend\n\nstore_counts = wave_table(dat, :store_type)\nstore_counts.label = [STORE_TYPE[t] for t in store_counts.store_type]\nselect(store_counts, :store_type, :label, :DEC2014, :JUN2015)\n```\n\n::: {#freq-store-type .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">store_type</th><th style = \"text-align: left;\">label</th><th style = \"text-align: left;\">DEC2014</th><th style = \"text-align: left;\">JUN2015</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: right;\">177</td><td style = \"text-align: right;\">209</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: right;\">407</td><td style = \"text-align: right;\">391</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: right;\">87</td><td style = \"text-align: right;\">102</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: right;\">73</td><td style = \"text-align: right;\">96</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nObservation counts are close but not equal between waves — 744 in December against 798 in\nJune. Products go in and out of stock, so a store visited twice does not yield the same basket\ntwice. That is the fact Q3's filter exists to handle.\n\n::: {#cell-freq-taxed .cell execution_count=1}\n``` {.julia .cell-code}\ntaxed_counts = DataFrame(store_type = 1:4,\n                         label = [STORE_TYPE[t] for t in 1:4])\nfor (col, tx) in ((\"non_taxed\", 0), (\"taxed\", 1))\n    taxed_counts[!, col] = [sum((dat.store_type .== t) .& (dat.taxed .== tx)) for t in 1:4]\nend\ntaxed_counts.share_taxed = round.(\n    100 .* taxed_counts.taxed ./ (taxed_counts.taxed .+ taxed_counts.non_taxed), digits = 1)\n\ntaxed_counts\n```\n\n::: {#freq-taxed .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">store_type</th><th style = \"text-align: left;\">label</th><th style = \"text-align: left;\">non_taxed</th><th style = \"text-align: left;\">taxed</th><th style = \"text-align: left;\">share_taxed</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: right;\">291</td><td style = \"text-align: right;\">253</td><td style = \"text-align: right;\">46.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: right;\">542</td><td style = \"text-align: right;\">583</td><td style = \"text-align: right;\">51.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: right;\">132</td><td style = \"text-align: right;\">130</td><td style = \"text-align: right;\">49.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: right;\">109</td><td style = \"text-align: right;\">135</td><td style = \"text-align: right;\">55.3</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nRoughly 60% of observations are taxed beverages in every store type, so the taxed/non-taxed\nsplit is not confounded with store type.\n\n::: {#cell-freq-product-type .cell execution_count=1}\n``` {.julia .cell-code}\nwave_table(dat, :type)\n```\n\n::: {#freq-product-type .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>13×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">type</th><th style = \"text-align: left;\">DEC2014</th><th style = \"text-align: left;\">JUN2015</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">ENERGY</td><td style = \"text-align: right;\">56</td><td style = \"text-align: right;\">58</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">ENERGY-DIET</td><td style = \"text-align: right;\">49</td><td style = \"text-align: right;\">54</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">JUICE</td><td style = \"text-align: right;\">70</td><td style = \"text-align: right;\">64</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">JUICE DRINK</td><td style = \"text-align: right;\">19</td><td style = \"text-align: right;\">17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">MILK</td><td style = \"text-align: right;\">63</td><td style = \"text-align: right;\">61</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">SODA</td><td style = \"text-align: right;\">239</td><td style = \"text-align: right;\">262</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">SODA-DIET</td><td style = \"text-align: right;\">128</td><td style = \"text-align: right;\">174</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">SPORT</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">SPORT-DIET</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">TEA</td><td style = \"text-align: right;\">52</td><td style = \"text-align: right;\">45</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">TEA-DIET</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">WATER</td><td style = \"text-align: right;\">48</td><td style = \"text-align: right;\">38</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">WATER-SWEET</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">1</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nSoda dominates (239 in December, 262 in June) and diet soda is second; sport drinks and\nsweetened water have a handful of observations each. The survey was designed around the\nbeverages the tax targets, and stocks more of what stores actually carry — so the counts\nreflect both the sampling design and shelf reality.\n\n## Q3. Conditional means {#p1-q3}\n\nThe paper's method, which the question asks us to follow: keep only products present in **all\nthree waves at the same store**, and only non-supplementary items (`supp == 0`).\n\nThe reason is Q2's finding. Comparing the December mean against the June mean over *different\nbaskets* measures two things at once — the price change, and the change in which products were\non the shelf. Restricting to a matched basket removes the second.\n\nThe book does this with a nested loop over every store × product pair. `groupby` states the\nsame condition directly and does it in one pass:\n\n::: {#cell-balanced-panel .cell execution_count=1}\n``` {.julia .cell-code}\n# Keep (store, product) pairs observed in all three waves.\ncomplete = combine(groupby(dat, [:store_id, :product_id]),\n                   :time => (t -> length(unique(t)) == 3) => :all_waves)\n\nbalanced = innerjoin(dat, complete[complete.all_waves, [:store_id, :product_id]];\n                     on = [:store_id, :product_id])\nbalanced = balanced[balanced.supp .== 0, :]\n\n(rows = nrow(balanced),\n stores = length(unique(balanced.store_id)),\n products = length(unique(balanced.product_id)))\n```\n\n::: {#balanced-panel .cell-output .cell-output-display execution_count=1}\n```\n(rows = 939, stores = 24, products = 55)\n```\n:::\n:::\n\n\n\n939 observations, 24 stores, 55 products — a much smaller but genuinely comparable sample.\n\n::: {#cell-price-table .cell execution_count=1}\n``` {.julia .cell-code}\nprice_means = combine(\n    groupby(balanced, [:taxed, :store_type, :time]),\n    nrow => :n,\n    :price_per_oz_c => (x -> round(mean(x), digits = 2)) => :mean_cents_per_oz)\n\nsort!(price_means, [:taxed, :store_type, :time])\nprice_means.store = [STORE_TYPE[t] for t in price_means.store_type]\nselect(price_means, :taxed, :store, :time, :n, :mean_cents_per_oz)\n```\n\n::: {#price-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>24×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">taxed</th><th style = \"text-align: left;\">store</th><th style = \"text-align: left;\">time</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean_cents_per_oz</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">11.19</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">11.48</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">11.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">70</td><td style = \"text-align: right;\">13.67</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">70</td><td style = \"text-align: right;\">13.82</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">70</td><td style = \"text-align: right;\">13.37</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">15.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">16.08</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">15.44</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">16.94</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">16.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">17.04</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">15.62</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">16.93</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">16.68</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">101</td><td style = \"text-align: right;\">15.85</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">101</td><td style = \"text-align: right;\">16.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">101</td><td style = \"text-align: right;\">15.49</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">18.18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">19.08</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">18.63</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">22</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: left;\">DEC2014</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">19.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">23</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: left;\">JUN2015</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">20.34</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">24</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: left;\">MAR2015</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">19.24</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery value reproduces the book's published solutions exactly. Note `n` is identical across\nwaves within each cell (36, 36, 36 for large supermarkets) — that is the balanced panel working.\n\nTwo patterns, before calculating anything:\n\n- **Taxed beverages cost more per ounce than untaxed ones in every store type and every wave**,\n  including December 2014, *before* the tax applied. Sodas are sold in smaller, pricier-per-ounce\n  formats than milk or juice.\n- **Prices rise between December and June** for taxed beverages, and rise much less for untaxed ones.\n\n**Could we assess the tax by comparing taxed against untaxed prices in a single period?** No.\nThe first pattern is the reason: taxed and untaxed beverages already differed by 4–5 cents per\nounce before the tax existed. That gap measures what kind of drinks they are, not the tax. Only\nthe *change* in the gap is informative.\n\n## Q4. Price changes {#p1-q4}\n\n::: {#cell-changes .cell execution_count=1}\n``` {.julia .cell-code}\nchanges = unstack(select(price_means, :taxed, :store_type, :time, :mean_cents_per_oz),\n                  [:taxed, :store_type], :time, :mean_cents_per_oz)\nchanges.change = round.(changes.JUN2015 .- changes.DEC2014, digits = 2)\nchanges.store = [STORE_TYPE[t] for t in changes.store_type]\n\nselect(sort(changes, [:taxed, :store_type]),\n       :taxed, :store, :DEC2014, :JUN2015, :change)\n```\n\n::: {#changes .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">taxed</th><th style = \"text-align: left;\">store</th><th style = \"text-align: left;\">DEC2014</th><th style = \"text-align: left;\">JUN2015</th><th style = \"text-align: left;\">change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: right;\">11.19</td><td style = \"text-align: right;\">11.48</td><td style = \"text-align: right;\">0.29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: right;\">13.67</td><td style = \"text-align: right;\">13.82</td><td style = \"text-align: right;\">0.15</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: right;\">15.2</td><td style = \"text-align: right;\">16.08</td><td style = \"text-align: right;\">0.88</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: right;\">16.94</td><td style = \"text-align: right;\">16.96</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: right;\">15.62</td><td style = \"text-align: right;\">16.93</td><td style = \"text-align: right;\">1.31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: right;\">15.85</td><td style = \"text-align: right;\">16.0</td><td style = \"text-align: right;\">0.15</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: right;\">18.18</td><td style = \"text-align: right;\">19.08</td><td style = \"text-align: right;\">0.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: right;\">19.41</td><td style = \"text-align: right;\">20.34</td><td style = \"text-align: right;\">0.93</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-changes .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 440))\nax = Axis(fig[1, 1];\n          title = \"Taxed beverages rose more than untaxed ones\",\n          ylabel = \"Change in price (cents per ounce)\",\n          xticks = (1:4, [\"Large\\nsupermarket\", \"Small\\nsupermarket\",\n                          \"Pharmacy\", \"Gas\\nstation\"]))\nhlines!(ax, 0; color = BASELINE, linewidth = 1)\n\nfor (i, tx) in enumerate((0, 1))\n    rows = sort(changes[changes.taxed .== tx, :], :store_type)\n    xs = collect((1:4) .+ (i - 1.5) * 0.2)\n    barplot!(ax, xs, rows.change; width = 0.16, color = series_color(i),\n             label = tx == 1 ? \"Taxed\" : \"Untaxed\")\n    for (x, v) in zip(xs, rows.change)\n        text!(ax, x, v; text = string(v), fontsize = 10,\n              align = (:center, v < 0 ? :top : :bottom), offset = (0, v < 0 ? -4 : 4))\n    end\nend\n\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Change in mean price per ounce between December 2014 and June 2015, by store type. Taxed beverages rose more than untaxed ones in three of four store types. Values are in the table above.](index_files/figure-html/fig-changes-output-1.svg){#fig-changes}\n:::\n:::\n\n\n\nThe large-supermarket contrast is the clearest: taxed beverages up **1.31** cents per ounce\nagainst **0.29** for untaxed. Gas stations show the opposite sign, on 22 taxed observations.\n\n## Q5. Are the changes statistically distinguishable? {#p1-q5}\n\nBecause the panel is balanced, each store-product appears in both waves, so the price change\ncan be computed per item and tested as a paired difference.\n\n::: {#cell-pvalues .cell execution_count=1}\n``` {.julia .cell-code}\nwide = unstack(select(balanced, :store_id, :product_id, :store_type, :taxed,\n                      :time, :price_per_oz_c),\n               [:store_id, :product_id, :store_type, :taxed], :time, :price_per_oz_c)\nwide.diff = wide.JUN2015 .- wide.DEC2014\n\ntests = DataFrame(store_type = Int[], taxed = Int[], n = Int[],\n                  mean_change = Float64[], p_value = Float64[])\nfor st in 1:4, tx in (0, 1)\n    # `unstack` widens the element type to admit missing even when the balanced\n    # panel leaves none, and the test needs a concrete Float64 vector.\n    d = collect(skipmissing(wide[(wide.store_type .== st) .& (wide.taxed .== tx), :diff]))\n    t = OneSampleTTest(d)\n    push!(tests, (st, tx, length(d), round(mean(d), digits = 3),\n                  round(pvalue(t), digits = 4)))\nend\ntests.store = [STORE_TYPE[t] for t in tests.store_type]\nselect(tests, :store, :taxed, :n, :mean_change, :p_value)\n```\n\n::: {#pvalues .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">store</th><th style = \"text-align: left;\">taxed</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean_change</th><th style = \"text-align: left;\">p_value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">0.288</td><td style = \"text-align: right;\">0.0777</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Large supermarket</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">36</td><td style = \"text-align: right;\">1.312</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">70</td><td style = \"text-align: right;\">0.146</td><td style = \"text-align: right;\">0.3678</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Small supermarket</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">101</td><td style = \"text-align: right;\">0.144</td><td style = \"text-align: right;\">0.429</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">0.88</td><td style = \"text-align: right;\">0.3645</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Pharmacy</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">0.897</td><td style = \"text-align: right;\">0.3556</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">0.029</td><td style = \"text-align: right;\">0.9399</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Gas station</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">0.925</td><td style = \"text-align: right;\">0.3305</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nTaxed beverages in large supermarkets and pharmacies show increases that are unlikely under no\nreal change. Untaxed beverages mostly do not. The cell sizes are small — 18 to 36 items — so\nthese are indicative rather than decisive.\n\n**But no p-value here can establish that the tax caused the rise.** Every comparison in Part\n3.1 is Berkeley in December against Berkeley in June. Anything else that moved prices over\nthose six months — supplier costs, inflation, seasonal demand — is inside the estimate. That is\nwhat Part 3.2 addresses.\n\n# Part 3.2 — Comparison with prices elsewhere {#part-3.2}\n\n::: {#cell-read-dta .cell execution_count=1}\n``` {.julia .cell-code}\npos = DataFrame(readstat(rawpath(\"03\", \"public_use_weighted_prices2.dta\")))\npos = dropmissing(pos, :price)\n\n# Stata string columns arrive as String15/String31; plain String compares cleanly.\nfor c in (:location, :beverage_group, :tax)\n    pos[!, c] = String.(pos[!, c])\nend\npos.date = pos.year .+ (pos.month .- 1) ./ 12\n\n(rows = nrow(pos), years = extrema(pos.year),\n groups = sort(unique(pos.beverage_group)))\n```\n\n::: {#read-dta .cell-output .cell-output-display execution_count=1}\n```\n(rows = 2696, years = (2013.0, 2016.0), groups = [\"fruit drinks/flavored waters\", \"milk\", \"milk substitutes\", \"soda\", \"water\"])\n```\n:::\n:::\n\n\n\n## Q1. Were the comparison stores well chosen? {#p2-q1}\n\nThe comparison stores are in adjacent non-Berkeley areas. What makes a comparison group\nsuitable is not that it resembles Berkeley on every measure, but that its prices would have\n**moved the same way** had Berkeley not taxed. The pre-tax period is what evidences that, and\n@fig-prices below is the test: two years of prices before the tax, and the question of whether\nthe two locations track each other.\n\nThe paper's S5 Table shows the comparison stores differ from Berkeley's on neighbourhood\ncharacteristics — income and demographics. That matters for *levels*, which need not match, and\nmatters much less for *trends*, which do.\n\n## Q2. Prices by location and tax status {#p2-q2}\n\n::: {#cell-price-panel .cell execution_count=1}\n``` {.julia .cell-code}\nmonthly = combine(groupby(pos, [:year, :month, :date, :location, :tax]),\n                  :price => mean => :price)\nsort!(monthly, :date)\n\n# `unstack` spreads a single column, so the two-way tax x location split becomes\n# one series label first.\nlabelled = transform(monthly,\n    [:tax, :location] => ByRow((t, l) -> \"$t, $l\") => :series)\n\nfirst(unstack(select(labelled, :year, :month, :series, :price),\n              [:year, :month], :series, :price), 8)\n```\n\n::: {#price-panel .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">month</th><th style = \"text-align: left;\">Non-taxed, Berkeley</th><th style = \"text-align: left;\">Non-taxed, Non-Berkeley</th><th style = \"text-align: left;\">Taxed, Berkeley</th><th style = \"text-align: left;\">Taxed, Non-Berkeley</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">5.72248</td><td style = \"text-align: right;\">5.34864</td><td style = \"text-align: right;\">8.6928</td><td style = \"text-align: right;\">7.99157</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: right;\">5.80647</td><td style = \"text-align: right;\">5.36386</td><td style = \"text-align: right;\">8.65457</td><td style = \"text-align: right;\">8.18088</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">5.85825</td><td style = \"text-align: right;\">5.42451</td><td style = \"text-align: right;\">8.82269</td><td style = \"text-align: right;\">8.18687</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">5.85834</td><td style = \"text-align: right;\">5.64346</td><td style = \"text-align: right;\">9.02207</td><td style = \"text-align: right;\">8.24645</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">5.79133</td><td style = \"text-align: right;\">5.18173</td><td style = \"text-align: right;\">8.67854</td><td style = \"text-align: right;\">7.75679</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">5.76184</td><td style = \"text-align: right;\">5.03197</td><td style = \"text-align: right;\">8.57345</td><td style = \"text-align: right;\">7.4264</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">7.0</td><td style = \"text-align: right;\">5.90282</td><td style = \"text-align: right;\">5.09817</td><td style = \"text-align: right;\">8.23329</td><td style = \"text-align: right;\">7.19362</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2013.0</td><td style = \"text-align: right;\">8.0</td><td style = \"text-align: right;\">5.83173</td><td style = \"text-align: right;\">5.08038</td><td style = \"text-align: right;\">8.82165</td><td style = \"text-align: right;\">7.48876</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-prices .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 440))\nLabel(fig[0, 1:2], \"Berkeley's taxed prices step up after January 2015; untaxed prices don't\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nylims = extrema(monthly.price) .+ (-0.4, 0.4)\n\npanels = [\"Taxed\", \"Non-taxed\"]\n\n# Build the axes up front rather than capturing one from inside the loop: at top\n# level, assigning to an outer name inside `for` creates a local under Julia's\n# soft scope, so the captured reference would still be `nothing` in a script.\naxs = [Axis(fig[1, i]; title = \"$(panels[i]) beverages\", xlabel = \"Year\",\n            ylabel = i == 1 ? \"Mean price (cents per ounce)\" : \"\",\n            limits = (nothing, ylims)) for i in eachindex(panels)]\n\nfor (i, ax) in enumerate(axs)\n    vlines!(ax, 2015.0; color = BASELINE, linewidth = 1)\n    for (j, loc) in enumerate((\"Berkeley\", \"Non-Berkeley\"))\n        s = monthly[(monthly.tax .== panels[i]) .& (monthly.location .== loc), :]\n        lines!(ax, s.date, s.price; color = series_color(j), label = loc)\n    end\n    i == 2 && hideydecorations!(ax; grid = false)\nend\n\n# One shared legend from the left panel, rather than the same two entries twice.\nLegend(fig[2, 1:2], first(axs); orientation = :horizontal, framevisible = false)\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean price per ounce by location, split into taxed and untaxed beverages. The rule marks January 2015, when the tax took effect. Faceting by tax status keeps location on two colours rather than putting four series on one axis.](index_files/figure-html/fig-prices-output-1.svg){#fig-prices}\n:::\n:::\n\n\n\n**Untaxed beverages**: the two locations move broadly together, with Berkeley about 0.6 cents\nhigher throughout. Berkeley does drift up slightly faster over the period — Q3 puts a number on\nit — but the panels stay close and there is no step at January 2015.\n\n**Taxed beverages**: the two move together through 2013 and 2014, then separate once the tax\ntakes effect. Berkeley steps up sharply; the comparison areas continue on roughly their previous\npath. The gap goes from about 1.0 cents to about 1.7.\n\nThat pre-tax co-movement is what licenses the comparison: two series that tracked each other for\ntwo years and diverge when the policy changes is a far stronger basis than Berkeley rising alone.\n\n**Is it reasonable to conclude the tax affected prices?** Yes — the timing and the size of the\nstep in the taxed panel, with no matching step in the untaxed one, are hard to explain otherwise.\nBut the untaxed panel is a qualified control rather than a perfect one: Berkeley's untaxed prices\nalso rose a little faster than its neighbours', so some general Berkeley drift is present. Q3\nquantifies how much that matters.\n\n## Q3. Difference-in-differences {#p2-q3}\n\nThe chart's logic as a number. Take the change in Berkeley, subtract the change outside\nBerkeley, and what remains is the part not explained by whatever moved prices in both places:\n\n::: {#cell-did .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Mean price in a cell, using the book's windows: pre through Dec 2014, post from Mar 2015.\"\"\"\nfunction cell_mean(df, loc, tx, period)\n    s = df[(df.location .== loc) .& (df.tax .== tx), :]\n    rows = period === :pre ? s[s.date .< 2015.0, :] : s[s.date .>= 2015.0 + 2 / 12, :]\n    return mean(rows.price)\nend\n\ndid = DataFrame(tax = String[], berkeley_pre = Float64[], berkeley_post = Float64[],\n                other_pre = Float64[], other_post = Float64[])\nfor tx in (\"Taxed\", \"Non-taxed\")\n    push!(did, (tx,\n        cell_mean(pos, \"Berkeley\", tx, :pre),  cell_mean(pos, \"Berkeley\", tx, :post),\n        cell_mean(pos, \"Non-Berkeley\", tx, :pre), cell_mean(pos, \"Non-Berkeley\", tx, :post)))\nend\n\ndid.berkeley_change = did.berkeley_post .- did.berkeley_pre\ndid.other_change = did.other_post .- did.other_pre\ndid.diff_in_diff = did.berkeley_change .- did.other_change\n\nselect(transform(did, names(did, Float64) .=> ByRow(x -> round(x, digits = 3)); renamecols = false),\n       :tax, :berkeley_change, :other_change, :diff_in_diff)\n```\n\n::: {#did .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">tax</th><th style = \"text-align: left;\">berkeley_change</th><th style = \"text-align: left;\">other_change</th><th style = \"text-align: left;\">diff_in_diff</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Taxed</td><td style = \"text-align: right;\">1.549</td><td style = \"text-align: right;\">0.814</td><td style = \"text-align: right;\">0.735</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Non-taxed</td><td style = \"text-align: right;\">0.474</td><td style = \"text-align: right;\">0.342</td><td style = \"text-align: right;\">0.132</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nFor **taxed** beverages the difference-in-differences is **+0.74 cents per ounce** against a tax\nof exactly 1 cent — roughly **74% pass-through** to the shelf. Distributors and retailers\nabsorbed about a quarter of it. That is in line with the published estimates for Berkeley, and\nit is the substantive answer to the project's question: the tax reached the shelf, but not all\nof it did.\n\nFor **untaxed** beverages the same calculation gives **+0.13**. Small next to 0.74, but not zero\n— and the test below says it is not noise either. That matters for how much weight the 0.74 can\ncarry, so it is worth being precise rather than treating the untaxed row as a clean null.\n\n::: {#cell-did-test .cell execution_count=1}\n``` {.julia .cell-code}\n# Berkeley's post-tax deviation from the comparison areas, month by month. Testing\n# whether the gap widened rather than comparing raw prices removes the level\n# difference between the two locations.\nfunction monthly_gap(tx)\n    b = monthly[(monthly.tax .== tx) .& (monthly.location .== \"Berkeley\"), :]\n    o = monthly[(monthly.tax .== tx) .& (monthly.location .== \"Non-Berkeley\"), :]\n    j = innerjoin(select(b, :date, :price => :berkeley),\n                  select(o, :date, :price => :other); on = :date)\n    j.gap = j.berkeley .- j.other\n    return j\nend\n\ngap_tests = DataFrame(tax = String[], gap_pre = Float64[], gap_post = Float64[],\n                      widening = Float64[], p_value = Float64[])\nfor tx in (\"Taxed\", \"Non-taxed\")\n    j = monthly_gap(tx)\n    pre = j[j.date .< 2015.0, :gap]\n    post = j[j.date .>= 2015.0 + 2 / 12, :gap]\n    push!(gap_tests, (tx, round(mean(pre), digits = 3), round(mean(post), digits = 3),\n                      round(mean(post) - mean(pre), digits = 3),\n                      round(pvalue(UnequalVarianceTTest(post, pre)), digits = 5)))\nend\n\ngap_tests\n```\n\n::: {#did-test .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">tax</th><th style = \"text-align: left;\">gap_pre</th><th style = \"text-align: left;\">gap_post</th><th style = \"text-align: left;\">widening</th><th style = \"text-align: left;\">p_value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Taxed</td><td style = \"text-align: right;\">0.973</td><td style = \"text-align: right;\">1.725</td><td style = \"text-align: right;\">0.752</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Non-taxed</td><td style = \"text-align: right;\">0.637</td><td style = \"text-align: right;\">0.773</td><td style = \"text-align: right;\">0.136</td><td style = \"text-align: right;\">0.00303</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe taxed gap widens by **0.75** cents per ounce with a *p*-value of essentially zero. The\nuntaxed gap widens by **0.14** with *p* = 0.003 — small, but statistically distinguishable from\nno change.\n\n**That untaxed result is a problem for the clean story, and worth taking seriously.** The\ndifference-in-differences rests on the comparison areas standing in for what Berkeley would have\ndone anyway. Untaxed drinks, which the tax never touched, should therefore show no widening. They\nshow a little. So something besides the tax was pushing Berkeley's beverage prices up relative to\nits neighbours over this period.\n\nTwo readings, and the data here cannot separate them:\n\n- **A Berkeley-wide price drift.** If whatever moved untaxed prices moved taxed ones equally, the\n  tax effect is nearer 0.74 − 0.13 ≈ **0.6 cents per ounce**, or 60% pass-through.\n- **A composition or measurement difference** specific to untaxed drinks, in which case 0.74\n  stands.\n\nEither way the qualitative conclusion survives: 0.13 is small beside 0.75, and the taxed\nwidening is roughly five times larger and begins when the tax does. But the honest interval on\npass-through is something like 60–75%, not a point estimate.\n\n**What the p-values do and do not tell us.** They address one question: could a difference this\nsize arise from ordinary month-to-month variation. They say nothing about whether the comparison\ngroup was well chosen — and the untaxed row is precisely where that assumption shows a crack. A\nbadly chosen comparison area would still produce a confident *p*-value, for a meaningless\nestimate. The *p*-value tests the difference, not the design.\n\n## Q4. Consumption behaviour {#p2-q4}\n\nThe paper reports sugar-sweetened beverage sales falling roughly 10% in Berkeley while rising\nslightly in the comparison areas, with no fall in total beverage calories sold and a rise in\nwater sales — consistent with substitution toward untaxed drinks rather than drinking less\noverall.\n\nThree explanations consistent with a ~1 cent per ounce price rise producing that:\n\n- **Substitution, not abstention.** The tax changes relative prices within the category. Water\n  and milk became cheaper relative to soda, and that is the margin shoppers moved on.\n- **Cross-border shopping.** Berkeley is small and bordered by untaxed cities. Some of the sales\n  decline is purchases relocating rather than consumption falling — which is why the sales\n  figures are weaker evidence about consumption than they first appear.\n- **Salience beyond price.** The tax was a publicised local campaign. Some response may be to\n  the message rather than to the cent.\n\n## Q5. Strengths and limitations {#p2-q5}\n\n**Strengths.** A genuine policy change rather than a laboratory manipulation; a comparison group\nwhose pre-tax prices track Berkeley's for two years; two independent data sources — hand-collected\nshelf prices and point-of-sale records — pointing the same way.\n\n**Limitations**, most consequential first, with what would address each:\n\n1. **The untaxed control is not perfectly parallel.** Berkeley's untaxed prices rose 0.13 cents\n   per ounce faster than the comparison areas' (Q3), which is small but detectable. Pass-through\n   is therefore bounded at roughly 60–75% rather than pinned at one number. More pre-tax years,\n   or several comparison areas rather than one aggregate, would tighten it.\n2. **26 stores, and a matched basket of 55 products.** Q3's balanced panel bought comparability\n   at the cost of sample size, and cells of 18 observations support weak inference. A larger\n   store panel is the only fix.\n2. **Berkeley is one small city.** It is unusually affluent, politically distinctive, and\n   surrounded by untaxed neighbours. None of that transfers automatically to a larger or poorer\n   jurisdiction. Later taxes in Philadelphia, Seattle and Mexico are the replication.\n3. **Cross-border shopping contaminates the comparison in both directions.** If Berkeley\n   shoppers buy soda outside the city, sales fall in Berkeley *and* rise in the comparison area,\n   which inflates the estimated difference.\n4. **Shelf prices are not transaction prices.** Promotions, multi-buys and loyalty discounts are\n   invisible in a shelf survey. Scanner data covers this and is what the second file provides.\n5. **Six months is short.** Pass-through can keep adjusting as contracts are renegotiated, so an\n   estimate at six months need not be the long-run one.\n\n## Q6. Designing the experiment {#p2-q6}\n\nWith authority over two neighbouring towns, the design problem is to get comparability by\nconstruction rather than by argument.\n\n- **Randomise which town is taxed.** With only two towns randomisation cannot balance\n  characteristics, so it does not solve much on its own — but it does remove the worst threat,\n  which is a town being selected for taxation *because* of its consumption patterns.\n- **Measure both towns for at least a year beforehand.** This is the most valuable single step.\n  Pre-treatment data is what lets you verify parallel trends instead of assuming them, and it is\n  exactly what makes @fig-prices persuasive.\n- **Choose non-adjacent towns, or measure the border.** Adjacency is what makes cross-border\n  shopping possible. If the towns must be neighbours, survey stores by distance from the border\n  so leakage can be estimated rather than ignored.\n- **Track untaxed products in the same stores.** They are the within-experiment control: a\n  spurious local shock moves them too, and a real tax does not.\n- **Announce and implement on a known date**, and record prices monthly on both sides of it, so\n  the timing of any change can be attributed rather than inferred.\n- **Collect transaction data, not just shelf prices**, and total beverage volume rather than only\n  taxed volume — otherwise substitution toward untaxed drinks reads as a fall in consumption.\n\nThe structural point is the one Part 3.1 illustrated by falling short of it: a before-and-after\ncomparison measures the policy plus everything else that changed. A comparison group that would\nhave moved the same way is what separates them, and pre-treatment data is the only way to know\nwhether you have one.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading a named Excel sheet | Setup | `XLSX.readtable(path, \"Data\")` |\n| Reading a Stata file | Part 3.2 | `readstat(path)` (ReadStatTables.jl) |\n| Frequency tables across waves | Q3.2 | `groupby` + counts, `unstack` |\n| Balanced panel construction | Q3.3 | `groupby` + `length(unique(t)) == 3`, `innerjoin` |\n| Conditional means | Q3.3 | `combine(groupby(df, [...]), col => mean)` |\n| Long to wide | Q3.4 | `unstack(df, keys, :time, :value)` |\n| Paired *t*-test on differences | Q3.5 | `OneSampleTTest(x .- y)` |\n| Difference-in-differences | Q3.3 | cell means, then difference of differences |\n| Composite encoding over 4 series | Q3.2 | facet by tax status, colour by location |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}