{
  "hash": "2e3919a79d8b0e6ab7a5725b54960ed3",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"4. Measuring wellbeing\"\nsubtitle: \"GDP, the HDI, and what an index leaves out\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nGDP per capita is the default measure of how well a country is doing. This project takes it\napart — what it is made of, how its composition differs across countries — and then builds a\nrival, the Human Development Index, from scratch to see how much the ranking depends on what\nyou choose to measure.\n\n- **[Part 4.1](#part-4.1)** — GDP and its components as a measure of material wellbeing\n- **[Part 4.2](#part-4.2)** — the HDI as a measure of wellbeing\n\nNew concepts: **index**, time series against cross-sectional data, and the **geometric mean** —\nthe choice of average that stops a country compensating for a collapse in one dimension by\nexcelling in another. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/04-01.html),\n[R walk-throughs](https://books.core-econ.org/doing-economics/book/text/04-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/04-04.html).\n\n## The data\n\n| | |\n|---|---|\n| **GDP** | UN National Accounts Main Aggregates, GDP and its breakdown at constant prices in US dollars, 220 countries, 1970–2024 |\n| **HDI** | UNDP Human Development Report 2025, composite indices complete time series |\n| **Alternatives** | World Bank WDI via its public API: under-five mortality, primary completion, household consumption per capita |\n\n::: {.callout-note}\n## Three notes on sources\n\n**The UN has rebased.** The book uses constant *2010* prices; the current file is constant\n*2020* prices. This matters more than it sounds: shares of **real** GDP depend on the base year,\nbecause components carry different deflators. Shares computed here differ from the book's by up\nto 0.06, and are more accurate for recent years than a 2010 base would be. Q4 returns to this.\n\n**The HDR arrives two ways.** The book reads the statistical annex spreadsheet, whose header\nspans seven rows with development-group labels interleaved among the data. UNDP also publishes\nthe same numbers as a tidy CSV, which is what this uses.\n\n**The World Bank indicators come from the API, not the download tool.** The book has you click\nthrough an interactive query builder. Requesting the series by indicator code is reproducible,\nwhich a manual download is not.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, CSV, DataFrames, JSON3\nusing Statistics\nusing StatsBase: competerank\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n# Part 4.1 — GDP and its components {#part-4.1}\n\nThe UN file puts years across the columns and one row per country-indicator. The header sits on\nrow 3, which is the book's `skip = 2`:\n\n::: {#cell-read-un .cell execution_count=1}\n``` {.julia .cell-code}\nun = DataFrame(XLSX.readtable(rawpath(\"04\", \"un-gdp-constant-usd.xlsx\"),\n                              \"Download-GDPconstant-USD-countr\"; first_row = 3))\nun.Country = String.(un.Country)\nun.IndicatorName = String.(un.IndicatorName)\n\nconst YEARS = 1970:2024\nconst GDP = \"Gross Domestic Product (GDP)\"\nconst HOUSEHOLD = \"Household consumption expenditure (including Non-profit institutions serving households)\"\nconst GOVERNMENT = \"General government final consumption expenditure\"\nconst CAPITAL = \"Gross capital formation\"\nconst EXPORTS = \"Exports of goods and services\"\nconst IMPORTS = \"Imports of goods and services\"\n\n(rows = nrow(un), countries = length(unique(un.Country)),\n indicators = length(unique(un.IndicatorName)))\n```\n\n::: {#read-un .cell-output .cell-output-display execution_count=1}\n```\n(rows = 3674, countries = 220, indicators = 17)\n```\n:::\n:::\n\n\n\nReshaping to long format makes everything downstream simpler — one row per country, indicator\nand year, which is what both the charts and the share calculations want:\n\n::: {#cell-tidy-un .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Coerce a spreadsheet cell to `Float64`, or `missing` if it is not a number.\"\"\"\nas_number(x) = x === missing ? missing :\n               x isa Number ? Float64(x) : tryparse(Float64, string(x))\n\ngdp_long = stack(un, string.(YEARS);\n                 variable_name = :year_str, value_name = :raw)\ngdp_long.year = parse.(Int, gdp_long.year_str)\ngdp_long.value = as_number.(gdp_long.raw)\nselect!(gdp_long, :Country => :country, :IndicatorName => :indicator, :year, :value)\n\nfirst(dropmissing(gdp_long), 4)\n```\n\n::: {#tidy-un .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">value</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Afghanistan</td><td style = \"text-align: left;\">Final consumption expenditure</td><td style = \"text-align: right;\">1970</td><td style = \"text-align: right;\">2.98257e9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Afghanistan</td><td style = \"text-align: left;\">Household consumption expenditure (including Non-profit institutions serving households)</td><td style = \"text-align: right;\">1970</td><td style = \"text-align: right;\">2.68965e9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Afghanistan</td><td style = \"text-align: left;\">General government final consumption expenditure</td><td style = \"text-align: right;\">1970</td><td style = \"text-align: right;\">3.19431e8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Afghanistan</td><td style = \"text-align: left;\">Gross capital formation</td><td style = \"text-align: right;\">1970</td><td style = \"text-align: right;\">1.35706e9</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n## Q1. Which countries have complete data {#p1-q1}\n\n::: {#cell-completeness .cell execution_count=1}\n``` {.julia .cell-code}\ngdp_only = gdp_long[gdp_long.indicator .== GDP, :]\n\ncompleteness = combine(groupby(gdp_only, :country),\n                       :value => (v -> sum(!ismissing, v)) => :years_available)\ncomplete = completeness[completeness.years_available .== length(YEARS), :]\n\n(countries = nrow(completeness),\n complete = nrow(complete),\n pct_incomplete = round(100 * (1 - nrow(complete) / nrow(completeness)), digits = 0))\n```\n\n::: {#completeness .cell-output .cell-output-display execution_count=1}\n```\n(countries = 220, complete = 179, pct_incomplete = 19.0)\n```\n:::\n:::\n\n\n\n**179 of 220 countries** have GDP for every year, so **19% are missing at least one** — matching\nthe book's figures exactly, even though this file now runs to 2024 rather than 2016. The 41\nincomplete cases are mostly states that did not exist for the whole period: the post-Soviet\nrepublics, South Sudan, Timor-Leste.\n\nThis is the first thing to check in any panel dataset, because it determines what comparisons\nare available. A chart of \"world GDP since 1970\" built from whichever countries happened to\nreport would confuse countries entering the data with the world growing.\n\n::: {#cell-freq-years .cell execution_count=1}\n``` {.julia .cell-code}\nfreqtable_binned(completeness.years_available;\n                 breaks = [0, 10, 20, 30, 40, 50, 55], closed = :right)\n```\n\n::: {#freq-years .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">bin</th><th style = \"text-align: left;\">count</th><th style = \"text-align: left;\">proportion</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: left;\">(0, 10]</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: right;\">20.0</td><td style = \"text-align: left;\">(10, 20]</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">0.0181818</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">20.0</td><td style = \"text-align: right;\">30.0</td><td style = \"text-align: left;\">(20, 30]</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.0272727</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">30.0</td><td style = \"text-align: right;\">40.0</td><td style = \"text-align: left;\">(30, 40]</td><td style = \"text-align: right;\">29</td><td style = \"text-align: right;\">0.131818</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">40.0</td><td style = \"text-align: right;\">50.0</td><td style = \"text-align: left;\">(40, 50]</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0.00909091</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">50.0</td><td style = \"text-align: right;\">55.0</td><td style = \"text-align: left;\">(50, 55]</td><td style = \"text-align: right;\">179</td><td style = \"text-align: right;\">0.813636</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n## Q2. Net exports {#p1-q2}\n\nNet exports are exports minus imports, and are not in the file as a row of their own — they have\nto be constructed:\n\n::: {#cell-net-exports .cell execution_count=1}\n``` {.julia .cell-code}\nwide = unstack(gdp_long, [:country, :year], :indicator, :value)\nwide.net_exports = wide[!, EXPORTS] .- wide[!, IMPORTS]\n\nfocus = [\"China\", \"United States\", \"India\"]\n# `Cols` because the indicator names are Strings while :country is a Symbol, and\n# DataFrames will not mix the two in one selector vector.\nsample = wide[in(focus).(wide.country) .& (wide.year .== 2023),\n              Cols(:country, EXPORTS, IMPORTS, :net_exports)]\nsample\n```\n\n::: {#net-exports .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">Exports of goods and services</th><th style = \"text-align: left;\">Imports of goods and services</th><th style = \"text-align: left;\">net_exports</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">3.36991e12</td><td style = \"text-align: right;\">2.78169e12</td><td style = \"text-align: right;\">5.88216e11</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">7.31411e11</td><td style = \"text-align: right;\">7.73165e11</td><td style = \"text-align: right;\">-4.17534e10</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">2.54807e12</td><td style = \"text-align: right;\">3.42776e12</td><td style = \"text-align: right;\">-8.79698e11</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nChina runs a surplus; the United States a deficit. Net exports is the one GDP component that can\nbe negative, which matters for charting: it cannot be stacked with the others.\n\n## Q3. Components over time {#p1-q3}\n\n::: {#cell-fig-components .cell execution_count=1}\n``` {.julia .cell-code}\ncomponents = [(HOUSEHOLD, \"Household consumption\"), (GOVERNMENT, \"Government consumption\"),\n              (CAPITAL, \"Gross capital formation\"), (:net_exports, \"Net exports\")]\n\nfig = Figure(size = (900, 560))\nLabel(fig[0, 1:2], \"China's capital formation overtook US levels; consumption did not\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\npair = wide[in([\"China\", \"United States\"]).(wide.country), :]\n\nfor (i, (col, label)) in enumerate(components)\n    r, c = fldmod1(i, 2)\n    ax = Axis(fig[r, c]; title = label,\n              xlabel = r == 2 ? \"Year\" : \"\",\n              ylabel = c == 1 ? \"Trillions of 2020 US\\$\" : \"\")\n    hlines!(ax, 0; color = BASELINE, linewidth = 1)\n    for (j, country) in enumerate((\"China\", \"United States\"))\n        s = dropmissing(pair[pair.country .== country, [:year, Symbol(col)]], Symbol(col))\n        lines!(ax, s.year, s[!, Symbol(col)] ./ 1e12;\n               color = series_color(j), label = country)\n    end\n    i == 1 && axislegend(ax; position = :lt, framevisible = false)\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![GDP components for China and the United States at constant 2020 prices. Faceting by component keeps each panel to two series, so only two hues are needed; a single panel with all four components would need four, which is past the point where adjacent colours stay reliably distinguishable.](index_files/figure-html/fig-components-output-1.svg){#fig-components}\n:::\n:::\n\n\n\n**(a) and (b)** Household consumption is the largest component for both countries, and the US\nlevel is still well above China's. Government consumption is much the smaller component in\nboth. Capital formation is where they diverge completely: China's rises from almost nothing to\nabove the US level around 2010.\n\n**(c)** The US series grow smoothly, interrupted at 2008–09 in consumption and sharply in capital\nformation — investment is the volatile component in a recession, consumption the stable one.\nChina's series are flat until the early 1990s and then climb steeply.\n\n**(d)** Net exports show what the levels hide: the US deficit widens from the 1980s, China's\nsurplus peaks around 2007 and then narrows.\n\n## Q4. Components as proportions {#p1-q4}\n\n::: {#cell-shares .cell execution_count=1}\n``` {.julia .cell-code}\nshare_of_gdp(col) = wide[!, Symbol(col)] ./ wide[!, GDP]\n\nshares = DataFrame(country = wide.country, year = wide.year,\n                   household = share_of_gdp(HOUSEHOLD),\n                   government = share_of_gdp(GOVERNMENT),\n                   capital = share_of_gdp(CAPITAL),\n                   net_exports = share_of_gdp(:net_exports))\n\nsnapshot = shares[in([\"Brazil\", \"China\", \"India\", \"Germany\", \"United States\"]).(shares.country) .&\n                  (shares.year .== 2015), :]\ntransform(snapshot, names(snapshot, Float64) .=> ByRow(x -> round(x, digits = 2));\n          renamecols = false)\n```\n\n::: {#shares .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">household</th><th style = \"text-align: left;\">government</th><th style = \"text-align: left;\">capital</th><th style = \"text-align: left;\">net_exports</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">0.627401</td><td style = \"text-align: right;\">0.204512</td><td style = \"text-align: right;\">0.170902</td><td style = \"text-align: right;\">-0.0103888</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">0.379306</td><td style = \"text-align: right;\">0.176028</td><td style = \"text-align: right;\">0.425578</td><td style = \"text-align: right;\">0.0278189</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">0.522856</td><td style = \"text-align: right;\">0.198986</td><td style = \"text-align: right;\">0.197605</td><td style = \"text-align: right;\">0.0786808</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">0.600596</td><td style = \"text-align: right;\">0.107052</td><td style = \"text-align: right;\">0.302888</td><td style = \"text-align: right;\">0.0049065</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">0.667757</td><td style = \"text-align: right;\">0.145423</td><td style = \"text-align: right;\">0.208781</td><td style = \"text-align: right;\">-0.022186</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {.callout-note}\n## Why these differ from the book's\n\nThe book reports 2015 household shares of 0.64 (Brazil), 0.37 (China), 0.55 (India), 0.55\n(Germany) and 0.62 (US). The figures above are 0.63, 0.38, 0.60, 0.52 and 0.67.\n\nThe cause is the rebasing. A share of *real* GDP is a ratio of two deflated series, and the\ndeflators are rebased along with the level, so the ratio moves when the base year moves. The\neffect grows with distance from the base year: a 2015 observation is five years from a 2020 base\nbut five years the other side of a 2010 one, and the composition of prices changed a great deal\nover that decade.\n\nA cross-check: US household consumption is about 68% of GDP at current prices, which the\n2020-base figure of 0.67 is close to and the 2010-base 0.62 is not. For share analysis a base\nyear near the years of interest — or current prices outright — is the better choice.\n:::\n\n::: {#cell-fig-shares .cell execution_count=1}\n``` {.julia .cell-code}\nstack_cols = [(:household, \"Household\"), (:government, \"Government\"), (:capital, \"Capital formation\")]\n\nfig = Figure(size = (900, 440))\nLabel(fig[0, 1:2], \"China invests about half its GDP; the US consumes about two-thirds of its\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\naxs = [Axis(fig[1, i]; title = c, xlabel = \"Year\",\n            ylabel = i == 1 ? \"Share of GDP\" : \"\", limits = (nothing, (0, 1)))\n       for (i, c) in enumerate((\"China\", \"United States\"))]\n\nfor (i, country) in enumerate((\"China\", \"United States\"))\n    s = dropmissing(shares[shares.country .== country, :],\n                    [:household, :government, :capital])\n    # Stack by accumulating: each band is drawn between the running total below it\n    # and the running total including it.\n    lower = zeros(nrow(s))\n    for (j, (col, label)) in enumerate(stack_cols)\n        upper = lower .+ s[!, col]\n        band!(axs[i], s.year, lower, upper;\n              color = (series_color(j), 0.85), label = label)\n        lower = upper\n    end\n    i == 2 && hideydecorations!(axs[i]; grid = false)\nend\n\nLegend(fig[2, 1:2], first(axs); orientation = :horizontal, framevisible = false)\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Composition of GDP over time. The three stacked components sum to total final expenditure before net exports, which is excluded because it can be negative and so cannot be stacked.](index_files/figure-html/fig-shares-output-1.svg){#fig-shares}\n:::\n:::\n\n\n\n**(c) and (d)** Proportions answer a question levels cannot. In levels, everything about the US\nis larger than almost everything about India, so the charts mostly show that the US economy is\nbig. In proportions the countries become comparable, and the structural difference appears:\nChina devotes roughly 43% of GDP to capital formation against the US's 21%, and consumes 38%\nagainst 67%.\n\nThat is the advantage of a proportion — it removes scale, which is usually the least interesting\nthing about a comparison between a large economy and a small one. The cost is that it hides\nscale entirely: a rising share can mean the numerator grew or the denominator shrank.\n\n## Q5. Comparing groups of countries {#p1-q5}\n\nThe book groups countries as developed, transition and developing using the UN's\nclassification, which is published only as a PDF. Rather than parse it, three countries stand in\nfor each group, named explicitly so the choice is visible rather than buried:\n\n::: {#cell-fig-groups .cell execution_count=1}\n``` {.julia .cell-code}\ngroups = [\"Developed\" => [\"United States\", \"Germany\", \"Japan\"],\n          \"Transition\" => [\"Russian Federation\", \"Kazakhstan\", \"Ukraine\"],\n          \"Developing\" => [\"India\", \"Brazil\", \"Nigeria\"]]\n\n# A country only earns a bar if all four shares are present for 2023, so a partial\n# row cannot silently plot as a short bar.\nsnapshot_2023 = dropmissing(shares[shares.year .== 2023, :],\n                            [:household, :government, :capital, :net_exports])\n\n# Wrapped in `let` so the running position counter is a genuine local. At top level\n# a `for` body assigning to an outer name gets its own local under Julia's soft\n# scope, which would leave `pos` undefined here.\nlayout = let\n    labels = String[]; positions = Float64[]; group_ticks = Tuple{Float64,String}[]\n    rows = NamedTuple[]\n    pos = 0.0\n    for (gname, members) in groups\n        first_pos = pos + 1\n        for country in members\n            s = snapshot_2023[snapshot_2023.country .== country, :]\n            if isempty(s)\n                @warn \"no complete 2023 shares for $country - omitted from the chart\"\n                continue\n            end\n            pos += 1\n            push!(labels, country); push!(positions, pos)\n            push!(rows, (household = s.household[1], government = s.government[1],\n                         capital = s.capital[1], net_exports = s.net_exports[1]))\n        end\n        push!(group_ticks, ((first_pos + pos) / 2, gname))\n        pos += 0.6\n    end\n    (; labels, positions, group_ticks, rows)\nend\n\nlabels, positions, group_ticks, rows = layout.labels, layout.positions,\n                                       layout.group_ticks, layout.rows\n\n# Leave headroom above the tallest stack for the category labels, so they sit\n# outside the bars rather than floating among them.\nstack_totals = [r.household + r.government + r.capital for r in rows]\ny_top = maximum(stack_totals) * 1.16\ny_bottom = min(0.0, minimum(r.net_exports for r in rows)) * 1.15\n\nfig = Figure(size = (900, 500))\nax = Axis(fig[1, 1]; title = \"Composition of GDP by development category, 2023\",\n          ylabel = \"Share of GDP\", xticks = (positions, labels),\n          xticklabelrotation = pi / 6, limits = (nothing, (y_bottom, y_top)))\nhlines!(ax, 0; color = BASELINE, linewidth = 1)\n\n# Offsets computed up front rather than accumulated in a loop variable: the running\n# total would be a fresh local on each iteration at top level (see the soft-scope\n# note on the R -> Julia page).\ncomponent_values = [[r[col] for r in rows] for (col, _) in stack_cols]\noffsets = [j == 1 ? zeros(length(rows)) : sum(component_values[1:j - 1])\n           for j in eachindex(stack_cols)]\n\nfor (j, (col, label)) in enumerate(stack_cols)\n    barplot!(ax, positions, component_values[j]; offset = offsets[j], width = 0.62,\n             color = series_color(j), label = label)\nend\nbarplot!(ax, positions, [r.net_exports for r in rows];\n         width = 0.62, color = series_color(4), label = \"Net exports\")\n\nfor (x, g) in group_ticks\n    text!(ax, x, y_top * 0.97; text = g, align = (:center, :top),\n          fontsize = 12, font = :bold, color = INK)\nend\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![GDP composition in 2023 for three countries from each UN development category. Net exports is shown separately because it can be negative.](index_files/figure-html/fig-groups-output-1.svg){#fig-groups}\n:::\n:::\n\n\n\n::: {#cell-group-table .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(country = labels,\n          household = round.([r.household for r in rows], digits = 2),\n          government = round.([r.government for r in rows], digits = 2),\n          capital = round.([r.capital for r in rows], digits = 2),\n          net_exports = round.([r.net_exports for r in rows], digits = 2))\n```\n\n::: {#group-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>9×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">household</th><th style = \"text-align: left;\">government</th><th style = \"text-align: left;\">capital</th><th style = \"text-align: left;\">net_exports</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">0.68</td><td style = \"text-align: right;\">0.14</td><td style = \"text-align: right;\">0.22</td><td style = \"text-align: right;\">-0.04</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">0.52</td><td style = \"text-align: right;\">0.22</td><td style = \"text-align: right;\">0.21</td><td style = \"text-align: right;\">0.05</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Japan</td><td style = \"text-align: right;\">0.53</td><td style = \"text-align: right;\">0.21</td><td style = \"text-align: right;\">0.25</td><td style = \"text-align: right;\">0.01</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Russian Federation</td><td style = \"text-align: right;\">0.56</td><td style = \"text-align: right;\">0.2</td><td style = \"text-align: right;\">0.3</td><td style = \"text-align: right;\">-0.05</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Kazakhstan</td><td style = \"text-align: right;\">0.54</td><td style = \"text-align: right;\">0.12</td><td style = \"text-align: right;\">0.32</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Ukraine</td><td style = \"text-align: right;\">0.76</td><td style = \"text-align: right;\">0.36</td><td style = \"text-align: right;\">0.19</td><td style = \"text-align: right;\">-0.28</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">0.6</td><td style = \"text-align: right;\">0.1</td><td style = \"text-align: right;\">0.3</td><td style = \"text-align: right;\">-0.01</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">0.63</td><td style = \"text-align: right;\">0.2</td><td style = \"text-align: right;\">0.16</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Nigeria</td><td style = \"text-align: right;\">0.78</td><td style = \"text-align: right;\">0.05</td><td style = \"text-align: right;\">0.22</td><td style = \"text-align: right;\">-0.02</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nHousehold consumption is the largest component in all nine — nowhere below 0.52. Beyond that,\nthe category pattern is weaker than the framing invites:\n\n- **Household share does not sort by development category.** Nigeria is highest at 0.78, but the\n  United States (0.68) is above both India (0.60) and Brazil (0.63). Ukraine sits at 0.76 for a\n  reason that has nothing to do with development category — see below.\n- **Capital formation is highest in Kazakhstan (0.32)**, then Russia and India at 0.30. Brazil,\n  a developing economy, is lowest of the nine at 0.16.\n- **Germany has the largest positive net exports (+0.05).** The transition group does not lead\n  here at all: Russia is −0.05 and Ukraine −0.28.\n\n**Ukraine is worth reading separately.** Government consumption is 0.36 and net exports −0.28 —\nwartime spending and an import surge financed from abroad. Its stack sums above 1.0 precisely\nbecause the negative net exports offset it. That is the accounting identity working\n(C + G + I + NX = GDP, which the table above satisfies to rounding), not an error, and it is why\nnet exports is drawn below the axis rather than stacked.\n\nThe general caution the chart makes concrete: three countries cannot represent a category. The\nwithin-group spread here is as large as the between-group spread on most components, and picking\nthree different countries would change every claim above.\n\n## Q6. GDP per capita as a measure of wellbeing {#p1-q6}\n\n**What it does well.** It is measured consistently across almost every country and back several\ndecades, which almost nothing else about wellbeing is. It correlates strongly with things people\nclearly value — life expectancy, schooling, nutrition. And it aggregates without needing anyone\nto decide how much a hospital is worth relative to a school; market prices do that.\n\n**What it misses**, roughly in order of how badly:\n\n- **Distribution.** A mean says nothing about who receives it. Two countries with identical GDP\n  per capita can have entirely different living standards for a median household. This is what\n  Project 5 measures.\n- **Unpaid work.** Childcare, subsistence farming and housework are all production and none of\n  it is counted, so a country where more of that work is marketised looks richer on identical\n  real activity.\n- **Depletion and damage.** Cutting a forest adds to GDP; the lost forest subtracts nothing.\n  Pollution generates cleanup spending, which also adds.\n- **Non-material dimensions.** Health, security, leisure, political freedom. Income buys some of\n  each, imperfectly.\n- **Defensive expenditure.** Spending forced by a problem — commuting, prisons, flood defence —\n  counts the same as spending that makes someone better off.\n\nThe reason GDP survives all this is the reason Part 4.2 matters: the alternatives require\nchoosing what to include and how to weight it, and those choices are contestable in a way that\n\"the market value of output\" is not.\n\n# Part 4.2 — The HDI {#part-4.2}\n\n::: {#cell-read-hdr .cell execution_count=1}\n``` {.julia .cell-code}\nhdr = CSV.read(rawpath(\"04\", \"hdr25-composite-time-series.csv\"), DataFrame)\n\nhdi = dropmissing(select(hdr,\n        :iso3, :country, :hdicode, :region,\n        :hdi_rank_2023 => :rank, :hdi_2023 => :hdi,\n        :le_2023 => :life_expectancy, :eys_2023 => :expected_schooling,\n        :mys_2023 => :mean_schooling, :gnipc_2023 => :gni_per_capita),\n    [:hdi, :life_expectancy, :expected_schooling, :mean_schooling, :gni_per_capita])\n\n(countries = nrow(hdi), classifications = sort(unique(skipmissing(hdi.hdicode))))\n```\n\n::: {#read-hdr .cell-output .cell-output-display execution_count=1}\n```\n(countries = 204, classifications = String31[\"High\", \"Low\", \"Medium\", \"Very High\"])\n```\n:::\n:::\n\n\n\n## Q1. The indicators for each dimension {#p2-q1}\n\nThe HDI covers three dimensions, with four indicators:\n\n| Dimension | Indicator | 2023 range |\n|---|---|---|\n| Health | Life expectancy at birth | see below |\n| Education | Expected years of schooling (for a child entering school) | |\n| Education | Mean years of schooling (for adults 25+) | |\n| Living standards | GNI per capita, PPP-adjusted | |\n\n::: {#cell-indicator-ranges .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(indicator = [\"Life expectancy (years)\", \"Expected schooling (years)\",\n                       \"Mean schooling (years)\", \"GNI per capita (PPP \\$)\"],\n          minimum = round.([minimum(hdi.life_expectancy), minimum(hdi.expected_schooling),\n                            minimum(hdi.mean_schooling), minimum(hdi.gni_per_capita)], digits = 1),\n          maximum = round.([maximum(hdi.life_expectancy), maximum(hdi.expected_schooling),\n                            maximum(hdi.mean_schooling), maximum(hdi.gni_per_capita)], digits = 1))\n```\n\n::: {#indicator-ranges .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">minimum</th><th style = \"text-align: left;\">maximum</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Life expectancy (years)</td><td style = \"text-align: right;\">54.5</td><td style = \"text-align: right;\">85.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Expected schooling (years)</td><td style = \"text-align: right;\">5.6</td><td style = \"text-align: right;\">20.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Mean schooling (years)</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">14.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">GNI per capita (PPP $)</td><td style = \"text-align: right;\">688.3</td><td style = \"text-align: right;\">1.66812e5</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEducation gets two indicators because the dimension has two distinct parts: how much schooling\nadults *have had*, and how much a child starting now can *expect*. A country that has recently\nexpanded schooling scores high on the second and low on the first, and both facts are real.\n\nGNI per capita rather than GDP per capita, because GNI counts income accruing to residents\nwherever it is earned. For countries with large foreign-owned production or many workers abroad\nthe two differ substantially — a distinction Luxembourg makes vivid in Q6.\n\n## Q2. The normalisation goalposts {#p2-q2}\n\nEach indicator is rescaled to $[0, 1]$ against fixed goalposts, so the index means the same\nthing across editions:\n\n$$\\text{dimension index} = \\frac{\\text{actual} - \\text{minimum}}{\\text{maximum} - \\text{minimum}}$$\n\n::: {#cell-goalposts .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(indicator = [\"Life expectancy\", \"Expected schooling\", \"Mean schooling\",\n                       \"GNI per capita (log)\"],\n          goalpost_min = [20, 0, 0, 100],\n          goalpost_max = [85, 18, 15, 75_000])\n```\n\n::: {#goalposts .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">indicator</th><th style = \"text-align: left;\">goalpost_min</th><th style = \"text-align: left;\">goalpost_max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Life expectancy</td><td style = \"text-align: right;\">20</td><td style = \"text-align: right;\">85</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Expected schooling</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Mean schooling</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">15</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">GNI per capita (log)</td><td style = \"text-align: right;\">100</td><td style = \"text-align: right;\">75000</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThese are not the observed minima and maxima, and that is deliberate. Fixed goalposts make the\nindex comparable over time: with observed extremes, every country's score would shift whenever\nthe best or worst performer changed, and no country's progress could be read from its own value.\n\nThe goalposts have defensible justifications — 20 years is roughly the lowest life expectancy\nrecorded for a society over a sustained period, 18 years of schooling is a master's degree — but\nthey are choices, and they set how much a given improvement is worth.\n\n## Q3. The dimension indices {#p2-q3}\n\n::: {#cell-dimension-indices .cell execution_count=1}\n``` {.julia .cell-code}\nhealth_index(le) = (le - 20) / (85 - 20)\n# Each schooling measure is capped at its goalpost before averaging, so exceeding\n# the goalpost cannot earn extra credit.\neducation_index(eys, mys) = (min(eys / 18, 1.0) + min(mys / 15, 1.0)) / 2\n# Income enters in logs: a given proportional gain matters the same at every level,\n# which is a statement about diminishing returns to income.\nincome_index(gni) = clamp((log(gni) - log(100)) / (log(75_000) - log(100)), 0, 1)\n\nhdi.I_health = health_index.(hdi.life_expectancy)\nhdi.I_education = education_index.(hdi.expected_schooling, hdi.mean_schooling)\nhdi.I_income = income_index.(hdi.gni_per_capita)\n\nfirst(select(hdi, :country, :I_health, :I_education, :I_income), 5)\n```\n\n::: {#dimension-indices .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">I_health</th><th style = \"text-align: left;\">I_education</th><th style = \"text-align: left;\">I_income</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Afghanistan</td><td style = \"text-align: right;\">0.708231</td><td style = \"text-align: right;\">0.383553</td><td style = \"text-align: right;\">0.450358</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Albania</td><td style = \"text-align: right;\">0.916954</td><td style = \"text-align: right;\">0.742237</td><td style = \"text-align: right;\">0.781266</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Algeria</td><td style = \"text-align: right;\">0.865554</td><td style = \"text-align: right;\">0.677634</td><td style = \"text-align: right;\">0.758031</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Andorra</td><td style = \"text-align: right;\">0.985246</td><td style = \"text-align: right;\">0.790966</td><td style = \"text-align: right;\">0.977524</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Angola</td><td style = \"text-align: right;\">0.686415</td><td style = \"text-align: right;\">0.536528</td><td style = \"text-align: right;\">0.633586</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe log on income is the substantive assumption in the whole index. It says an extra \\$1,000\nmatters far more to a country at \\$2,000 than to one at \\$60,000. Without it, rich countries\nwould dominate the index on income alone.\n\n## Q4. Recomputing the HDI {#p2-q4}\n\nThe HDI is the **geometric mean** of the three dimension indices:\n\n$$\\text{HDI} = \\sqrt[3]{I_\\text{health} \\times I_\\text{education} \\times I_\\text{income}}$$\n\n::: {#cell-recompute-hdi .cell execution_count=1}\n``` {.julia .cell-code}\nhdi.hdi_computed = [geometric_mean([r.I_health, r.I_education, r.I_income])\n                    for r in eachrow(hdi)]\nhdi.error = hdi.hdi_computed .- hdi.hdi\n\n(countries = nrow(hdi),\n max_abs_error = round(maximum(abs.(hdi.error)), digits = 4),\n mean_abs_error = round(mean(abs.(hdi.error)), digits = 5),\n within_0_001 = round(100 * mean(abs.(hdi.error) .< 0.001), digits = 1),\n within_0_005 = round(100 * mean(abs.(hdi.error) .< 0.005), digits = 1))\n```\n\n::: {#recompute-hdi .cell-output .cell-output-display execution_count=1}\n```\n(countries = 204, max_abs_error = 0.0036, mean_abs_error = 0.00029, within_0_001 = 99.0, within_0_005 = 100.0)\n```\n:::\n:::\n\n\n\n**99% of the 204 countries reproduce to within 0.001**, and all of them to within 0.005. The\nlargest residual is San Marino at 0.0036, where UNDP substitutes an estimate for a missing\ncomponent.\n\n::: {#cell-top-hdi .cell execution_count=1}\n``` {.julia .cell-code}\nfirst(select(sort(hdi, :hdi_computed, rev = true),\n             :country, :rank, :hdi, :hdi_computed), 8)\n```\n\n::: {#top-hdi .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">rank</th><th style = \"text-align: left;\">hdi</th><th style = \"text-align: left;\">hdi_computed</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Union{Missing, Int64}\" style = \"text-align: left;\">Int64?</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Iceland</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">0.972</td><td style = \"text-align: right;\">0.971859</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Switzerland</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0.97</td><td style = \"text-align: right;\">0.970125</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Norway</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0.97</td><td style = \"text-align: right;\">0.970069</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Denmark</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">0.962</td><td style = \"text-align: right;\">0.961959</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">0.959</td><td style = \"text-align: right;\">0.959294</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">0.959</td><td style = \"text-align: right;\">0.959178</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Australia</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">0.958</td><td style = \"text-align: right;\">0.957845</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Hong Kong, China (SAR)</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">0.955</td><td style = \"text-align: right;\">0.957406</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Why the geometric mean rather than the arithmetic one.** It refuses to let one dimension\nsubstitute for another. Compare two hypothetical countries:\n\n::: {#cell-mean-comparison .cell execution_count=1}\n``` {.julia .cell-code}\nbalanced = [0.6, 0.6, 0.6]\nlopsided = [0.95, 0.85, 0.0]\n\nDataFrame(country = [\"Balanced (0.6, 0.6, 0.6)\", \"Lopsided (0.95, 0.85, 0.0)\"],\n          arithmetic = round.([mean(balanced), mean(lopsided)], digits = 3),\n          geometric = round.([geometric_mean(balanced), geometric_mean(lopsided)], digits = 3))\n```\n\n::: {#mean-comparison .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">arithmetic</th><th style = \"text-align: left;\">geometric</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Balanced (0.6, 0.6, 0.6)</td><td style = \"text-align: right;\">0.6</td><td style = \"text-align: right;\">0.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Lopsided (0.95, 0.85, 0.0)</td><td style = \"text-align: right;\">0.6</td><td style = \"text-align: right;\">0.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe arithmetic mean rates them the same. The geometric mean sends the lopsided country to zero,\nbecause no amount of income compensates for a life expectancy of 20. That is a value judgement\nbuilt into the arithmetic, and a defensible one: these dimensions are not tradeable.\n\n## Q5. An alternative index {#p2-q5}\n\nDifferent indicators for the same three dimensions, from the World Bank:\n\n| Dimension | HDI uses | This uses instead |\n|---|---|---|\n| Health | Life expectancy at birth | Under-five mortality per 1,000 live births |\n| Education | Expected + mean years of schooling | Primary completion rate (% of relevant age group) |\n| Living standards | GNI per capita | Household final consumption expenditure per capita |\n\nEach is a defensible measure of the same dimension, and each emphasises something different.\nUnder-five mortality weights the very start of life. Primary completion measures whether basic\nschooling is finished rather than how many years are attended. Household consumption measures\nwhat residents actually spend, rather than income that may accrue to firms or foreign owners.\n\n::: {#cell-read-wb .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    world_bank(file, name)\n\nParse a World Bank v2 API JSON payload into a two-column frame. The payload is\n`[metadata, rows]`; rows with a null value are dropped.\n\"\"\"\nfunction world_bank(file, name)\n    payload = JSON3.read(read(rawpath(\"04\", file), String))\n    out = DataFrame(iso3 = String[], value = Float64[])\n    for row in payload[2]\n        row.value === nothing && continue\n        push!(out, (String(row.countryiso3code), Float64(row.value)))\n    end\n    rename!(unique(out, :iso3), :value => name)\nend\n\nunder5 = world_bank(\"wb-under5-mortality-2023.json\", :under5_mortality)\nprimary = world_bank(\"wb-primary-completion-2023.json\", :primary_completion)\nconsumption = world_bank(\"wb-household-consumption-pc-2023.json\", :household_consumption)\n\n(under5 = nrow(under5), primary = nrow(primary), consumption = nrow(consumption))\n```\n\n::: {#read-wb .cell-output .cell-output-display execution_count=1}\n```\n(under5 = 240, primary = 175, consumption = 202)\n```\n:::\n:::\n\n\n\n::: {#cell-alternative-index .cell execution_count=1}\n``` {.julia .cell-code}\nalt = innerjoin(hdi, under5, primary, consumption; on = :iso3)\n\n\"\"\"Rescale to [0, 1] against the observed range; `invert` for measures where less is better.\"\"\"\nfunction rescale(v; invert = false)\n    lo, hi = extrema(v)\n    s = (v .- lo) ./ (hi - lo)\n    return invert ? 1 .- s : s\nend\n\nalt.A_health = rescale(alt.under5_mortality; invert = true)\nalt.A_education = rescale(alt.primary_completion)\nalt.A_income = rescale(log.(alt.household_consumption))\nalt.alt_index = [geometric_mean([r.A_health, r.A_education, r.A_income])\n                 for r in eachrow(alt)]\n\n(countries_in_both = nrow(alt),)\n```\n\n::: {#alternative-index .cell-output .cell-output-display execution_count=1}\n```\n(countries_in_both = 109,)\n```\n:::\n:::\n\n\n\n**109 countries** have every HDI component and all three alternatives — down from 204, because\nprimary completion and household consumption are reported less widely than life expectancy.\nThat attrition is itself a finding: the official HDI's indicators were chosen partly *because*\nthey are available almost everywhere, and an index is worthless for countries it cannot cover.\n\nNote that these dimensions are rescaled against the **observed** range rather than fixed\ngoalposts, which is what Q2 warned about — these scores are not comparable to a future edition's.\nFor a one-off ranking comparison that is acceptable; for a series it would not be.\n\n## Q6. Comparing the rankings {#p2-q6}\n\n::: {#cell-rank-compare .cell execution_count=1}\n``` {.julia .cell-code}\nsort!(alt, :alt_index, rev = true); alt.alt_rank = 1:nrow(alt)\nsort!(alt, :hdi, rev = true);       alt.hdi_rank = 1:nrow(alt)\nalt.rank_change = alt.hdi_rank .- alt.alt_rank\n\n(rank_correlation = round(cor(alt.hdi_rank, alt.alt_rank), digits = 3),\n level_correlation = round(cor(alt.hdi, alt.alt_index), digits = 3),\n mean_abs_rank_change = round(mean(abs.(alt.rank_change)), digits = 1),\n max_rank_change = maximum(abs.(alt.rank_change)))\n```\n\n::: {#rank-compare .cell-output .cell-output-display execution_count=1}\n```\n(rank_correlation = 0.951, level_correlation = 0.932, mean_abs_rank_change = 6.8, max_rank_change = 58)\n```\n:::\n:::\n\n\n\n::: {#cell-fig-alt-index .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 620))\nax = Axis(fig[1, 1];\n          title = \"Rank correlation 0.951 — close, but not the same ranking\",\n          xlabel = \"Official HDI rank (1 = highest)\",\n          ylabel = \"Alternative index rank (1 = highest)\")\n\n# The diagonal is agreement; distance from it is disagreement.\nlines!(ax, [1, nrow(alt)], [1, nrow(alt)]; color = BASELINE, linewidth = 1)\nscatter!(ax, alt.hdi_rank, alt.alt_rank; color = series_color(1))\n\noutliers = first(sort(alt, :rank_change, by = abs, rev = true), 6)\nfor r in eachrow(outliers)\n    text!(ax, r.hdi_rank, r.alt_rank; text = r.country, fontsize = 11,\n          color = MUTED, align = (:left, :bottom), offset = (7, 3))\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The alternative index against the official HDI, for the 109 countries with complete data. Countries far from the diagonal are those whose ranking depends on which indicators were chosen.](index_files/figure-html/fig-alt-index-output-1.svg){#fig-alt-index}\n:::\n:::\n\n\n\n::: {#cell-movers .cell execution_count=1}\n``` {.julia .cell-code}\nmovers = select(sort(alt, :rank_change, rev = true),\n                :country, :hdi_rank, :alt_rank, :rank_change)\nvcat(first(movers, 5), last(movers, 5))\n```\n\n::: {#movers .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">hdi_rank</th><th style = \"text-align: left;\">alt_rank</th><th style = \"text-align: left;\">rank_change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Vanuatu</td><td style = \"text-align: right;\">89</td><td style = \"text-align: right;\">31</td><td style = \"text-align: right;\">58</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Tonga</td><td style = \"text-align: right;\">59</td><td style = \"text-align: right;\">41</td><td style = \"text-align: right;\">18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Mexico</td><td style = \"text-align: right;\">52</td><td style = \"text-align: right;\">35</td><td style = \"text-align: right;\">17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Samoa</td><td style = \"text-align: right;\">76</td><td style = \"text-align: right;\">59</td><td style = \"text-align: right;\">17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Portugal</td><td style = \"text-align: right;\">26</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">15</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Bahrain</td><td style = \"text-align: right;\">24</td><td style = \"text-align: right;\">42</td><td style = \"text-align: right;\">-18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Ukraine</td><td style = \"text-align: right;\">55</td><td style = \"text-align: right;\">73</td><td style = \"text-align: right;\">-18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Lebanon</td><td style = \"text-align: right;\">65</td><td style = \"text-align: right;\">83</td><td style = \"text-align: right;\">-18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Romania</td><td style = \"text-align: right;\">37</td><td style = \"text-align: right;\">58</td><td style = \"text-align: right;\">-21</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Luxembourg</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">38</td><td style = \"text-align: right;\">-23</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe two indices agree closely — a rank correlation of **0.951** — which is reassuring about both.\nWellbeing is not so arbitrary that any choice of indicator gives any answer.\n\nBut the disagreements are systematic, not noise:\n\n- **Luxembourg falls 23 places.** Its GNI per capita is among the world's highest, inflated by\n  cross-border commuters and a large financial sector — income recorded in the country that does\n  not accrue to residents' households. Household consumption per capita, which measures what\n  residents actually spend, ranks it far lower. This is the clearest case that the *choice of\n  income measure* is doing work rather than the concept.\n- **Vanuatu rises 58 places**, the largest move. Its primary completion rate and child mortality\n  are much better than its schooling *years* and GNI would suggest.\n- Countries with recent conflict or economic collapse (Ukraine, Lebanon) fall, because household\n  consumption responds faster than life expectancy or accumulated schooling years.\n\nThe lesson is not that one index is right. It is that a country's rank is a joint statement about\nits circumstances *and* about the measurement choices, and those choices deserve to be visible.\nBoth indices here use the same three dimensions and the same geometric mean — only the\nindicators differ — and that alone moves some countries by dozens of places.\n\n## Q7. GDP per capita against the HDI {#p2-q7}\n\n::: {#cell-fig-hdi-gni .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (800, 560))\nax = Axis(fig[1, 1];\n          title = \"Income and human development rise together, with sharply diminishing returns\",\n          xlabel = \"GNI per capita (PPP \\$, log scale)\", ylabel = \"HDI\",\n          xscale = log10)\nscatter!(ax, hdi.gni_per_capita, hdi.hdi; color = series_color(1))\n\n# Label the countries furthest from what income alone predicts, in each direction.\n# The line is fitted by least squares rather than guessed, so \"furthest\" means\n# something: residuals from HDI regressed on log income.\nlog_gni = log10.(hdi.gni_per_capita)\nslope = cov(log_gni, hdi.hdi) / var(log_gni)\nintercept = mean(hdi.hdi) - slope * mean(log_gni)\nresidual = hdi.hdi .- (intercept .+ slope .* log_gni)\n\nlines!(ax, extrema(hdi.gni_per_capita) |> collect,\n       intercept .+ slope .* log10.(collect(extrema(hdi.gni_per_capita)));\n       color = BASELINE, linewidth = 1)\n\nfor idx in vcat(partialsortperm(residual, 1:3), partialsortperm(residual, 1:3; rev = true))\n    text!(ax, hdi.gni_per_capita[idx], hdi.hdi[idx]; text = hdi.country[idx],\n          fontsize = 11, color = MUTED, align = (:left, :center), offset = (7, 0))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![HDI against GNI per capita on a log scale. The relationship is strong but flattens: beyond roughly 40,000 dollars further income buys very little measured human development.](index_files/figure-html/fig-hdi-gni-output-1.svg){#fig-hdi-gni}\n:::\n:::\n\n\n\n::: {#cell-hdi-gni-corr .cell execution_count=1}\n``` {.julia .cell-code}\ngni_rank = competerank(-hdi.gni_per_capita)\n(correlation_log_gni_hdi = round(cor(log.(hdi.gni_per_capita), hdi.hdi), digits = 3),\n rank_correlation = round(cor(gni_rank, hdi.rank), digits = 3))\n```\n\n::: {#hdi-gni-corr .cell-output .cell-output-display execution_count=1}\n```\n(correlation_log_gni_hdi = 0.963, rank_correlation = missing)\n```\n:::\n:::\n\n\n\nThe two measures correlate strongly, which is why GDP per capita survives as a proxy. But the\ncurve flattens: among countries above roughly \\$40,000 the HDI barely moves with income, while\nbelow \\$5,000 small income differences track large differences in human development.\n\nTwo kinds of country sit off the line:\n\n- **High income, lower HDI than income predicts** — typically oil and gas exporters, where\n  national income is high but schooling and health outcomes have not followed.\n- **Lower income, higher HDI than income predicts** — countries that invested in health and\n  education at modest income levels.\n\nThose two groups are the whole argument for the HDI. If income predicted human development\nperfectly, the index would be redundant.\n\n## Q8. Strengths and limitations of the HDI {#p2-q8}\n\n**Strengths.** It made a political point effectively: publishing a ranking that disagreed with\nGDP forced attention onto health and education. It is transparent — Q4 rebuilt it from four\npublished numbers and matched to three decimal places, which is not true of most composite\nindices. And the geometric mean encodes a real position, that the dimensions do not substitute.\n\n**Limitations:**\n\n1. **The weights are arbitrary and invisible.** Equal thirds looks neutral but is a choice, and\n   nothing in the presentation flags it. The goalposts and the log on income are further choices\n   with large effects.\n2. **It ignores distribution.** Like GDP per capita, it is built from national averages. UNDP\n   publishes an inequality-adjusted HDI for this reason, and countries fall substantially under it.\n3. **Its dimensions are narrow.** No environment, no security, no political freedom, no\n   inequality — mostly because those are harder to measure comparably, which means the index is\n   shaped by data availability as much as by what matters. Q5 showed the same pressure operating.\n4. **The indicators saturate.** Most rich countries now sit near the goalposts on health and\n   schooling, so the index has little power to discriminate among them and their ordering is\n   driven mostly by income — the thing it was built to look past.\n5. **Years of schooling is not learning.** It counts attendance, not what was learned, and the\n   gap between the two is large and varies by country.\n\n**Alternatives** that address different parts of this: the **inequality-adjusted HDI** (adds\ndistribution), the **Multidimensional Poverty Index** (deprivation counts rather than averages),\nthe **OECD Better Life Index** (eleven dimensions, and lets the user set the weights — which\nconcedes that no single weighting is correct), and the **Planetary pressures-adjusted HDI**,\nwhich discounts for per-capita emissions and material footprint and reorders the top of the table\nconsiderably.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Wide to long reshaping | Part 4.1 | `stack(df, cols)` |\n| Long to wide | Q4.2 | `unstack(df, keys, :indicator, :value)` |\n| Completeness by group | Q4.1 | `combine(groupby(df, :country), col => count)` |\n| Derived variables | Q4.2 | `df.net_exports = df[!, EXPORTS] .- df[!, IMPORTS]` |\n| Small multiples | Q4.3 | `fldmod1(i, 2)` into `fig[r, c]` |\n| Stacked areas | Q4.4 | `band!(ax, x, lower, upper)` with a running total |\n| Stacked bars | Q4.5 | `barplot!(...; offset = lower)` |\n| Parsing an API payload | Q4.2 Q5 | `JSON3.read`, then a typed frame |\n| Geometric mean | Q4.2 Q4 | `geometric_mean` |\n| Rank correlation | Q4.2 Q6 | `competerank`, `cor` |\n| Log axis | Q4.2 Q7 | `Axis(...; xscale = log10)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}