{
  "hash": "7a88e2b335d6e70fe192651e876ec455",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"7. Supply and demand\"\nsubtitle: \"Fitting curves to a market, and why you cannot see either one directly\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nThe US watermelon market, 1930–1951, from Henry Suits' 1955 study. Watermelons are a good\nteaching market: the crop is planted months before it is sold, so supply in any year is\neffectively fixed by decisions made earlier, which is what makes it possible to separate the\nsupply curve from the demand curve at all.\n\n- **[Part 7.1](#part-7.1)** — supply, demand, and equilibrium\n- **[Part 7.2](#part-7.2)** — elasticities and what shifts each curve\n\nNew concepts: the **natural log transformation**, elasticity read off a log-log slope, and\n**simultaneity** — the reason a scatter of price against quantity traces out neither curve. Book\npages: [project](https://books.core-econ.org/doing-economics/book/text/07-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/07-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/07-04.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames\nusing Statistics\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-watermelon .cell execution_count=1}\n``` {.julia .cell-code}\n# `log.pv` and `log.w` contain the string \"NA\", which is what the book's `na = \"NA\"`\n# handles. Column names use dots, so they need string indexing rather than symbols.\nmelons = DataFrame(XLSX.readtable(rawpath(\"07\", \"watermelon-market.xlsx\"), \"Sheet1\";\n                                  infer_eltypes = true))\nfor col in names(melons)\n    if eltype(melons[!, col]) === Any\n        melons[!, col] = [v isa Number ? Float64(v) : missing for v in melons[!, col]]\n    end\nend\n\n(rows = nrow(melons), years = extrema(melons.Year), columns = names(melons))\n```\n\n::: {#read-watermelon .cell-output .cell-output-display execution_count=1}\n```\n(rows = 22, years = (1930, 1951), columns = [\"Year\", \"log.q\", \"log.h\", \"log.p\", \"log.pc\", \"log.pv\", \"log.w\", \"log.n\", \"log.y_n\", \"log.pf\"])\n```\n:::\n:::\n\n\n\n::: {.callout-important}\n## These logs are base 10, not natural\n\nThe book states that \"whenever log (or ln) is used in economics, it refers to natural\nlogarithms\", and Q1 asks you to recover levels with `exp()`. Applied to this file that gives\nquantities of about 5 to 7 — for a series whose actual values are 48 to 86.\n\nThe population column settles it, because US population is independently known:\n\n::: {#cell-log-base-test .cell execution_count=1}\n``` {.julia .cell-code}\nknown_population = [(1930, 123.2), (1940, 132.2), (1950, 151.3), (1951, 154.9)]\n\nDataFrame(year = first.(known_population),\n          log_n = [only(melons[melons.Year .== y, \"log.n\"]) for (y, _) in known_population],\n          natural = [round(exp(only(melons[melons.Year .== y, \"log.n\"])), digits = 2)\n                     for (y, _) in known_population],\n          base_10 = [round(10^only(melons[melons.Year .== y, \"log.n\"]), digits = 2)\n                     for (y, _) in known_population],\n          actual_millions = last.(known_population))\n```\n\n::: {#log-base-test .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">log_n</th><th style = \"text-align: left;\">natural</th><th style = \"text-align: left;\">base_10</th><th style = \"text-align: left;\">actual_millions</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1930</td><td style = \"text-align: right;\">2.09</td><td style = \"text-align: right;\">8.08</td><td style = \"text-align: right;\">123.03</td><td style = \"text-align: right;\">123.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1940</td><td style = \"text-align: right;\">2.121</td><td style = \"text-align: right;\">8.34</td><td style = \"text-align: right;\">132.13</td><td style = \"text-align: right;\">132.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">1950</td><td style = \"text-align: right;\">2.181</td><td style = \"text-align: right;\">8.86</td><td style = \"text-align: right;\">151.71</td><td style = \"text-align: right;\">151.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">1951</td><td style = \"text-align: right;\">2.189</td><td style = \"text-align: right;\">8.93</td><td style = \"text-align: right;\">154.53</td><td style = \"text-align: right;\">154.9</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n`10^log.n` matches the true population to within 0.4%. `exp(log.n)` is not a population at all.\nSo this project uses base 10 to recover levels, and says so wherever it matters.\n\n**Elasticities are unaffected.** A log-log slope is a percentage elasticity whatever base the\nlogs use, because changing base multiplies both sides by the same constant. Only the *levels*\nrecovered by exponentiating depend on it — which is why the error is easy to miss.\n:::\n\n# Part 7.1 — Supply, demand and equilibrium {#part-7.1}\n\n## Q1. Price and quantity over time {#p1-q1}\n\n::: {#cell-levels .cell execution_count=1}\n``` {.julia .cell-code}\nmelons.price = 10 .^ melons[!, \"log.p\"]\nmelons.quantity = 10 .^ melons[!, \"log.q\"]\nmelons.harvest = 10 .^ melons[!, \"log.h\"]\n\nselect(first(melons, 6), :Year, \"log.p\", :price, \"log.q\", :quantity)\n```\n\n::: {#levels .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Year</th><th style = \"text-align: left;\">log.p</th><th style = \"text-align: left;\">price</th><th style = \"text-align: left;\">log.q</th><th style = \"text-align: left;\">quantity</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1930</td><td style = \"text-align: right;\">2.068</td><td style = \"text-align: right;\">116.95</td><td style = \"text-align: right;\">1.932</td><td style = \"text-align: right;\">85.5067</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1931</td><td style = \"text-align: right;\">2.004</td><td style = \"text-align: right;\">100.925</td><td style = \"text-align: right;\">1.892</td><td style = \"text-align: right;\">77.983</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">1932</td><td style = \"text-align: right;\">1.897</td><td style = \"text-align: right;\">78.886</td><td style = \"text-align: right;\">1.826</td><td style = \"text-align: right;\">66.9885</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">1933</td><td style = \"text-align: right;\">1.968</td><td style = \"text-align: right;\">92.8966</td><td style = \"text-align: right;\">1.751</td><td style = \"text-align: right;\">56.3638</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">1934</td><td style = \"text-align: right;\">2.017</td><td style = \"text-align: right;\">103.992</td><td style = \"text-align: right;\">1.779</td><td style = \"text-align: right;\">60.1174</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">1935</td><td style = \"text-align: right;\">1.982</td><td style = \"text-align: right;\">95.9401</td><td style = \"text-align: right;\">1.822</td><td style = \"text-align: right;\">66.3743</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-time-series .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 420))\nLabel(fig[0, 1:2], \"Price rises sharply through the war; quantity drifts down\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nspecs = [(:price, \"Price\", \"Price (index)\", 1), (:quantity, \"Quantity\", \"Millions of melons\", 2)]\nfor (col, title, ylab, i) in specs\n    ax = Axis(fig[1, i]; title = title, xlabel = \"Year\", ylabel = ylab)\n    lines!(ax, melons.Year, melons[!, col]; color = series_color(i))\n    scatter!(ax, melons.Year, melons[!, col]; color = series_color(i), markersize = 7)\n    # 1942-1945: wartime, when the series behave differently.\n    vspan!(ax, 1942, 1945; color = (BASELINE, 0.35))\nend\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Watermelon price and quantity, 1930–1951. Two panels rather than one: price is an index and quantity is millions of melons, so a single axis would need two scales — and the alignment of two scales is arbitrary.](index_files/figure-html/fig-time-series-output-1.svg){#fig-time-series}\n:::\n:::\n\n\n\nPrice is flat through the 1930s and then rises steeply from about 1942 — the shaded war years —\nroughly quadrupling by the end of the sample. Quantity moves in a much narrower band and drifts\ndownward. Rising price with falling quantity is the signature of supply contracting rather than\ndemand growing, which Part 7.2's supply equation confirms: it carries a WWII coefficient of\n−0.36.\n\n## Q2. Supply and demand curves {#p1-q2}\n\nThe book works with a stylised version of the market rather than Suits' full estimates:\n\n$$\\log P = -2.0 + 1.7 \\log Q \\quad \\text{(supply)} \\qquad \\log P = 8.5 - 0.82 \\log Q \\quad \\text{(demand)}$$\n\nThese are stated in **natural** logs — a separate convention from the data file, and the one that\nreproduces the book's published prices.\n\n::: {#cell-curve-table .cell execution_count=1}\n``` {.julia .cell-code}\nsupply_log_price(log_q) = -2.0 + 1.7 * log_q\ndemand_log_price(log_q) = 8.5 - 0.82 * log_q\n\ncurves = DataFrame(Q = 20:5:100)\ncurves.log_Q = log.(curves.Q)\ncurves.supply_log_P = round.(supply_log_price.(curves.log_Q), digits = 3)\ncurves.demand_log_P = round.(demand_log_price.(curves.log_Q), digits = 3)\ncurves.supply_P = round.(exp.(supply_log_price.(curves.log_Q)), digits = 2)\ncurves.demand_P = round.(exp.(demand_log_price.(curves.log_Q)), digits = 2)\n\ncurves\n```\n\n::: {#curve-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>17×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Q</th><th style = \"text-align: left;\">log_Q</th><th style = \"text-align: left;\">supply_log_P</th><th style = \"text-align: left;\">demand_log_P</th><th style = \"text-align: left;\">supply_P</th><th style = \"text-align: left;\">demand_P</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">20</td><td style = \"text-align: right;\">2.99573</td><td style = \"text-align: right;\">3.093</td><td style = \"text-align: right;\">6.043</td><td style = \"text-align: right;\">22.04</td><td style = \"text-align: right;\">421.37</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">25</td><td style = \"text-align: right;\">3.21888</td><td style = \"text-align: right;\">3.472</td><td style = \"text-align: right;\">5.861</td><td style = \"text-align: right;\">32.2</td><td style = \"text-align: right;\">350.91</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">30</td><td style = \"text-align: right;\">3.4012</td><td style = \"text-align: right;\">3.782</td><td style = \"text-align: right;\">5.711</td><td style = \"text-align: right;\">43.91</td><td style = \"text-align: right;\">302.18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">35</td><td style = \"text-align: right;\">3.55535</td><td style = \"text-align: right;\">4.044</td><td style = \"text-align: right;\">5.585</td><td style = \"text-align: right;\">57.06</td><td style = \"text-align: right;\">266.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">40</td><td style = \"text-align: right;\">3.68888</td><td style = \"text-align: right;\">4.271</td><td style = \"text-align: right;\">5.475</td><td style = \"text-align: right;\">71.6</td><td style = \"text-align: right;\">238.68</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">45</td><td style = \"text-align: right;\">3.80666</td><td style = \"text-align: right;\">4.471</td><td style = \"text-align: right;\">5.379</td><td style = \"text-align: right;\">87.47</td><td style = \"text-align: right;\">216.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">50</td><td style = \"text-align: right;\">3.91202</td><td style = \"text-align: right;\">4.65</td><td style = \"text-align: right;\">5.292</td><td style = \"text-align: right;\">104.63</td><td style = \"text-align: right;\">198.77</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">55</td><td style = \"text-align: right;\">4.00733</td><td style = \"text-align: right;\">4.812</td><td style = \"text-align: right;\">5.214</td><td style = \"text-align: right;\">123.03</td><td style = \"text-align: right;\">183.83</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">60</td><td style = \"text-align: right;\">4.09434</td><td style = \"text-align: right;\">4.96</td><td style = \"text-align: right;\">5.143</td><td style = \"text-align: right;\">142.65</td><td style = \"text-align: right;\">171.17</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">65</td><td style = \"text-align: right;\">4.17439</td><td style = \"text-align: right;\">5.096</td><td style = \"text-align: right;\">5.077</td><td style = \"text-align: right;\">163.44</td><td style = \"text-align: right;\">160.29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">70</td><td style = \"text-align: right;\">4.2485</td><td style = \"text-align: right;\">5.222</td><td style = \"text-align: right;\">5.016</td><td style = \"text-align: right;\">185.39</td><td style = \"text-align: right;\">150.84</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">75</td><td style = \"text-align: right;\">4.31749</td><td style = \"text-align: right;\">5.34</td><td style = \"text-align: right;\">4.96</td><td style = \"text-align: right;\">208.46</td><td style = \"text-align: right;\">142.55</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">80</td><td style = \"text-align: right;\">4.38203</td><td style = \"text-align: right;\">5.449</td><td style = \"text-align: right;\">4.907</td><td style = \"text-align: right;\">232.63</td><td style = \"text-align: right;\">135.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">85</td><td style = \"text-align: right;\">4.44265</td><td style = \"text-align: right;\">5.553</td><td style = \"text-align: right;\">4.857</td><td style = \"text-align: right;\">257.88</td><td style = \"text-align: right;\">128.64</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">90</td><td style = \"text-align: right;\">4.49981</td><td style = \"text-align: right;\">5.65</td><td style = \"text-align: right;\">4.81</td><td style = \"text-align: right;\">284.2</td><td style = \"text-align: right;\">122.75</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: right;\">95</td><td style = \"text-align: right;\">4.55388</td><td style = \"text-align: right;\">5.742</td><td style = \"text-align: right;\">4.766</td><td style = \"text-align: right;\">311.56</td><td style = \"text-align: right;\">117.43</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: right;\">100</td><td style = \"text-align: right;\">4.60517</td><td style = \"text-align: right;\">5.829</td><td style = \"text-align: right;\">4.724</td><td style = \"text-align: right;\">339.95</td><td style = \"text-align: right;\">112.59</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAt **Q = 65** the supply price is **163.44** and the demand price **160.29**, matching the book\nexactly.\n\n::: {#cell-equilibrium .cell execution_count=1}\n``` {.julia .cell-code}\n# Setting the two expressions equal: -2.0 + 1.7 q = 8.5 - 0.82 q, so q = 10.5 / 2.52.\nlog_q_star = 10.5 / 2.52\nq_star = exp(log_q_star)\np_star = exp(supply_log_price(log_q_star))\n\n(log_Q_star = round(log_q_star, digits = 4), Q_star = round(q_star, digits = 2),\n log_P_star = round(supply_log_price(log_q_star), digits = 4), P_star = round(p_star, digits = 2))\n```\n\n::: {#equilibrium .cell-output .cell-output-display execution_count=1}\n```\n(log_Q_star = 4.1667, Q_star = 64.5, log_P_star = 5.0833, P_star = 161.31)\n```\n:::\n:::\n\n\n\nEquilibrium is where the curves cross: **Q\\* ≈ 64.5, P\\* ≈ 161.3**. The table brackets it — supply\nis below demand at Q = 60 and above it at Q = 65.\n\n::: {#cell-fig-curves .cell execution_count=1}\n``` {.julia .cell-code}\nq_grid = 20:0.5:100\n\nfig = Figure(size = (780, 560))\nax = Axis(fig[1, 1];\n          title = \"Equilibrium at Q ≈ $(round(q_star, digits = 1)), P ≈ $(round(p_star, digits = 0))\",\n          xlabel = \"Quantity (millions of melons)\", ylabel = \"Price\")\nlines!(ax, q_grid, exp.(supply_log_price.(log.(q_grid)));\n       color = series_color(1), label = \"Supply\")\nlines!(ax, q_grid, exp.(demand_log_price.(log.(q_grid)));\n       color = series_color(2), label = \"Demand\")\nscatter!(ax, [q_star], [p_star]; color = INK, markersize = 11)\ntext!(ax, q_star, p_star; text = \"  equilibrium\", align = (:left, :center),\n      fontsize = 11, color = INK)\naxislegend(ax; position = :rt, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Supply and demand for watermelons, from the stylised model. Both curves are drawn in price–quantity space with quantity on the horizontal axis, following the convention in the book.](index_files/figure-html/fig-curves-output-1.svg){#fig-curves}\n:::\n:::\n\n\n\nThe supply curve slopes up and the demand curve down, and both are curved rather than straight\nbecause a linear relationship *in logs* is a power relationship in levels.\n\n## Q3. A negative supply shock {#p1-q3}\n\nA drought or a disease outbreak shifts supply left: at any price, less is offered. In the log\nspecification that is a fall in the intercept.\n\n::: {#cell-shock .cell execution_count=1}\n``` {.julia .cell-code}\nshocked_supply_log_price(log_q) = -1.4 + 1.7 * log_q   # intercept -2.0 -> -1.4\n\nlog_q_shock = (8.5 + 1.4) / (1.7 + 0.82)\nq_shock = exp(log_q_shock)\np_shock = exp(shocked_supply_log_price(log_q_shock))\n\nDataFrame(scenario = [\"Before shock\", \"After shock\"],\n          Q = round.([q_star, q_shock], digits = 2),\n          P = round.([p_star, p_shock], digits = 2),\n          Q_change_pct = round.([0.0, 100 * (q_shock - q_star) / q_star], digits = 1),\n          P_change_pct = round.([0.0, 100 * (p_shock - p_star) / p_star], digits = 1))\n```\n\n::: {#shock .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">scenario</th><th style = \"text-align: left;\">Q</th><th style = \"text-align: left;\">P</th><th style = \"text-align: left;\">Q_change_pct</th><th style = \"text-align: left;\">P_change_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Before shock</td><td style = \"text-align: right;\">64.5</td><td style = \"text-align: right;\">161.31</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">After shock</td><td style = \"text-align: right;\">50.83</td><td style = \"text-align: right;\">196.09</td><td style = \"text-align: right;\">-21.2</td><td style = \"text-align: right;\">21.6</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-shock .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (820, 580))\nax = Axis(fig[1, 1];\n          title = \"Supply contracts: quantity falls $(abs(round(100*(q_shock-q_star)/q_star, digits = 0)))%, price rises $(round(100*(p_shock-p_star)/p_star, digits = 0))%\",\n          xlabel = \"Quantity (millions of melons)\", ylabel = \"Price\",\n          limits = ((20, 100), (0, 600)))\n\ndemand_p = exp.(demand_log_price.(log.(q_grid)))\n\n# Consumer surplus: between the demand curve and the new price, up to the new quantity.\ninside = q_grid .<= q_shock\nband!(ax, q_grid[inside], fill(p_shock, sum(inside)), demand_p[inside];\n      color = (series_color(2), 0.18))\n# Producer surplus: between the new price and the new supply curve.\nband!(ax, q_grid[inside], exp.(shocked_supply_log_price.(log.(q_grid[inside]))),\n      fill(p_shock, sum(inside)); color = (series_color(3), 0.22))\n\nlines!(ax, q_grid, demand_p; color = series_color(2), label = \"Demand\")\nlines!(ax, q_grid, exp.(supply_log_price.(log.(q_grid)));\n       color = (series_color(1), 0.45), linestyle = :dash, label = \"Supply (before)\")\nlines!(ax, q_grid, exp.(shocked_supply_log_price.(log.(q_grid)));\n       color = series_color(1), label = \"Supply (after)\")\n\nscatter!(ax, [q_star, q_shock], [p_star, p_shock]; color = INK, markersize = 10)\naxislegend(ax; position = :rt, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![A negative supply shock. Quantity falls and price rises; the shaded regions are consumer surplus above the equilibrium price and producer surplus below it, after the shock.](index_files/figure-html/fig-shock-output-1.svg){#fig-shock}\n:::\n:::\n\n\n\n**What happens to surplus.** Quantity falls and price rises, and all three measures shrink:\n\n- **Consumer surplus falls** unambiguously. Consumers buy less and pay more for each unit, so both\n  the height and the width of their surplus triangle shrink.\n- **Total surplus falls.** Fewer units are traded, and every unit no longer traded was one whose\n  value to a consumer exceeded its cost of production. That lost value is the deadweight cost of\n  the shock.\n- **Producer surplus also falls here**, which is worth stating because it is not automatic. A\n  higher price per unit pulls producer surplus up while the smaller quantity and higher costs pull\n  it down. Which dominates depends on the elasticity of demand:\n\n::: {#cell-revenue-check .cell execution_count=1}\n``` {.julia .cell-code}\nrevenue_before = p_star * q_star\nrevenue_after = p_shock * q_shock\n(revenue_before = round(revenue_before, digits = 0),\n revenue_after = round(revenue_after, digits = 0),\n revenue_change_pct = round(100 * (revenue_after - revenue_before) / revenue_before, digits = 1))\n```\n\n::: {#revenue-check .cell-output .cell-output-display execution_count=1}\n```\n(revenue_before = 10405.0, revenue_after = 9968.0, revenue_change_pct = -4.2)\n```\n:::\n:::\n\n\n\nQuantity falls 21.2% while price rises 21.6%, so **revenue falls about 4.2%** — and producers are\nselling that smaller quantity from a higher cost curve, so surplus falls on both counts.\n\nThe reason is elastic demand. With an elasticity of 1.22, a contraction in supply raises price\nproportionally *less* than it cuts quantity, so revenue shrinks. Had demand been inelastic, price\nwould have risen more than quantity fell and producers could have **gained** from a bad harvest —\nwhich is the standard explanation for why agricultural price supports and supply restrictions can\nhelp farmers in markets for staples.\n\nSo \"a bad harvest hurts farmers\" is not a general truth. It holds when demand is elastic, as it\nis for a discretionary fruit with close substitutes, and reverses when demand is inelastic, as it\nis for staples.\n\n# Part 7.2 — Elasticities and shifts {#part-7.2}\n\n## Q1. Price elasticities {#p2-q1}\n\nInverting the stylised curves puts quantity on the left, which is the form whose slope *is* the\nelasticity:\n\n::: {#cell-elasticities .cell execution_count=1}\n``` {.julia .cell-code}\n# log P = -2.0 + 1.7 log Q  =>  log Q = (2.0 + log P) / 1.7\n# log P =  8.5 - 0.82 log Q =>  log Q = (8.5 - log P) / 0.82\nDataFrame(curve = [\"Supply\", \"Demand\"],\n          intercept = round.([2.0 / 1.7, 8.5 / 0.82], digits = 2),\n          elasticity = round.([1 / 1.7, -1 / 0.82], digits = 2),\n          verdict = [\"inelastic (|e| < 1)\", \"elastic (|e| > 1)\"])\n```\n\n::: {#elasticities .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">curve</th><th style = \"text-align: left;\">intercept</th><th style = \"text-align: left;\">elasticity</th><th style = \"text-align: left;\">verdict</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Supply</td><td style = \"text-align: right;\">1.18</td><td style = \"text-align: right;\">0.59</td><td style = \"text-align: left;\">inelastic (|e| &lt; 1)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Demand</td><td style = \"text-align: right;\">10.37</td><td style = \"text-align: right;\">-1.22</td><td style = \"text-align: left;\">elastic (|e| &gt; 1)</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nSupply: $\\log Q = 1.18 + 0.59 \\log P$. Demand: $\\log Q = 10.37 - 1.22 \\log P$. Both match the\nbook.\n\n**Price elasticity of supply is 0.59** — inelastic. A 10% price rise brings only about 5.9% more\nmelons. That is what you would expect from a crop planted months before it is sold: by the time\nthe price is known, the acreage is committed, so the only response available within the season is\nat the margin of whether to harvest and ship.\n\n**Price elasticity of demand is 1.22** — elastic. A 10% price rise cuts quantity demanded by about\n12.2%. Also unsurprising: a watermelon is a discretionary purchase with close substitutes, so\nbuyers switch to other fruit rather than pay more.\n\nThe two together explain the shock result in Q1.3. Inelastic supply means a shift in supply moves\nquantity little and price a lot; elastic demand means the price rise is not enough to compensate\nproducers for the lost volume.\n\n## Q2. The supply equation {#p2-q2}\n\nSuits' estimated supply equation:\n\n$$\\log Q_t = 2.42 + 0.58 \\log P_{t-1} - 0.32 \\log C_{t-1} - 0.12 \\log T_{t-1} + 0.07\\, CP_t - 0.36\\, WW2_t$$\n\n::: {#cell-supply-coefficients .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(\n    variable = [\"Lagged watermelon price\", \"Lagged cotton price\", \"Lagged vegetable price\",\n                \"Cotton acreage programme\", \"Second World War\"],\n    symbol = [\"log P(t-1)\", \"log C(t-1)\", \"log T(t-1)\", \"CP\", \"WW2\"],\n    coefficient = [0.580, -0.321, -0.124, 0.073, -0.360],\n    interpretation = [\"own-price elasticity\", \"cross-price elasticity\",\n                      \"cross-price elasticity\", \"shift (dummy)\", \"shift (dummy)\"])\n```\n\n::: {#supply-coefficients .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">symbol</th><th style = \"text-align: left;\">coefficient</th><th style = \"text-align: left;\">interpretation</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Lagged watermelon price</td><td style = \"text-align: left;\">log P(t-1)</td><td style = \"text-align: right;\">0.58</td><td style = \"text-align: left;\">own-price elasticity</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Lagged cotton price</td><td style = \"text-align: left;\">log C(t-1)</td><td style = \"text-align: right;\">-0.321</td><td style = \"text-align: left;\">cross-price elasticity</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Lagged vegetable price</td><td style = \"text-align: left;\">log T(t-1)</td><td style = \"text-align: right;\">-0.124</td><td style = \"text-align: left;\">cross-price elasticity</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Cotton acreage programme</td><td style = \"text-align: left;\">CP</td><td style = \"text-align: right;\">0.073</td><td style = \"text-align: left;\">shift (dummy)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Second World War</td><td style = \"text-align: left;\">WW2</td><td style = \"text-align: right;\">-0.36</td><td style = \"text-align: left;\">shift (dummy)</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Everything is lagged one year**, and that is the identifying assumption rather than a technical\ndetail. Planting decisions respond to *last* year's prices because this year's are unknown at\nplanting. It also means supply is predetermined with respect to this year's demand, which is what\nlets the two curves be separated at all — Q4 returns to this.\n\n- **Own price, +0.58.** A 1% higher watermelon price last year raises this year's crop 0.58%.\n  Inelastic, and consistent with the 0.59 from the stylised model.\n- **Cotton price, −0.32** and **vegetable price, −0.12.** Both negative, because these are\n  competing uses of the same land: when cotton is more valuable, farmers plant cotton. Both are\n  smaller than 1 in absolute value, so substitution is real but partial — land is not freely\n  switchable.\n- **Cotton programme, +0.07.** The federal programme restricted cotton acreage, pushing land into\n  other crops including watermelons. Positive, as the mechanism predicts.\n- **Second World War, −0.36.** The largest coefficient in the equation. Labour, fuel and rail\n  capacity were diverted to the war effort, so less was planted and shipped. This is the\n  coefficient that explains the price spike in @fig-time-series.\n\n## Q3. The demand equation {#p2-q3}\n\n$$\\log (X_t/N_t) = \\alpha_0 - 1.13 \\log P_t + 1.75 \\log(Y_t/N_t) - 0.97 \\log F_t$$\n\n::: {#cell-demand-coefficients .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(\n    variable = [\"Watermelon price\", \"Income per capita\", \"Railway freight cost\"],\n    symbol = [\"log P(t)\", \"log Y/N(t)\", \"log F(t)\"],\n    coefficient = [-1.125, 1.750, -0.968],\n    interpretation = [\"own-price elasticity\", \"income elasticity\", \"cost pass-through\"])\n```\n\n::: {#demand-coefficients .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>3×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">symbol</th><th style = \"text-align: left;\">coefficient</th><th style = \"text-align: left;\">interpretation</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Watermelon price</td><td style = \"text-align: left;\">log P(t)</td><td style = \"text-align: right;\">-1.125</td><td style = \"text-align: left;\">own-price elasticity</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Income per capita</td><td style = \"text-align: left;\">log Y/N(t)</td><td style = \"text-align: right;\">1.75</td><td style = \"text-align: left;\">income elasticity</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Railway freight cost</td><td style = \"text-align: left;\">log F(t)</td><td style = \"text-align: right;\">-0.968</td><td style = \"text-align: left;\">cost pass-through</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe dependent variable is quantity **per capita**, which handles population growth by\nconstruction rather than by including population as a regressor.\n\n- **Own price, −1.13.** Elastic, close to the stylised model's 1.22. A 1% price rise cuts\n  consumption per head by 1.13%.\n- **Income per capita, +1.75.** Greater than 1, which makes watermelons a **luxury** in the\n  technical sense: as income rises, spending on them rises *more than proportionally*. Plausible\n  for a fresh, perishable, non-essential fruit in the 1930s and 40s.\n- **Freight cost, −0.97.** Almost exactly −1. Watermelons are heavy, bulky and perishable, so rail\n  freight is a large share of delivered cost, and a 1% rise in freight cuts quantity about 1%.\n  This is the variable that makes the demand curve identifiable — it shifts what consumers pay\n  without shifting what farmers decide to plant.\n\nThe book notes the demand coefficients have **wide confidence intervals**, which is the honest\ncaveat: 22 annual observations is a very small sample for estimating four parameters, so these\npoint estimates are imprecise even where the signs are clear.\n\n## Q4. Exogenous demand shocks, and why identification needs them {#p2-q4}\n\nAn **exogenous** shock shifts one curve without being caused by anything in the market itself.\nThat property is what makes it useful, and the reason is the **simultaneity problem**.\n\nEvery observed price–quantity pair is an *intersection* of supply and demand. Plotting the data\ndirectly traces out neither curve:\n\n::: {#cell-fig-scatter .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 540))\nax = Axis(fig[1, 1];\n          title = \"Observed pairs are intersections, so this scatter is neither curve\",\n          xlabel = \"Quantity (millions of melons)\", ylabel = \"Price\")\nscatter!(ax, melons.quantity, melons.price; color = series_color(1))\nfor i in (argmin(melons.Year), argmax(melons.price), argmax(melons.Year))\n    text!(ax, melons.quantity[i], melons.price[i]; text = string(melons.Year[i]),\n          fontsize = 11, color = MUTED, align = (:left, :center), offset = (7, 0))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Observed price against quantity, 1930–1951. Each point is an equilibrium, not a point on either curve — which is why the cloud has no useful slope.](index_files/figure-html/fig-scatter-output-1.svg){#fig-scatter}\n:::\n:::\n\n\n\n::: {#cell-naive-slope .cell execution_count=1}\n``` {.julia .cell-code}\nq = log.(melons.quantity); p = log.(melons.price)\nnaive_slope = cov(q, p) / var(q)\n(naive_slope_of_logP_on_logQ = round(naive_slope, digits = 3),\n correlation = round(cor(q, p), digits = 3))\n```\n\n::: {#naive-slope .cell-output .cell-output-display execution_count=1}\n```\n(naive_slope_of_logP_on_logQ = 0.777, correlation = 0.184)\n```\n:::\n:::\n\n\n\nThe naive slope is **+0.78**, with a correlation of only 0.18. Read as a demand curve that is\nnonsense — it says quantity and price rise together, so demand would slope *upward*. Read as a\nsupply curve it is also wrong, since the supply relationship in this model has slope 1.7.\n\nIt is neither, because it is a mixture of both, weighted by how much each curve happened to shift\nover these 22 years. Supply moved a great deal (the war, the cotton programme) and demand moved\ntoo (income, freight), so the intersections wander across the plane and their slope estimates\nnothing. Separating the curves requires variables that shift one and not the other.\n\n**Two exogenous demand shocks, and why each qualifies:**\n\n1. **Railway freight rates** — the `F` in the demand equation. Rates were set by regulated\n   tariffs and by conditions in the rail industry, both determined outside the watermelon market.\n   They change what consumers pay per melon without changing the growing conditions or planting\n   incentives farmers face. A watermelon farmer's acreage decision does not move national freight\n   tariffs, so the causation runs one way.\n\n2. **Per-capita income** — the `Y/N` term. Aggregate income is driven by the macroeconomy: the\n   Depression, wartime employment, post-war expansion. Watermelons are far too small a share of\n   national spending for the market to affect national income, so income shifts demand while being\n   unaffected by it.\n\n**What makes them exogenous is the absence of a reverse channel**, and it has to be argued\nmechanism by mechanism rather than asserted. A weather shock, by contrast, is exogenous to the\n*supply* side but would be a poor demand shifter — hot weather raises watermelon demand *and*\naffects the crop, so it shifts both curves and identifies neither.\n\nThe symmetric point completes the argument. Suits identifies **demand** using freight and income,\nwhich shift demand only; and **supply** using lagged prices, the cotton programme and the war,\nwhich shift supply only. Each curve is traced out by variation that moves the *other* one along\nit. That is the whole method, and it is why the equations in Q2 and Q3 contain the variables they\ndo.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Recovering levels from logs | Q7.1 Q1 | `10 .^ x` (base 10 here, not `exp`) |\n| Verifying a log base against known data | Setup | compare `exp` and `10^` with US population |\n| Shading a period on a chart | Q7.1 Q1 | `vspan!(ax, 1942, 1945)` |\n| Curves from a function over a grid | Q7.1 Q2 | `lines!(ax, grid, f.(log.(grid)))` |\n| Solving for equilibrium | Q7.1 Q2 | set the expressions equal, solve for `log Q` |\n| Shading surplus regions | Q7.1 Q3 | `band!(ax, x, lower, upper)` |\n| Elasticity from a log-log slope | Q7.2 Q1 | invert the curve; the slope *is* the elasticity |\n| Dot-named columns | Setup | `df[!, \"log.p\"]`, not `df.log.p` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}