{
  "hash": "4dd3f6e5c8e6697e51ae2b9f6e7658ff",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"2. Collecting and analysing data from experiments\"\nsubtitle: \"A public goods game, and whether punishment changed behaviour\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nA public goods game run in 16 cities, twice: once with no way to punish free-riders, once with\none. The question is whether the rule change caused the difference in behaviour, or whether a\ndifference that size could have come up by chance.\n\n- **[Part 2.1](#part-2.1)** — collecting data by playing the game\n- **[Part 2.2](#part-2.2)** — describing the data\n- **[Part 2.3](#part-2.3)** — how the rule change affected behaviour\n\nNew concepts: standard deviation, range, *p*-value, and what an experiment has to look like\nbefore a difference can be called causal. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/02-01.html),\n[R walk-throughs](https://books.core-econ.org/doing-economics/book/text/02-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/02-04.html).\n\n## The experiment\n\nGroups of four, ten rounds. Each round every player gets $20 and chooses how much to put into\na common pot. Every dollar contributed pays $0.40 to *each* of the four players — so a dollar\ncontributed returns $1.60 to the group but only $0.40 to the contributor. Contributing is\ncollectively optimal and individually costly, which is what makes it a public goods problem.\n\nThe second experiment is identical except that after seeing what everyone contributed, players\ncan pay $1 to fine another player $3.\n\n## The data\n\n| | |\n|---|---|\n| **Source** | Herrmann, Thöni & Gächter (2008), *Antisocial Punishment Across Societies*, Science 319(5868) — via CORE Econ |\n| **Shape** | Two 10 × 16 blocks: periods 1–10 down, 16 cities across |\n| **Cities** | Copenhagen, Dnipropetrovs'k, Minsk, St. Gallen, Muscat, Samara, Zurich, Boston, Bonn, Chengdu, Seoul, Riyadh, Nottingham, Athens, Istanbul, Melbourne |\n\nThe file is a frozen snapshot, so every figure below reproduces the book's published solutions\nexactly.\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames, Statistics, Random\nusing HypothesisTests\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\nBoth blocks live on one sheet with headers on rows 2 and 16. The book's R code reads them as\ntwo ranges, `A2:Q12` and `A16:Q26`; the same two slices in Julia:\n\n::: {#cell-read-data .cell execution_count=1}\n``` {.julia .cell-code}\nconst SHEET = \"Public goods contributions\"\npath = rawpath(\"02\", \"public-goods-experiment.xlsx\")\n\nraw = XLSX.readdata(path, SHEET, \"A1:Q26\")\ncities = String.(raw[2, 2:17])\n\n# Rows 3-12 and 17-26 are periods 1-10 of each condition.\nno_pun   = Float64.(raw[3:12,  2:17])\nwith_pun = Float64.(raw[17:26, 2:17])\n\n(cities = length(cities), no_punishment = size(no_pun), with_punishment = size(with_pun))\n```\n\n::: {#read-data .cell-output .cell-output-display execution_count=1}\n```\n(cities = 16, no_punishment = (10, 16), with_punishment = (10, 16))\n```\n:::\n:::\n\n\n\nA tidy long-format table is easier to work with than two matrices, and is what the charts use:\n\n::: {#cell-tidy .cell execution_count=1}\n``` {.julia .cell-code}\ncontributions = DataFrame(\n    period = repeat(1:10, outer = 2 * length(cities)),\n    city = repeat(cities, inner = 10, outer = 2),\n    condition = repeat([\"Without punishment\", \"With punishment\"], inner = 10 * length(cities)),\n    contribution = vcat(vec(no_pun), vec(with_pun)),\n)\n\nfirst(contributions, 4)\n```\n\n::: {#tidy .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">city</th><th style = \"text-align: left;\">condition</th><th style = \"text-align: left;\">contribution</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Copenhagen</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">14.1029</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">Copenhagen</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">14.1324</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">Copenhagen</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">13.7206</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: left;\">Copenhagen</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">12.8971</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n# Part 2.1 — Collecting data by playing the game {#part-2.1}\n\n## Q1. Chart your group's average contribution by period {#p1-q1}\n\nThis part asks you to play the game in class and plot your own results, so there is no dataset\nto substitute — the answer depends on what your group actually did.\n\nWhat can be provided is the code, written to take any table of `period` and `contribution` and\nproduce the chart the question asks for. Below it runs on one city from the Herrmann data\n(Copenhagen, no punishment) so the output is visible; swap in your own numbers and it works\nunchanged.\n\n::: {#cell-fig-own-data .cell execution_count=1}\n``` {.julia .cell-code}\n# Replace this with your own group's numbers.\nown_data = DataFrame(period = 1:10, contribution = no_pun[:, 1])\n\nfig = Figure(size = (700, 400))\nax = Axis(fig[1, 1];\n          title = \"Average contribution by period\",\n          subtitle = \"Demonstration data: Copenhagen, without punishment\",\n          xlabel = \"Period\", ylabel = \"Average contribution (\\$)\",\n          xticks = 1:10)\nlines!(ax, own_data.period, own_data.contribution; color = series_color(1))\nscatter!(ax, own_data.period, own_data.contribution; color = series_color(1))\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The Part 2.1 chart, demonstrated on Copenhagen's no-punishment series. Replace `own_data` with your own class results to answer the question.](index_files/figure-html/fig-own-data-output-1.svg){#fig-own-data}\n:::\n:::\n\n\n\nThe pattern to look for, and the one Herrmann et al. found nearly everywhere: contributions\nstart moderately high and **decay** as the rounds proceed. Players begin willing to cooperate,\nobserve others contributing less, and reduce their own contributions in response.\n\n## Q2. Comparison with Figure 3 of the paper {#p1-q2}\n\nFigure 3 of Herrmann et al. is the no-punishment panel — the same 16 series plotted below in\n@fig-means. The comparison to make is on three specific things:\n\n- **Starting level.** Across the 16 cities, period 1 averages **10.58**, with individual cities\n  ranging from 7.96 to 14.10.\n- **Ending level.** Period 10 averages **4.38**, ranging from 1.30 to 8.68.\n- **Shape.** Monotone decay in nearly every city.\n\nA single classroom group will be noisier than any of these city averages, because each city\nfigure already averages over many groups.\n\n## Q3. Why classroom results differ from the published study {#p1-q3}\n\nFour reasons, in rough order of how much they matter:\n\n1. **Sample size.** Each published city average pools many groups of four; a classroom\n   produces one or a few. Small samples swing widely for no substantive reason.\n2. **Stakes.** The published experiment paid real money. Hypothetical payoffs weaken the\n   incentive that the game is built on.\n3. **Who is playing.** Subjects were recruited to be strangers. Classmates know each other,\n   expect to meet again, and can be seen — so reputation and social pressure enter a game\n   designed to exclude them.\n4. **Common knowledge.** Students who already know the theoretical prediction play differently\n   from subjects who don't.\n\n# Part 2.2 — Describing the data {#part-2.2}\n\n## Q1. Mean contribution per period {#p2-q1}\n\n::: {#cell-means-table .cell execution_count=1}\n``` {.julia .cell-code}\nmeans = DataFrame(\n    period = 1:10,\n    without_punishment = [mean(no_pun[p, :]) for p in 1:10],\n    with_punishment = [mean(with_pun[p, :]) for p in 1:10],\n)\nmeans.difference = means.with_punishment .- means.without_punishment\n\nmeans\n```\n\n::: {#means-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">without_punishment</th><th style = \"text-align: left;\">with_punishment</th><th style = \"text-align: left;\">difference</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">10.5783</td><td style = \"text-align: right;\">10.6388</td><td style = \"text-align: right;\">0.0604458</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">10.6284</td><td style = \"text-align: right;\">11.9548</td><td style = \"text-align: right;\">1.3264</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">10.4071</td><td style = \"text-align: right;\">12.6643</td><td style = \"text-align: right;\">2.25726</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">9.81303</td><td style = \"text-align: right;\">12.9667</td><td style = \"text-align: right;\">3.15363</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">9.30543</td><td style = \"text-align: right;\">13.3316</td><td style = \"text-align: right;\">4.0262</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">8.45484</td><td style = \"text-align: right;\">13.5022</td><td style = \"text-align: right;\">5.04739</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">7.83757</td><td style = \"text-align: right;\">13.5747</td><td style = \"text-align: right;\">5.73711</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">7.37639</td><td style = \"text-align: right;\">13.6355</td><td style = \"text-align: right;\">6.25915</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">6.39299</td><td style = \"text-align: right;\">13.5695</td><td style = \"text-align: right;\">7.17656</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">4.38377</td><td style = \"text-align: right;\">12.8699</td><td style = \"text-align: right;\">8.48611</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery one of these twenty means matches the book's published solutions to two decimal places.\n\n::: {#cell-fig-means .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (820, 460))\nax = Axis(fig[1, 1];\n          title = \"Punishment reverses the decay in contributions\",\n          xlabel = \"Period\", ylabel = \"Average contribution (\\$)\",\n          xticks = 1:10)\n\n# All 32 city series as context. Sixteen cities cannot each get their own hue -\n# past eight, colours stop being distinguishable - so the cities carry no colour\n# and the two condition means carry all of it. Kept at low opacity: at full\n# strength 32 lines out-ink the two that matter.\nfor j in eachindex(cities)\n    lines!(ax, 1:10, no_pun[:, j];   color = (BASELINE, 0.4), linewidth = 0.75)\n    lines!(ax, 1:10, with_pun[:, j]; color = (BASELINE, 0.4), linewidth = 0.75)\nend\n\nlines!(ax, 1:10, means.without_punishment;\n       color = series_color(1), linewidth = 3, label = \"Without punishment\")\nlines!(ax, 1:10, means.with_punishment;\n       color = series_color(2), linewidth = 3, label = \"With punishment\")\n\n# Legend only. Direct end-labels would land inside the grey band and simply\n# restate the legend sitting beside them.\naxislegend(ax; position = :lb, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean contribution by period in each condition, with the 16 individual city series behind in grey. Values are in the table above.](index_files/figure-html/fig-means-output-1.svg){#fig-means}\n:::\n:::\n\n\n\nThe two conditions start in the same place — 10.58 against 10.64, a gap of 0.06 — and then\nseparate completely. Without punishment, contributions fall by about 6 dollars to 4.38. With\npunishment, they *rise* through period 8 and finish at 12.87.\n\nThat the two lines start together is the single most important feature of the chart, and Q4\nreturns to why.\n\n## Q2. Periods 1 and 10 side by side {#p2-q2}\n\n::: {#cell-fig-columns .cell execution_count=1}\n``` {.julia .cell-code}\nendpoints = means[[1, 10], :]\n\nfig = Figure(size = (620, 420))\nax = Axis(fig[1, 1];\n          title = \"Identical at the start, $(round(endpoints.difference[2], digits = 1)) dollars apart at the end\",\n          ylabel = \"Mean contribution (\\$)\",\n          xticks = ([1, 2], [\"Period 1\", \"Period 10\"]),\n          limits = ((0.6, 2.4), nothing))\n\nfor (i, (col, label)) in enumerate(((:without_punishment, \"Without punishment\"),\n                                    (:with_punishment, \"With punishment\")))\n    xs = [1, 2] .+ (i - 1.5) * 0.18\n    # Thin bars with air either side: four wide blocks read as decoration rather\n    # than data, and the height is what carries the value.\n    barplot!(ax, xs, endpoints[!, col]; width = 0.14,\n             color = series_color(i), label = label)\n    # Two bars per group, so a value on each cap is four labels, not forty.\n    for (x, v) in zip(xs, endpoints[!, col])\n        text!(ax, x, v; text = string(round(v, digits = 2)),\n              align = (:center, :bottom), offset = (0, 4), fontsize = 11)\n    end\nend\n\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean contribution in the first and last period of each condition. Nearly identical at period 1, far apart at period 10.](index_files/figure-html/fig-columns-output-1.svg){#fig-columns}\n:::\n:::\n\n\n\n## Q3. Standard deviation {#p2-q3}\n\n::: {#cell-sd-table .cell execution_count=1}\n``` {.julia .cell-code}\nsummary_stats = DataFrame(period = Int[], condition = String[], mean = Float64[],\n                          variance = Float64[], sd = Float64[], min = Float64[],\n                          max = Float64[], range = Float64[])\n\nfor p in (1, 10), (m, cond) in ((no_pun, \"Without punishment\"), (with_pun, \"With punishment\"))\n    v = m[p, :]\n    push!(summary_stats, (p, cond, mean(v), var(v), std(v),\n                          minimum(v), maximum(v), maximum(v) - minimum(v)))\nend\n\nselect(summary_stats, :period, :condition, :mean, :sd)\n```\n\n::: {#sd-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">condition</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">10.5783</td><td style = \"text-align: right;\">2.02072</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">10.6388</td><td style = \"text-align: right;\">3.20726</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">4.38377</td><td style = \"text-align: right;\">2.18713</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">12.8699</td><td style = \"text-align: right;\">3.89802</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nPeriod 1: **2.02** without punishment against **3.21** with. Period 10: **2.19** against\n**3.90**.\n\nThis answers the question the book poses directly — the two experiments both average about\n10.6 in period 1, so are the datasets the same? No. Equal means with different standard\ndeviations means the same centre and a different spread: with punishment, cities are more\nspread out around that shared average. A mean alone cannot distinguish the two datasets, which\nis the reason to report spread alongside it.\n\nThe **rule of thumb** is that roughly 95% of observations fall within two standard deviations\nof the mean:\n\n::: {#cell-rule-of-thumb .cell execution_count=1}\n``` {.julia .cell-code}\nrule = transform(summary_stats,\n    [:mean, :sd] => ByRow((m, s) -> round(m - 2s, digits = 1)) => :lower,\n    [:mean, :sd] => ByRow((m, s) -> round(m + 2s, digits = 1)) => :upper)\n\nwithin = [100 * mean(abs.(m[p, :] .- mean(m[p, :])) .<= 2 * std(m[p, :]))\n          for p in (1, 10) for m in (no_pun, with_pun)]\n\nselect(transform(rule, [] => (() -> within) => :pct_within),\n       :period, :condition, :lower, :upper, :pct_within)\n```\n\n::: {#rule-of-thumb .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">condition</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">pct_within</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">6.5</td><td style = \"text-align: right;\">14.6</td><td style = \"text-align: right;\">100.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">4.2</td><td style = \"text-align: right;\">17.1</td><td style = \"text-align: right;\">100.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">8.8</td><td style = \"text-align: right;\">100.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">5.1</td><td style = \"text-align: right;\">20.7</td><td style = \"text-align: right;\">100.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe intervals match the book's ([8.6, 12.6], [7.5, 13.7], [2.3, 6.5], [9.1, 16.7]). All four\ncontain 93.75% of observations — 15 of 16 cities — against the 95% the rule predicts. With only\n16 observations the achievable percentages are multiples of 6.25, so 93.75% is as close to 95%\nas this sample can get. The rule of thumb assumes an approximately normal distribution and is\nan approximation even then; it holds well here.\n\n## Q4. Minimum, maximum and range {#p2-q4}\n\n::: {#cell-minmax .cell execution_count=1}\n``` {.julia .cell-code}\nselect(summary_stats, :period, :condition, :min, :max, :range)\n```\n\n::: {#minmax .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">condition</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">range</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">7.95833</td><td style = \"text-align: right;\">14.1029</td><td style = \"text-align: right;\">6.14461</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">5.81818</td><td style = \"text-align: right;\">16.0179</td><td style = \"text-align: right;\">10.1997</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">1.3</td><td style = \"text-align: right;\">8.68182</td><td style = \"text-align: right;\">7.38182</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">6.20455</td><td style = \"text-align: right;\">17.5119</td><td style = \"text-align: right;\">11.3074</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n## Q5. The full summary table {#p2-q5}\n\n::: {#cell-full-summary .cell execution_count=1}\n``` {.julia .cell-code}\nsummary_stats\n```\n\n::: {#full-summary .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×8 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">period</th><th style = \"text-align: left;\">condition</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">variance</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">range</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">10.5783</td><td style = \"text-align: right;\">4.08332</td><td style = \"text-align: right;\">2.02072</td><td style = \"text-align: right;\">7.95833</td><td style = \"text-align: right;\">14.1029</td><td style = \"text-align: right;\">6.14461</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">10.6388</td><td style = \"text-align: right;\">10.2865</td><td style = \"text-align: right;\">3.20726</td><td style = \"text-align: right;\">5.81818</td><td style = \"text-align: right;\">16.0179</td><td style = \"text-align: right;\">10.1997</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">Without punishment</td><td style = \"text-align: right;\">4.38377</td><td style = \"text-align: right;\">4.78352</td><td style = \"text-align: right;\">2.18713</td><td style = \"text-align: right;\">1.3</td><td style = \"text-align: right;\">8.68182</td><td style = \"text-align: right;\">7.38182</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">10</td><td style = \"text-align: left;\">With punishment</td><td style = \"text-align: right;\">12.8699</td><td style = \"text-align: right;\">15.1946</td><td style = \"text-align: right;\">3.89802</td><td style = \"text-align: right;\">6.20455</td><td style = \"text-align: right;\">17.5119</td><td style = \"text-align: right;\">11.3074</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nReading across the four rows:\n\n- **Period 1 means are effectively equal** (10.58, 10.64) while everything describing spread\n  differs — SD 2.02 against 3.21, range 6.14 against 10.20.\n- **By period 10 the means diverge** (4.38 against 12.87) and the spreads widen in both\n  conditions.\n- **The with-punishment condition is more variable throughout.** Punishment did not move every\n  city the same way; it moved the average up while spreading cities further apart. Athens\n  finishes at 6.20 while Seoul reaches 17.51.\n\nThat last point is easy to miss from the means alone, and it is what the Herrmann paper is\nactually about — the paper's title concerns *antisocial* punishment, cases where players fined\nhigh contributors rather than free-riders, which happened much more in some cities than others.\n\n# Part 2.3 — How did changing the rules affect behaviour? {#part-2.3}\n\n## Q1. The coin-flip exercise {#p3-q1}\n\nThe exercise is to flip a coin six times with one hand, record the result, then repeat with the\nother hand, and note that the two runs differ even though nothing about the process changed.\n\nSimulating it makes the same point with enough replications to see the distribution rather than\ntwo draws from it. The seed is fixed so the page renders identically each time:\n\n::: {#cell-coin-flips .cell execution_count=1}\n``` {.julia .cell-code}\nrng = MersenneTwister(20260902)\n\nleft  = rand(rng, Bool, 6)\nright = rand(rng, Bool, 6)\n\n(left_sequence = Int.(left), left_heads = sum(left),\n right_sequence = Int.(right), right_heads = sum(right))\n```\n\n::: {#coin-flips .cell-output .cell-output-display execution_count=1}\n```\n(left_sequence = [0, 0, 0, 0, 1, 0], left_heads = 1, right_sequence = [0, 0, 0, 0, 1, 1], right_heads = 2)\n```\n:::\n:::\n\n\n\nTwo runs of an identical process, different results — different counts and different sequences.\nAny difference between the hands is chance, because there is no mechanism by which the hand\ncould matter.\n\n::: {#cell-fig-coins .cell execution_count=1}\n``` {.julia .cell-code}\nruns = [sum(rand(rng, Bool, 6)) for _ in 1:10_000]\ncounts = [count(==(k), runs) for k in 0:6]\n\nfig = Figure(size = (700, 400))\nax = Axis(fig[1, 1];\n          title = \"A fair coin produces a spread of outcomes, not always three heads\",\n          xlabel = \"Heads in six flips\", ylabel = \"Runs out of 10,000\",\n          xticks = 0:6)\nbarplot!(ax, 0:6, counts; width = 0.7, color = series_color(1))\nfor (k, c) in zip(0:6, counts)\n    text!(ax, k, c; text = string(c), align = (:center, :bottom),\n          offset = (0, 4), fontsize = 11)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Heads in six flips, over 10,000 simulated runs of a fair coin. Getting 4 heads rather than 3 is unremarkable; the distribution says how surprised to be by any given count.](index_files/figure-html/fig-coins-output-1.svg){#fig-coins}\n:::\n:::\n\n\n\nThis is the logic a *p*-value formalises: to judge whether an observed difference is meaningful,\nyou need to know what range of differences the no-real-effect case produces.\n\n## Q2. The *p*-value for period 1 {#p3-q2}\n\nThe same 16 cities appear in both conditions, so the two samples are **paired** — comparing\nCopenhagen with Copenhagen, not the two groups as unrelated samples. The book makes this\ncorrection explicitly, and it matters: pairing removes between-city differences from the\ncomparison.\n\nIn R that is `t.test(x, y, paired = TRUE)`. Julia has no separate paired test; a paired *t*-test\n*is* a one-sample test on the differences, which is what `OneSampleTTest` on `x .- y` does:\n\n::: {#cell-ttest-p1 .cell execution_count=1}\n``` {.julia .cell-code}\np1_test = OneSampleTTest(no_pun[1, :] .- with_pun[1, :])\n```\n\n::: {#ttest-p1 .cell-output .cell-output-display execution_count=1}\n```\nOne sample t-test\n-----------------\nPopulation details:\n    parameter of interest:   Mean\n    value under h_0:         0\n    point estimate:          -0.0604458\n    95% confidence interval: (-0.9196, 0.7987)\n\nTest summary:\n    outcome with 95% confidence: fail to reject h_0\n    two-sided p-value:           0.8828\n\nDetails:\n    number of observations:   16\n    t-statistic:              -0.14995904535850296\n    degrees of freedom:       15\n    empirical standard error: 0.40308176858461536\n```\n:::\n:::\n\n\n\n::: {#cell-ttest-p1-pvalue .cell execution_count=1}\n``` {.julia .cell-code}\n(mean_difference = mean(no_pun[1, :] .- with_pun[1, :]),\n p_value = pvalue(p1_test))\n```\n\n::: {#ttest-p1-pvalue .cell-output .cell-output-display execution_count=1}\n```\n(mean_difference = -0.060445757218365925, p_value = 0.8827947293072503)\n```\n:::\n:::\n\n\n\nThe mean difference is **−0.06** with a *p*-value of **0.88**. There is no detectable\ndifference between the two conditions in period 1.\n\nThe *p*-value is the probability of seeing a difference at least this large if the two\nconditions really had the same mean. At 0.88 the observed gap is entirely ordinary under that\nassumption — the same reading as getting 4 heads instead of 3 in @fig-coins.\n\n## Q3. The *p*-value for period 10 {#p3-q3}\n\n::: {#cell-ttest-p10 .cell execution_count=1}\n``` {.julia .cell-code}\np10_test = OneSampleTTest(no_pun[10, :] .- with_pun[10, :])\n```\n\n::: {#ttest-p10 .cell-output .cell-output-display execution_count=1}\n```\nOne sample t-test\n-----------------\nPopulation details:\n    parameter of interest:   Mean\n    value under h_0:         0\n    point estimate:          -8.48611\n    95% confidence interval: (-11.28, -5.695)\n\nTest summary:\n    outcome with 95% confidence: reject h_0\n    two-sided p-value:           <1e-04\n\nDetails:\n    number of observations:   16\n    t-statistic:              -6.480599529730059\n    degrees of freedom:       15\n    empirical standard error: 1.3094637858753957\n```\n:::\n:::\n\n\n\n::: {#cell-ttest-p10-pvalue .cell execution_count=1}\n``` {.julia .cell-code}\n(mean_difference = mean(no_pun[10, :] .- with_pun[10, :]),\n p_value = pvalue(p10_test))\n```\n\n::: {#ttest-p10-pvalue .cell-output .cell-output-display execution_count=1}\n```\n(mean_difference = -8.486110394942632, p_value = 1.0374516722799413e-5)\n```\n:::\n:::\n\n\n\nA mean difference of **−8.49** with a *p*-value of **0.00001**. A gap this large would arise by\nchance about once in a hundred thousand times if punishment made no difference.\n\nFor comparison, the unpaired form the book starts with — R's default `t.test(x, y)`, which is\nWelch's test:\n\n::: {#cell-ttest-unpaired .cell execution_count=1}\n``` {.julia .cell-code}\nunpaired = UnequalVarianceTTest(no_pun[10, :], with_pun[10, :])\n(paired_p = pvalue(p10_test), unpaired_p = pvalue(unpaired))\n```\n\n::: {#ttest-unpaired .cell-output .cell-output-display execution_count=1}\n```\n(paired_p = 1.0374516722799413e-5, unpaired_p = 8.758435771909662e-8)\n```\n:::\n:::\n\n\n\nBoth reject decisively here, but the paired test is the correct one and gives the smaller\n*p*-value, because removing between-city variation leaves a cleaner comparison.\n\n**Why the size of the difference is not enough on its own.** 8.49 dollars sounds large, but\n\"large\" has no meaning without knowing how much the quantity varies. A difference of 8.49 in a\nsetting where cities routinely differ by 20 would be noise. The *p*-value is what supplies that\ncontext: it measures the difference in units of its own sampling variability. That is why\nperiod 1's difference of 0.06 and period 10's of 8.49 get such different verdicts — not because\none number is bigger, but because only one is big relative to the spread.\n\n## Q4. What makes punishment the cause {#p3-q4}\n\nThe *p*-value establishes that the period 10 difference is not chance. It does not, by itself,\nestablish that *punishment* produced it — something else differing between the two groups could\nbe responsible.\n\nWhat rules that out is the period 1 result. Both conditions used the same 16 cities, and at\nperiod 1 — before anyone had an opportunity to punish — the two groups were statistically\nindistinguishable (*p* = 0.88). So the groups were comparable before the treatment took effect\nand differed sharply after it, with the punishment option being the thing that changed between\nthem.\n\nThat structure is what makes an experiment able to support a causal claim:\n\n- **The treatment is assigned, not chosen.** Subjects did not select into the punishment\n  condition, so the groups do not differ in ways that also affect contributions.\n- **The groups are verifiably similar beforehand.** This is testable, and the period 1\n  comparison is the test.\n- **Only one thing differs.** Same payoffs, same rounds, same protocol — only the punishment\n  option changes.\n\nThe period 1 comparison is doing real work. Without it, an argument that the punishment cities\nwere simply more cooperative to begin with would be unanswerable.\n\n## Q5. Limitations {#p3-q5}\n\nFive, with what would address each:\n\n1. **Subject pools are not their societies.** The subjects were mostly university students in\n   16 cities, so \"Athens\" means the students who turned up in Athens. Recruiting broader\n   samples would help; it is expensive, which is why it is rarely done.\n2. **Laboratory behaviour need not transfer.** A $20 endowment in a ten-round game is not a tax\n   bill or a team project. Field experiments in real settings are the check.\n3. **Subjects know they are observed.** Being watched encourages generosity, likely inflating\n   contributions in both conditions. This biases levels more than the between-condition\n   difference, which is what the analysis rests on.\n4. **Ten rounds with a known end.** Contributions drop sharply in the final period in nearly\n   every city, an artefact of the game ending rather than of preferences. Randomising the\n   endpoint removes it.\n5. **The mechanism is not identified.** The experiment shows punishment raised contributions,\n   not why — deterrence, reciprocity, and anger are all consistent with it. Varying the fine's\n   size and cost separately would begin to separate them.\n\nThe design handles the threat that matters most for the causal claim — pre-treatment\ncomparability — and these limitations bear on how far the result generalises rather than on\nwhether it holds in this setting.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading a fixed cell range | Setup | `XLSX.readdata(path, sheet, \"A1:Q26\")` |\n| Long-format reshaping | Setup | `DataFrame` with `repeat(...; inner, outer)` |\n| Mean by group | Q2.1 | `mean(m[p, :])` |\n| Emphasis over 16 series | Q2.1 | grey context lines, colour on the two means |\n| Grouped column chart | Q2.2 | dodged `barplot!` |\n| Standard deviation, variance | Q2.3 | `std`, `var` |\n| Min, max, range | Q2.4 | `minimum`, `maximum` |\n| Simulation with a fixed seed | Q3.1 | `MersenneTwister(seed)`, `rand(rng, Bool, n)` |\n| Paired *t*-test | Q3.2, Q3.3 | `OneSampleTTest(x .- y)` |\n| Unpaired (Welch) *t*-test | Q3.3 | `UnequalVarianceTTest(x, y)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}