{
  "hash": "6d7257880f38c9ee2a5a3864f2d67c27",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"5. Measuring inequality\"\nsubtitle: \"Lorenz curves, Gini coefficients, and inequality that isn't about money\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nProject 4 ended on GDP per capita's largest blind spot: a mean says nothing about who receives\nit. This project measures that directly — first for income, then for two things money does not\nbuy.\n\n- **[Part 5.1](#part-5.1)** — measuring income inequality\n- **[Part 5.2](#part-5.2)** — measuring other kinds of inequality\n\nNew concepts: the **Lorenz curve**, the **Gini coefficient**, and inter-decile ratios. Book\npages: [project](https://books.core-econ.org/doing-economics/book/text/05-01.html),\n[R walk-throughs](https://books.core-econ.org/doing-economics/book/text/05-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/05-04.html).\n\n::: {.callout-important}\n## The book's dataset no longer exists\n\nPart 5.1 uses decile income data from the Global Consumption and Income Project. The book sends\nyou to the GCIP site to download `GCIPrawdata.xlsx`. **That site is gone** — `gcip.info` has\nbeen taken over by an SEO spam operation and `globalinc.org` redirects to an unrelated domain.\nEven the Internet Archive's recent captures are the spam site.\n\nCaptures from before the takeover still hold the real files. This project uses an 18 March 2017\ncapture of the GCIP Global Income Distribution export, committed to this repository so it\ncannot be lost again. It reproduces the book's published cumulative shares exactly for China\n2014 and the United States in both years, and to within 0.03 percentage points for China 1980.\n\nThe export is shaped differently from the book's: `share1`–`share10` and `income1`–`income10`\nrather than `Decile 1 Income` onward, and a CSV inside a zip rather than a spreadsheet.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing ZipFile, CSV, DataFrames\nusing Statistics\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n::: {#cell-read-gcip .cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"Read the GCIP CSV straight out of the archive, without unpacking it.\"\"\"\nfunction read_gcip()\n    archive = ZipFile.Reader(rawpath(\"05\", \"gcip-gid-excel.zip\"))\n    try\n        idx = findfirst(f -> endswith(f.name, \"previewexcel.csv\"), archive.files)\n        idx === nothing && error(\"gid-previewexcel.csv not found in the archive\")\n        return CSV.read(read(archive.files[idx]), DataFrame)\n    finally\n        close(archive)\n    end\nend\n\ngcip = read_gcip()\n(rows = nrow(gcip), countries = length(unique(gcip.country)),\n years = extrema(gcip.year))\n```\n\n::: {#read-gcip .cell-output .cell-output-display execution_count=1}\n```\n(rows = 8839, countries = 161, years = (1960, 2015))\n```\n:::\n:::\n\n\n\n# Part 5.1 — Measuring income inequality {#part-5.1}\n\nTwo countries with very different inequality trajectories: **China**, which industrialised\nrapidly over this period, and the **United States**.\n\n## Q1. Cumulative income share by decile {#p1-q1}\n\n::: {#cell-cumulative-shares .cell execution_count=1}\n``` {.julia .cell-code}\nconst PAIRS = [(\"China\", 1980), (\"China\", 2014),\n               (\"United States\", 1980), (\"United States\", 2014)]\n\n\"\"\"Decile income shares for one country-year, poorest decile first.\"\"\"\nfunction decile_shares_of(df, country, year)\n    row = df[(df.country .== country) .& (df.year .== year), :]\n    isempty(row) && error(\"no GCIP row for $country $year\")\n    return [row[1, Symbol(\"share$i\")] for i in 1:10]\nend\n\ncumulative = DataFrame(decile = 1:10)\nfor (country, year) in PAIRS\n    # cumsum turns per-decile shares into the Lorenz curve's vertical axis.\n    cumulative[!, \"$country $year\"] = round.(100 .* cumsum(decile_shares_of(gcip, country, year)),\n                                             digits = 2)\nend\n\ncumulative\n```\n\n::: {#cumulative-shares .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">decile</th><th style = \"text-align: left;\">China 1980</th><th style = \"text-align: left;\">China 2014</th><th style = \"text-align: left;\">United States 1980</th><th style = \"text-align: left;\">United States 2014</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">3.15</td><td style = \"text-align: right;\">0.92</td><td style = \"text-align: right;\">2.29</td><td style = \"text-align: right;\">1.88</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">7.66</td><td style = \"text-align: right;\">2.84</td><td style = \"text-align: right;\">6.22</td><td style = \"text-align: right;\">5.14</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">13.44</td><td style = \"text-align: right;\">5.81</td><td style = \"text-align: right;\">11.52</td><td style = \"text-align: right;\">9.66</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">20.48</td><td style = \"text-align: right;\">9.95</td><td style = \"text-align: right;\">18.08</td><td style = \"text-align: right;\">15.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">28.82</td><td style = \"text-align: right;\">15.44</td><td style = \"text-align: right;\">25.89</td><td style = \"text-align: right;\">22.45</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">38.56</td><td style = \"text-align: right;\">22.55</td><td style = \"text-align: right;\">35.04</td><td style = \"text-align: right;\">30.92</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">49.92</td><td style = \"text-align: right;\">31.75</td><td style = \"text-align: right;\">45.73</td><td style = \"text-align: right;\">41.09</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">63.26</td><td style = \"text-align: right;\">43.95</td><td style = \"text-align: right;\">58.45</td><td style = \"text-align: right;\">53.58</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">79.33</td><td style = \"text-align: right;\">61.43</td><td style = \"text-align: right;\">74.39</td><td style = \"text-align: right;\">69.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">100.0</td><td style = \"text-align: right;\">100.0</td><td style = \"text-align: right;\">100.0</td><td style = \"text-align: right;\">100.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe ninth-decile row is the one to read: in 1980 the poorest 90% of China received **79.33%** of\nincome; by 2014 they received **61.43%**. The United States moved from 74.39% to 69.90%.\n\nThese reproduce the book's published solutions exactly for three of the four series. China 1980\ndiffers by 0.01–0.03 percentage points in the first three deciles — a GCIP revision between the\nbook's vintage and this export, not a method difference, since the same columns match to the\ndigit everywhere else.\n\n## Q2. Lorenz curves {#p1-q2}\n\n::: {#cell-fig-lorenz .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 500))\nLabel(fig[0, 1:2], \"China's distribution moved further from equality than the US's\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\naxs = [Axis(fig[1, i]; title = country,\n            xlabel = \"Cumulative share of population\",\n            ylabel = i == 1 ? \"Cumulative share of income\" : \"\",\n            limits = ((0, 1), (0, 1)), aspect = 1)\n       for (i, country) in enumerate((\"China\", \"United States\"))]\n\nfor (i, country) in enumerate((\"China\", \"United States\"))\n    # Perfect equality: everyone holds the same, so share == population share.\n    lines!(axs[i], [0, 1], [0, 1]; color = BASELINE, linewidth = 1)\n    for (j, year) in enumerate((1980, 2014))\n        curve = lorenz(decile_shares_of(gcip, country, year))\n        lines!(axs[i], curve.population, curve.share;\n               color = series_color(j), label = string(year))\n    end\n    i == 2 && hideydecorations!(axs[i]; grid = false)\nend\n\nLegend(fig[2, 1:2], first(axs); orientation = :horizontal, framevisible = false)\ncolgap!(fig.layout, 28)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Lorenz curves for China and the United States, 1980 and 2014. The diagonal is perfect equality; the further a curve bows below it, the more unequal the distribution. Faceting by country keeps each panel to two curves, so the colour channel carries year rather than four country-year combinations.](index_files/figure-html/fig-lorenz-output-1.svg){#fig-lorenz}\n:::\n:::\n\n\n\n`lorenz` prepends the origin, so the curve runs from $(0,0)$ to $(1,1)$ and can be plotted\nstraight against the diagonal.\n\n## Q3. Reading the curves {#p1-q3}\n\n**Within each country over time.** Both curves bow further from the diagonal in 2014 than in\n1980, so inequality rose in both. The movement is far larger for China. Its 1980 curve is the\nclosest to equality of the four — a legacy of a centrally planned economy with compressed wage\nscales — and its 2014 curve is the furthest from it.\n\n**Between countries in each year.** In 1980 China was substantially *more* equal than the United\nStates. By 2014 the ordering has reversed and China is the more unequal of the two.\n\n**What plausibly drove this.** For China, market liberalisation from 1978: returns to skill and\ncapital reappeared, coastal provinces industrialised far faster than inland ones, and the\nrural–urban gap widened. Growth was fast and very unevenly distributed — average incomes rose\nenormously while the distribution stretched. For the United States, a slower widening usually\nattributed to some mix of skill-biased technical change, declining union coverage, and falling\ntop marginal tax rates.\n\nOne thing the curves cannot show: China's poorest decile is far better off in absolute terms in\n2014 than in 1980, despite receiving a smaller share. A Lorenz curve is scale-free — it\ndescribes shares, not levels — so a country can become more unequal while everyone gets richer.\n\n## Q4. Gini coefficients {#p1-q4}\n\nThe Gini is twice the area between the Lorenz curve and the diagonal: 0 at perfect equality,\napproaching 1 as one unit takes everything.\n\n::: {#cell-gini-table .cell execution_count=1}\n``` {.julia .cell-code}\ngini_table = DataFrame(\n    country = first.(PAIRS), year = last.(PAIRS),\n    gini_from_deciles = [round(gini(decile_shares_of(gcip, c, y)), digits = 4)\n                         for (c, y) in PAIRS],\n    gini_published = [round(gcip[(gcip.country .== c) .& (gcip.year .== y), :gini][1], digits = 4)\n                      for (c, y) in PAIRS])\ngini_table.difference = round.(gini_table.gini_from_deciles .- gini_table.gini_published,\n                               digits = 4)\ngini_table\n```\n\n::: {#gini-table .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">gini_from_deciles</th><th style = \"text-align: left;\">gini_published</th><th style = \"text-align: left;\">difference</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.2908</td><td style = \"text-align: right;\">0.2944</td><td style = \"text-align: right;\">-0.0036</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">0.5107</td><td style = \"text-align: right;\">0.5234</td><td style = \"text-align: right;\">-0.0127</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.3448</td><td style = \"text-align: right;\">0.3511</td><td style = \"text-align: right;\">-0.0063</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">0.4</td><td style = \"text-align: right;\">0.4086</td><td style = \"text-align: right;\">-0.0086</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe ordering matches the chart exactly, which is the check the question asks for: China 1980 is\nlowest (0.291), China 2014 highest (0.511), and the US sits between them in both years — the\nsame ranking as how far each curve bows from the diagonal.\n\n::: {.callout-note}\n## Why these are slightly below GCIP's own Gini\n\nEvery value computed from deciles comes out **0.004 to 0.013 below** the Gini GCIP publishes for\nthe same country-year, and the gap is largest for the most unequal case (China 2014).\n\nThis is not an error in either number. A Gini computed from ten decile shares treats everyone\ninside a decile as having identical income, so all **within-decile** inequality vanishes. The\nLorenz curve becomes ten straight segments instead of a smooth curve, and straight segments cut\nthe corner — the area between curve and diagonal is understated, so the Gini is too.\n\nGCIP computes its figure from the underlying distribution, which keeps that inequality. The gap\ngrows with inequality because the top decile is where within-group spread is largest: lumping\nthe top 10% into a single average hides the most.\n\nThe practical lesson: a Gini from grouped data is a lower bound, and coarser grouping means a\nlarger bias. Quintiles would understate further than deciles do.\n:::\n\n## Q5. Inter-decile ratios {#p1-q5}\n\n::: {#cell-ratios .cell execution_count=1}\n``` {.julia .cell-code}\n# The 90/10 ratio compares income AT the 90th percentile with income AT the 10th -\n# not the mean of the top decile against the mean of the bottom one, which is a\n# different and larger quantity. The percentile columns exist for benchmark years\n# only, and 2014 is not one of them, so 2015 stands in.\nconst RATIO_YEARS = [1980, 2015]\n\nfunction ratios_for(df, country, year)\n    row = df[(df.country .== country) .& (df.year .== year), :]\n    p10, p50, p90 = row.incomeatperc10[1], row.incomeatperc50[1], row.incomeatperc90[1]\n    any(ismissing, (p10, p50, p90)) && return (missing, missing, missing)\n    return (p90 / p10, p90 / p50, p50 / p10)\nend\n\nratio_table = DataFrame(country = String[], year = Int[],\n                        r90_10 = Union{Missing,Float64}[],\n                        r90_50 = Union{Missing,Float64}[],\n                        r50_10 = Union{Missing,Float64}[])\nfor country in (\"China\", \"United States\"), year in RATIO_YEARS\n    r = ratios_for(gcip, country, year)\n    push!(ratio_table, (country, year,\n                        map(x -> ismissing(x) ? missing : round(x, digits = 2), r)...))\nend\nratio_table\n```\n\n::: {#ratios .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">r90_10</th><th style = \"text-align: left;\">r90_50</th><th style = \"text-align: left;\">r50_10</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">4.65</td><td style = \"text-align: right;\">1.98</td><td style = \"text-align: right;\">2.34</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">15.59</td><td style = \"text-align: right;\">3.51</td><td style = \"text-align: right;\">4.44</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">5.82</td><td style = \"text-align: right;\">2.19</td><td style = \"text-align: right;\">2.66</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">2015</td><td style = \"text-align: right;\">7.5</td><td style = \"text-align: right;\">2.52</td><td style = \"text-align: right;\">2.98</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**Why policymakers use these rather than a single Gini.** A Gini compresses the whole\ndistribution into one number, so two countries with the same Gini can be unequal in different\nplaces. The three ratios separate that:\n\n- **90/10** is overall spread, top to bottom.\n- **90/50** isolates the top half — how far the well-off are above the median.\n- **50/10** isolates the bottom half — how far the median is above the poor.\n\nThe distinction matters because the policies differ. A high 50/10 is about poverty and the\nbottom of the labour market, addressed by minimum wages, transfers and in-work benefits. A high\n90/50 is about top incomes, addressed by progressive taxation. A single Gini cannot tell you\nwhich problem you have.\n\nReading the table: China's 90/10 more than doubles between 1980 and 2015, and both halves widen.\nThe United States starts more unequal on every ratio and widens more modestly.\n\n## Q6. Comparing across countries {#p1-q6}\n\nThe book sends you to the OECD's interactive portal to browse ratio measures and Gini\ncoefficients for 42 countries. The same comparison is computable here, which has the advantage\nof being reproducible rather than a screenshot:\n\n::: {#cell-cross-country .cell execution_count=1}\n``` {.julia .cell-code}\nbenchmark = gcip[(gcip.year .== 2015) .& .!ismissing.(gcip.incomeatperc90) .&\n                 .!ismissing.(gcip.incomeatperc10), :]\n\ncross = DataFrame(country = benchmark.country,\n                  gini = round.(benchmark.gini, digits = 3),\n                  r90_10 = round.(benchmark.incomeatperc90 ./ benchmark.incomeatperc10, digits = 2),\n                  r50_10 = round.(benchmark.incomeatperc50 ./ benchmark.incomeatperc10, digits = 2),\n                  palma = round.(benchmark.palmaratio, digits = 2))\nsort!(cross, :gini, rev = true)\n\nvcat(first(cross, 8), last(cross, 8))\n```\n\n::: {#cross-country .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>16×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">gini</th><th style = \"text-align: left;\">r90_10</th><th style = \"text-align: left;\">r50_10</th><th style = \"text-align: left;\">palma</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"InlineStrings.String31\" style = \"text-align: left;\">String31</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">South Africa</td><td style = \"text-align: right;\">0.662</td><td style = \"text-align: right;\">22.13</td><td style = \"text-align: right;\">4.07</td><td style = \"text-align: right;\">8.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Zambia</td><td style = \"text-align: right;\">0.636</td><td style = \"text-align: right;\">22.73</td><td style = \"text-align: right;\">4.9</td><td style = \"text-align: right;\">8.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Kenya</td><td style = \"text-align: right;\">0.605</td><td style = \"text-align: right;\">18.01</td><td style = \"text-align: right;\">4.64</td><td style = \"text-align: right;\">7.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Jamaica</td><td style = \"text-align: right;\">0.595</td><td style = \"text-align: right;\">25.79</td><td style = \"text-align: right;\">6.17</td><td style = \"text-align: right;\">6.27</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Malawi</td><td style = \"text-align: right;\">0.594</td><td style = \"text-align: right;\">15.74</td><td style = \"text-align: right;\">4.16</td><td style = \"text-align: right;\">6.59</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Mozambique</td><td style = \"text-align: right;\">0.592</td><td style = \"text-align: right;\">17.76</td><td style = \"text-align: right;\">4.62</td><td style = \"text-align: right;\">6.51</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Cameroon</td><td style = \"text-align: right;\">0.588</td><td style = \"text-align: right;\">15.87</td><td style = \"text-align: right;\">4.17</td><td style = \"text-align: right;\">6.35</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Cote d&apos;Ivoire</td><td style = \"text-align: right;\">0.587</td><td style = \"text-align: right;\">18.49</td><td style = \"text-align: right;\">4.85</td><td style = \"text-align: right;\">6.31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Belgium</td><td style = \"text-align: right;\">0.275</td><td style = \"text-align: right;\">3.63</td><td style = \"text-align: right;\">2.03</td><td style = \"text-align: right;\">0.97</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">0.273</td><td style = \"text-align: right;\">3.58</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: right;\">0.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Finland</td><td style = \"text-align: right;\">0.27</td><td style = \"text-align: right;\">3.38</td><td style = \"text-align: right;\">1.83</td><td style = \"text-align: right;\">0.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Iceland</td><td style = \"text-align: right;\">0.269</td><td style = \"text-align: right;\">3.34</td><td style = \"text-align: right;\">1.89</td><td style = \"text-align: right;\">0.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">Czech Republic</td><td style = \"text-align: right;\">0.263</td><td style = \"text-align: right;\">3.07</td><td style = \"text-align: right;\">1.82</td><td style = \"text-align: right;\">0.94</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">Slovak Republic</td><td style = \"text-align: right;\">0.26</td><td style = \"text-align: right;\">3.55</td><td style = \"text-align: right;\">2.07</td><td style = \"text-align: right;\">0.88</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">Norway</td><td style = \"text-align: right;\">0.258</td><td style = \"text-align: right;\">3.36</td><td style = \"text-align: right;\">1.91</td><td style = \"text-align: right;\">0.89</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">Slovenia</td><td style = \"text-align: right;\">0.256</td><td style = \"text-align: right;\">3.23</td><td style = \"text-align: right;\">1.87</td><td style = \"text-align: right;\">0.88</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-gini-vs-ratio .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 560))\nax = Axis(fig[1, 1];\n          title = \"Two measures of the same distributions, correlation \" *\n                  \"$(round(cor(cross.gini, cross.r90_10), digits = 3))\",\n          xlabel = \"Gini coefficient\", ylabel = \"90/10 ratio\")\nscatter!(ax, cross.gini, cross.r90_10; color = series_color(1))\n\nfor name in (\"China\", \"United States\", \"South Africa\", \"Sweden\")\n    idx = findfirst(==(name), cross.country)\n    idx === nothing && continue\n    text!(ax, cross.gini[idx], cross.r90_10[idx]; text = name, fontsize = 11,\n          color = MUTED, align = (:left, :center), offset = (7, 0))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Gini against the 90/10 ratio across countries in 2015. The two measures agree on the broad ordering but not exactly — vertical spread at a given Gini is where the summary measure hides something.](index_files/figure-html/fig-gini-vs-ratio-output-1.svg){#fig-gini-vs-ratio}\n:::\n:::\n\n\n\n**Why more than one measure matters.** The two correlate strongly but not perfectly, and the\nscatter at a given Gini is the point: countries with the same Gini can have quite different\n90/10 ratios, because the Gini weights the middle of the distribution heavily while the ratio\nignores it entirely. Neither is wrong; they answer different questions. Reporting one alone lets\nthe choice of measure decide the ranking.\n\n## Q7. Measures other than the Gini {#p1-q7}\n\nThe book points at the Chartbook of Economic Inequality and asks for two measures excluding the\nGini. Two that this dataset already carries, so they can be computed rather than browsed:\n\n::: {#cell-other-measures .cell execution_count=1}\n``` {.julia .cell-code}\nalt_measures = DataFrame(country = String[], year = Int[],\n                         palma = Float64[], top1_share = Union{Missing,Float64}[],\n                         top5_share = Union{Missing,Float64}[])\nfor (country, year) in PAIRS\n    row = gcip[(gcip.country .== country) .& (gcip.year .== year), :]\n    push!(alt_measures, (country, year, round(row.palmaratio[1], digits = 3),\n                         ismissing(row.sharetop1[1]) ? missing : round(100row.sharetop1[1], digits = 2),\n                         ismissing(row.sharetop5[1]) ? missing : round(100row.sharetop5[1], digits = 2)))\nend\nalt_measures\n```\n\n::: {#other-measures .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">year</th><th style = \"text-align: left;\">palma</th><th style = \"text-align: left;\">top1_share</th><th style = \"text-align: left;\">top5_share</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">1.01</td><td style = \"text-align: right;\">2.39</td><td style = \"text-align: right;\">11.13</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">3.876</td><td style = \"font-style: italic; text-align: right;\">missing</td><td style = \"font-style: italic; text-align: right;\">missing</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">1.416</td><td style = \"text-align: right;\">3.99</td><td style = \"text-align: right;\">15.28</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">2014</td><td style = \"text-align: right;\">1.953</td><td style = \"font-style: italic; text-align: right;\">missing</td><td style = \"font-style: italic; text-align: right;\">missing</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n**The Palma ratio** is the income share of the richest 10% divided by that of the poorest 40%.\nIts rationale is empirical: across countries the middle five deciles receive a strikingly stable\nshare of income, so almost all cross-country variation in inequality is a contest between the\ntop decile and the bottom four. The Palma looks only where the action is, and unlike the Gini it\ndoes not dilute that with a large stable middle.\n\n**The top 1% share** is the share of total income going to the highest-earning 1%. It captures\nwhat both the Gini and decile ratios miss by construction: everything inside the top decile.\nMuch of the measured rise in US inequality since 1980 is concentrated in the top 1%, which a\ndecile-based Lorenz curve cannot see at all — the same limitation as the callout in Q4, at the\nother end of the distribution.\n\nTheir weakness is the mirror image of their strength: both discard most of the distribution, so\nneither would detect a change confined to the middle. This is the running theme — each measure\nis a deliberate choice about where to look.\n\n# Part 5.2 — Other kinds of inequality {#part-5.2}\n\nIncome is one dimension. Two more, where the inequality is in something money cannot be\nredistributed to fix directly.\n\n## Q1. Inequality in length of life {#p2-q1}\n\n::: {#cell-read-lifespan .cell execution_count=1}\n``` {.julia .cell-code}\nlifespan = CSV.read(rawpath(\"05\", \"lifespan-inequality-gini-females.csv\"), DataFrame)\nrename!(lifespan, names(lifespan)[4] => :lifespan_gini)\n\n(rows = nrow(lifespan), entities = length(unique(lifespan.Entity)),\n years = extrema(lifespan.Year))\n```\n\n::: {#read-lifespan .cell-output .cell-output-display execution_count=1}\n```\n(rows = 20804, entities = 264, years = (1751, 2023))\n```\n:::\n:::\n\n\n\nA **Gini of lifespan** applies the same arithmetic to age at death instead of income. A value of\n0 would mean everyone dies at exactly the same age; higher values mean length of life is more\nunequally distributed. It is a measure of how much *mortality risk* varies within a population,\nand most of that variation comes from deaths that happen early.\n\n::: {#cell-fig-lifespan .cell execution_count=1}\n``` {.julia .cell-code}\nconst COUNTRIES_10 = [\"Japan\", \"Germany\", \"United States\", \"Russia\", \"Brazil\",\n                      \"China\", \"Mexico\", \"South Africa\", \"India\", \"Nigeria\"]\n\nwindow = lifespan[in(COUNTRIES_10).(lifespan.Entity) .&\n                  (lifespan.Year .>= 1952) .& (lifespan.Year .<= 2002), :]\n\nylims = extrema(window.lifespan_gini) .+ (-0.02, 0.02)\n\nfig = Figure(size = (960, 460))\nLabel(fig[0, 1:5], \"Lifespan inequality fell almost everywhere - and rose in Russia and South Africa\";\n      fontsize = 15, font = :bold, color = INK, halign = :left,\n      tellwidth = false, padding = (0, 0, 8, 0))\n\nfor (i, country) in enumerate(COUNTRIES_10)\n    r, c = fldmod1(i, 5)\n    ax = Axis(fig[r, c]; title = country, limits = (nothing, ylims),\n              xlabel = r == 2 ? \"Year\" : \"\", ylabel = c == 1 ? \"Lifespan Gini\" : \"\",\n              xticks = 1960:20:2000)\n    s = sort(window[window.Entity .== country, :], :Year)\n    lines!(ax, s.Year, s.lifespan_gini; color = series_color(1))\n    c != 1 && hideydecorations!(ax; grid = false)\n    r != 2 && hidexdecorations!(ax; grid = false)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Gini coefficient of female lifespan inequality, 1952–2002, for ten countries on shared axes. Ten series cannot each take a hue, so each country gets its own panel.](index_files/figure-html/fig-lifespan-output-1.svg){#fig-lifespan}\n:::\n:::\n\n\n\nTwo patterns. **The dominant one is convergence downward**: every country starts higher in 1952\nthan it ends in 2002, and the falls are largest where the starting level was highest — India and\nNigeria drop furthest. Falling lifespan inequality is mostly falling *child* mortality, because\na death at age 2 pulls the distribution far more than a death at 75.\n\n**The exceptions are informative.** Russia's series falls sharply to about 1970, then stalls and\nrises again through the 1990s — the post-Soviet mortality crisis, concentrated in\nworking-age adults. South Africa turns upward in the 1990s, the timing of the HIV/AIDS epidemic.\nBoth show up as *rising inequality in length of life* rather than a fall in the average, which\nis the sort of thing a mean life expectancy reports much later and more weakly.\n\n## Q2. Ranking countries, 1952 against 2002 {#p2-q2}\n\n::: {#cell-fig-lifespan-change .cell execution_count=1}\n``` {.julia .cell-code}\nendpoints = DataFrame(country = String[], y1952 = Float64[], y2002 = Float64[])\nfor country in COUNTRIES_10\n    s = lifespan[lifespan.Entity .== country, :]\n    a = s[s.Year .== 1952, :lifespan_gini]\n    b = s[s.Year .== 2002, :lifespan_gini]\n    (isempty(a) || isempty(b)) && continue\n    push!(endpoints, (country, a[1], b[1]))\nend\nendpoints.change = endpoints.y2002 .- endpoints.y1952\nsort!(endpoints, :y2002)\n\nfig = Figure(size = (860, 480))\nax = Axis(fig[1, 1]; title = \"Lifespan inequality, sorted by 2002\",\n          ylabel = \"Lifespan Gini\",\n          xticks = (1:nrow(endpoints), endpoints.country),\n          xticklabelrotation = pi / 6)\n\nfor (j, (col, label)) in enumerate(((:y1952, \"1952\"), (:y2002, \"2002\")))\n    xs = collect((1:nrow(endpoints)) .+ (j - 1.5) * 0.2)\n    barplot!(ax, xs, endpoints[!, col]; width = 0.16,\n             color = series_color(j), label = label)\nend\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Lifespan inequality in 1952 and 2002, sorted by the 2002 value. Every country improved, but the ordering changed substantially.](index_files/figure-html/fig-lifespan-change-output-1.svg){#fig-lifespan-change}\n:::\n:::\n\n\n\n::: {#cell-rank-change .cell execution_count=1}\n``` {.julia .cell-code}\nranked = copy(endpoints)\nsort!(ranked, :y1952); ranked.rank_1952 = 1:nrow(ranked)\nsort!(ranked, :y2002); ranked.rank_2002 = 1:nrow(ranked)\nranked.rank_change = ranked.rank_1952 .- ranked.rank_2002\nselect(ranked, :country, :y1952, :y2002, :change, :rank_1952, :rank_2002, :rank_change)\n```\n\n::: {#rank-change .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">y1952</th><th style = \"text-align: left;\">y2002</th><th style = \"text-align: left;\">change</th><th style = \"text-align: left;\">rank_1952</th><th style = \"text-align: left;\">rank_2002</th><th style = \"text-align: left;\">rank_change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Japan</td><td style = \"text-align: right;\">0.192446</td><td style = \"text-align: right;\">0.0790791</td><td style = \"text-align: right;\">-0.113367</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">0.143804</td><td style = \"text-align: right;\">0.0835613</td><td style = \"text-align: right;\">-0.0602425</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">United States</td><td style = \"text-align: right;\">0.139356</td><td style = \"text-align: right;\">0.0987449</td><td style = \"text-align: right;\">-0.0406106</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">-2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Mexico</td><td style = \"text-align: right;\">0.358898</td><td style = \"text-align: right;\">0.1178</td><td style = \"text-align: right;\">-0.241098</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">China</td><td style = \"text-align: right;\">0.348151</td><td style = \"text-align: right;\">0.120628</td><td style = \"text-align: right;\">-0.227523</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Russia</td><td style = \"text-align: right;\">0.246176</td><td style = \"text-align: right;\">0.124521</td><td style = \"text-align: right;\">-0.121655</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">-2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Brazil</td><td style = \"text-align: right;\">0.325251</td><td style = \"text-align: right;\">0.124747</td><td style = \"text-align: right;\">-0.200503</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">-2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">India</td><td style = \"text-align: right;\">0.431588</td><td style = \"text-align: right;\">0.206883</td><td style = \"text-align: right;\">-0.224705</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">South Africa</td><td style = \"text-align: right;\">0.370898</td><td style = \"text-align: right;\">0.263679</td><td style = \"text-align: right;\">-0.107219</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">-1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Nigeria</td><td style = \"text-align: right;\">0.467135</td><td style = \"text-align: right;\">0.344205</td><td style = \"text-align: right;\">-0.12293</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery country improved on the level, so the interesting content is in the reordering. **Russia\nis the clearest mover in the wrong direction**: comparatively equal in 1952, it ends worse\nthan several countries it started ahead of, because its improvement stopped around 1970 while\neveryone else's continued. The countries that started worst improved most, which is convergence\n— but convergence from very different causes, and it did not reach everyone.\n\n## Q3. A health inequality measure {#p2-q3}\n\nThe question asks you to choose a measure. **Choice made here: the lifespan Gini above, extended\nto its full modern coverage** rather than a WHO access indicator — because it is a genuine\ninequality measure rather than a level, and it is available for enough countries to rank.\n\nAn access measure like \"share of the population with essential medicines\" is a *level*: it tells\nyou how many people are covered, not how unevenly. Two countries at 80% coverage can differ\ncompletely in who the missing 20% are. That distinction is the whole subject of this project, so\na distributional measure is the better fit.\n\n::: {#cell-recent-lifespan .cell execution_count=1}\n``` {.julia .cell-code}\nrecent_year = maximum(lifespan.Year)\nrecent = dropmissing(lifespan[(lifespan.Year .== recent_year) .& .!ismissing.(lifespan.Code), :],\n                     :lifespan_gini)\n\n(year = recent_year, countries = nrow(recent),\n lowest = recent.Entity[argmin(recent.lifespan_gini)],\n lowest_value = round(minimum(recent.lifespan_gini), digits = 3),\n highest = recent.Entity[argmax(recent.lifespan_gini)],\n highest_value = round(maximum(recent.lifespan_gini), digits = 3),\n median_value = round(median(recent.lifespan_gini), digits = 3))\n```\n\n::: {#recent-lifespan .cell-output .cell-output-display execution_count=1}\n```\n(year = 2023, countries = 248, lowest = \"Macao\", lowest_value = 0.063, highest = \"Nigeria\", highest_value = 0.281, median_value = 0.103)\n```\n:::\n:::\n\n\n\n**How it is built.** Take the distribution of age at death implied by a period life table, then\ncompute the Gini of that distribution exactly as for income. The inputs are age-specific\nmortality rates, so it inherits their quality — which is the main limitation, since countries\nwith weak vital registration have modelled rather than measured rates.\n\n**Two further limitations.** It is a *period* measure: it describes the mortality conditions of\none year applied to a synthetic cohort, not the experience of any real generation. And it treats\nall early deaths alike regardless of cause, so it cannot distinguish an epidemic from a war from\na rise in infant mortality — the Russia and South Africa series above look similar in shape and\nhave nothing in common in cause.\n\n## Q4. Gender inequality in education {#p2-q4}\n\n::: {#cell-read-education .cell execution_count=1}\n``` {.julia .cell-code}\neducation = CSV.read(rawpath(\"05\", \"gender-gap-education-levels.csv\"), DataFrame)\nrename!(education,\n        \"Girls in primary education\" => :girls_primary,\n        \"Boys in primary education\" => :boys_primary,\n        \"Women in tertiary education\" => :women_tertiary,\n        \"Men in tertiary education\" => :men_tertiary)\n\n(rows = nrow(education), entities = length(unique(education.Entity)),\n years = extrema(education.Year))\n```\n\n::: {#read-education .cell-output .cell-output-display execution_count=1}\n```\n(rows = 10603, entities = 243, years = (1820, 2025))\n```\n:::\n:::\n\n\n\n**Choice made here: the gender parity ratio in primary enrolment** — girls enrolled divided by\nboys enrolled. A ratio of 1 is parity, below 1 means girls are under-enrolled. A ratio is the\nright form because raw counts confound the gender gap with population size and with overall\nenrolment growth.\n\n::: {#cell-parity .cell execution_count=1}\n``` {.julia .cell-code}\nedu = dropmissing(education, [:girls_primary, :boys_primary])\nedu = edu[(edu.boys_primary .> 0) .& .!ismissing.(edu.Code), :]\nedu.parity = edu.girls_primary ./ edu.boys_primary\n\nwindow_edu = edu[(edu.Year .>= 1980) .& (edu.Year .<= 2010), :]\ncoverage = combine(groupby(window_edu, :Entity), nrow => :years)\n\n# Coverage is thin: of 206 countries in the window only 11 report 25 or more of the\n# 31 years. A hardcoded country list would mostly miss, so the ten are selected from\n# the data instead - among countries with at least 15 observations, the ten furthest\n# from parity at their first observation, which are the ones with ground to cover.\neligible = coverage[coverage.years .>= 15, :Entity]\n\nstarts = combine(groupby(window_edu[in(eligible).(window_edu.Entity), :], :Entity)) do g\n    s = sort(g, :Year)\n    (; start_year = s.Year[1], start_parity = s.parity[1])\nend\nsort!(starts, :start_parity)\nEDU_10 = first(starts, 10).Entity\n\n(countries_in_window = nrow(coverage), with_15_plus_years = length(eligible),\n selected = EDU_10)\n```\n\n::: {#parity .cell-output .cell-output-display execution_count=1}\n```\n(countries_in_window = 206, with_15_plus_years = 48, selected = [\"Benin\", \"Guinea\", \"Gambia\", \"Oman\", \"Burkina Faso\", \"Central African Republic\", \"Morocco\", \"Togo\", \"Burundi\", \"Bangladesh\"])\n```\n:::\n:::\n\n\n\n::: {#cell-fig-parity .cell execution_count=1}\n``` {.julia .cell-code}\npanel = edu[in(EDU_10).(edu.Entity) .& (edu.Year .>= 1980) .& (edu.Year .<= 2010), :]\ncontext = edu[in(eligible).(edu.Entity) .& (edu.Year .>= 1980) .& (edu.Year .<= 2010), :]\n\nfig = Figure(size = (820, 480))\nax = Axis(fig[1, 1];\n          title = \"Primary enrolment moved toward parity almost everywhere\",\n          xlabel = \"Year\", ylabel = \"Girls per boy enrolled\")\n\n# Every eligible country as recessive context; parity as the reference line.\nfor country in eligible\n    s = sort(context[context.Entity .== country, :], :Year)\n    lines!(ax, s.Year, s.parity; color = (BASELINE, 0.35), linewidth = 0.75)\nend\nhlines!(ax, 1.0; color = BASELINE, linewidth = 1)\n\n# Three highlighted, which is as many as can carry distinct hues in a scatter of lines.\nfor (j, country) in enumerate(first(EDU_10, 3))\n    s = sort(panel[panel.Entity .== country, :], :Year)\n    lines!(ax, s.Year, s.parity; color = series_color(j), linewidth = 3, label = country)\nend\ntext!(ax, 1981, 1.005; text = \"parity\", align = (:left, :bottom),\n      fontsize = 11, color = MUTED)\naxislegend(ax; position = :rb, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Gender parity in primary enrolment, 1980–2010. All countries with sufficient coverage are shown in grey; the ten selected are drawn in colour only where they can be told apart, with the rest carried by the table below.](index_files/figure-html/fig-parity-output-1.svg){#fig-parity}\n:::\n:::\n\n\n\n::: {#cell-parity-change .cell execution_count=1}\n``` {.julia .cell-code}\n# Anchored on each country's first and last available observation rather than on\n# 1980 and 2010 exactly, since few countries report both of those years.\nchange = combine(groupby(panel, :Entity)) do g\n    s = sort(g, :Year)\n    (; from_year = s.Year[1], from = round(s.parity[1], digits = 3),\n       to_year = s.Year[end], to = round(s.parity[end], digits = 3),\n       change = round(s.parity[end] - s.parity[1], digits = 3))\nend\nsort!(change, :change, rev = true)\nrename!(change, :Entity => :country)\nchange\n```\n\n::: {#parity-change .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">from_year</th><th style = \"text-align: left;\">from</th><th style = \"text-align: left;\">to_year</th><th style = \"text-align: left;\">to</th><th style = \"text-align: left;\">change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Gambia</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.499</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">1.044</td><td style = \"text-align: right;\">0.546</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Benin</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.439</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">0.902</td><td style = \"text-align: right;\">0.463</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Bangladesh</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.688</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">1.1</td><td style = \"text-align: right;\">0.413</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Oman</td><td style = \"text-align: right;\">1981</td><td style = \"text-align: right;\">0.581</td><td style = \"text-align: right;\">2009</td><td style = \"text-align: right;\">0.972</td><td style = \"text-align: right;\">0.39</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Morocco</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.622</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">1.007</td><td style = \"text-align: right;\">0.385</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Guinea</td><td style = \"text-align: right;\">1984</td><td style = \"text-align: right;\">0.489</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">0.844</td><td style = \"text-align: right;\">0.354</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Burundi</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.679</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">1.023</td><td style = \"text-align: right;\">0.345</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Burkina Faso</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.598</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">0.914</td><td style = \"text-align: right;\">0.317</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Togo</td><td style = \"text-align: right;\">1980</td><td style = \"text-align: right;\">0.656</td><td style = \"text-align: right;\">2008</td><td style = \"text-align: right;\">0.899</td><td style = \"text-align: right;\">0.243</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Central African Republic</td><td style = \"text-align: right;\">1981</td><td style = \"text-align: right;\">0.616</td><td style = \"text-align: right;\">2010</td><td style = \"text-align: right;\">0.769</td><td style = \"text-align: right;\">0.153</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fig-parity-change .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (800, 440))\nax = Axis(fig[1, 1]; title = \"Gain in girls-per-boy enrolment, first to last observation\",\n          ylabel = \"Change in parity ratio\",\n          xticks = (1:nrow(change), change.country), xticklabelrotation = pi / 6)\nhlines!(ax, 0; color = BASELINE, linewidth = 1)\nbarplot!(ax, 1:nrow(change), change.change; width = 0.5, color = series_color(1))\nfor (x, v) in zip(1:nrow(change), change.change)\n    text!(ax, x, v; text = string(v), fontsize = 10,\n          align = (:center, v < 0 ? :top : :bottom), offset = (0, v < 0 ? -4 : 4))\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Change in primary enrolment parity between each country's first and last observation in 1980–2010, sorted. The anchor years differ by country and are given in the table above.](index_files/figure-html/fig-parity-change-output-1.svg){#fig-parity-change}\n:::\n:::\n\n\n\n**The pattern.** These ten were selected as the furthest from parity at the start, so having\nground to cover is true by construction. What is not is how much they covered: mean parity goes\nfrom **0.587 to 0.947**, no country moved backwards, and Gambia gains 0.55 to end above parity.\nThe gap largely closed within a generation.\n\nTwo things the selection does not force. **Five of the ten reached 0.95 or better**, and the\nlaggard is stark — the Central African Republic gains only 0.153 and ends at 0.769, still a\nquarter short. Convergence was fast but not universal.\n\n**Four ended above 1.0** — Bangladesh at 1.10, Gambia 1.04, Burundi 1.02, Morocco 1.01 — meaning\nmore girls than boys enrolled. That is not \"parity overshot into female advantage\"; it usually\nmeans boys are leaving school for paid work, which is its own inequality. It also shows why the\nratio needs reading in both directions rather than treated as a target to hit.\n\n**Limitations, and they are substantial.**\n\n- **Enrolment is not attendance, and neither is learning.** A child counted as enrolled may\n  attend rarely. Parity in enrolment is compatible with a large gap in years completed or in\n  what was learned.\n- **Parity is not equality, in either direction.** A ratio of 1.0 says the same *number* of girls\n  and boys are enrolled, not that they receive the same quality of schooling, sit the same\n  subjects, or face the same expectations afterwards. And the four countries above 1.0 show the\n  measure is not monotone in \"good\": a ratio drifting above parity because boys are leaving for\n  work is a problem the number reports as an improvement.\n- **It says nothing about level.** Two countries can both be at parity with one enrolling 95% of\n  children and the other 45%. Perfect parity at low enrolment is equality of deprivation — which\n  is exactly the objection Q3 raised against using a coverage level as an inequality measure,\n  running the other way.\n- **Primary is the easiest level.** Gaps are typically much wider at secondary and tertiary, so\n  primary parity is the most flattering indicator available.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Reading a CSV inside a zip | Setup | `ZipFile.Reader`, then `CSV.read(read(f), ...)` |\n| Cumulative shares | Q5.1 Q1 | `cumsum` |\n| Lorenz curve | Q5.1 Q2 | `lorenz(shares)` |\n| Gini coefficient | Q5.1 Q4 | `gini(shares)` |\n| Inter-decile ratios | Q5.1 Q5 | percentile columns, not decile means |\n| Small multiples over 10 series | Q5.2 Q1 | `fldmod1(i, 5)` into `fig[r, c]` |\n| Sorted grouped bars | Q5.2 Q2 | `sort!` then dodged `barplot!` |\n| Rank change | Q5.2 Q2 | sort twice, difference the positions |\n| Emphasis over many series | Q5.2 Q4 | grey context lines, colour on three |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}