{
  "hash": "f54fba783cbc0687aeda2845495c63c2",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"8. Measuring the non-monetary cost of unemployment\"\nsubtitle: \"What 129,515 survey respondents say about life satisfaction, and how much of the work is cleaning\"\nengine: julia\njulia:\n  exeflags: [\"--project=@.\"]\n---\n\nThe European Values Study, four waves between 1981 and 2010, 164,997 respondents across 46\ncountries. The question is whether unemployed people report lower life satisfaction than\nemployed people, and whether that gap is larger where the social norm of working is stronger.\n\n- **[Part 8.1](#part-8.1)** — cleaning and summarizing the data\n- **[Part 8.2](#part-8.2)** — visualizing the data\n- **[Part 8.3](#part-8.3)** — confidence intervals for a difference in means\n\nNew concept: the **confidence interval for a difference in means**. But most of this project is\ndata cleaning — the file arrives with missing values coded as the string `.a`, ordinal scales\nstored as words, one column packing two variables, and four waves that do not ask the same\nquestions. Book pages:\n[project](https://books.core-econ.org/doing-economics/book/text/08-01.html),\n[R walk-through](https://books.core-econ.org/doing-economics/book/text/08-03.html),\n[solutions](https://books.core-econ.org/doing-economics/book/text/08-04.html).\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing XLSX, DataFrames\nusing Statistics, StatsBase, HypothesisTests\nusing CairoMakie\nusing DoingEconomics\n\nCairoMakie.activate!(type = \"svg\")\nuse_doingecon_theme!()\n```\n:::\n\n\n\n# Part 8.1 — Cleaning and summarizing the data {#part-8.1}\n\n## Q1. Import the four waves and label the variables {#p1-q1}\n\n**(a)** The workbook holds one sheet per wave. All four share the same 17 columns, so they stack\ndirectly — `reduce(vcat, ...)` is the Julia equivalent of the book's repeated `rbind`.\n\n::: {#cell-read-evs .cell execution_count=1}\n``` {.julia .cell-code}\nconst WAVES = [\"1981-1984\", \"1990-1993\", \"1999-2001\", \"2008-2010\"]\npath = rawpath(\"08\", \"life-satisfaction-evs.xlsx\")\n\nevs = reduce(vcat, [DataFrame(XLSX.readtable(path, \"Wave $i\")) for i in 1:4])\n\nDataFrame(wave = WAVES, number = 1:4,\n          respondents = [sum(evs.S002EVS .== w) for w in WAVES])\n```\n\n::: {#read-evs .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">wave</th><th style = \"text-align: left;\">number</th><th style = \"text-align: left;\">respondents</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">1981-1984</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">19378</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">1990-1993</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">38213</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">1999-2001</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">41125</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">2008-2010</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">66281</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n164,997 rows and 17 columns. The variable names are EVS codes, which carry no meaning on their\nown.\n\n**(b)** The workbook's `Data dictionary` sheet is an empty template — it lists the 17 codes with\nblank name and description columns for you to fill in from the codebook PDF. Two of its rows\nare worth noting: it lists `S009` (a country ISO code), which is not actually in the data, and\nit omits nothing else.\n\nR attaches labels with `attr`, which stores a *positional vector* alongside the frame. Julia's\nDataFrames has per-column metadata instead, keyed by column name:\n\n::: {#cell-label-columns .cell execution_count=1}\n``` {.julia .cell-code}\nlabels = [\n    \"S002EVS\" => (\"EVS wave\", \"Survey wave\"),\n    \"S003\"    => (\"Country\", \"Country or region\"),\n    \"S006\"    => (\"Respondent\", \"Original respondent number\"),\n    \"A009\"    => (\"Health\", \"State of health (subjective)\"),\n    \"A170\"    => (\"Life satisfaction\", \"Satisfaction with your life as a whole\"),\n    \"C036\"    => (\"Work Q1\", \"To develop talents you need to have a job\"),\n    \"C037\"    => (\"Work Q2\", \"Humiliating to receive money without working for it\"),\n    \"C038\"    => (\"Work Q3\", \"People who don't work become lazy\"),\n    \"C039\"    => (\"Work Q4\", \"Work is a duty towards society\"),\n    \"C041\"    => (\"Work Q5\", \"Work comes first even if it means less spare time\"),\n    \"X001\"    => (\"Sex\", \"Sex\"),\n    \"X003\"    => (\"Age\", \"Age in years\"),\n    \"X007\"    => (\"Marital status\", \"Marital status\"),\n    \"X011_01\" => (\"Children\", \"How many living children do you have\"),\n    \"X025A\"   => (\"Education\", \"Educational level (ISCED one digit)\"),\n    \"X028\"    => (\"Employment\", \"Employment status\"),\n    \"X047D\"   => (\"Income\", \"Monthly household income (thousands of PPP euros)\"),\n]\n\nfor (col, (label, description)) in labels\n    colmetadata!(evs, col, \"label\", label; style = :note)\n    colmetadata!(evs, col, \"description\", description; style = :note)\nend\n\nDataFrame(variable = first.(labels),\n          label = [l for (_, (l, _)) in labels],\n          description = [d for (_, (_, d)) in labels])\n```\n\n::: {#label-columns .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>17×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">label</th><th style = \"text-align: left;\">description</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">S002EVS</td><td style = \"text-align: left;\">EVS wave</td><td style = \"text-align: left;\">Survey wave</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">S003</td><td style = \"text-align: left;\">Country</td><td style = \"text-align: left;\">Country or region</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">S006</td><td style = \"text-align: left;\">Respondent</td><td style = \"text-align: left;\">Original respondent number</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">A009</td><td style = \"text-align: left;\">Health</td><td style = \"text-align: left;\">State of health (subjective)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">A170</td><td style = \"text-align: left;\">Life satisfaction</td><td style = \"text-align: left;\">Satisfaction with your life as a whole</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">C036</td><td style = \"text-align: left;\">Work Q1</td><td style = \"text-align: left;\">To develop talents you need to have a job</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">C037</td><td style = \"text-align: left;\">Work Q2</td><td style = \"text-align: left;\">Humiliating to receive money without working for it</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">C038</td><td style = \"text-align: left;\">Work Q3</td><td style = \"text-align: left;\">People who don&apos;t work become lazy</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">C039</td><td style = \"text-align: left;\">Work Q4</td><td style = \"text-align: left;\">Work is a duty towards society</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">C041</td><td style = \"text-align: left;\">Work Q5</td><td style = \"text-align: left;\">Work comes first even if it means less spare time</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">X001</td><td style = \"text-align: left;\">Sex</td><td style = \"text-align: left;\">Sex</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">X003</td><td style = \"text-align: left;\">Age</td><td style = \"text-align: left;\">Age in years</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">X007</td><td style = \"text-align: left;\">Marital status</td><td style = \"text-align: left;\">Marital status</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">X011_01</td><td style = \"text-align: left;\">Children</td><td style = \"text-align: left;\">How many living children do you have</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">X025A</td><td style = \"text-align: left;\">Education</td><td style = \"text-align: left;\">Educational level (ISCED one digit)</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">X028</td><td style = \"text-align: left;\">Employment</td><td style = \"text-align: left;\">Employment status</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">X047D</td><td style = \"text-align: left;\">Income</td><td style = \"text-align: left;\">Monthly household income (thousands of PPP euros)</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {.callout-note}\n## `colmetadata!` beats `attr` for exactly one reason\n\nR's `attr(df, \"labels\")` is a vector matched to columns *by position*. Drop a column or reorder\none and every label after it silently points at the wrong variable — and the book's own code\nthen indexes it with `attr(df, \"labels\")[attr(df, \"names\") == \"X028\"]`, which is the workaround\nfor that fragility.\n\nJulia's metadata is keyed by column, and `style = :note` makes it survive the operations that\nwould break a positional vector:\n\n::: {#cell-metadata-survives .cell execution_count=1}\n``` {.julia .cell-code}\nwave4_only = select(evs[evs.S002EVS .== last(WAVES), :], :X028, :A170)\n\n(columns = names(wave4_only),\n still_labelled = colmetadata(wave4_only, :X028, \"description\"))\n```\n\n::: {#metadata-survives .cell-output .cell-output-display execution_count=1}\n```\n(columns = [\"X028\", \"A170\"], still_labelled = \"Employment status\")\n```\n:::\n:::\n\n\n\nA `filter` and a `select` that reversed the column order, and the label is still attached to the\nright variable.\n:::\n\n## Q2. Whether these self-reports can be compared at all {#p1-q2}\n\n**(a) Life satisfaction (`A170`) across people and countries.** The 1–10 answers are numbers,\nbut treating them as a measured quantity needs three assumptions, and they get progressively\nharder to accept.\n\n1. **Ordinality within a person** — that a respondent's 7 is more satisfied than their 6. This is\n   the weak assumption and it is fine.\n2. **Cardinality** — that the step from 6 to 7 is the same size as the step from 8 to 9. Every\n   mean in this project needs this. There is no reason it holds, and reported scales tend to\n   compress at the top: moving 9 → 10 is a bigger real change than 5 → 6.\n3. **Interpersonal and cross-country comparability** — that your 7 and my 7 describe the same\n   internal state. This is the one that actually bites for this project, because the whole design\n   compares country averages. Translation of the question, norms about admitting\n   dissatisfaction, and the tendency to answer near the scale midpoint all vary systematically by\n   country.\n\nThe third assumption is where the project's conclusions are most exposed. It matters less than it\nlooks, though, because the analysis in Parts 8.2 and 8.3 works with *differences between groups\ninside the same country*. Any country-level offset — a national habit of answering high, a\ntranslation that shifts the whole scale — cancels out of a within-country difference. What does\nnot cancel is a country-level difference in how *unemployed* people specifically respond, which\nis precisely the social-norm channel under study. The design cannot separate \"the unemployed are\nless satisfied\" from \"the unemployed report their satisfaction differently.\"\n\n**(b) Misreporting employment status (`X028`).** Self-reported status is a single choice among\neight categories, so misreporting is likely and, worse, likely non-random. Three mechanisms:\n\n- **Stigma.** If unemployment is shameful — the premise of the whole project — some unemployed\n  respondents will report \"housewife\", \"student\", or \"self employed\" instead. This is\n  correlated with the outcome and with the country's work ethic, so it biases the estimate in the\n  direction of the hypothesis being tested.\n- **Ambiguity.** Someone with a few hours of casual work, or unemployed but retraining, has a\n  genuine choice of answers. The category set is not a partition of real situations.\n- **Reference period.** No date is attached. Someone laid off last week may still answer\n  \"full time\".\n\nThe stigma channel is the damaging one because it is *the same variable* as the explanatory\nmechanism. Note the direction: it removes the most-ashamed unemployed people from the unemployed\ncategory, which biases the measured gap *downward* in high-stigma countries — against the\npaper's hypothesis, not for it.\n\n**(c) Response biases in the work-attitude items (`C036`–`C041`).** Three that apply here:\n\n- **Acquiescence bias** — a tendency to agree with whatever is asserted. All five work items are\n  phrased in the pro-work direction (\"work is a duty towards society\"), so acquiescence inflates\n  the work-ethic score with no reverse-coded item to offset it. *Check:* the average would sit\n  above the 3.0 midpoint everywhere, and the five items would correlate positively with each\n  other more strongly than their content warrants. The observed means are 3.72 for men and 3.64\n  for women, both well above the 3.0 midpoint, which is consistent with this.\n- **Social desirability** — reporting the answer that reflects well on you. Its signature is\n  country-level: it would make the work-ethic measure track the local norm about what one *ought*\n  to say rather than individual belief, which is a problem because the country average is exactly\n  what Part 8.2 uses. *Check:* compare against a behavioural measure such as actual hours worked;\n  a norm-driven score should predict stated attitudes better than behaviour.\n- **Anchoring to the scale midpoint** — using the middle option as a default. *Check:* look for\n  an excess mass at exactly 3.0 in the five-item average. Because the average of five whole\n  numbers lands on multiples of 0.2, a genuine spike at 3.0 is visible in the frequency tables\n  in [Part 8.2 Q1](#p2-q1).\n\n## Q3. Recoding {#p1-q3}\n\nFive separate problems. Taking them in order.\n\n**(a) Missing values arrive as the string `.a`.** This is the conversion artefact that does the\nmost damage, because a single `.a` in a column forces every value in it to be stored as text —\nso nothing is numeric until it is fixed.\n\n::: {#cell-count-dot-a .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(variable = names(evs),\n          dot_a = [count(v -> v isa AbstractString && strip(v) == \".a\", evs[!, c])\n                   for c in names(evs)],\n          stored_as = [string(eltype(evs[!, c])) for c in names(evs)])\n```\n\n::: {#count-dot-a .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>17×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">dot_a</th><th style = \"text-align: left;\">stored_as</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">S002EVS</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">S003</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">S006</td><td style = \"text-align: right;\">0</td><td style = \"text-align: left;\">Int64</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">A009</td><td style = \"text-align: right;\">42093</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">A170</td><td style = \"text-align: right;\">1400</td><td style = \"text-align: left;\">Any</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">C036</td><td style = \"text-align: right;\">61170</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">C037</td><td style = \"text-align: right;\">61637</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">C038</td><td style = \"text-align: right;\">61115</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">C039</td><td style = \"text-align: right;\">61586</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">C041</td><td style = \"text-align: right;\">61153</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">X001</td><td style = \"text-align: right;\">98</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">X003</td><td style = \"text-align: right;\">604</td><td style = \"text-align: left;\">Any</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">X007</td><td style = \"text-align: right;\">962</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">X011_01</td><td style = \"text-align: right;\">99324</td><td style = \"text-align: left;\">Any</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">X025A</td><td style = \"text-align: right;\">99331</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">X028</td><td style = \"text-align: right;\">1645</td><td style = \"text-align: left;\">String</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">X047D</td><td style = \"text-align: right;\">83536</td><td style = \"text-align: left;\">Any</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n::: {#cell-fix-missing .cell execution_count=1}\n``` {.julia .cell-code}\nfor col in names(evs)\n    evs[!, col] = [(v isa AbstractString && strip(v) == \".a\") ? missing : v\n                   for v in evs[!, col]]\nend\nsum(count(ismissing, evs[!, c]) for c in names(evs))\n```\n\n::: {#fix-missing .cell-output .cell-output-display execution_count=1}\n```\n635654\n```\n:::\n:::\n\n\n\n**(b) Life satisfaction mixes numbers with words.** The endpoints of the scale were exported as\ntheir labels, so `A170` contains `2`–`9` as text plus `\"Dissatisfied\"` and `\"Satisfied\"`.\n\n::: {#cell-recode-a170 .cell execution_count=1}\n``` {.julia .cell-code}\nnum(x) = x === missing ? missing :\n         x isa Number ? Float64(x) : tryparse(Float64, string(x))\n\nevs.A170 = [v === missing ? missing :\n            v == \"Dissatisfied\" ? 1.0 :\n            v == \"Satisfied\"    ? 10.0 : num(v) for v in evs.A170]\n\nextrema(skipmissing(evs.A170))\n```\n\n::: {#recode-a170 .cell-output .cell-output-display execution_count=1}\n```\n(1.0, 10.0)\n```\n:::\n:::\n\n\n\n**(c) Number of children has `\"No children\"` where it means zero.**\n\n::: {#cell-recode-children .cell execution_count=1}\n``` {.julia .cell-code}\nevs.X011_01 = [v === missing ? missing : v == \"No children\" ? 0.0 : num(v)\n               for v in evs.X011_01]\nextrema(skipmissing(evs.X011_01))\n```\n\n::: {#recode-children .cell-output .cell-output-display execution_count=1}\n```\n(0.0, 16.0)\n```\n:::\n:::\n\n\n\n**(d) Two ordinal scales stored as words.** The five work items and subjective health both need\nnumbers before they can be averaged.\n\n::: {#cell-recode-scales .cell execution_count=1}\n``` {.julia .cell-code}\nconst AGREE = Dict(\"Strongly disagree\" => 1.0, \"Disagree\" => 2.0,\n                   \"Neither agree nor disagree\" => 3.0,\n                   \"Agree\" => 4.0, \"Strongly agree\" => 5.0)\nconst HEALTH = Dict(\"Very poor\" => 1.0, \"Poor\" => 2.0, \"Fair\" => 3.0,\n                    \"Good\" => 4.0, \"Very good\" => 5.0)\nconst WORK_ITEMS = [\"C036\", \"C037\", \"C038\", \"C039\", \"C041\"]\n\nfor col in WORK_ITEMS\n    evs[!, col] = [v === missing ? missing : AGREE[v] for v in evs[!, col]]\nend\nevs.A009 = [v === missing ? missing : HEALTH[v] for v in evs.A009]\nevs.X003 = num.(evs.X003)\nevs.X047D = num.(evs.X047D)\n\nDataFrame(item = vcat(WORK_ITEMS, \"A009\"),\n          answered = [count(!ismissing, evs[!, c]) for c in vcat(WORK_ITEMS, \"A009\")],\n          mean = [round(mean(skipmissing(evs[!, c])), digits = 3)\n                  for c in vcat(WORK_ITEMS, \"A009\")])\n```\n\n::: {#recode-scales .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">item</th><th style = \"text-align: left;\">answered</th><th style = \"text-align: left;\">mean</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">C036</td><td style = \"text-align: right;\">103827</td><td style = \"text-align: right;\">3.905</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">C037</td><td style = \"text-align: right;\">103360</td><td style = \"text-align: right;\">3.493</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">C038</td><td style = \"text-align: right;\">103882</td><td style = \"text-align: right;\">3.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">C039</td><td style = \"text-align: right;\">103411</td><td style = \"text-align: right;\">3.67</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">C041</td><td style = \"text-align: right;\">103844</td><td style = \"text-align: right;\">3.309</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">A009</td><td style = \"text-align: right;\">122904</td><td style = \"text-align: right;\">3.737</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nIndexing `AGREE[v]` directly rather than `get(AGREE, v, num(v))` is deliberate: if the file ever\ncontains a label not in the map, this throws instead of silently producing a `missing`.\n\n**(e) Education packs a code and a description into one cell.** `X025A` looks like\n`\"3 :  (Upper) secondary education\"` — the ISCED level and its name, separated by a colon.\nSplitting on `\" : \"` gives a numeric level and a text description.\n\n::: {#cell-split-education .cell execution_count=1}\n``` {.julia .cell-code}\nparts = [v === missing ? missing : split(string(v), \" : \") for v in evs.X025A]\nevs.Education_1 = [p === missing ? missing : num(first(p)) for p in parts]\nevs.Education_2 = [p === missing ? missing :\n                   (length(p) > 1 ? String(strip(p[2])) : missing) for p in parts]\n\nlevels = [(code, desc) for (code, desc) in zip(evs.Education_1, evs.Education_2)\n          if code !== missing]\nsort!(unique!(levels); by = first)\nDataFrame(isced = first.(levels), description = last.(levels))\n```\n\n::: {#split-education .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>7×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">isced</th><th style = \"text-align: left;\">description</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String\" style = \"text-align: left;\">String</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: left;\">Pre-primary education or none education</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: left;\">Primary education or first stage of basic education</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: left;\">Lower secondary or second stage of basic education</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: left;\">(Upper) secondary education</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: left;\">Post-secondary non-tertiary education</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: left;\">First stage of tertiary education</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: left;\">Second stage of tertiary education</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n## Q4. Dropping incomplete observations, wave by wave {#p1-q4}\n\nThis is the step where it is easy to destroy the dataset. **The four waves do not ask the same\nquestions**, so a single `dropmissing` across all variables would delete every respondent in\nwaves that never asked one of them — silently, and with no error.\n\nThe book's filter therefore has four tiers. `A170`, `X003`, `X028`, `X007` and `X001` are\nrequired in all waves; subjective health only in waves 1, 2 and 4; the work items and income only\nin waves 3 and 4; children and education only in wave 4.\n\n::: {#cell-filter-missing .cell execution_count=1}\n``` {.julia .cell-code}\ncomplete_in(df, cols) = [all(!ismissing(row[c]) for c in cols) for row in eachrow(df)]\n\n# Keep a row unless its wave asked these questions and it left one blank.\nfunction require_complete(df, cols; asked_in)\n    keep = .!in.(df.S002EVS, Ref(asked_in)) .| complete_in(df, cols)\n    return df[keep, :]\nend\n\nsteps = DataFrame(step = String[\"all four waves, raw\"], rows = Int[nrow(evs)])\n\nclean = evs[complete_in(evs, [\"A170\", \"X003\", \"X028\", \"X007\", \"X001\"]), :]\npush!(steps, (\"core variables, all waves\", nrow(clean)))\n\nclean = require_complete(clean, vcat(WORK_ITEMS, \"X047D\"); asked_in = WAVES[3:4])\npush!(steps, (\"work items and income, waves 3-4\", nrow(clean)))\n\nclean = require_complete(clean, [\"X011_01\", \"X025A\"]; asked_in = WAVES[4:4])\npush!(steps, (\"children and education, wave 4\", nrow(clean)))\n\nclean = require_complete(clean, [\"A009\"]; asked_in = WAVES[[1, 2, 4]])\npush!(steps, (\"subjective health, waves 1-2-4\", nrow(clean)))\n\nsteps.kept = round.(100 .* steps.rows ./ nrow(evs), digits = 1)\nsteps\n```\n\n::: {#filter-missing .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>5×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">step</th><th style = \"text-align: left;\">rows</th><th style = \"text-align: left;\">kept</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">all four waves, raw</td><td style = \"text-align: right;\">164997</td><td style = \"text-align: right;\">100.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">core variables, all waves</td><td style = \"text-align: right;\">160633</td><td style = \"text-align: right;\">97.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">work items and income, waves 3-4</td><td style = \"text-align: right;\">130502</td><td style = \"text-align: right;\">79.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">children and education, wave 4</td><td style = \"text-align: right;\">129930</td><td style = \"text-align: right;\">78.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">subjective health, waves 1-2-4</td><td style = \"text-align: right;\">129515</td><td style = \"text-align: right;\">78.5</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n129,515 of 164,997 respondents survive — 78.5%. Where they came from:\n\n::: {#cell-wave-counts .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(wave = WAVES, number = 1:4,\n          raw = [sum(evs.S002EVS .== w) for w in WAVES],\n          clean = [sum(clean.S002EVS .== w) for w in WAVES],\n          kept = [round(100 * sum(clean.S002EVS .== w) / sum(evs.S002EVS .== w), digits = 1)\n                  for w in WAVES])\n```\n\n::: {#wave-counts .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>4×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">wave</th><th style = \"text-align: left;\">number</th><th style = \"text-align: left;\">raw</th><th style = \"text-align: left;\">clean</th><th style = \"text-align: left;\">kept</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">1981-1984</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">19378</td><td style = \"text-align: right;\">18776</td><td style = \"text-align: right;\">96.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">1990-1993</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">38213</td><td style = \"text-align: right;\">36827</td><td style = \"text-align: right;\">96.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">1999-2001</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">41125</td><td style = \"text-align: right;\">24089</td><td style = \"text-align: right;\">58.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">2008-2010</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">66281</td><td style = \"text-align: right;\">49823</td><td style = \"text-align: right;\">75.2</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nWave 3 loses the most (41.4% dropped) because it is the first wave asked the income question, and\nincome is the item people most often refuse. No wave is wiped out, which is the check that the\ntiered filter worked.\n\n::: {.callout-important}\n## Name the waves that asked, not the ones that didn't\n\nThe book writes each of these as an inverted comparison against the waves that *lack* the\nquestion — `S002EVS != \"2008-2010\" | complete.cases(...)` for the wave-4 items, and\n`S002EVS == \"1999-2001\" | complete.cases(...)` for health, because wave 3 is the one wave that\ndid not ask it. Two of the three conditions are negations and one is not, which is easy to get\nbackwards.\n\nGetting the polarity wrong does not error. It silently deletes a wave. Hence `asked_in`, which\ntakes the waves that *did* ask and does the inversion in one place, so each call reads as the\nsurvey design rather than as its complement. The per-wave counts below are the check that it\nworked.\n\nThe first attempt at this cell also hit a Julia-specific trap. Wrapping each filter in a `let`\nblock and assigning `clean = clean[keep, :]` inside it fails with\n`UndefVarError: clean not defined in local scope`: `let` introduces a hard scope, so assigning\nto `clean` there creates a *new local* and the right-hand side then reads it before it exists.\nA plain function that returns a new frame avoids the question entirely. The\n[R → Julia page](../../reference/r-to-julia.qmd) has the general form of this.\n:::\n\n## Q5. Work ethic and relative income {#p1-q5}\n\n**(a)** Work ethic is the mean of the five attitude items.\n\n::: {#cell-work-ethic .cell execution_count=1}\n``` {.julia .cell-code}\nclean.work_ethic = [all(!ismissing(row[c]) for c in WORK_ITEMS) ?\n                    mean(Float64[row[c] for c in WORK_ITEMS]) : missing\n                    for row in eachrow(clean)]\n\n(available = sum(!ismissing, clean.work_ethic),\n waves_3_and_4 = sum(clean.S002EVS .== WAVES[3]) + sum(clean.S002EVS .== WAVES[4]),\n distinct_values = length(unique(skipmissing(clean.work_ethic))),\n range = extrema(skipmissing(clean.work_ethic)))\n```\n\n::: {#work-ethic .cell-output .cell-output-display execution_count=1}\n```\n(available = 73912, waves_3_and_4 = 73912, distinct_values = 21, range = (1.0, 5.0))\n```\n:::\n:::\n\n\n\n73,912 respondents have a work-ethic score, and that is exactly waves 3 and 4 summed. The\narithmetic landing precisely is the check that the tiered filter tracked the survey design rather\nthan dropping rows at random.\n\n::: {.callout-note}\n## The book describes six items; this file has five\n\nThe project text refers to variables `C036` **to** `C041`, which reads as six questions. `C040`\nis not in the extract — the columns run `C036, C037, C038, C039, C041`. So the work-ethic measure\nis an average of **five** whole numbers, which is why it moves in steps of 0.2 and takes 21\ndistinct values from 1.0 to 5.0. The book's own walk-through says \"based on the five survey\nquestions\" and describes the 0.2 spacing, so five is intended; only the variable range in the\nquestion text is loose.\n:::\n\n**(b) Why deviation from the country mean is the wrong measure of relative income.** The study\ndefines relative income as household income minus the country average. If the income\ndistribution has a long right tail — which every income distribution does — the mean sits above\nthe median, so the *typical* household has a negative deviation. Three consequences:\n\n- Most people are recorded as below-average, and the measure reports the skew of the\n  distribution rather than the person's position in it.\n- The mean is pulled by the top tail, so the measure of a middle household's relative standing\n  moves when the rich get richer and nothing about that household changes.\n- Countries with different amounts of top-end inequality are not comparable, because the same\n  deviation means a different rank position in each.\n\n**(c) Percentile instead.** The percentile of a household's income is its rank position, which is\ninvariant to the shape of the distribution.\n\n::: {#cell-income-percentile .cell execution_count=1}\n``` {.julia .cell-code}\nclean.percentile = Vector{Union{Missing,Float64}}(missing, nrow(clean))\n\nfor w in WAVES[3:4]\n    rows = findall((clean.S002EVS .== w) .& .!ismissing.(clean.X047D))\n    isempty(rows) && continue\n    income = Float64.(clean.X047D[rows])\n    clean.percentile[rows] = round.(ecdf(income)(income) .* 100, digits = 1)\nend\n\n(scored = sum(!ismissing, clean.percentile),\n range = extrema(skipmissing(clean.percentile)),\n mean = round(mean(skipmissing(clean.percentile)), digits = 2))\n```\n\n::: {#income-percentile .cell-output .cell-output-display execution_count=1}\n```\n(scored = 73912, range = (0.1, 100.0), mean = 50.21)\n```\n:::\n:::\n\n\n\n`ecdf` returns the empirical distribution function, and applying it to its own input gives each\nobservation's percentile. It cannot handle `missing`, so the loop restricts to waves 3 and 4\nwhere income was asked.\n\nOne thing the book's method does that is worth flagging: the percentile is computed **per wave,\npooling all countries**. That is not the \"relative income within your country\" the question\nmotivated — a median-income German and a median-income Moldovan land at very different\npercentiles of the pooled distribution, so this variable mixes national income levels with\nindividual position. It is a defensible measure of European relative standing; it is not the\nwithin-country measure the text describes.\n\n## Q6. Summary tables {#p1-q6}\n\nEverything from here uses wave 4 (2008–2010), the only wave with all variables.\n\n::: {#cell-wave4 .cell execution_count=1}\n``` {.julia .cell-code}\nwave4 = clean[clean.S002EVS .== WAVES[4], :]\nconst STATUSES = sort(unique(skipmissing(wave4.X028)))\n\n(respondents = nrow(wave4), countries = length(unique(wave4.S003)),\n statuses = STATUSES)\n```\n\n::: {#wave4 .cell-output .cell-output-display execution_count=1}\n```\n(respondents = 49823, countries = 46, statuses = [\"Full time\", \"Housewife\", \"Other\", \"Part time\", \"Retired\", \"Self employed\", \"Students\", \"Unemployed\"])\n```\n:::\n:::\n\n\n\n**(a) Employment status by country, as a share of each country's respondents.**\n\n::: {#tbl-employment .cell tbl-cap='Employment status as a percentage of each country\\'s wave-4 respondents. Rows sum to 100.' execution_count=1}\n``` {.julia .cell-code}\nemployment = DataFrame(country = String[])\nfor s in STATUSES\n    employment[!, s] = Float64[]\nend\nfor c in sort(unique(wave4.S003))\n    rows = wave4[wave4.S003 .== c, :]\n    push!(employment, (c, [round(100 * count(==(s), skipmissing(rows.X028)) / nrow(rows),\n                                 digits = 1) for s in STATUSES]...))\nend\n# 46 rows: `show_all` keeps every country visible. Quarto's engine displays results with\n# `:limit => true`, which would otherwise hide 20 of them behind a `⋮`.\nshow_all(employment)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>46×9 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">Full time</th><th style = \"text-align: left;\">Housewife</th><th style = \"text-align: left;\">Other</th><th style = \"text-align: left;\">Part time</th><th style = \"text-align: left;\">Retired</th><th style = \"text-align: left;\">Self employed</th><th style = \"text-align: left;\">Students</th><th style = \"text-align: left;\">Unemployed</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Albania</td><td style = \"text-align: right;\">29.4</td><td style = \"text-align: right;\">7.4</td><td style = \"text-align: right;\">1.5</td><td style = \"text-align: right;\">5.5</td><td style = \"text-align: right;\">9.1</td><td style = \"text-align: right;\">22.1</td><td style = \"text-align: right;\">7.3</td><td style = \"text-align: right;\">17.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Armenia</td><td style = \"text-align: right;\">23.9</td><td style = \"text-align: right;\">20.9</td><td style = \"text-align: right;\">1.1</td><td style = \"text-align: right;\">8.1</td><td style = \"text-align: right;\">18.4</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">6.7</td><td style = \"text-align: right;\">15.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Austria</td><td style = \"text-align: right;\">39.8</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">1.9</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: right;\">25.5</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">8.4</td><td style = \"text-align: right;\">2.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Belarus</td><td style = \"text-align: right;\">57.9</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">7.0</td><td style = \"text-align: right;\">18.6</td><td style = \"text-align: right;\">3.4</td><td style = \"text-align: right;\">6.9</td><td style = \"text-align: right;\">2.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Belgium</td><td style = \"text-align: right;\">42.9</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">3.7</td><td style = \"text-align: right;\">8.9</td><td style = \"text-align: right;\">23.0</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">5.2</td><td style = \"text-align: right;\">6.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Bosnia Herzegovina</td><td style = \"text-align: right;\">34.1</td><td style = \"text-align: right;\">9.3</td><td style = \"text-align: right;\">0.8</td><td style = \"text-align: right;\">2.9</td><td style = \"text-align: right;\">14.7</td><td style = \"text-align: right;\">3.1</td><td style = \"text-align: right;\">8.2</td><td style = \"text-align: right;\">27.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Bulgaria</td><td style = \"text-align: right;\">46.3</td><td style = \"text-align: right;\">2.6</td><td style = \"text-align: right;\">0.8</td><td style = \"text-align: right;\">2.8</td><td style = \"text-align: right;\">31.3</td><td style = \"text-align: right;\">5.6</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">8.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Croatia</td><td style = \"text-align: right;\">41.6</td><td style = \"text-align: right;\">3.4</td><td style = \"text-align: right;\">0.9</td><td style = \"text-align: right;\">2.8</td><td style = \"text-align: right;\">26.0</td><td style = \"text-align: right;\">2.9</td><td style = \"text-align: right;\">8.8</td><td style = \"text-align: right;\">13.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Cyprus</td><td style = \"text-align: right;\">46.3</td><td style = \"text-align: right;\">13.7</td><td style = \"text-align: right;\">1.3</td><td style = \"text-align: right;\">2.8</td><td style = \"text-align: right;\">24.4</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">1.7</td><td style = \"text-align: right;\">3.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Czech Republic</td><td style = \"text-align: right;\">46.6</td><td style = \"text-align: right;\">3.1</td><td style = \"text-align: right;\">4.7</td><td style = \"text-align: right;\">1.7</td><td style = \"text-align: right;\">31.3</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">5.4</td><td style = \"text-align: right;\">3.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Denmark</td><td style = \"text-align: right;\">55.9</td><td style = \"text-align: right;\">0.3</td><td style = \"text-align: right;\">1.3</td><td style = \"text-align: right;\">6.7</td><td style = \"text-align: right;\">24.3</td><td style = \"text-align: right;\">5.9</td><td style = \"text-align: right;\">4.1</td><td style = \"text-align: right;\">1.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Estonia</td><td style = \"text-align: right;\">50.4</td><td style = \"text-align: right;\">4.1</td><td style = \"text-align: right;\">2.2</td><td style = \"text-align: right;\">5.1</td><td style = \"text-align: right;\">28.5</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">3.4</td><td style = \"text-align: right;\">2.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">Finland</td><td style = \"text-align: right;\">52.3</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">3.9</td><td style = \"text-align: right;\">5.1</td><td style = \"text-align: right;\">22.8</td><td style = \"text-align: right;\">6.2</td><td style = \"text-align: right;\">3.7</td><td style = \"text-align: right;\">4.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">46.8</td><td style = \"text-align: right;\">5.6</td><td style = \"text-align: right;\">1.9</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">28.8</td><td style = \"text-align: right;\">2.8</td><td style = \"text-align: right;\">3.1</td><td style = \"text-align: right;\">4.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">Georgia</td><td style = \"text-align: right;\">19.5</td><td style = \"text-align: right;\">11.6</td><td style = \"text-align: right;\">0.8</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">19.4</td><td style = \"text-align: right;\">7.1</td><td style = \"text-align: right;\">2.6</td><td style = \"text-align: right;\">32.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">38.4</td><td style = \"text-align: right;\">4.6</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">8.4</td><td style = \"text-align: right;\">28.6</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">2.7</td><td style = \"text-align: right;\">11.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: right;\">33.5</td><td style = \"text-align: right;\">7.3</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">11.2</td><td style = \"text-align: right;\">29.0</td><td style = \"text-align: right;\">5.7</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">7.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">Greece</td><td style = \"text-align: right;\">28.5</td><td style = \"text-align: right;\">17.4</td><td style = \"text-align: right;\">0.4</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">26.7</td><td style = \"text-align: right;\">13.7</td><td style = \"text-align: right;\">6.2</td><td style = \"text-align: right;\">4.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: left;\">Hungary</td><td style = \"text-align: right;\">46.4</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: right;\">24.0</td><td style = \"text-align: right;\">3.5</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">9.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: left;\">Iceland</td><td style = \"text-align: right;\">54.5</td><td style = \"text-align: right;\">2.3</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">9.9</td><td style = \"text-align: right;\">7.1</td><td style = \"text-align: right;\">11.4</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">3.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: left;\">Ireland</td><td style = \"text-align: right;\">41.9</td><td style = \"text-align: right;\">19.8</td><td style = \"text-align: right;\">1.6</td><td style = \"text-align: right;\">9.7</td><td style = \"text-align: right;\">13.9</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">1.6</td><td style = \"text-align: right;\">6.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">22</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">32.9</td><td style = \"text-align: right;\">8.3</td><td style = \"text-align: right;\">0.5</td><td style = \"text-align: right;\">9.1</td><td style = \"text-align: right;\">23.1</td><td style = \"text-align: right;\">13.7</td><td style = \"text-align: right;\">7.1</td><td style = \"text-align: right;\">5.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">23</td><td style = \"text-align: left;\">Kosovo</td><td style = \"text-align: right;\">19.6</td><td style = \"text-align: right;\">11.7</td><td style = \"text-align: right;\">0.5</td><td style = \"text-align: right;\">5.2</td><td style = \"text-align: right;\">5.8</td><td style = \"text-align: right;\">9.4</td><td style = \"text-align: right;\">18.0</td><td style = \"text-align: right;\">29.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">24</td><td style = \"text-align: left;\">Latvia</td><td style = \"text-align: right;\">52.0</td><td style = \"text-align: right;\">6.2</td><td style = \"text-align: right;\">2.3</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">23.2</td><td style = \"text-align: right;\">3.3</td><td style = \"text-align: right;\">4.3</td><td style = \"text-align: right;\">4.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">25</td><td style = \"text-align: left;\">Lithuania</td><td style = \"text-align: right;\">50.1</td><td style = \"text-align: right;\">4.1</td><td style = \"text-align: right;\">2.9</td><td style = \"text-align: right;\">5.2</td><td style = \"text-align: right;\">24.0</td><td style = \"text-align: right;\">3.4</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">4.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">26</td><td style = \"text-align: left;\">Luxembourg</td><td style = \"text-align: right;\">51.3</td><td style = \"text-align: right;\">9.4</td><td style = \"text-align: right;\">1.1</td><td style = \"text-align: right;\">7.4</td><td style = \"text-align: right;\">15.4</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">9.9</td><td style = \"text-align: right;\">2.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">27</td><td style = \"text-align: left;\">Macedonia</td><td style = \"text-align: right;\">35.7</td><td style = \"text-align: right;\">4.3</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">1.7</td><td style = \"text-align: right;\">16.7</td><td style = \"text-align: right;\">3.7</td><td style = \"text-align: right;\">8.5</td><td style = \"text-align: right;\">28.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">28</td><td style = \"text-align: left;\">Malta</td><td style = \"text-align: right;\">33.8</td><td style = \"text-align: right;\">32.3</td><td style = \"text-align: right;\">0.7</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">23.4</td><td style = \"text-align: right;\">2.3</td><td style = \"text-align: right;\">0.5</td><td style = \"text-align: right;\">3.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">29</td><td style = \"text-align: left;\">Moldova</td><td style = \"text-align: right;\">30.5</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">1.9</td><td style = \"text-align: right;\">7.6</td><td style = \"text-align: right;\">25.6</td><td style = \"text-align: right;\">4.9</td><td style = \"text-align: right;\">4.4</td><td style = \"text-align: right;\">17.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">30</td><td style = \"text-align: left;\">Montenegro</td><td style = \"text-align: right;\">39.0</td><td style = \"text-align: right;\">4.6</td><td style = \"text-align: right;\">0.6</td><td style = \"text-align: right;\">2.1</td><td style = \"text-align: right;\">16.6</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">4.8</td><td style = \"text-align: right;\">27.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">31</td><td style = \"text-align: left;\">Netherlands</td><td style = \"text-align: right;\">32.4</td><td style = \"text-align: right;\">9.5</td><td style = \"text-align: right;\">3.7</td><td style = \"text-align: right;\">18.2</td><td style = \"text-align: right;\">27.8</td><td style = \"text-align: right;\">6.5</td><td style = \"text-align: right;\">0.8</td><td style = \"text-align: right;\">1.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">32</td><td style = \"text-align: left;\">Northern Cyprus</td><td style = \"text-align: right;\">31.2</td><td style = \"text-align: right;\">19.6</td><td style = \"text-align: right;\">2.2</td><td style = \"text-align: right;\">5.2</td><td style = \"text-align: right;\">8.9</td><td style = \"text-align: right;\">8.9</td><td style = \"text-align: right;\">13.6</td><td style = \"text-align: right;\">10.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">33</td><td style = \"text-align: left;\">Northern Ireland</td><td style = \"text-align: right;\">30.1</td><td style = \"text-align: right;\">10.4</td><td style = \"text-align: right;\">4.5</td><td style = \"text-align: right;\">8.7</td><td style = \"text-align: right;\">29.4</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">1.3</td><td style = \"text-align: right;\">12.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">34</td><td style = \"text-align: left;\">Norway</td><td style = \"text-align: right;\">53.2</td><td style = \"text-align: right;\">2.2</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">9.5</td><td style = \"text-align: right;\">12.6</td><td style = \"text-align: right;\">8.2</td><td style = \"text-align: right;\">7.1</td><td style = \"text-align: right;\">0.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">35</td><td style = \"text-align: left;\">Poland</td><td style = \"text-align: right;\">41.8</td><td style = \"text-align: right;\">6.0</td><td style = \"text-align: right;\">0.1</td><td style = \"text-align: right;\">3.1</td><td style = \"text-align: right;\">28.0</td><td style = \"text-align: right;\">5.8</td><td style = \"text-align: right;\">7.6</td><td style = \"text-align: right;\">7.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">36</td><td style = \"text-align: left;\">Portugal</td><td style = \"text-align: right;\">46.2</td><td style = \"text-align: right;\">5.2</td><td style = \"text-align: right;\">1.6</td><td style = \"text-align: right;\">3.3</td><td style = \"text-align: right;\">33.5</td><td style = \"text-align: right;\">1.7</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">7.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">37</td><td style = \"text-align: left;\">Romania</td><td style = \"text-align: right;\">41.1</td><td style = \"text-align: right;\">10.5</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: right;\">3.2</td><td style = \"text-align: right;\">34.0</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">2.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">38</td><td style = \"text-align: left;\">Russian Federation</td><td style = \"text-align: right;\">54.4</td><td style = \"text-align: right;\">5.8</td><td style = \"text-align: right;\">2.7</td><td style = \"text-align: right;\">5.1</td><td style = \"text-align: right;\">23.8</td><td style = \"text-align: right;\">1.3</td><td style = \"text-align: right;\">2.7</td><td style = \"text-align: right;\">4.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">39</td><td style = \"text-align: left;\">Serbia</td><td style = \"text-align: right;\">34.2</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">1.1</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">25.2</td><td style = \"text-align: right;\">6.9</td><td style = \"text-align: right;\">4.1</td><td style = \"text-align: right;\">21.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">40</td><td style = \"text-align: left;\">Slovakia</td><td style = \"text-align: right;\">41.0</td><td style = \"text-align: right;\">1.7</td><td style = \"text-align: right;\">4.9</td><td style = \"text-align: right;\">2.2</td><td style = \"text-align: right;\">39.7</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">5.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">41</td><td style = \"text-align: left;\">Slovenia</td><td style = \"text-align: right;\">47.4</td><td style = \"text-align: right;\">2.5</td><td style = \"text-align: right;\">2.7</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">31.6</td><td style = \"text-align: right;\">4.4</td><td style = \"text-align: right;\">7.0</td><td style = \"text-align: right;\">3.1</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">42</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: right;\">41.5</td><td style = \"text-align: right;\">16.3</td><td style = \"text-align: right;\">0.1</td><td style = \"text-align: right;\">4.6</td><td style = \"text-align: right;\">19.9</td><td style = \"text-align: right;\">6.3</td><td style = \"text-align: right;\">3.2</td><td style = \"text-align: right;\">8.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">43</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">54.8</td><td style = \"text-align: right;\">0.4</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">7.4</td><td style = \"text-align: right;\">15.4</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">4.1</td><td style = \"text-align: right;\">4.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">44</td><td style = \"text-align: left;\">Switzerland</td><td style = \"text-align: right;\">48.5</td><td style = \"text-align: right;\">6.4</td><td style = \"text-align: right;\">3.2</td><td style = \"text-align: right;\">14.0</td><td style = \"text-align: right;\">21.3</td><td style = \"text-align: right;\">2.9</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">2.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">45</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: right;\">16.4</td><td style = \"text-align: right;\">42.4</td><td style = \"text-align: right;\">0.6</td><td style = \"text-align: right;\">2.1</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: right;\">7.7</td><td style = \"text-align: right;\">5.9</td><td style = \"text-align: right;\">14.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">46</td><td style = \"text-align: left;\">Ukraine</td><td style = \"text-align: right;\">40.9</td><td style = \"text-align: right;\">6.8</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">4.8</td><td style = \"text-align: right;\">32.1</td><td style = \"text-align: right;\">4.4</td><td style = \"text-align: right;\">3.2</td><td style = \"text-align: right;\">6.7</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe full-time share runs from **16.4% in Turkey to 57.9% in Belarus**, and the categories that\nabsorb the difference are not the same everywhere. Three patterns stand out.\n\n**Turkey's 42.4% \"housewife\" share** is the largest single number in the table and more than\ntriple the next-highest country's (Malta, 32.3%). Read alongside its 16.4% full-time share, this\nis a labour market where most women are outside recorded employment entirely. It matters for\nthis project: a category that large is absorbing people who in another country would be counted\nas unemployed, which mechanically shrinks Turkey's measured unemployed group.\n\n**Unemployment ranges from 0.7% (Norway) to 32.5% (Georgia)**, with Kosovo at 29.8%, Macedonia at\n28.0% and Bosnia Herzegovina at 27.0%. In those four countries unemployment is not a minority\ncondition, which undercuts the stigma mechanism before any estimate is made — a norm cannot\neasily stigmatise a third of the population. [Part 8.2 Q4](#p2-q4) shows this in the data.\n\n**Part-time work is a Northern European institution**: the Netherlands 18.2%, Switzerland 14.0%,\nGreat Britain 11.2%, against under 3% in most of the Balkans. Retirement shares vary nearly as\nmuch (Slovakia 39.7%, Kosovo 5.8%) and track age structure rather than policy alone.\n\n**(b) Summary statistics by sex.** This reproduces the book's Figure 8.1.\n\n::: {#tbl-summary-sex .cell tbl-cap='Summary statistics by sex, wave 4. Reproduces the book\\'s Figure 8.1.' execution_count=1}\n``` {.julia .cell-code}\nconst SUMMARY_VARS = [\"A170\" => \"Life satisfaction\", \"A009\" => \"Self-reported health\",\n                      \"work_ethic\" => \"Work ethic\", \"X003\" => \"Age\",\n                      \"Education_1\" => \"Education\", \"X011_01\" => \"Number of children\"]\n\nsummary_table = DataFrame(variable = String[], male_mean = Float64[], male_sd = Float64[],\n                          female_mean = Float64[], female_sd = Float64[])\nfor (col, label) in SUMMARY_VARS\n    stats = map([\"Male\", \"Female\"]) do sex\n        x = collect(skipmissing(wave4[wave4.X001 .== sex, col]))\n        (round(mean(x), digits = 2), round(std(x), digits = 2))\n    end\n    push!(summary_table, (label, stats[1]..., stats[2]...))\nend\nsummary_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">male_mean</th><th style = \"text-align: left;\">male_sd</th><th style = \"text-align: left;\">female_mean</th><th style = \"text-align: left;\">female_sd</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Life satisfaction</td><td style = \"text-align: right;\">7.03</td><td style = \"text-align: right;\">2.28</td><td style = \"text-align: right;\">6.93</td><td style = \"text-align: right;\">2.32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Self-reported health</td><td style = \"text-align: right;\">3.77</td><td style = \"text-align: right;\">0.93</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">0.97</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Work ethic</td><td style = \"text-align: right;\">3.72</td><td style = \"text-align: right;\">0.76</td><td style = \"text-align: right;\">3.64</td><td style = \"text-align: right;\">0.76</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Age</td><td style = \"text-align: right;\">46.87</td><td style = \"text-align: right;\">17.36</td><td style = \"text-align: right;\">47.28</td><td style = \"text-align: right;\">17.47</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Education</td><td style = \"text-align: right;\">3.14</td><td style = \"text-align: right;\">1.31</td><td style = \"text-align: right;\">3.05</td><td style = \"text-align: right;\">1.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Number of children</td><td style = \"text-align: right;\">1.55</td><td style = \"text-align: right;\">1.43</td><td style = \"text-align: right;\">1.69</td><td style = \"text-align: right;\">1.39</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery value matches the published solution. Men and women are indistinguishable on most of these\n— life satisfaction 7.03 against 6.93, work ethic 3.72 against 3.64, age 46.9 against 47.3 —\nwhich is worth knowing before sex is used as a control. The two real gaps are **self-reported\nhealth** (3.77 against 3.60) and **number of children** (1.55 against 1.69, a reporting\ndifference as much as a real one).\n\nNote the standard deviations relative to the means. Life satisfaction has an SD of about 2.3 on\na 1–10 scale, against a male–female gap of 0.10: the spread *within* each sex is more than\ntwenty times the difference between them. That ratio is the reason Part 8.3 needs confidence intervals rather than eyeballed\ncomparisons of averages.\n\n# Part 8.2 — Visualizing the data {#part-8.2}\n\n## Q1. Has work ethic shifted over time? {#p2-q1}\n\nWaves 3 and 4 are the two that asked the work-attitude items. The book uses Germany as its\nexample; **Great Britain is not in wave 3 at all**, so the three countries here are Germany,\nSpain and Turkey — the three that appear in both waves and span the range of work-ethic scores.\n\n**(a) Frequency tables.** Because the number surveyed differs by wave, the comparable quantity is\nthe percentage at each score, not the count.\n\n::: {#cell-work-ethic-freq .cell execution_count=1}\n``` {.julia .cell-code}\nconst P2_COUNTRIES = [\"Germany\", \"Spain\", \"Turkey\"]\nconst SCORES = collect(1.0:0.2:5.0)\n\nfunction work_ethic_freq(country, wave)\n    rows = clean[(clean.S003 .== country) .& (clean.S002EVS .== wave) .&\n                 .!ismissing.(clean.work_ethic), :]\n    counts = [count(v -> isapprox(v, s; atol = 1e-8), rows.work_ethic) for s in SCORES]\n    DataFrame(score = SCORES, frequency = counts,\n              percentage = round.(100 .* counts ./ nrow(rows), digits = 2))\nend\n\ngermany3 = work_ethic_freq(\"Germany\", WAVES[3])\ngermany4 = work_ethic_freq(\"Germany\", WAVES[4])\n\nDataFrame(score = SCORES,\n          wave3_n = germany3.frequency, wave3_pct = germany3.percentage,\n          wave4_n = germany4.frequency, wave4_pct = germany4.percentage)\n```\n\n::: {#work-ethic-freq .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>21×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">score</th><th style = \"text-align: left;\">wave3_n</th><th style = \"text-align: left;\">wave3_pct</th><th style = \"text-align: left;\">wave4_n</th><th style = \"text-align: left;\">wave4_pct</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">0.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">1.2</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">0.21</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">0.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.42</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">1.6</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">0.63</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.36</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">1.8</td><td style = \"text-align: right;\">15</td><td style = \"text-align: right;\">1.05</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">0.53</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">2.0</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">1.26</td><td style = \"text-align: right;\">18</td><td style = \"text-align: right;\">1.07</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">2.2</td><td style = \"text-align: right;\">21</td><td style = \"text-align: right;\">1.47</td><td style = \"text-align: right;\">22</td><td style = \"text-align: right;\">1.31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">2.4</td><td style = \"text-align: right;\">47</td><td style = \"text-align: right;\">3.28</td><td style = \"text-align: right;\">35</td><td style = \"text-align: right;\">2.08</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">2.6</td><td style = \"text-align: right;\">68</td><td style = \"text-align: right;\">4.75</td><td style = \"text-align: right;\">44</td><td style = \"text-align: right;\">2.61</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">2.8</td><td style = \"text-align: right;\">79</td><td style = \"text-align: right;\">5.52</td><td style = \"text-align: right;\">75</td><td style = \"text-align: right;\">4.46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">3.0</td><td style = \"text-align: right;\">114</td><td style = \"text-align: right;\">7.96</td><td style = \"text-align: right;\">90</td><td style = \"text-align: right;\">5.35</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">3.2</td><td style = \"text-align: right;\">130</td><td style = \"text-align: right;\">9.08</td><td style = \"text-align: right;\">125</td><td style = \"text-align: right;\">7.43</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">3.4</td><td style = \"text-align: right;\">166</td><td style = \"text-align: right;\">11.59</td><td style = \"text-align: right;\">152</td><td style = \"text-align: right;\">9.03</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: right;\">3.6</td><td style = \"text-align: right;\">171</td><td style = \"text-align: right;\">11.94</td><td style = \"text-align: right;\">171</td><td style = \"text-align: right;\">10.16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">185</td><td style = \"text-align: right;\">12.92</td><td style = \"text-align: right;\">180</td><td style = \"text-align: right;\">10.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">164</td><td style = \"text-align: right;\">11.45</td><td style = \"text-align: right;\">207</td><td style = \"text-align: right;\">12.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: right;\">4.2</td><td style = \"text-align: right;\">106</td><td style = \"text-align: right;\">7.4</td><td style = \"text-align: right;\">191</td><td style = \"text-align: right;\">11.35</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: right;\">4.4</td><td style = \"text-align: right;\">55</td><td style = \"text-align: right;\">3.84</td><td style = \"text-align: right;\">166</td><td style = \"text-align: right;\">9.86</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: right;\">4.6</td><td style = \"text-align: right;\">34</td><td style = \"text-align: right;\">2.37</td><td style = \"text-align: right;\">79</td><td style = \"text-align: right;\">4.69</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: right;\">4.8</td><td style = \"text-align: right;\">20</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">37</td><td style = \"text-align: right;\">2.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">21</td><td style = \"text-align: right;\">1.47</td><td style = \"text-align: right;\">74</td><td style = \"text-align: right;\">4.4</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe book's Figures 8.4 and 8.5 give Germany's modal values: wave 3 peaks at a score of **3.8 with\n185 respondents (12.92%)** and wave 4 at **4.0 with 207 (12.30%)**. Both counts and both\npercentages reproduce exactly.\n\n::: {#cell-germany-check .cell execution_count=1}\n``` {.julia .cell-code}\n(wave3 = (n = sum(germany3.frequency),\n          mode = germany3.score[argmax(germany3.frequency)],\n          at_mode = maximum(germany3.frequency),\n          pct = germany3.percentage[argmax(germany3.frequency)]),\n wave4 = (n = sum(germany4.frequency),\n          mode = germany4.score[argmax(germany4.frequency)],\n          at_mode = maximum(germany4.frequency),\n          pct = germany4.percentage[argmax(germany4.frequency)]))\n```\n\n::: {#germany-check .cell-output .cell-output-display execution_count=1}\n```\n(wave3 = (n = 1432, mode = 3.8, at_mode = 185, pct = 12.92), wave4 = (n = 1683, mode = 4.0, at_mode = 207, pct = 12.3))\n```\n:::\n:::\n\n\n\n**(b) One chart per country, both waves overlaid.**\n\n::: {#cell-fig-work-ethic .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (900, 720))\naxes_ = [Axis(fig[i, 1];\n              title = P2_COUNTRIES[i],\n              ylabel = \"% of respondents\",\n              xlabel = i == 3 ? \"Work ethic score (mean of five items)\" : \"\",\n              xticks = (1.0:0.4:5.0, string.(1.0:0.4:5.0)),\n              limits = ((0.85, 5.15), (0, 14)))\n         for i in 1:3]\n\nfor (i, country) in enumerate(P2_COUNTRIES)\n    for (j, wave) in enumerate(WAVES[3:4])\n        freq = work_ethic_freq(country, wave)\n        barplot!(axes_[i], freq.score .+ (j == 1 ? -0.05 : 0.05), freq.percentage;\n                 width = 0.09, color = series_color(j),\n                 label = j == 1 ? \"Wave 3 (1999-2001)\" : \"Wave 4 (2008-2010)\")\n    end\nend\n\nLegend(fig[0, 1], axes_[1]; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Distribution of work ethic scores in waves 3 and 4, as a percentage of each wave's respondents. Two series, so the wave carries the colour; countries are separate panels rather than a fourth and fifth hue. Bars are dodged rather than drawn transparently on top of each other — overlapping fills produce a third colour that reads as a third category.](index_files/figure-html/fig-work-ethic-output-1.svg){#fig-work-ethic}\n:::\n:::\n\n\n\n**(c) What changed.** All three moved up, by very different amounts.\n\n- **Germany** moved most. The mode went from 3.8 to 4.0 and the mean from 3.48 to 3.73. Both\n  tails shifted: the share scoring 4.4 or above rose from **9.1% to 21.2%** while the share at\n  3.0 or below fell from 26.5% to 17.9%.\n- **Spain** barely moved (3.56 to 3.59). Its mode went the other way, 4.0 down to 3.8, and the\n  distribution widened slightly at both ends — the ≥4.4 share rose from 12.3% to 15.4% with the\n  ≤3.0 share flat at about 24%.\n- **Turkey** is a different distribution altogether: centred near 4.2, strongly left-skewed, and\n  in wave 4 the **mode is the 5.0 ceiling itself**. The share giving the maximum on all five\n  items doubled, from 13.3% to 26.0%.\n\n::: {#cell-work-ethic-shift .cell tbl-cap='Where each distribution sits and how much of it is in the tails. Every figure quoted in the discussion of Q1(c) comes from this table.' execution_count=1}\n``` {.julia .cell-code}\nfunction distribution_stats(country, wave)\n    f = work_ethic_freq(country, wave)\n    w = weights(f.frequency)\n    total = sum(f.frequency)\n    (mean = round(mean(f.score, w), digits = 2),\n     sd = round(std(f.score, w; corrected = false), digits = 2),\n     mode = f.score[argmax(f.frequency)],\n     pct_high = round(100 * sum(f.frequency[f.score .>= 4.4 - 1e-9]) / total, digits = 1),\n     pct_low = round(100 * sum(f.frequency[f.score .<= 3.0 + 1e-9]) / total, digits = 1),\n     pct_at_ceiling = round(100 * last(f.frequency) / total, digits = 1))\nend\n\nshift = DataFrame(country = String[], wave = String[], mean = Float64[], sd = Float64[],\n                  mode = Float64[], pct_high = Float64[], pct_low = Float64[],\n                  pct_at_ceiling = Float64[])\nfor country in P2_COUNTRIES, (i, wave) in enumerate(WAVES[3:4])\n    push!(shift, (country, \"wave $(i + 2)\", distribution_stats(country, wave)...))\nend\nshift\n```\n\n::: {#work-ethic-shift .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×8 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">wave</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">mode</th><th style = \"text-align: left;\">pct_high</th><th style = \"text-align: left;\">pct_low</th><th style = \"text-align: left;\">pct_at_ceiling</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: left;\">wave 3</td><td style = \"text-align: right;\">3.48</td><td style = \"text-align: right;\">0.68</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">9.1</td><td style = \"text-align: right;\">26.5</td><td style = \"text-align: right;\">1.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: left;\">wave 4</td><td style = \"text-align: right;\">3.73</td><td style = \"text-align: right;\">0.7</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">21.2</td><td style = \"text-align: right;\">17.9</td><td style = \"text-align: right;\">4.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">wave 3</td><td style = \"text-align: right;\">3.56</td><td style = \"text-align: right;\">0.69</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">12.3</td><td style = \"text-align: right;\">23.9</td><td style = \"text-align: right;\">1.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">wave 4</td><td style = \"text-align: right;\">3.59</td><td style = \"text-align: right;\">0.71</td><td style = \"text-align: right;\">3.8</td><td style = \"text-align: right;\">15.4</td><td style = \"text-align: right;\">24.1</td><td style = \"text-align: right;\">1.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">wave 3</td><td style = \"text-align: right;\">4.18</td><td style = \"text-align: right;\">0.59</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">41.0</td><td style = \"text-align: right;\">3.5</td><td style = \"text-align: right;\">13.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">wave 4</td><td style = \"text-align: right;\">4.27</td><td style = \"text-align: right;\">0.63</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">49.5</td><td style = \"text-align: right;\">5.5</td><td style = \"text-align: right;\">26.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe Turkish ceiling is a measurement problem, not a finding. When a quarter of respondents give\nthe maximum on every item, the scale has stopped distinguishing between them, and any further\nstrengthening of attitudes cannot show up. Turkey's mean is **censored from above**, so 4.27\nis a lower bound on where the distribution would sit on an unbounded scale — and the country\nwhose work ethic the hypothesis most relies on is the one where the measure works least well.\n\nTen years is one wave, and the movements are small against individual variation. Germany's 0.25\nshift is the largest of the three and amounts to roughly a third of the within-country standard\ndeviation of 0.70. The gap between Germany and Turkey in the same wave is 0.54 — twice\nGermany's movement across two decades.\n\n## Q2. Life satisfaction over four waves {#p2-q2}\n\n**(a) Mean life satisfaction by wave, for countries surveyed in all four.**\n\n::: {#tbl-life-sat-waves .cell tbl-cap='Mean life satisfaction by wave. Only the 11 countries present in all four waves.' execution_count=1}\n``` {.julia .cell-code}\nwaves_per_country = combine(groupby(clean, :S003),\n                            :S002EVS => (x -> length(unique(x))) => :waves)\nconst ALL_FOUR = sort(waves_per_country[waves_per_country.waves .== 4, :S003])\n\nlife_sat = DataFrame(country = ALL_FOUR)\nfor (i, w) in enumerate(WAVES)\n    life_sat[!, \"wave$i\"] = [round(mean(clean[(clean.S003 .== c) .& (clean.S002EVS .== w),\n                                              :A170]), digits = 2) for c in ALL_FOUR]\nend\nlife_sat.change = round.(life_sat.wave4 .- life_sat.wave1, digits = 2)\nsort!(life_sat, :change)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>11×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">wave1</th><th style = \"text-align: left;\">wave2</th><th style = \"text-align: left;\">wave3</th><th style = \"text-align: left;\">wave4</th><th style = \"text-align: left;\">change</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">7.22</td><td style = \"text-align: right;\">7.03</td><td style = \"text-align: right;\">7.43</td><td style = \"text-align: right;\">6.77</td><td style = \"text-align: right;\">-0.45</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">8.03</td><td style = \"text-align: right;\">7.99</td><td style = \"text-align: right;\">7.62</td><td style = \"text-align: right;\">7.68</td><td style = \"text-align: right;\">-0.35</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Ireland</td><td style = \"text-align: right;\">7.82</td><td style = \"text-align: right;\">7.88</td><td style = \"text-align: right;\">8.21</td><td style = \"text-align: right;\">7.82</td><td style = \"text-align: right;\">0.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Iceland</td><td style = \"text-align: right;\">8.05</td><td style = \"text-align: right;\">8.01</td><td style = \"text-align: right;\">8.08</td><td style = \"text-align: right;\">8.07</td><td style = \"text-align: right;\">0.02</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Northern Ireland</td><td style = \"text-align: right;\">7.66</td><td style = \"text-align: right;\">7.88</td><td style = \"text-align: right;\">8.07</td><td style = \"text-align: right;\">7.82</td><td style = \"text-align: right;\">0.16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Denmark</td><td style = \"text-align: right;\">8.21</td><td style = \"text-align: right;\">8.17</td><td style = \"text-align: right;\">8.31</td><td style = \"text-align: right;\">8.41</td><td style = \"text-align: right;\">0.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Netherlands</td><td style = \"text-align: right;\">7.75</td><td style = \"text-align: right;\">7.77</td><td style = \"text-align: right;\">7.83</td><td style = \"text-align: right;\">7.99</td><td style = \"text-align: right;\">0.24</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Belgium</td><td style = \"text-align: right;\">7.37</td><td style = \"text-align: right;\">7.6</td><td style = \"text-align: right;\">7.42</td><td style = \"text-align: right;\">7.63</td><td style = \"text-align: right;\">0.26</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">6.71</td><td style = \"text-align: right;\">6.77</td><td style = \"text-align: right;\">6.98</td><td style = \"text-align: right;\">7.05</td><td style = \"text-align: right;\">0.34</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">7.15</td><td style = \"text-align: right;\">6.97</td><td style = \"text-align: right;\">7.29</td><td style = \"text-align: right;\">0.69</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">6.65</td><td style = \"text-align: right;\">7.3</td><td style = \"text-align: right;\">7.18</td><td style = \"text-align: right;\">7.4</td><td style = \"text-align: right;\">0.75</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nOnly **11 of 46 countries** appear in all four waves, all of them in Western Europe. The EVS\nexpanded eastward after 1990, so the balanced panel is not a sample of Europe — it is a sample of\nthe countries rich enough to have been surveyed in 1981.\n\n**(b) One line per country.**\n\n::: {#cell-fig-life-sat-waves .cell execution_count=1}\n``` {.julia .cell-code}\nconst HIGHLIGHT = [\"Germany\", \"Spain\", \"Sweden\"]\n\nfig = Figure(size = (900, 520))\nax = Axis(fig[1, 1];\n          title = \"Eleven countries, four decades, a range of 1.6 points\",\n          ylabel = \"Mean life satisfaction (1-10)\",\n          xlabel = \"Survey wave\",\n          xticks = (1:4, [\"1\\n1981-84\", \"2\\n1990-93\", \"3\\n1999-2001\", \"4\\n2008-10\"]),\n          limits = ((0.85, 4.9), (6.2, 8.7)))\n\nfor row in eachrow(life_sat)\n    row.country in HIGHLIGHT && continue\n    lines!(ax, 1:4, [row.wave1, row.wave2, row.wave3, row.wave4];\n           color = GRIDLINE, linewidth = 2)\n    text!(ax, 4.06, row.wave4; text = row.country, fontsize = 10,\n          align = (:left, :center), color = MUTED)\nend\n\nfor (i, country) in enumerate(HIGHLIGHT)\n    row = only(eachrow(life_sat[life_sat.country .== country, :]))\n    values = [row.wave1, row.wave2, row.wave3, row.wave4]\n    lines!(ax, 1:4, values; color = series_color(i), linewidth = 2.5)\n    scatter!(ax, 1:4, values; color = series_color(i))\n    # Ink, not the series colour: the coloured line and dot beside the label already\n    # carry identity, and slot 3 sits below the 3:1 contrast floor for text.\n    text!(ax, 4.06, row.wave4; text = country, fontsize = 11,\n          align = (:left, :center), color = INK, font = :bold)\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Mean life satisfaction across the four waves, for the 11 countries surveyed in all of them. Eleven series exceed the eight fixed categorical slots, so the palette is not extended: three countries carry colour and the rest are grey context, direct-labelled at the right edge.](index_files/figure-html/fig-life-sat-waves-output-1.svg){#fig-life-sat-waves}\n:::\n:::\n\n\n\n**(c) What the averages do and do not show.** The dominant feature is how little moves.\nDenmark and Iceland sit near 8.1–8.4 for thirty years; France near 6.7–7.1. The **country\nranking is nearly fixed**, and the cross-country spread (about 1.6 points) is far larger than any\ncountry's movement over four waves.\n\nWithin that, three things are visible:\n\n- **Spain and Italy rose most** (+0.69 and +0.75 from wave 1 to wave 4), both from low starting\n  points, both over the decades of their post-1980 convergence.\n- **Germany fell 0.45**, and the path is not a trend — 7.22, 7.03, 7.43, 6.77. The wave-4 value\n  is the lowest of the four and the drop from wave 3 is 0.66, the largest single-wave move in the\n  table.\n- **Sweden fell 0.35**, entirely between waves 2 and 3 (7.99 → 7.62).\n\n**What a mean of a 1–10 ordinal scale hides**, and what would supplement it:\n\n1. **The distribution.** A mean of 7.0 is produced both by everyone answering 7 and by half\n   answering 4 and half answering 10. The share below some threshold — say the proportion\n   answering 5 or less — measures something a mean cannot, and is the quantity relevant to\n   welfare.\n2. **Spread.** Standard deviations here run from about 1.7 to 3.1 across countries. Two countries\n   with equal means and that difference in spread are not in the same state.\n3. **Composition.** The samples are not the same people, and not even the same kind of people —\n   the population ages between waves, and [Q3](#p2-q3) shows life satisfaction correlates with\n   age, health and income. Some of the wave-to-wave movement is a changing sample.\n4. **Precision.** Nothing above has an interval attached. With 300–1,700 respondents per country\n   per wave, a standard error on a mean is roughly 0.05–0.13, so a 0.1-point move is not\n   distinguishable from noise. This is what Part 8.3 fixes.\n\n**(d) Events behind two of these.** Germany's fall between waves 3 and 4 has an obvious\ncandidate: the wave-4 fieldwork (2008–2010) sits on the financial crisis, and German\nunemployment had risen through the Hartz reforms of 2003–2005 to a post-reunification peak near\n11% in 2005. The German figures back this up specifically — unemployment among wave-4 German\nrespondents is **11.2%**, and their mean life satisfaction is **4.61**, the lowest of any\nemployment group in any of the 46 countries. A large and unusually miserable unemployed group is\nenough to move a national average.\n\nSpain's rise from 6.60 to 7.29 spans its entry into the European Communities in 1986, two decades\nof income convergence, and the construction boom. Wave 4 caught Spain in 2008–2010, when\nunemployment was climbing past 20% — yet the average was still at its highest. Whatever drove\nthe long rise was strong enough to survive the crisis, which is a caution against reading these\naverages as a business-cycle indicator.\n\n## Q3. Correlations {#p2-q3}\n\n**(a)** Employment status and sex are text, so the correlation table needs numeric versions\nfirst. Full-time employment is coded 1 for full-time, 0 for unemployed, and **missing for the\nother six statuses** — the variable is a contrast between two groups, not an employment\nindicator, so retired and part-time respondents must be excluded rather than coded 0.\n\n::: {#tbl-correlations .cell tbl-cap='Correlation with life satisfaction and with work ethic, wave 4. Reproduces the book\\'s Figure 8.4.' execution_count=1}\n``` {.julia .cell-code}\nwave4.full_time = [s == \"Full time\" ? 1.0 : s == \"Unemployed\" ? 0.0 : missing\n                   for s in wave4.X028]\nwave4.female = [s == \"Female\" ? 1.0 : 0.0 for s in wave4.X001]\n\nconst CORR_VARS = [\"A170\" => \"Life satisfaction\", \"work_ethic\" => \"Work ethic\",\n                   \"X003\" => \"Age\", \"Education_1\" => \"Education\",\n                   \"full_time\" => \"Full-time employment\", \"female\" => \"Female\",\n                   \"A009\" => \"Self-reported health\", \"X047D\" => \"Income\",\n                   \"X011_01\" => \"Number of children\", \"percentile\" => \"Relative income\"]\n\nfunction pairwise_cor(a, b)\n    ok = .!ismissing.(wave4[!, a]) .& .!ismissing.(wave4[!, b])\n    round(cor(Float64.(wave4[ok, a]), Float64.(wave4[ok, b])), digits = 3)\nend\n\nDataFrame(variable = last.(CORR_VARS),\n          life_satisfaction = [pairwise_cor(\"A170\", c) for (c, _) in CORR_VARS],\n          work_ethic = [pairwise_cor(\"work_ethic\", c) for (c, _) in CORR_VARS],\n          observations = [sum(.!ismissing.(wave4[!, c]) .& .!ismissing.(wave4.A170))\n                          for (c, _) in CORR_VARS])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>10×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">life_satisfaction</th><th style = \"text-align: left;\">work_ethic</th><th style = \"text-align: left;\">observations</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Life satisfaction</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">-0.034</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Work ethic</td><td style = \"text-align: right;\">-0.034</td><td style = \"text-align: right;\">1.0</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Age</td><td style = \"text-align: right;\">-0.082</td><td style = \"text-align: right;\">0.133</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Education</td><td style = \"text-align: right;\">0.094</td><td style = \"text-align: right;\">-0.145</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Full-time employment</td><td style = \"text-align: right;\">0.184</td><td style = \"text-align: right;\">-0.027</td><td style = \"text-align: right;\">24891</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Female</td><td style = \"text-align: right;\">-0.021</td><td style = \"text-align: right;\">-0.048</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Self-reported health</td><td style = \"text-align: right;\">0.376</td><td style = \"text-align: right;\">-0.073</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Income</td><td style = \"text-align: right;\">0.235</td><td style = \"text-align: right;\">-0.152</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Number of children</td><td style = \"text-align: right;\">-0.017</td><td style = \"text-align: right;\">0.089</td><td style = \"text-align: right;\">49823</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">Relative income</td><td style = \"text-align: right;\">0.296</td><td style = \"text-align: right;\">-0.187</td><td style = \"text-align: right;\">49823</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll ten pairs match the book's printed values to the last digit it shows.\n\n**(b) Reading the coefficients.** Signs first, because the coding decides them.\n\n**Life satisfaction.** The largest correlate is **self-reported health at 0.376** — bigger than\nincome, bigger than employment, bigger than anything else measured. Two caveats: both are\nself-reports collected in the same interview, so a respondent's general disposition inflates the\ncorrelation, and causation runs both ways.\n\n**Relative income (0.296) correlates more strongly than raw income (0.235).** The percentile is a\nmonotone transformation of income, so a change in correlation is a change in *functional form*:\nit says the linear-in-euros specification is wrong, and satisfaction responds more nearly to rank\nor to log income than to absolute amounts. The pooled percentile also picks up cross-country\nincome differences, so part of the increase is between-country variation, not a better\nwithin-country measure.\n\n**Full-time employment (0.184)** is positive as coded: full-time (1) is more satisfied than\nunemployed (0). Note its observation count — 24,891 against 49,823 for every other row, because\nsix of the eight statuses are excluded by construction.\n\n**Age (−0.082) and children (−0.017)** are both small and negative. The age relationship is the\nwell-documented U-shape, and a linear correlation is the wrong summary of it: a coefficient near\nzero is consistent with a strong non-linear relationship, and this is a case where the number\nunderstates what is there.\n\n**Work ethic.** Its correlation with life satisfaction is **−0.034 — effectively zero**. This is\nthe single most important number in the table for this project, because it says work ethic is not\na proxy for wellbeing at the individual level. Whatever the country-level relationship in\n[Q4](#p2-q4) turns out to be, it is not an artefact of happier people having stronger work\nattitudes.\n\nWork ethic's own correlates all point one way: **education −0.145**, **relative income −0.187**,\n**income −0.152**, age **+0.133**. Stronger work ethic goes with being older, less educated, and\npoorer. That is a coherent picture — the measure is tracking something like traditionalism — and\nit is also a warning for Q4, because those characteristics are correlated with the *country*\nsomeone lives in. A cross-country correlation of work ethic with anything else risks picking up\nnational income instead.\n\n## Q4. Does the employment gap track work ethic? {#p2-q4}\n\n**(a) and (b)** Mean life satisfaction by country and employment status, for the three statuses\nof interest, and the two differences: `D1` = full-time minus unemployed, `D2` = full-time minus\nretired.\n\n::: {#tbl-gaps .cell tbl-cap='Mean life satisfaction by employment status, wave 4, with the two differences and each country\\'s mean work ethic. Sorted by work ethic.' execution_count=1}\n``` {.julia .cell-code}\nconst CATS = [\"Full time\", \"Retired\", \"Unemployed\"]\n\ngaps = DataFrame(country = String[], work_ethic = Float64[], full_time = Float64[],\n                 retired = Float64[], unemployed = Float64[], D1 = Float64[], D2 = Float64[])\nfor c in sort(unique(wave4.S003))\n    rows = wave4[wave4.S003 .== c, :]\n    groups = [Float64.(rows[coalesce.(rows.X028 .== s, false), :A170]) for s in CATS]\n    any(g -> length(g) < 2, groups) && continue\n    means = mean.(groups)\n    push!(gaps, (c, mean(skipmissing(rows.work_ethic)), means...,\n                 means[1] - means[3], means[1] - means[2]))\nend\nsort!(gaps, :work_ethic)\nshow_all(transform(gaps, names(gaps, Not(:country)) .=> ByRow(x -> round(x, digits = 2));\n                   renamecols = false))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>46×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">work_ethic</th><th style = \"text-align: left;\">full_time</th><th style = \"text-align: left;\">retired</th><th style = \"text-align: left;\">unemployed</th><th style = \"text-align: left;\">D1</th><th style = \"text-align: left;\">D2</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Iceland</td><td style = \"text-align: right;\">2.81</td><td style = \"text-align: right;\">8.2</td><td style = \"text-align: right;\">8.45</td><td style = \"text-align: right;\">7.23</td><td style = \"text-align: right;\">0.97</td><td style = \"text-align: right;\">-0.24</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Netherlands</td><td style = \"text-align: right;\">3.15</td><td style = \"text-align: right;\">8.04</td><td style = \"text-align: right;\">7.95</td><td style = \"text-align: right;\">7.0</td><td style = \"text-align: right;\">1.04</td><td style = \"text-align: right;\">0.09</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Sweden</td><td style = \"text-align: right;\">3.25</td><td style = \"text-align: right;\">7.88</td><td style = \"text-align: right;\">8.17</td><td style = \"text-align: right;\">6.52</td><td style = \"text-align: right;\">1.36</td><td style = \"text-align: right;\">-0.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Finland</td><td style = \"text-align: right;\">3.27</td><td style = \"text-align: right;\">7.82</td><td style = \"text-align: right;\">8.02</td><td style = \"text-align: right;\">5.77</td><td style = \"text-align: right;\">2.05</td><td style = \"text-align: right;\">-0.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: right;\">3.29</td><td style = \"text-align: right;\">7.53</td><td style = \"text-align: right;\">7.93</td><td style = \"text-align: right;\">6.03</td><td style = \"text-align: right;\">1.51</td><td style = \"text-align: right;\">-0.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Northern Ireland</td><td style = \"text-align: right;\">3.31</td><td style = \"text-align: right;\">7.68</td><td style = \"text-align: right;\">7.77</td><td style = \"text-align: right;\">7.54</td><td style = \"text-align: right;\">0.14</td><td style = \"text-align: right;\">-0.09</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Belgium</td><td style = \"text-align: right;\">3.31</td><td style = \"text-align: right;\">7.72</td><td style = \"text-align: right;\">7.83</td><td style = \"text-align: right;\">6.37</td><td style = \"text-align: right;\">1.35</td><td style = \"text-align: right;\">-0.12</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Croatia</td><td style = \"text-align: right;\">3.41</td><td style = \"text-align: right;\">7.31</td><td style = \"text-align: right;\">6.48</td><td style = \"text-align: right;\">7.17</td><td style = \"text-align: right;\">0.14</td><td style = \"text-align: right;\">0.83</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Switzerland</td><td style = \"text-align: right;\">3.45</td><td style = \"text-align: right;\">8.04</td><td style = \"text-align: right;\">8.12</td><td style = \"text-align: right;\">5.76</td><td style = \"text-align: right;\">2.28</td><td style = \"text-align: right;\">-0.08</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: left;\">France</td><td style = \"text-align: right;\">3.47</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">6.97</td><td style = \"text-align: right;\">6.24</td><td style = \"text-align: right;\">0.96</td><td style = \"text-align: right;\">0.23</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: left;\">Ireland</td><td style = \"text-align: right;\">3.47</td><td style = \"text-align: right;\">7.9</td><td style = \"text-align: right;\">7.83</td><td style = \"text-align: right;\">7.18</td><td style = \"text-align: right;\">0.71</td><td style = \"text-align: right;\">0.07</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: left;\">Poland</td><td style = \"text-align: right;\">3.5</td><td style = \"text-align: right;\">7.46</td><td style = \"text-align: right;\">6.57</td><td style = \"text-align: right;\">7.06</td><td style = \"text-align: right;\">0.4</td><td style = \"text-align: right;\">0.89</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: left;\">Latvia</td><td style = \"text-align: right;\">3.5</td><td style = \"text-align: right;\">6.52</td><td style = \"text-align: right;\">5.93</td><td style = \"text-align: right;\">5.31</td><td style = \"text-align: right;\">1.21</td><td style = \"text-align: right;\">0.59</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">14</td><td style = \"text-align: left;\">Denmark</td><td style = \"text-align: right;\">3.54</td><td style = \"text-align: right;\">8.54</td><td style = \"text-align: right;\">8.21</td><td style = \"text-align: right;\">7.2</td><td style = \"text-align: right;\">1.34</td><td style = \"text-align: right;\">0.34</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">15</td><td style = \"text-align: left;\">Malta</td><td style = \"text-align: right;\">3.54</td><td style = \"text-align: right;\">7.7</td><td style = \"text-align: right;\">7.76</td><td style = \"text-align: right;\">5.95</td><td style = \"text-align: right;\">1.75</td><td style = \"text-align: right;\">-0.06</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">16</td><td style = \"text-align: left;\">Bosnia Herzegovina</td><td style = \"text-align: right;\">3.55</td><td style = \"text-align: right;\">7.33</td><td style = \"text-align: right;\">7.01</td><td style = \"text-align: right;\">6.77</td><td style = \"text-align: right;\">0.56</td><td style = \"text-align: right;\">0.33</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">17</td><td style = \"text-align: left;\">Estonia</td><td style = \"text-align: right;\">3.55</td><td style = \"text-align: right;\">6.93</td><td style = \"text-align: right;\">6.25</td><td style = \"text-align: right;\">4.97</td><td style = \"text-align: right;\">1.95</td><td style = \"text-align: right;\">0.67</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">18</td><td style = \"text-align: left;\">Lithuania</td><td style = \"text-align: right;\">3.56</td><td style = \"text-align: right;\">6.59</td><td style = \"text-align: right;\">5.63</td><td style = \"text-align: right;\">4.53</td><td style = \"text-align: right;\">2.06</td><td style = \"text-align: right;\">0.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">19</td><td style = \"text-align: left;\">Norway</td><td style = \"text-align: right;\">3.58</td><td style = \"text-align: right;\">8.19</td><td style = \"text-align: right;\">8.26</td><td style = \"text-align: right;\">8.0</td><td style = \"text-align: right;\">0.19</td><td style = \"text-align: right;\">-0.07</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">20</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: right;\">3.59</td><td style = \"text-align: right;\">7.34</td><td style = \"text-align: right;\">7.21</td><td style = \"text-align: right;\">7.19</td><td style = \"text-align: right;\">0.15</td><td style = \"text-align: right;\">0.13</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">21</td><td style = \"text-align: left;\">Belarus</td><td style = \"text-align: right;\">3.62</td><td style = \"text-align: right;\">6.1</td><td style = \"text-align: right;\">5.62</td><td style = \"text-align: right;\">5.61</td><td style = \"text-align: right;\">0.49</td><td style = \"text-align: right;\">0.48</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">22</td><td style = \"text-align: left;\">Russian Federation</td><td style = \"text-align: right;\">3.62</td><td style = \"text-align: right;\">6.86</td><td style = \"text-align: right;\">5.7</td><td style = \"text-align: right;\">6.4</td><td style = \"text-align: right;\">0.46</td><td style = \"text-align: right;\">1.16</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">23</td><td style = \"text-align: left;\">Czech Republic</td><td style = \"text-align: right;\">3.63</td><td style = \"text-align: right;\">7.3</td><td style = \"text-align: right;\">6.89</td><td style = \"text-align: right;\">6.07</td><td style = \"text-align: right;\">1.24</td><td style = \"text-align: right;\">0.42</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">24</td><td style = \"text-align: left;\">Serbia</td><td style = \"text-align: right;\">3.67</td><td style = \"text-align: right;\">7.17</td><td style = \"text-align: right;\">6.67</td><td style = \"text-align: right;\">6.73</td><td style = \"text-align: right;\">0.44</td><td style = \"text-align: right;\">0.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">25</td><td style = \"text-align: left;\">Slovenia</td><td style = \"text-align: right;\">3.68</td><td style = \"text-align: right;\">7.83</td><td style = \"text-align: right;\">7.13</td><td style = \"text-align: right;\">6.76</td><td style = \"text-align: right;\">1.07</td><td style = \"text-align: right;\">0.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">26</td><td style = \"text-align: left;\">Luxembourg</td><td style = \"text-align: right;\">3.68</td><td style = \"text-align: right;\">7.87</td><td style = \"text-align: right;\">8.24</td><td style = \"text-align: right;\">5.5</td><td style = \"text-align: right;\">2.37</td><td style = \"text-align: right;\">-0.37</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">27</td><td style = \"text-align: left;\">Montenegro</td><td style = \"text-align: right;\">3.71</td><td style = \"text-align: right;\">7.63</td><td style = \"text-align: right;\">7.22</td><td style = \"text-align: right;\">7.47</td><td style = \"text-align: right;\">0.16</td><td style = \"text-align: right;\">0.42</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">28</td><td style = \"text-align: left;\">Austria</td><td style = \"text-align: right;\">3.72</td><td style = \"text-align: right;\">7.44</td><td style = \"text-align: right;\">7.74</td><td style = \"text-align: right;\">6.07</td><td style = \"text-align: right;\">1.36</td><td style = \"text-align: right;\">-0.31</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">29</td><td style = \"text-align: left;\">Germany</td><td style = \"text-align: right;\">3.73</td><td style = \"text-align: right;\">7.26</td><td style = \"text-align: right;\">6.85</td><td style = \"text-align: right;\">4.61</td><td style = \"text-align: right;\">2.65</td><td style = \"text-align: right;\">0.41</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">30</td><td style = \"text-align: left;\">Italy</td><td style = \"text-align: right;\">3.73</td><td style = \"text-align: right;\">7.43</td><td style = \"text-align: right;\">7.44</td><td style = \"text-align: right;\">6.6</td><td style = \"text-align: right;\">0.83</td><td style = \"text-align: right;\">-0.01</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">31</td><td style = \"text-align: left;\">Ukraine</td><td style = \"text-align: right;\">3.74</td><td style = \"text-align: right;\">6.34</td><td style = \"text-align: right;\">5.44</td><td style = \"text-align: right;\">4.95</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">0.9</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">32</td><td style = \"text-align: left;\">Greece</td><td style = \"text-align: right;\">3.82</td><td style = \"text-align: right;\">7.15</td><td style = \"text-align: right;\">6.62</td><td style = \"text-align: right;\">5.98</td><td style = \"text-align: right;\">1.17</td><td style = \"text-align: right;\">0.53</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">33</td><td style = \"text-align: left;\">Slovakia</td><td style = \"text-align: right;\">3.83</td><td style = \"text-align: right;\">7.47</td><td style = \"text-align: right;\">6.71</td><td style = \"text-align: right;\">6.12</td><td style = \"text-align: right;\">1.35</td><td style = \"text-align: right;\">0.76</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">34</td><td style = \"text-align: left;\">Macedonia</td><td style = \"text-align: right;\">3.85</td><td style = \"text-align: right;\">7.19</td><td style = \"text-align: right;\">6.67</td><td style = \"text-align: right;\">6.61</td><td style = \"text-align: right;\">0.58</td><td style = \"text-align: right;\">0.52</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">35</td><td style = \"text-align: left;\">Hungary</td><td style = \"text-align: right;\">3.85</td><td style = \"text-align: right;\">6.65</td><td style = \"text-align: right;\">5.89</td><td style = \"text-align: right;\">4.86</td><td style = \"text-align: right;\">1.79</td><td style = \"text-align: right;\">0.76</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">36</td><td style = \"text-align: left;\">Romania</td><td style = \"text-align: right;\">3.87</td><td style = \"text-align: right;\">7.14</td><td style = \"text-align: right;\">6.57</td><td style = \"text-align: right;\">7.41</td><td style = \"text-align: right;\">-0.27</td><td style = \"text-align: right;\">0.56</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">37</td><td style = \"text-align: left;\">Northern Cyprus</td><td style = \"text-align: right;\">3.88</td><td style = \"text-align: right;\">6.74</td><td style = \"text-align: right;\">6.44</td><td style = \"text-align: right;\">5.64</td><td style = \"text-align: right;\">1.1</td><td style = \"text-align: right;\">0.29</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">38</td><td style = \"text-align: left;\">Armenia</td><td style = \"text-align: right;\">3.89</td><td style = \"text-align: right;\">6.04</td><td style = \"text-align: right;\">4.85</td><td style = \"text-align: right;\">5.46</td><td style = \"text-align: right;\">0.58</td><td style = \"text-align: right;\">1.18</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">39</td><td style = \"text-align: left;\">Moldova</td><td style = \"text-align: right;\">3.9</td><td style = \"text-align: right;\">7.12</td><td style = \"text-align: right;\">5.98</td><td style = \"text-align: right;\">6.07</td><td style = \"text-align: right;\">1.05</td><td style = \"text-align: right;\">1.14</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">40</td><td style = \"text-align: left;\">Portugal</td><td style = \"text-align: right;\">3.9</td><td style = \"text-align: right;\">6.84</td><td style = \"text-align: right;\">5.88</td><td style = \"text-align: right;\">5.44</td><td style = \"text-align: right;\">1.4</td><td style = \"text-align: right;\">0.96</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">41</td><td style = \"text-align: left;\">Albania</td><td style = \"text-align: right;\">3.92</td><td style = \"text-align: right;\">6.63</td><td style = \"text-align: right;\">5.81</td><td style = \"text-align: right;\">6.07</td><td style = \"text-align: right;\">0.57</td><td style = \"text-align: right;\">0.83</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">42</td><td style = \"text-align: left;\">Georgia</td><td style = \"text-align: right;\">3.99</td><td style = \"text-align: right;\">6.12</td><td style = \"text-align: right;\">4.69</td><td style = \"text-align: right;\">5.42</td><td style = \"text-align: right;\">0.7</td><td style = \"text-align: right;\">1.43</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">43</td><td style = \"text-align: left;\">Cyprus</td><td style = \"text-align: right;\">4.07</td><td style = \"text-align: right;\">7.38</td><td style = \"text-align: right;\">7.03</td><td style = \"text-align: right;\">6.56</td><td style = \"text-align: right;\">0.82</td><td style = \"text-align: right;\">0.35</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">44</td><td style = \"text-align: left;\">Kosovo</td><td style = \"text-align: right;\">4.07</td><td style = \"text-align: right;\">6.3</td><td style = \"text-align: right;\">6.04</td><td style = \"text-align: right;\">6.78</td><td style = \"text-align: right;\">-0.49</td><td style = \"text-align: right;\">0.26</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">45</td><td style = \"text-align: left;\">Bulgaria</td><td style = \"text-align: right;\">4.12</td><td style = \"text-align: right;\">6.18</td><td style = \"text-align: right;\">4.97</td><td style = \"text-align: right;\">4.69</td><td style = \"text-align: right;\">1.48</td><td style = \"text-align: right;\">1.2</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">46</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: right;\">4.27</td><td style = \"text-align: right;\">6.5</td><td style = \"text-align: right;\">6.61</td><td style = \"text-align: right;\">5.76</td><td style = \"text-align: right;\">0.74</td><td style = \"text-align: right;\">-0.11</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAll 46 countries have at least two respondents in each of the three groups. Spot checks against\nthe solutions: Great Britain 7.53 / 7.93 / 6.03, Spain 7.34 / 7.21 / 7.19, Turkey 6.50 / 6.61 /\n5.76, Germany 7.26 / 6.85 / 4.61 — all exact.\n\n**The full-time/unemployed gap is positive in 44 of 46 countries.** The two exceptions are\n**Kosovo (−0.49)** and **Romania (−0.27)**, where the unemployed report *higher* satisfaction\nthan full-time workers. The full-time/retired gap is far more mixed: negative in 13 countries,\nwhere the retired are the more satisfied group.\n\nWhether social norms explain this cannot be settled by the table. What the table does establish\nis that the gap is not a fixed quantity: it ranges from −0.49 to **+2.65 in Germany**, a spread\nlarger than the entire cross-country range of national average life satisfaction. Something\ncountry-specific is at work. Candidates other than norms: the generosity of unemployment\ninsurance, the *duration* of unemployment spells, and how selective unemployment is — where 2%\nare unemployed they are a different sort of person than where 30% are.\n\n**(c) Each difference against country work ethic.**\n\n::: {#cell-fig-gaps .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (960, 460))\npanels = [(:D1, \"Full-time minus unemployed\", 1), (:D2, \"Full-time minus retired\", 2)]\n\nfor (col, label, i) in panels\n    ax = Axis(fig[1, i];\n              title = label,\n              xlabel = \"Country mean work ethic\",\n              ylabel = i == 1 ? \"Difference in mean life satisfaction\" : \"\",\n              limits = ((2.7, 4.4), (-0.8, 2.9)))\n    hlines!(ax, [0]; color = BASELINE, linewidth = 1, linestyle = :dash)\n    scatter!(ax, gaps.work_ethic, gaps[!, col]; color = series_color(1))\n    for country in [\"Great Britain\", \"Spain\", \"Turkey\", \"Germany\"]\n        row = only(eachrow(gaps[gaps.country .== country, :]))\n        text!(ax, row.work_ethic, row[col]; text = country, fontsize = 10,\n              align = (:center, :bottom), offset = (0, 7), color = INK_SECONDARY)\n    end\nend\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Country mean work ethic against each life-satisfaction gap, wave 4. One series per panel, so one colour; the three countries used in Part 8.3 are labelled. The dashed rule is zero difference, not a fit.](index_files/figure-html/fig-gaps-output-1.svg){#fig-gaps}\n:::\n:::\n\n\n\n**(d) The correlations, and what they do to the hypothesis.**\n\n::: {#cell-gap-correlations .cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(difference = [\"D1: full-time minus unemployed\", \"D2: full-time minus retired\"],\n          correlation_with_work_ethic = round.([cor(gaps.D1, gaps.work_ethic),\n                                                cor(gaps.D2, gaps.work_ethic)], digits = 4),\n          countries = nrow(gaps))\n```\n\n::: {#gap-correlations .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>2×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">correlation_with_work_ethic</th><th style = \"text-align: left;\">countries</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">D1: full-time minus unemployed</td><td style = \"text-align: right;\">-0.1576</td><td style = \"text-align: right;\">46</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">D2: full-time minus retired</td><td style = \"text-align: right;\">0.4843</td><td style = \"text-align: right;\">46</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nBoth reproduce the book's walk-through exactly (−0.1575654 and 0.4842609).\n\n**`D1` is −0.158 — the wrong sign for the hypothesis.** The paper's prediction is that where the\nwork norm is stronger, being unemployed costs more, so `D1` should rise with work ethic. In this\ncross-section it falls slightly. The relationship is weak enough that with 46 countries it is not\ndistinguishable from zero, so the honest statement is: **this data provides no support for the\nhypothesis, rather than evidence against it**.\n\nThe scatter shows why, and it is not subtle. The high-work-ethic countries in wave 4 are Turkey,\nBulgaria, Kosovo, Cyprus, Georgia, Albania and Moldova, and several of them have unemployment\nabove 25%. Where unemployment is a mass condition it is both less stigmatising and less\nselective, which pushes `D1` down exactly where work ethic is highest. The two effects are\nconfounded by construction, and the [Q3](#p2-q3) finding that work ethic correlates −0.19 with\nrelative income is the same problem in individual-level form: **work ethic is partly a proxy for\nbeing poor**, and poor countries have high unemployment.\n\n**`D2` is +0.484 — strong, and in the direction norms predict.** Where the work ethic is stronger,\nthe retired are much worse off relative to full-time workers; where it is weakest, the retired\nare *more* satisfied (Great Britain −0.40, Austria −0.31, Luxembourg −0.37). This is the more\ninteresting result, and it is the comparison where the norm argument should be *weakest* — the\nintroduction argues that norms of working apply less to the elderly.\n\nTwo readings, and this data cannot separate them:\n\n1. **Norms extend to the retired.** In strongly pro-work societies, leaving work is itself\n   costly, so retirement carries some of the same penalty as unemployment.\n2. **Pensions, not norms.** High-work-ethic countries here are poorer countries with weaker\n   pension systems. The retired are worse off because they have less money.\n\nReading (2) is the more parsimonious one given that work ethic correlates −0.15 with income at\nthe individual level, and it does not require the norm mechanism at all. `D2` correlating three\ntimes more strongly than `D1` is a signal that the country-level work-ethic variable is carrying\nnational income, which affects the retired directly.\n\n# Part 8.3 — Confidence intervals for a difference in means {#part-8.3}\n\nEvery difference in Part 8.2 was a point estimate with nothing attached. A difference of 0.15 in\nSpain and 1.51 in Great Britain are not comparable until it is known how precisely each was\nmeasured.\n\nFor a single mean, the standard error is the sample SD over the root of the sample size. For a\ndifference between two independent groups, the standard errors combine in quadrature:\n\n$$\\text{SE}(\\bar{x}_1 - \\bar{x}_2) = \\sqrt{\\text{SE}_1^2 + \\text{SE}_2^2}\n  = \\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$$\n\nIndependence is what licenses adding the variances, and it holds here — the full-time and\nunemployed respondents are different people. It would *not* hold in the paired design of\n[Project 2](../02-data-from-experiments/index.qmd), where the same subjects generate both groups.\n\n## Q1. Three countries, low, middle and high work ethic {#p3-q1}\n\nFrom the [Q4 table](#p2-q4), sorted by work ethic across 46 countries: **Great Britain** ranks\n5th (3.29, bottom third), **Spain** 20th (3.59, middle third), **Turkey** 46th (4.27, top). These\nare the book's three.\n\n**(a) Means, standard deviations and counts.**\n\n::: {#tbl-ci-inputs .cell tbl-cap='Life satisfaction by employment status for the three chosen countries, wave 4. Reproduces the book\\'s Solution figure 8.14.' execution_count=1}\n``` {.julia .cell-code}\nconst P3_COUNTRIES = [\"Turkey\", \"Spain\", \"Great Britain\"]\n\ngroup_values(country, status) =\n    Float64.(wave4[(wave4.S003 .== country) .&\n                   coalesce.(wave4.X028 .== status, false), :A170])\n\nci_inputs = DataFrame(country = String[], status = String[], n = Int[],\n                      mean = Float64[], sd = Float64[], se = Float64[])\nfor country in P3_COUNTRIES, status in CATS\n    x = group_values(country, status)\n    push!(ci_inputs, (country, status, length(x), round(mean(x), digits = 2),\n                      round(std(x), digits = 2), round(std(x) / sqrt(length(x)), digits = 4)))\nend\nci_inputs\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>9×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">status</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">sd</th><th style = \"text-align: left;\">se</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full time</td><td style = \"text-align: right;\">330</td><td style = \"text-align: right;\">6.5</td><td style = \"text-align: right;\">2.55</td><td style = \"text-align: right;\">0.1403</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Retired</td><td style = \"text-align: right;\">201</td><td style = \"text-align: right;\">6.61</td><td style = \"text-align: right;\">2.6</td><td style = \"text-align: right;\">0.1831</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Unemployed</td><td style = \"text-align: right;\">299</td><td style = \"text-align: right;\">5.76</td><td style = \"text-align: right;\">3.13</td><td style = \"text-align: right;\">0.1812</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full time</td><td style = \"text-align: right;\">377</td><td style = \"text-align: right;\">7.34</td><td style = \"text-align: right;\">1.7</td><td style = \"text-align: right;\">0.0878</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Retired</td><td style = \"text-align: right;\">181</td><td style = \"text-align: right;\">7.21</td><td style = \"text-align: right;\">1.93</td><td style = \"text-align: right;\">0.1436</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Unemployed</td><td style = \"text-align: right;\">73</td><td style = \"text-align: right;\">7.19</td><td style = \"text-align: right;\">2.14</td><td style = \"text-align: right;\">0.2503</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full time</td><td style = \"text-align: right;\">334</td><td style = \"text-align: right;\">7.53</td><td style = \"text-align: right;\">1.85</td><td style = \"text-align: right;\">0.101</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Retired</td><td style = \"text-align: right;\">289</td><td style = \"text-align: right;\">7.93</td><td style = \"text-align: right;\">1.98</td><td style = \"text-align: right;\">0.1164</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Unemployed</td><td style = \"text-align: right;\">78</td><td style = \"text-align: right;\">6.03</td><td style = \"text-align: right;\">2.19</td><td style = \"text-align: right;\">0.2475</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nEvery mean, SD and count matches the published table. The standard errors show immediately where\nthe imprecision will come from: Great Britain's unemployed group has 78 respondents against 334\nfull-time, so its SE is 0.248 against 0.101. **The small group dominates the width of the\ninterval**, which is why the unemployed comparisons are less precise than the retired ones\ndespite the differences being larger.\n\n**(b) The differences, their standard errors and 95% intervals.**\n\n::: {#tbl-ci .cell tbl-cap='95% confidence intervals for differences in mean life satisfaction, wave 4.' execution_count=1}\n``` {.julia .cell-code}\nconst Z = 1.96\n\nci_table = DataFrame(country = String[], comparison = String[], difference = Float64[],\n                     se = Float64[], half_width = Float64[], lower = Float64[],\n                     upper = Float64[], excludes_zero = Bool[])\nfor country in P3_COUNTRIES\n    for (other, label) in [(\"Unemployed\", \"Full-time - unemployed\"),\n                           (\"Retired\", \"Full-time - retired\")]\n        x, y = group_values(country, \"Full time\"), group_values(country, other)\n        diff = mean(x) - mean(y)\n        se = sqrt(var(x) / length(x) + var(y) / length(y))\n        push!(ci_table, (country, label, round(diff, digits = 3), round(se, digits = 4),\n                         round(Z * se, digits = 3), round(diff - Z * se, digits = 3),\n                         round(diff + Z * se, digits = 3), abs(diff) > Z * se))\n    end\nend\nci_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×8 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">comparison</th><th style = \"text-align: left;\">difference</th><th style = \"text-align: left;\">se</th><th style = \"text-align: left;\">half_width</th><th style = \"text-align: left;\">lower</th><th style = \"text-align: left;\">upper</th><th style = \"text-align: left;\">excludes_zero</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Bool\" style = \"text-align: left;\">Bool</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">0.737</td><td style = \"text-align: right;\">0.2292</td><td style = \"text-align: right;\">0.449</td><td style = \"text-align: right;\">0.288</td><td style = \"text-align: right;\">1.187</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">-0.107</td><td style = \"text-align: right;\">0.2307</td><td style = \"text-align: right;\">0.452</td><td style = \"text-align: right;\">-0.559</td><td style = \"text-align: right;\">0.345</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">0.145</td><td style = \"text-align: right;\">0.2653</td><td style = \"text-align: right;\">0.52</td><td style = \"text-align: right;\">-0.375</td><td style = \"text-align: right;\">0.665</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">0.127</td><td style = \"text-align: right;\">0.1683</td><td style = \"text-align: right;\">0.33</td><td style = \"text-align: right;\">-0.203</td><td style = \"text-align: right;\">0.457</td><td style = \"text-align: right;\">false</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">1.507</td><td style = \"text-align: right;\">0.2673</td><td style = \"text-align: right;\">0.524</td><td style = \"text-align: right;\">0.983</td><td style = \"text-align: right;\">2.031</td><td style = \"text-align: right;\">true</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">-0.398</td><td style = \"text-align: right;\">0.1542</td><td style = \"text-align: right;\">0.302</td><td style = \"text-align: right;\">-0.7</td><td style = \"text-align: right;\">-0.096</td><td style = \"text-align: right;\">true</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThese match the book's R walk-through exactly: Great Britain 1.51 ± 0.524 and −0.398 ± 0.302,\nSpain 0.145 ± 0.520 and 0.127 ± 0.330, Turkey 0.737 ± 0.449 and −0.107 ± 0.452.\n\n**(c) Cross-check with a t-test.** Welch's t-test uses the same standard error but a t\ndistribution with estimated degrees of freedom instead of the normal's 1.96, so the intervals\nshould be marginally wider.\n\n::: {#tbl-ttest .cell tbl-cap='Welch\\'s t-test against the manual intervals. Julia\\'s UnequalVarianceTTest is R\\'s t.test default.' execution_count=1}\n``` {.julia .cell-code}\nttest_table = DataFrame(country = String[], comparison = String[], manual = Float64[],\n                        welch = Float64[], t = Float64[], df = Float64[], p = Float64[])\nfor row in eachrow(ci_table)\n    other = endswith(row.comparison, \"unemployed\") ? \"Unemployed\" : \"Retired\"\n    x, y = group_values(row.country, \"Full time\"), group_values(row.country, other)\n    test = UnequalVarianceTTest(x, y)\n    lower, upper = confint(test)\n    push!(ttest_table, (row.country, row.comparison, row.half_width,\n                        round((upper - lower) / 2, digits = 3),\n                        round(test.t, digits = 3), round(test.df, digits = 1),\n                        # `digits` would print the smallest p-value as 0.0; `sigdigits`\n                        # keeps it readable however small it gets.\n                        round(pvalue(test), sigdigits = 2)))\nend\nttest_table\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">comparison</th><th style = \"text-align: left;\">manual</th><th style = \"text-align: left;\">welch</th><th style = \"text-align: left;\">t</th><th style = \"text-align: left;\">df</th><th style = \"text-align: left;\">p</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">0.449</td><td style = \"text-align: right;\">0.45</td><td style = \"text-align: right;\">3.218</td><td style = \"text-align: right;\">575.1</td><td style = \"text-align: right;\">0.0014</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">0.452</td><td style = \"text-align: right;\">0.453</td><td style = \"text-align: right;\">-0.464</td><td style = \"text-align: right;\">416.4</td><td style = \"text-align: right;\">0.64</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">0.52</td><td style = \"text-align: right;\">0.527</td><td style = \"text-align: right;\">0.547</td><td style = \"text-align: right;\">90.5</td><td style = \"text-align: right;\">0.59</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">0.33</td><td style = \"text-align: right;\">0.331</td><td style = \"text-align: right;\">0.754</td><td style = \"text-align: right;\">318.3</td><td style = \"text-align: right;\">0.45</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">0.524</td><td style = \"text-align: right;\">0.53</td><td style = \"text-align: right;\">5.638</td><td style = \"text-align: right;\">104.1</td><td style = \"text-align: right;\">1.5e-7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">0.302</td><td style = \"text-align: right;\">0.303</td><td style = \"text-align: right;\">-2.581</td><td style = \"text-align: right;\">593.8</td><td style = \"text-align: right;\">0.01</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nThe two agree to within 0.01 in every case, and the largest gap is Turkey's retired comparison\n(0.452 against 0.453) where the smaller group has 201 respondents. The book's walk-through prints\nTurkey's t-test interval as `[0.2873459, 1.1875704]`, which this reproduces to seven digits.\n\nThe p-values add what the intervals imply: Great Britain's full-time/unemployed difference has\np = 1.5 × 10⁻⁷, Turkey's p = 0.0014, and Spain's p = 0.59.\n\n::: {.callout-warning}\n## The book's Solutions page computes these intervals differently — and gets them wrong\n\nThe project text states the correct formula, $\\sqrt{s_1^2/n_1 + s_2^2/n_2}$, and the R\nwalk-through implements it. But the Solutions page (Figures 8.15–8.18, built in Excel) uses\n$\\sqrt{s_1^2 + s_2^2}$ as an \"SD of difference in means\" and then divides by $\\sqrt{n_1 + n_2}$:\n\n::: {#cell-solutions-formula .cell execution_count=1}\n``` {.julia .cell-code}\npublished = DataFrame(\n    country = [\"Great Britain\", \"Spain\", \"Turkey\", \"Great Britain\", \"Spain\", \"Turkey\"],\n    comparison = repeat([\"Full-time - unemployed\", \"Full-time - retired\"], inner = 3),\n    published_half_width = [0.28, 0.25, 0.32, 0.21, 0.21, 0.31])\n\ncheck = DataFrame(country = String[], comparison = String[], sd_combined = Float64[],\n                  n_combined = Int[], solutions_half_width = Float64[],\n                  correct_half_width = Float64[])\nfor row in eachrow(ci_table)\n    other = endswith(row.comparison, \"unemployed\") ? \"Unemployed\" : \"Retired\"\n    x, y = group_values(row.country, \"Full time\"), group_values(row.country, other)\n    sd_combined = sqrt(var(x) + var(y))\n    n_combined = length(x) + length(y)\n    push!(check, (row.country, row.comparison, round(sd_combined, digits = 2), n_combined,\n                  round(Z * sd_combined / sqrt(n_combined), digits = 3), row.half_width))\nend\nleftjoin(check, published, on = [:country, :comparison])\n```\n\n::: {#solutions-formula .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×7 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">country</th><th style = \"text-align: left;\">comparison</th><th style = \"text-align: left;\">sd_combined</th><th style = \"text-align: left;\">n_combined</th><th style = \"text-align: left;\">solutions_half_width</th><th style = \"text-align: left;\">correct_half_width</th><th style = \"text-align: left;\">published_half_width</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Union{Missing, Float64}\" style = \"text-align: left;\">Float64?</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">2.86</td><td style = \"text-align: right;\">412</td><td style = \"text-align: right;\">0.276</td><td style = \"text-align: right;\">0.524</td><td style = \"text-align: right;\">0.28</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">2.73</td><td style = \"text-align: right;\">450</td><td style = \"text-align: right;\">0.253</td><td style = \"text-align: right;\">0.52</td><td style = \"text-align: right;\">0.25</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full-time - unemployed</td><td style = \"text-align: right;\">4.04</td><td style = \"text-align: right;\">629</td><td style = \"text-align: right;\">0.316</td><td style = \"text-align: right;\">0.449</td><td style = \"text-align: right;\">0.32</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">Great Britain</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">2.71</td><td style = \"text-align: right;\">623</td><td style = \"text-align: right;\">0.213</td><td style = \"text-align: right;\">0.302</td><td style = \"text-align: right;\">0.21</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Spain</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">2.58</td><td style = \"text-align: right;\">558</td><td style = \"text-align: right;\">0.214</td><td style = \"text-align: right;\">0.33</td><td style = \"text-align: right;\">0.21</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Turkey</td><td style = \"text-align: left;\">Full-time - retired</td><td style = \"text-align: right;\">3.64</td><td style = \"text-align: right;\">531</td><td style = \"text-align: right;\">0.309</td><td style = \"text-align: right;\">0.452</td><td style = \"text-align: right;\">0.31</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n`solutions_half_width` reproduces the published figures to the two decimals they print, so this\nis the formula they used. It is not the same quantity: dividing a combined SD by\n$\\sqrt{n_1 + n_2}$ only coincides with the correct expression when the two groups are equal in\nsize and variance, and here they never are — Great Britain's unemployed group is a quarter the\nsize of its full-time group.\n\n**The published intervals are too narrow by 40% to 106%.** Great Britain's full-time/retired\ninterval is printed as ±0.21 when it is ±0.30; Spain's full-time/unemployed as ±0.25 when it is\n±0.52.\n\n**None of the six conclusions change**, which is why the error survived: every interval that\nexcludes zero still excludes it, and every one that contains zero still contains it. The\nsubstantive answers on the Solutions page are right. Only the widths are wrong, and this page\nuses the text's formula and the R walk-through's numbers.\n:::\n\n**(d) The differences with their intervals.**\n\n::: {#cell-fig-ci .cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (860, 500))\nax = Axis(fig[1, 1];\n          title = \"Full-time workers are more satisfied than the unemployed; against the retired it depends\",\n          ylabel = \"Difference in mean life satisfaction\",\n          xlabel = \"Ordered by country mean work ethic\",\n          xticks = (1:3, [\"Great Britain\\n3.29 (low)\", \"Spain\\n3.59 (middle)\",\n                          \"Turkey\\n4.27 (high)\"]),\n          limits = ((0.5, 3.5), (-1.0, 2.3)))\nhlines!(ax, [0]; color = BASELINE, linewidth = 1)\n\nconst ORDERED = [\"Great Britain\", \"Spain\", \"Turkey\"]\nfor (j, label) in enumerate([\"Full-time - unemployed\", \"Full-time - retired\"])\n    rows = [only(eachrow(ci_table[(ci_table.country .== c) .&\n                                  (ci_table.comparison .== label), :])) for c in ORDERED]\n    positions = collect((1:3) .+ (j == 1 ? -0.19 : 0.19))\n    barplot!(ax, positions, [r.difference for r in rows];\n             width = 0.34, color = series_color(j), label = label)\n    errorbars!(ax, positions, [r.difference for r in rows], [r.half_width for r in rows];\n               color = INK_SECONDARY, whiskerwidth = 12, linewidth = 2)\nend\n\nLegend(fig[0, 1], ax; orientation = :horizontal, framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Difference in mean life satisfaction with 95% confidence intervals, wave 4, countries ordered by work ethic from lowest to highest. Two series, so the comparison carries the colour. Error bars are the half-widths from the table above; the zero rule is what each interval is read against.](index_files/figure-html/fig-ci-output-1.svg){#fig-ci}\n:::\n:::\n\n\n\n**(e) Reading the six intervals.** Two clean results, three nulls, and one that matters.\n\n**Full-time versus unemployed.** All three differences are positive, but only two are\ndistinguishable from zero.\n\n- **Great Britain: 1.51 [0.98, 2.03].** The largest gap and the most precisely estimated relative\n  to its size. On a 1–10 scale a point and a half is substantial — comparable to the entire\n  spread between the highest and lowest country averages in the balanced panel.\n- **Turkey: 0.74 [0.29, 1.19].** Half the British gap, still excludes zero. Turkey's interval is\n  the narrowest of the three despite the largest standard deviations, because it has 299\n  unemployed respondents against Great Britain's 78.\n- **Spain: 0.15 [−0.38, 0.67].** Indistinguishable from zero. The interval is wide enough to\n  contain both no difference and a gap of two-thirds of a point, so this is *uninformative*\n  rather than evidence of no difference — a distinction the Solutions' narrower ±0.25 obscures.\n\n**And this is the ordering the hypothesis predicts backwards.** Great Britain has the *lowest*\nwork ethic of the three and the largest gap; Turkey has the highest work ethic and a gap half the\nsize. Spain sits in the middle on work ethic and has no measurable gap at all. Three countries\nis not a test, but it is the same pattern as the −0.158 correlation across all 46.\n\n**Full-time versus retired.** Only Great Britain's differs from zero, and it is negative:\n**−0.40 [−0.70, −0.10]**, p = 0.010. British retirees are *more* satisfied than full-time\nworkers. Spain (0.13 [−0.20, 0.46]) and Turkey (−0.11 [−0.56, 0.35]) are both nulls with\nintervals wide enough to include moderate effects either way.\n\n**On precision generally.** The half-widths run from 0.30 to 0.52 while the differences run from\n0.11 to 1.51 — so the measurement error is the same order of magnitude as most of the effects.\nTwo consequences worth being explicit about:\n\n1. **The country-level `D1` and `D2` values in [Part 8.2](#p2-q4) inherit this.** Each of those\n   46 differences carries an interval of roughly ±0.3 to ±0.6, and the correlations of −0.158 and\n   0.484 were computed as though they were exact. The attenuation from that noise biases both\n   correlations toward zero, which weakens the negative `D1` finding and means the true `D2`\n   relationship is, if anything, stronger than 0.484.\n2. **Precision is driven by the smallest group, not the sample.** Wave 4 has 49,823 respondents;\n   these intervals are set by groups of 73 to 78 people. Norway has 7 unemployed respondents and\n   the Netherlands 14 — country-level differences for them are essentially unmeasured, and they\n   entered the Part 8.2 correlations with the same weight as Turkey's 299.\n\nNone of this identifies a causal effect. Unemployment is not assigned at random, and the same\ncharacteristics that make someone likely to become unemployed — poor health, low education —\nindependently reduce life satisfaction. The correlation of 0.376 between satisfaction and health\nis larger than any employment gap here. What would help: a **natural experiment** such as a plant\nclosure, which makes job loss independent of the individual; or **panel data** on the same person\nbefore and after, which differences out everything fixed about them. The Winkelmann study the\nproject follows uses exactly that panel strategy, which is why it can say more than this\ncross-section can.\n\n## What this project covered\n\n| Concept | Where | In Julia |\n|---|---|---|\n| Stacking sheets into one frame | Q8.1 Q1 | `reduce(vcat, [DataFrame(XLSX.readtable(...))])` |\n| Variable labels that survive `select` | Q8.1 Q1 | `colmetadata!(df, col, \"label\", v; style = :note)` |\n| String sentinel to `missing` | Q8.1 Q3 | comprehension over every column |\n| Recoding a verbal scale | Q8.1 Q3 | `Dict` lookup that throws on an unknown label |\n| Splitting one column into two | Q8.1 Q3 | `split(v, \" : \")`, then take each part |\n| Wave-specific complete cases | Q8.1 Q4 | `(wave .!= w) .| ok`, checked by per-wave counts |\n| Row means across columns | Q8.1 Q5 | `mean(Float64[row[c] for c in cols])` |\n| Percentiles of a distribution | Q8.1 Q5 | `ecdf(x)(x)` from StatsBase |\n| Pairwise-complete correlation | Q8.2 Q3 | mask both columns, then `cor` |\n| Weighted mean and SD | Q8.2 Q1 | `mean(x, weights(w))`, `std(x, weights(w))` |\n| Grey-context emphasis past 8 series | Q8.2 Q2 | grey lines plus 3 coloured, direct-labelled |\n| SE of a difference in means | Q8.3 Q1 | `sqrt(var(x)/length(x) + var(y)/length(y))` |\n| Welch's t-test | Q8.3 Q1 | `UnequalVarianceTTest(x, y)`, `confint`, `pvalue` |\n| Error bars on a column chart | Q8.3 Q1 | `errorbars!(ax, x, y, half_width)` |\n\nThe [R → Julia page](../../reference/r-to-julia.qmd) has the full translation table.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}